### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by GoGross** [parse-community/Parse-SDK-JS#1001]
[This package](https://www.jsdelivr.com/package/npm/parse) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by dplewis** [comment]
Can you open a PR for this? There is CDN currently setup but it takes a while to update.

**Comment by dplewis** [comment]
Closing as default file isn't required for jsdelivr. 

https://cdn.jsdelivr.net/npm/parse@2.9.1/dist/parse.min.js
