### ISSUE TITLE
Exact search in `matches` doesn't return anything but `equalTo` does 

### ISSUE THREAD

**Issue by JeromeDeLeon** [parse-community/Parse-SDK-JS#1004]
### Issue Description

I have this use case where I use `productQuery.matches("name", new RegExp(search, "i"))` to search product. Everything worked fine until I searched exact product name and didn't return anything.

### Steps to reproduce

1. Create an `Sample` class
2. Add `name` column
3. Add row and fill up `abc 12345 (swap)` for name
4. Search `abc 12345 (swap)` using above or using `string contains string` (parse-dashboard)

### Expected Results

Expected `abc 12345 (swap)` to show instead of nothing 

### Actual Outcome

Empty result

### Test Case

To accurately reproduce your issue. Add your test cases [here](https://github.com/parse-community/Parse-SDK-JS/tree/master/integration/test) and read the [Contributing Guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/CONTRIBUTING.md) to run the tests. 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0
  - Operating System:     Ubuntu 18.04
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **JS SDK**
  - JS SDK version: 2.9.1
  - Application? (Browser, Node, React-Native, etc): Browser

**Comment by dplewis** [comment]
You issue is with parentheses. Try the following, it escapes them.

`query.matches('name', 'abc 12345 \\(swap\\)', 'i');`
