### ISSUE TITLE
Disable limit of fetching

### ISSUE THREAD

**Issue by JeromeDeLeon** [parse-community/Parse-SDK-JS#1034]
**Is your feature request related to a problem? Please describe.**
I have several use cases where I need to fetch data and display it on screen. I patched with limit 9999 but It's pain to do this for all my use cases and pagination is a no for me even the infinite scrolling. I have seen similar issues got close, but if would be great to let user's decide the limit since the server decided to opt out the limit but the SDK defaults the limit of 100 and I don't know where to find that code.

**Describe the solution you'd like**
Remove the limit of 100

**Describe alternatives you've considered**

**Additional context**

**Comment by JeromeDeLeon** [comment]
I have asked this on the parse-community but deleted? I don't know what happen but seems like that concern is more like a feature hence it got deleted so I posted it here.

**Comment by davimacedo** [comment]
As long as I know there is no default limit in the SDK. If you remove the limit from the server, you should be fine.

**Comment by JeromeDeLeon** [comment]
Seemed strange because I haven't specified any limit on my PS Options

**Comment by davimacedo** [comment]
Actually if you don't pass anything, the server defaults to 100. Take a look [here](https://github.com/parse-community/parse-server/blob/981628520584b71608b3fff2aeb57db8b5ed3e1f/src/Routers/ClassesRouter.js#L193). The maxLimit configuration param is only use to limit the max number that someone can passo through query.limit() to the server.

**Comment by JeromeDeLeon** [comment]
How should I make it to infinite? do I need to specify 99999 as maxLimit?

**Comment by davimacedo** [comment]
It is infinity by default, but you still need to use the query.limit() function, otherwise it will limit 100.

**Comment by davimacedo** [comment]
Maybe you can try a beforeFind trigger to set the limit for you so you don't need to call query.limit() everytime.

**Comment by JeromeDeLeon** [comment]
Is it not possible to disable this `options.limit = Number(100)`? Are we force to implement pagination or the likes to solve this? because I don't know the number of products to be transferred by the user, so to solve this I need to put limit(99999) for use cases?

**Comment by davimacedo** [comment]
It is currently not possible to disable. You have to set the limit(), otherwise it defaults to 100. It would probably not be a good idea to fetch more than 10,000 objects in a single call. You can also use the query.each() function. It performs the pagination for you and returns all objects.

**Comment by JeromeDeLeon** [comment]
I haven't come across with `each` but based on the doc, it just mimic the `forEach` of an array. Can you give me an example on how to achieve pagination with that?

**Comment by davimacedo** [comment]
No. It manages the pagination for you. It does how many finds are required for you. You can see its implementation [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseQuery.js#L852). You have two different ways to use it:

```js
query.each(obj => {
  // this callback is called for each fetched object
});
```

or

```js
const objs = await query.each(); // You will have all fetched objects at the end
```

**Comment by JeromeDeLeon** [comment]
Thanks. I'll try it out :)
