### ISSUE TITLE
Can't upload file

### ISSUE THREAD

**Issue by smartfung** [parse-community/Parse-SDK-JS#1040]
### Issue Description

I used React Native, the Parse JS SDK version is 2.9.0

When I add file to object. I got an error.
```
const Product = Parse.Object.extend("Product");
const feed = new Product();
var base64 = "V29ya2luZyBhdCBQYXJzZSBpcyBncmVhdCE=";
var file = new Parse.File("myfile.txt", { base64: base64 });
product.set(name, file)
product.save()


```
The Error is 

> object._getId is not a function. (In 'object._getId()', 'object._getId' is undefined

When I check my AWS S3, I can find the file. But return error

**Comment by davimacedo** [comment]
What is the line of code that is throwing the error? Can you share the complete error stack?

**Comment by dplewis** [comment]
@smartfung I don't see `feed` being used and I don't know what `product` is. Its really hard to debug this. Can you provide more information as well as any Subclasses you might be using.
