### ISSUE TITLE
Disable logging directory creation

### ISSUE THREAD

**Issue by REPTILEHAUS** [parse-community/Parse-SDK-JS#1046]
Ive been trying to get Bunyan or extend Winston to use Googles Cloud Logging solutions, I can get winston  working to some extent using addAdapter but my server breaks because Parse tries to create a logs directory even when told explicitly not to in the config - its not possible to create new directories on the server, its configured that way.

https://github.com/parse-community/parse-server/issues/6307

**Comment by dplewis** [comment]
Closing as duplicate.
