### ISSUE TITLE
Saving a file does not pass in session token

### ISSUE THREAD

**Issue by stevestencil** [parse-community/Parse-SDK-JS#1049]
### Issue Description

When saving a Parse.File from the browser, the session token is not passed into the headers of the request. This only appears to happen when uploading a file directly from the browser.

It appears this will only happen when using the File object from the browser as it calls the [saveFile()](https://github.com/parse-community/Parse-SDK-JS/blob/6dc6e5ca7625adeac1afd3f5fe287ca7ed2f7f3e/src/ParseFile.js#L221) function. All other file sources use the [saveBase64()](https://github.com/parse-community/Parse-SDK-JS/blob/6dc6e5ca7625adeac1afd3f5fe287ca7ed2f7f3e/src/ParseFile.js#L241) function which adds the session token and then calls [RESTController.ajax()](https://github.com/parse-community/Parse-SDK-JS/blob/6dc6e5ca7625adeac1afd3f5fe287ca7ed2f7f3e/src/RESTController.js#L89) function. when calling [saveFile()](https://github.com/parse-community/Parse-SDK-JS/blob/6dc6e5ca7625adeac1afd3f5fe287ca7ed2f7f3e/src/ParseFile.js#L221) it calls  [RESTController.ajax()](https://github.com/parse-community/Parse-SDK-JS/blob/6dc6e5ca7625adeac1afd3f5fe287ca7ed2f7f3e/src/RESTController.js#L89) directly without adding the session token.

### Steps to reproduce

1) create a new file using the File object selected with a file upload control from a browser
2) save the file
3) view the payload that is sent to the server

### Expected Results

Session token should be passed in with request

### Actual Outcome

Only the application id is passed in

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.7.2
  - Operating System:  OSX
  - Hardware: All
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): All

- **JS SDK**
  - JS SDK version: 2.7.1
  - Application? (Browser, Node, React-Native, etc): Browser

**Comment by dplewis** [comment]
I believe you are correct but do files actually use the sessionToken or is this documented anywhere?

**Comment by stevestencil** [comment]
Currently they do not use the sessionToken anywhere. However this is something I think we should change. I have read through multiple issues (#2137 and  #4672) that require the sessionToken to implement. Adding in the sessionToken to the files route is the first step to allowing things like:

- adding security to uploading files
- adding beforeSaveFile and afterSaveFile hooks
- adding meta data to files when saving to s3 (such as createdBy)
