### ISSUE TITLE
Parse React Native photo upload error on android

### ISSUE THREAD

**Issue by YousefAlsbaihi** [parse-community/Parse-SDK-JS#1050]
### Issue Description

Uploading a file to Parse backend using react native on IOS works fine, on android it does return an error

### Steps to reproduce

```
import Parse from "parse/react-native";
...    
...

let base64 = cy.state.image;
        let imageFile = new Parse.File("image.png", base64, "image/png");
        imageFile.save().then(
          img=>{
            console.log("......", img)
          }
        )

```
### Expected Results which the results i get when trying the app on IOS using EXPO

```
...... Object {
  "__type": "File",
  "name": "fe9e1132894eeca3a6102d6a1e0a567c_image.png",
  "url": "http://SERVER_IP_ADDRESS/parse/app2/files/app2/fe9e1132894eeca3a6102d6a1e0a567c_image.png",
}
```

### Actual Outcome the results i get when i use the same code on Android 

```
...... Object {
  "__type": "File",
  "name": undefined,
  "url": undefined,
}

```

### Environment Setup

- **Server**
  - parse-server version : [3.9.0]
  - Operating System:     [Ubuntu 16.04.6 (LTS) x64]
  - Hardware:             [3GB / 60GB Disk]
  - Localhost or remote server?: [Digital Ocean]

- **JS SDK**
  - JS SDK version: [2.11.0]
  - Application? : [React-Native using Expo]

### Extra informations

 - i tried downgrading the JS SDK version to 2.6.0, 2.10.0 
 - the app works and upload files perfectly fine on IOS but not on android, i even tried different android version.

**Comment by dplewis** [comment]
Are there any error messages being thrown or server logs you can post?

**Comment by YousefAlsbaihi** [comment]
@dplewis 
this is just a log, the server error is `_object.getid` undefined

**Comment by dplewis** [comment]
Can you debug the issue or post a stack trace?

A clean sample project to reproduce this issue would also be appreciated.

**Comment by HaneenSous** [comment]
Sorry for the late reply. here is the error message from Parse 

`object._getId is not a function. (In 'object._getId()', 'object._getId' is undefined)`

this only happens on Android IOS is completely fine.

The Code i use to save the image: 



```
const Posts = Parse.Object.extend("Posts");
    const posts = new Posts();
    let base64 = this.state.image; // <<< This is the image as Base64 after it's picked from the phone library
    let imageFile = new Parse.File("image.png", base64, "image/png");
    imageFile.save().then(
      function() {
        posts.set("media", imageFile);
        posts.save().then(
          posts => {
               console.log("======POST SAVED");
          },
          error => {
            console.log("======", error.message);
          }
        );
      },
      function(error) {}
    );

```

i tried a lot of solutions to work around it and other ways to save like save the image first then create post but still same issue on Android, IOS works perfectly fine but only android.

**Comment by YousefAlsbaihi** [comment]
Sorry for the late reply. here is the error message from Parse 

`object._getId is not a function. (In 'object._getId()', 'object._getId' is undefined)`

this only happens on Android IOS is completely fine.

The Code i use to save the image: 



```
const Posts = Parse.Object.extend("Posts");
    const posts = new Posts();
    let base64 = this.state.image; // <<< This is the image as Base64 after it's picked from the phone library
    let imageFile = new Parse.File("image.png", base64, "image/png");
    imageFile.save().then(
      function() {
        posts.set("media", imageFile);
        posts.save().then(
          posts => {
               console.log("======POST SAVED");
          },
          error => {
            console.log("======", error.message);
          }
        );
      },
      function(error) {}
    );

```

i tried a lot of solutions to work around it and other ways to save like save the image first then create post but still same issue on Android, IOS works perfectly fine but only android.

**Comment by dplewis** [comment]
@YousefAlsbaihi I tried an expo app and saving file worked for both iOS and Android.

```
let imageFile = new Parse.File("image.png", base64, "image/png");
```

Should be as per [docs](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseFile.js#L82)

```
let imageFile = new Parse.File("image.png", { base64 }, "image/png");
```

**Comment by Chocolladin** [comment]
I am having the same issue, only on Android, tried @dplewis solution with an URI, still same results. @YousefAlsbaihi You managed to solved it out ? 

Regards,

Bertrand

**Comment by estradanic** [comment]
Is there any progress on this? I'm having the same error message. Similar problem but with the Javascript SDK.
