### ISSUE TITLE
become() does not work on React Native

### ISSUE THREAD

**Issue by jklepatch** [parse-community/Parse-SDK-JS#1052]
### Issue Description

I am trying to create a parse session with a token by using

```
Parse.user.become(parseToken)
```

However  it gives me this error:

```
Cannot call currentUser() when using a platform with an async storage system
```

I have followed the configuration steps for parse on mobile:

```
  Parse = require('parse/react-native');
  Parse.setAsyncStorage(AsyncStorage);
```

### Steps to reproduce

 Try to create a parse session with a token on React Native with `become()`

### Expected Results

I expect to use  `become()` on React Native to create a parse session from a token.

### Actual Outcome

Error:

```
Cannot call currentUser() when using a platform with an async storage system
```

### Environment Setup

* Parse SDK: 2.11.0
* Parse server: 2.10.0
* React Native: 0.61.5
* OS: MacOS Mojave 10.14.6

**Comment by dplewis** [comment]
Thanks for reporting, will try to get a fix out soon.

**Comment by capacitivellc** [comment]
Is this released yet?

**Comment by dplewis** [comment]
We will be doing a release this weekend! Stay tuned

**Comment by MileanCo** [comment]
I also get this problem when doing
```
const user = new Parse.User();
user.linkWith('spotify', { authData: auth_data_spotify })
```

Is this patch released yet?
