### ISSUE TITLE
LiveQuery connection fails because sessionToken is null, but sessionToken is present in localStorage. Parse also sends sessionToken with some cloud function calls but not others.

### ISSUE THREAD

**Issue by akritskiy** [parse-community/Parse-SDK-JS#1055]
LiveQuery works fine most of the time, but sometimes opening the connection fails because the sessionToken in the request payload is null.

The error message on the backend is: "error: Connect message error %s"

This message comes from: /node_modules/parse-server/lib/LiveQuery/ParseLiveQueryServer.js (line 317) on the back-end. I added some console logs and the actual error message is “Invalid type: null (expected string)” and the request is
```
{ op: 'connect',
  applicationId: 'MyAppId',
  javascriptKey: 'myKey',
  sessionToken: null,
  installationId: '109b15ba-b772-4962-9dc4-ae0da8ded1c9' }
```

The request fails because the sessionToken is null. When I look in local storage, the sessionToken is there, and all other requests work fine as far as I can tell.

Another observation: In the network tab in Chrome Dev Tools, I can see Cloud functions being called. As I go down the list, it looks like the first half of the requests have the sessionToken in the request payload, but the rest don't include the sessionToken. These requests work fine, but they are just Cloud functions and I don't understand why the sessionToken gets sent with some requests but not others. It could be said that maybe these requests don't need the token, but on the other hand, the LiveQuery request definitely does need the token, and it's failing because the session token is not being sent.

### Steps to reproduce

In App.js (React) we have the Parse setup:
```
import Parse from 'parse'
Parse.initialize('MyApp', 'myKey')
Parse.serverURL = process.env.API_URL + '/parse'
Parse.CoreManager.set('REQUEST_ATTEMPT_LIMIT', 0)
```

I made a testing screen where I create a simple query for a single object with a "count" on it, subscribe, then handle updates...

```
const query = new Parse.Query('test')
query.equalTo('objectId', '7bXrkGxHFv')
query.limit(1)

const livequerySubscription = await query.subscribe()

livequerySubscription.on('open', () => {
    console.log('livequery connection opened')
})

livequerySubscription.on('update', obj => {
    console.log('livequery received update, object: ', obj.toJSON())

    let count = obj.toJSON().count
    setCount(count) // This displays the "count" in the UI
})
```

Then I have a button that changes the count and saves.

I log in with a user and navigate to my testing screen. In the console, I see "livequery connection opened." I click the button and see "livequery received update" and the UI gets updated with the new count.

I hit refresh. Same procedure works.

I repeat this several times and eventually I don't see the connection opened message. I click the button, the count gets updated but I do not get a "livequery received update" message and the UI doesn't get updated.

On the API side, I see what I described above…
```
Invalid type: null (expected string)

The request: 
{ op: 'connect',
  applicationId: 'MyAppId',
  javascriptKey: 'myKey',
  sessionToken: null,
  installationId: '109b15ba-b772-4962-9dc4-ae0da8ded1c9' }
```

### Expected Results

LiveQuery connection should open consistently, and sessionToken should be sent consistently w/ all requests.

### Actual Outcome

Seems like Parse stops sending the sessionToken with some requests and it breaks LiveQuery.

### Test Case

I haven't written any test cases for this.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.10.0
  - Operating System:     Mac
  - Hardware:            
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Local, but also happens on remote (Azure)

- **JS SDK**
  - JS SDK version: 2.11.0
  - Application? (Browser, Node, React-Native, etc): Browser (React)

**Comment by dplewis** [comment]
Can you post server logs? VERBOSE=1

I can try to write a failing test shortly.

**Comment by akritskiy** [comment]
I can't post server logs because there are user names and emails in there. Sorry.

**Comment by dplewis** [comment]
No problem, we understand. Just a small snippet with redacted sensitive information showing the query and error is enough to replicate. If not that’s fine

**Comment by akritskiy** [comment]
Sure thing...

When the LiveQuery connection opens, it looks like this:
```
verbose: Request: %j
verbose: Push Response : %j
verbose: Create client 08e40868-49a9-4cef-877e-81041afb4bfb new subscription: 29
verbose: Current client number: %d
```
Followed by the get and put request to change the count...
```
verbose: REQUEST for [GET] /parse/classes/test: {
  "where": {
    "objectId": "7bXrkGxHFv"
  },
  "limit": 1
} {"method":"GET","url":"/parse/classes/test","headers":{"host":"localhost:1337","connection":"keep-alive","content-length":"200","origin":"http://localhost:2201","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36","content-type":"text/plain","accept":"*/*","sec-fetch-site":"same-site","sec-fetch-mode":"cors","referer":"http://localhost:2201/","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"},"body":{"where":{"objectId":"7bXrkGxHFv"},"limit":1}}
verbose: RESPONSE from [GET] /parse/classes/test: {
  "response": {
    "results": [
      {
        "objectId": "7bXrkGxHFv",
        "count": 191573,
        "createdAt": "2020-01-02T20:07:06.062Z",
        "updatedAt": "2020-01-08T19:54:37.302Z"
      }
    ]
  }
} {"result":{"response":{"results":[{"objectId":"7bXrkGxHFv","count":191573,"createdAt":"2020-01-02T20:07:06.062Z","updatedAt":"2020-01-08T19:54:37.302Z"}]}}}
verbose: REQUEST for [PUT] /parse/classes/test/7bXrkGxHFv: {
  "count": 392051
} {"method":"PUT","url":"/parse/classes/test/7bXrkGxHFv","headers":{"host":"localhost:1337","connection":"keep-alive","content-length":"171","origin":"http://localhost:2201","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36","content-type":"text/plain","accept":"*/*","sec-fetch-site":"same-site","sec-fetch-mode":"cors","referer":"http://localhost:2201/","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"},"body":{"count":392051}}
verbose: Raw request from cloud code current : %j | original : %j
verbose: Subscribe messsage %j
verbose: RippleAppafterSave is triggered
verbose: ClassName: %s | ObjectId: %s
verbose: Current client number : %d
verbose: RESPONSE from [PUT] /parse/classes/test/7bXrkGxHFv: {
  "response": {
    "updatedAt": "2020-01-08T19:56:21.269Z"
  }
} {"result":{"response":{"updatedAt":"2020-01-08T19:56:21.269Z"}}}
verbose: Original %j | Current %j | Match: %s, %s, %s, %s | Query: %s
verbose: Push Response : %j
```

And after refreshing a couple of times, we have the unsuccessful connection... Just this over and over, as it tries to establish the connection.
```
error: Connect message error %s
verbose: Request: %j
verbose: Push Response : %j
error: Connect message error %s
verbose: Request: %j
verbose: Push Response : %j
error: Connect message error %s
verbose: Request: %j
verbose: Push Response : %j
```

**Comment by dplewis** [comment]
@akritskiy I added a fix https://github.com/parse-community/Parse-SDK-JS/pull/1058 please try it out and let me know If it works.

Also, I couldn't figure out how you got a null sessionToken just by looking at the code.

**Comment by akritskiy** [comment]
@dplewis Your fix works well as far as I can tell. That's awesome. I've been stuck on that for a couple of days. Thanks!

I'm confused about the null sessionToken too. Maybe this will make sense to you... We found one workaround where we restored a DB from an old DB dump, and the sessionToken was not becoming null with the old data. When looking at the requests in the dev tools network tab, all requests had the sessionToken on them. However, when I compare the _User and _Session objects between the two DBs, I see no difference and there's no mention of sessionToken in our codebase, so I have no idea how it's being set to null, honestly. I will look into it some more though.

If you figure it out, please let me know. Thanks.
