### ISSUE TITLE
Livequery not firing events due to ACL 

### ISSUE THREAD

**Issue by heinrich-fresh** [parse-community/Parse-SDK-JS#1059]
### Issue Description

I have been trying to use LiveQuery in an Angular 8 application.  Everything seems to work fine, the socket connects, on the server, I can see a new client connects. But none of the events are firing off. 

After debugging for quite a while I realized it might be the ACL causing the issue. So If I Remove the ACL / Make it public the event fires perfectly. 

Which brings me to the issue. So everywhere I can see that you pass the session token to the subscribe method. Although if I look at the SDK, you cannot do that.  

I am also Using Typescript and according to the @types.
subscribe returns Promise of type LiveQuerySubscription. But you cannot pass any parameters ('sessionToken') to the subscribe function. 

It seems as if the SDK is suppose to pass the sessionToken when it does the Subscribe, but it does not. 

This only happens if there is ACL roles defined. Once you remove that and make it public the events start to fire.  

I am using typescript, But even with regular JavaScript, I encounter the same issue. 

### Steps to reproduce

Parse Dashboard :
Create a Todo Class 
Add a row with a ACL permission

Create a Angular / simple Client side application. 
add this code:
```
import Parse from 'parse';
let query = new Parse.Query("Todos");
let subscription = query.subscribe()
subscription.on("open", () => {
      console.log("Todo Live Query started successfully");
    });
subscription.on("update", (update:any) => {
      console.log("update " + update);
})
```

### Expected Results
When you change a value in the Todo class the update event should be fired. 

### Actual Outcome
 None of the events are fired unless you make the ACL public Read and write. 

### Test Case
None as o yet. 

### Environment Setup

- **Server**
  - parse-server version : 2.3.3
  - Operating System:   Not sure -> Sashido Server 
  - Hardware:    Not sure -> Sashido Server 
  - Remote Server Hosted by Sashido

- **JS SDK**
  - JS SDK version: 2.11.0
  - Application? Angular 8 

### Logs/Trace
Server logs : 
Jan 10, 2020, 15:51:04 +02:00- ERROR
Connect message error Additional properties not allowed
Jan 10, 2020, 15:51:04 +02:00- INFO
Create new client: 265

**Comment by dplewis** [comment]
Please update your server to the latest version and reopen if this issue persists.

There is an existing test for Live Query ACL in [LiveQueryTests](https://github.com/parse-community/Parse-SDK-JS/blob/master/integration/test/ParseLiveQueryTest.js#L165).

Feel free to open a Pull Requests with additional tests to replicate your issue to see if they persists on the latest server version.

**Comment by heinrich-fresh** [comment]
@dplewis  Our production server is version 2.3.3 but even If I create a local server the same issue.

Those tests are done with parse/node. This is browser application? So not the same thing. 
I will write a test, but this is still an issue in my opinion.

**Comment by dplewis** [comment]
@heinrich-fresh Unfortunately we don't support older versions of Parse Server. Updating to the latest version may solve your issue. I asked to add tests to see if that issue is still present in the latest version (tests run against latest master branch kinda)

> Those tests are done with parse/node. This is browser application? So not the same thing.

LiveQuery uses websockets. There is websocket support for both node and browser [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/LiveQueryClient.js#L480)
