### ISSUE TITLE
Fetching object with id "" doesn't work as expected

### ISSUE THREAD

**Issue by percypyan** [parse-community/Parse-SDK-JS#1063]
### Issue Description

As expected, when you try to fetch an object with an ID that don't exist in database, you get a 101.
But in the case your object as an empty string as ID, the fetch do not throw any error even is the returned data does not match the expected result.

Given the following object: `MyClass.createWithoutData("fakeID")`.
A fetch will trigger the following API call:
```
curl -X GET \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
  https://parse-server.com/parse/classes/MyClass/fakeID
```
This call return a 404.

Now, given the following object: `MyClass.createWithoutData("")`.
A fetch will trigger the following API call:
```
curl -X GET \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
  https://parse-server.com/parse/classes/MyClass/
```
This call return a list of the first 100 objects of the MyClass collection under the `results` key.

### Steps to reproduce

Simply fetch an object created either of this ways:
- `Object.createWithoutData("")`
- `const object = new Object(); object.id = ""`

### Expected Results

The REST API act as it should, but the SDK should prevent this call by throwing something (a 101 or anything else that you find appropriate).

The other way to handle it is to prevent the usage of `Parse.Object.createWithoutData` method with an empty string. The outcome is that we still can create an object and set is ID to "" manually.

### Actual Outcome

The object contains a new `results` attribute that contain the list of objects fetched.

### Test Case

To accurately reproduce your issue. Add your test cases [here](https://github.com/parse-community/Parse-SDK-JS/tree/master/integration/test) and read the [Contributing Guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/CONTRIBUTING.md) to run the tests. 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.3.9
  - Operating System:     macOS 10.15 / Heroku operating system (I suppose Ubuntu)
  - Hardware:             MacBook Pro / Heroku servers
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost and Heroku

- **JS SDK**
  - JS SDK version: 2.7.1
  - Application? (Browser, Node, React-Native, etc): Node

### Logs/Trace

![Capture d’écran 2020-01-14 à 12 48 28](https://user-images.githubusercontent.com/10176618/72342217-4e1d6900-36cc-11ea-90ca-9ec72eb27981.png)
![Capture d’écran 2020-01-14 à 12 49 11](https://user-images.githubusercontent.com/10176618/72342220-4e1d6900-36cc-11ea-83b3-bf4be1caa80d.png)

**Comment by percypyan** [comment]
After your validation and your decision about the way to handle this case, I'm willing to create the Pull Request needed to fix this issue.

**Comment by dplewis** [comment]
@percypyan I think that if you call fetch on a new object nothing should happen. Setting an empty objectId is almost like creating a new object. What do you think?

**Comment by percypyan** [comment]
@dplewis Yes I agree. So maybe the fix is simply to update the `ParseObject._getId` method to check `typeof this.id === 'string' &&  this.id` instead of `typeof this.id === 'string'`.

**Comment by percypyan** [comment]
Maybe instead of have nothing happening we should have a 101 since fetch is a way to retrieve data available on the server, no ?

**Comment by dplewis** [comment]
> But in the case your object as an empty string as ID, the fetch do not throw any error even is the returned data does not match the expected result.

Your fix will through an error for object not found. Please feel free to open a PR with tests. 

@acinader @davimacedo Thoughts?

**Comment by davimacedo** [comment]
I'd change the fetch() function to throw an error in the case there is no id and before doing the api call.

**Comment by percypyan** [comment]
Ok, I'll do a PR to fix this!

**Comment by dplewis** [comment]
> The REST API act as it should

Can you point in the docs that states this? I don't this exists in any other SDKs.

> The object is filled with a new results key that contain the list of objects fetched.

I don't understand what this actual outcome means. Can you elaborate?

Should this be addressed in fetchAll as well? Would this be a breaking change?

**Comment by percypyan** [comment]
Yes : https://docs.parseplatform.org/rest/guide/#basic-queries
The query generated with an empty ID match the basic query.

> I don't understand what this actual outcome means. Can you elaborate?
Of course :
```
const MyClass = Parse.Object.extend("MyClass")
const myObject = MyClass.createWithoutData("")
/* Attributes are {} */
await myObject.fetch()
/* Attributes are { results: ParseObject[] } */
```
Is this snippet helping you?

**Comment by dplewis** [comment]
Might have to scroll to view comment.
```
const MyClass = Parse.Object.extend("MyClass")
const myObject = MyClass.createWithoutData("")
/* Attributes are {} */
await myObject.fetch()
/* Attributes are { results: MyClass[] } */ <— if attributes returned {} without error would that be an appropriate fix for you?
```

**Comment by percypyan** [comment]
My opinion is that an error should be thrown. If not, someone can fetch an object with include before first save and would not be able to see that the sub-object aren't fetched appropriately.

Two examples:
```
const object1 = new MyClass()
await object1.save()
const object2 = new MyClass()
await object2.save({ otherObject: object1 })

/* Somewhere in the code... */
const object3 = new MyClass()
myObject.set("otherObject", object2)
/* Expect to retrieve object2 and object1 but only object2 will be present in attributes */
await myObject.fetchWithInclude("otherObject.otherObject")
```
and
```
const myObject = new MyClass()
/* Missing await here */
myObject.save({ otherObject: MyClass.createWithoutData("anExistingID") })

/* Expect to retrieve object of ID "anExistingID" but don't */
await myObject.fetchWithInclude("otherObject")

/* Get undefined here but expected a value  */
myObject.get("otherObject").get("anAttribute")
```

In this 2 case we expect some value to be present and either runtime errors or unexpected behaviors will probably happen. The debugging will only be harder without an error.

For this reason, I think we should throw an error here.

**Comment by dplewis** [comment]
> The debugging will only be harder without an error.

This is an easy fix, depending on how you fix it will result in a breaking change as you would be throwing errors where a lot of users aren't expecting.

Here is the issue. You can see why you get the REST Calls posted above.

```
return RESTController.request(
        'GET',
        'classes/' + target.className + '/' + target._getId(),
        params,
        options
      ).then(async (response) => {
        if (target instanceof ParseObject) {
          target._clearPendingOps();
          target._clearServerData();
          target._finishFetch(response);
        }
        await localDatastore._updateObjectIfPinned(target);
        return target;
      });
```

A fix would be for `'classes/' + target.className + '/' + ""`

```
return RESTController.request(
        'GET',
        'classes/' + target.className + '/' + target._getId(),
        params,
        options
      ).then(async (response) => {
        if (response.result) {
         return target; // No changes or errors thrown.
        }
        if (target instanceof ParseObject) {
          target._clearPendingOps();
          target._clearServerData();
          target._finishFetch(response);
        }
        await localDatastore._updateObjectIfPinned(target);
        return target;
      });
```

`object.fetch()` is different from `query.get()` but should `fetch` emulate `get` internally?

The JS SDK guide also recommends the following workaround

```
if (!myObject.isDataAvailable()) {
  await myObject.fetch();
}
```

@acinder @davimacedo Thoughts?

**Comment by dplewis** [comment]
To fix your unique case, an error would work. I'll submit a PR shortly.

**Comment by percypyan** [comment]
I can do it now if you like

**Comment by dplewis** [comment]
Go for it. I’ll be happy to review it.

**Comment by percypyan** [comment]
I'll opened the following: #1066

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/1066
