### ISSUE TITLE
Missing types for `enableEncryptedUser` and `secret`

### ISSUE THREAD

**Issue by JeromeDeLeon** [parse-community/Parse-SDK-JS#1077]

**Comment by dplewis** [comment]
If you are referencing to TypeScript, you can open an PR fix on the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/parse) Repo

**Comment by dplewis** [comment]
PR Submitted

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42173

**Comment by dplewis** [comment]
Closing via  @types/parse@2.10.15
