### ISSUE TITLE
Query.reduce is not resolving returned promises

### ISSUE THREAD

**Issue by acinader** [parse-community/Parse-SDK-JS#1089]
If a Parse.Query.reduce executor function returns a promise, the next iteration of the executor function will receive a promise in the accumulator instead of the resolved value as the documentation (and reason) implies.

**Comment by acinader** [comment]
I think that handling the promise in the executor is the way to go.  i.e. it's good as is.  closing.

**Comment by dplewis** [comment]
The extra test case wouldn’t hurt
