### ISSUE TITLE
File upload progress method was called once

### ISSUE THREAD

**Issue by JeromeDeLeon** [parse-community/Parse-SDK-JS#1096]
### Issue Description

I'm trying to track the progress of the file being uploaded to the server, but it seemed like `progress` method was only called once after the file was successfully uploaded to the server resulting the call to `1 213 213`. I tried uploading three different files, starting from 500kB then 5mB and 12mB files. What I got was single call from each file.

```js
1 243 243 // File 1
1 215 215 // File 2
1 251 251 // File 3
```

### Steps to reproduce

1. Create a sample file either Blob or File instance is fine.
2. Add that sample file to Parse File.
3. Save it but pass a callback function to `progress`

```js
const fileObj = new Parse.File('sample', file);
fileObj.save({ progress: console.log })
```

### Expected Results

The log will start from 0 then gradually increases until it reaches a 100% or 1

### Actual Outcome

Log called only once with 1 as the output

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.10.0
  - Operating System:    Linux
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital Ocean

- **JS SDK**
  - JS SDK version: 2.11.0
  - Application? (Browser, Node, React-Native, etc): Browser

**Comment by dplewis** [comment]
Which browser are you using?

progress is handled [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/RESTController.js#L162)

**Comment by JeromeDeLeon** [comment]
Chrome Browser latest version

**Comment by JeromeDeLeon** [comment]
> Which browser are you using?
> 
> progress is handled [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/RESTController.js#L162)

Yes, I saw that one and even the latest changes and tests. That's why I'm wondering why was it called only once.

**Comment by ladigitale** [comment]
According to [Mozzilla](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Monitoring_progress)  
> The upload events are fired on the XMLHttpRequest.upload object
So, parse supports only progress download yet.

**Comment by JeromeDeLeon** [comment]
I don't think so. I believe this feature worked before in our previous app that's why I was wondering what happened.

**Comment by JeromeDeLeon** [comment]
I'll try to investigate more.

**Comment by ladigitale** [comment]
The data you 've posted show that the progressEvent fired is related to download.
It has downloaded 243 bytes whose body should look like : 

> ({"url":"ONLINE_FILE_URL","name":"ONLINE_FILE_NAME"})

I juste made a test by adding ".upload" between "xhr" and ".onProgress" and the progress event works great.

**Comment by JeromeDeLeon** [comment]
Sorry, this is new to me. All this time, I though, `onprogress` event on `XMLHttpRequest` was for `upload` and `download`.

**Comment by JeromeDeLeon** [comment]
Then, how come this works before on our app?

**Comment by ladigitale** [comment]
See : [here](https://github.com/parse-community/Parse-SDK-JS/commit/e66948e4b9704f21998e82f1f3d04dccba9b4e9a)

The upload attribute was initially used in RestControler.js

**Comment by JeromeDeLeon** [comment]
Seems like it. Before, what was not working was download progress because of `upload` being present in `XMLHTTPRequest` statement. Now, they removed it and instead used `onprogressevent`.

I assumed, we could do something like this:

```js
xhr.upload.onprogress = (event) => {
  if(options && typeof options.progress === 'function') {
    if (event.lengthComputable) {
      options.uploadProgress(event.loaded / event.total, event.loaded, event.total);
    } else {
      options.uploadProgress(null);
    }
  }
};

xhr.onprogress = (event) => {
  if(options && typeof options.progress === 'function') {
    if (event.lengthComputable) {
      options.progress(event.loaded / event.total, event.loaded, event.total);
    } else {
      options.progress(null);
    }
  }
};
```

We could add `uploadProgress`, not sure if that makes sense to avoid collision if they both run at the same time? or one after the other. If not, then using `progress` for both is fine.

**Comment by JeromeDeLeon** [comment]
Upon checking, I modified the `parse` in my `node_modules` and tried adding `xhr.upload.onprogress` and works just fine.

**Comment by ladigitale** [comment]
Maybe i would keep the same callback, but add an optional parametter to it in order to give the type of the progess ("upload" or "download").

**Comment by ladigitale** [comment]
Or a method on the File object that would give more info or control on this object. But i know it's way more complicated

**Comment by ladigitale** [comment]
> Maybe i would keep the same callback, but add an optional parameter to it in order to give the type of the progess ("upload" or "download").

Or maybe pass the original event instead of the type.

**Comment by JeromeDeLeon** [comment]
We can move the discussion there. :smile:

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/1140
