### ISSUE TITLE
Allow saving with custom objectId

### ISSUE THREAD

**Issue by JeromeDeLeon** [parse-community/Parse-SDK-JS#1097]
**Is your feature request related to a problem? Please describe.**
This feature was already merged on Parse Server but I just tried it with this SDK and got the result of `Object not found` and upon looking up, [ParseObject#L313](https://github.com/parse-community/Parse-SDK-JS/blob/05b097c6256ca058f10a0c2551b01d1f321b123d/src/ParseObject.js#L313) was the cause of it because if it detects an objectId being present, it will simply update the object hence the `PUT` method. Correct me if I'm wrong. 

**Describe the solution you'd like**
Ability to set `objectId` without making an update to the non-existent record.

**Describe alternatives you've considered**
For now, we could just use REST API to manually create an object.

**Additional context**
I thought of a solution that we could check if it is new or not but looking up to `isNew` method, it checks whether `this.id` is present or not and unfortunately, hitting save will automatically replace `this.id` the `objectId` we assigned to it.

**Comment by JeromeDeLeon** [comment]
At first, I thought of adding `_existed` property to `ParseObject` but seems like too cumbersome and not a good solution IMO, so I thought of another one. We could just replace `_localId` of the `objectId` that we set instead of `uuid`?

**Comment by JeromeDeLeon** [comment]
We also need to support reverting `id` back to `undefined` in case it failed to save.

**Comment by dplewis** [comment]
@JeromeDeLeon Thanks for your suggestions.

Have global config `CoreManager.get('AllowCustomId')` this will allow us to make sure that an objectId is required (or we could reuse _localId) before saving.

The next problem is with `PUT` vs `POST`. I think we can use the fact that a saved / existing object doesn't have a _localId.

@parse-community/core-maintainers Thoughts?

**Comment by davimacedo** [comment]
It looks a good approach.
