### ISSUE TITLE
Files not saving with session token when cascade saved

### ISSUE THREAD

**Issue by stevestencil** [parse-community/Parse-SDK-JS#1106]
### Issue Description

When saving an object that has an unsaved Parse.File, the Parse.File will not receive the sessionToken or masterKey options that are passed into the options of the parent object.

### Steps to reproduce

1) create a new Parse.File
2) create a new Parse.Object
3) set the Parse.File as a property on the Parse.Object
4) call save({ sessionToken: 'some-session-token' }) on Parse.Object

The file will save but without the session token being passed in as an option

example:
```
const someObject = new Parse.Object('Foo');
const someFile = new Parse.File('file.txt', [1,2,3]);
someObject.set('file', someFile);
await someObject.save(null, { sessionToken: 'some-token' });
```

### Expected Results

The file should contain either the masterKey or sessionToken that was passed in when calling save on the parent object.

### Actual Outcome

the file is being saved as if calling `someFile.save()` instead of `someFile.save({ sessionToken: 'some-token' });`

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.1.0
  - Operating System:     macOS Catalina
  - Hardware:             iMac
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): All of the above

- **JS SDK**
  - JS SDK version: 2.11.0
  - Application? (Browser, Node, React-Native, etc): All

**Comment by dplewis** [comment]
Good catch! PR coming soon.

**Comment by dplewis** [comment]
This will have to be done on the server side

**Comment by stevestencil** [comment]
What has to be done on server side? Anything I can help with?

**Comment by dplewis** [comment]
Sorry, object.save() is handled on the server side. a fix for this will have to be done on the Parse Server repo if it doesn’t already exist

**Comment by stevestencil** [comment]
I’m on my phone right now so I can’t look at the code but when I first checked it out the PR you just made should fix the issue. Maybe I’m missing something?

**Comment by dplewis** [comment]
That’s was for saveAll, save will still have to be done

**Comment by stevestencil** [comment]
Ahh I see... I believe passing in the options on the save function on line 2267 in ParseObject.js should do the trick?

**Comment by dplewis** [comment]
That is for an array of objects aka saveAll

**Comment by stevestencil** [comment]
Haha I’m sorry that’s exactly what you did in your PR... I’m on my phone so it’s a little challenging to look at the code... I will look at it tomorrow when I get in front of a computer

**Comment by stevestencil** [comment]
@dplewis When files are saved within a cascade they will always be passed into the save() function of the DefaultController as an array. So the PR you have should be all that is needed to fix this.

When calling `save()` on ParseObject it calls `unsavedChildren()`, this returns an object with an array of files. This array is then passed into the `save()` function of the DefaultController.

**Comment by dplewis** [comment]
Nice! We can close this out then. I’ll probably write a test case later.
