### ISSUE TITLE
Using SDK after 2.0.2 causes Flow to emit an error

### ISSUE THREAD

**Issue by noahsilas** [parse-community/Parse-SDK-JS#1111]
### Issue Description

When upgrading the JS SDK, trying to run `flow` causes an error in the `parse` node module:
```
Error -┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/parse/lib/react-native/encode.js:66:7

Unexpected token :, expected the token ,

     63│     return {
     64│       __type: 'Date',
     65│       iso: value
     66│       /*: any*/
     67│       .toJSON()
     68│     };
     69│   }

Found 1 error
```

### Steps to reproduce

I've set up a repository that tries to use the latest `flow-bin` and the latest `parse` modules at the same time.

```sh
git clone https://github.com/noahsilas/parse-flow-repo
cd parse-flow-repo
npm install
npm run flow
```

### Expected Results

There should not be any errors.

### Actual Outcome

The error shown above is emitted.

### Test Case

Altering the version of the parse sdk loaded, I've found that this appears to have started happening in the 2.1.x series. In the repro app, you can try the following:

```sh
npm install --save parse@2.0.2
npm run flow
# no errors!

npm install --save parse@2.1.0
npm run flow
# errors!
```

**Comment by dplewis** [comment]
I’m surprised travis ci didn’t catch this. Interesting

**Comment by dplewis** [comment]
@noahsilas Can you check if the latest SDK release fixed this issue?

**Comment by noahsilas** [comment]
Looks like it's fixed! Thank you!
