### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by rabidaudio** [parse-community/Parse-SDK-JS#112]
I've been publishing the Parse SDK to [bower](http://bower.io) since about `v1.3.1` from my repo over here: https://github.com/rabidaudio/bower-parse

I was [recently made aware](https://github.com/rabidaudio/bower-parse/pull/9) that this NPM package exists, and I think ideally this repo should adopt managing bower publishing as well. I'm happy to unpublish it from bower so that y'all can use the namespace. There are a few sticky issues though that I want to bring up:
1. Bower requires that the built versions (i.e. `/dist`) be included in the repository. This isn't a huge deal, except that every tagged version needs to be retroactively updated to include the compiled versions and the proper `bower.json` file.
2. Versions dating back to `1.3.1` are on bower currently, but this repo only goes back to `1.6.4`. So theoretically some users may still be on older versions, meaning there needs to be some way to backport to these versions as well.

One way to solve this:
- for `1.6.4` to present: make a new commit which is exactly the same as the tagged commit, plus bower.json and the build files. Then force-retag the new commit. That shouldn't break new/existing npm users because all the expect files are there, and it should work for bower users as well.
- for `1.3.1` to `1.6.4`: make new commit that is basically a cherry-pick from that snapshot on my repo. this should work for bower users. I'm pretty sure NPM won't report those versions as available without a `package.json` file, so npm users should be unaffected.

I can send a PR and help transfer publishing ownership, but I want y'all's thoughts first.

Related:
#9 #26 #94

**Comment by andrewimm** [comment]
@rabidaudio really appreciate the effort you've gone through to make our SDK available through bower.
We're still discussing whether we want to add bower as another official distribution channel, since it adds more effort on our end with each release, and requires significant modification of the past git tree. We'll update here as we consider this move, but in the meantime I wanted to let you know that we've seen your post and are actively churning on this.

**Comment by rabidaudio** [comment]
Thanks for the update. Let me know what you decide.

**Comment by cleever** [comment]
Any updates on this?

**Comment by andrewimm** [comment]
I'm not exactly excited about taking on the responsibility of adding yet another distribution channel to the release process. If the community wants to continue doing this, we'd support that. Regarding the associated PR, if we choose to officially support bower, we'll take the ReactJS approach of maintaining a separate repository for builds. Builds should not live in this repo.

**Comment by cleever** [comment]
thanks @andrewimm

**Comment by rabidaudio** [comment]
That's fine. I created an IFTTT to open an issue on new releases, which should help me stay on top of it. Let me know if you ever decide to adopt it.

**Comment by lebobbi** [comment]
Any news about this?

**Comment by flovilmart** [comment]
as mentioned by @andrewimm we'll not move forward with builds in this repository, but we can automate bower builds through CI or a hook.
