### ISSUE TITLE
Updating file is not allowed

### ISSUE THREAD

**Issue by JeromeDeLeon** [parse-community/Parse-SDK-JS#1130]
### Issue Description

I just tried the new feature of Parse.File, and unfortunately, adding metadata on existing Parse.File object will result to an error saying that `Cannot read property 'format' of undefined`.

### Steps to reproduce

1. Create a `Sample` class
2. Add a `profile` column with Parse.File as it's type
3. Add new row by attaching a sample file
4. Query it using Parse JS sdk
5. Add metadata
6. Save

### Expected Results

Able to update the file or it's metadata or tags

### Actual Outcome

```js
TypeError: Cannot read property 'format' of undefined
    at ParseFile.value (ParseFile.js:412)
```

### Test Case

To accurately reproduce your issue. Add your test cases [here](https://github.com/parse-community/Parse-SDK-JS/tree/master/integration/test) and read the [Contributing Guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/CONTRIBUTING.md) to run the tests. 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.1.0
  - Operating System:     Ubuntu 18.04
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **JS SDK**
  - JS SDK version: 2.12.0
  - Application? (Browser, Node, React-Native, etc): Browser

### Logs/Trace

I tried logging before saving

```js
{
  _name: "ff4191d6149de942d1f720c12052a5b3_sample.jpg"
  _url: "http://localhost:7000/v1/files/sampleKey/ff4191d6149de942d1f720c12052a5b3_sample.jpg"
  _source: undefined
  _previousSave: undefined
  _data: undefined
  _requestTask: undefined
  _metadata: {foo: 1}
  _tags: {}
}
```

**Comment by dplewis** [comment]
@JeromeDeLeon Can you add an integration test case?

**Comment by stevestencil** [comment]
You can only add metadata and tags to a file that has not been saved already. You can do this on the client side or in the beforeSaveFile trigger. @dplewis should we add logic that will either throw an error or fail silently if metadata or tags are added to an already saved file?

**Comment by JeromeDeLeon** [comment]
May I know why is that the case?

**Comment by stevestencil** [comment]
1) Parse-server API does not support updating files
2) The file adapters do not support updating files (only create, get, and delete)
3) S3 does not support updating of metadata at all (it has to be set when you create the file). (I'm not sure about other storage solutions with updating metadata)

**Comment by JeromeDeLeon** [comment]
This become useless when you have an existing files tho and decided to update this to latest version but since we couldn't do something if the file storage itself doesn't want to support it. Thanks for clarification.
