### ISSUE TITLE
Parse client side parsing or conversion of Pointer array 

### ISSUE THREAD

**Issue by rizzla22** [parse-community/Parse-SDK-JS#1132]
Parse community is down so I cant ask there. Can you point me in the right direction as Im not sure is this handled serverside or client side with the JS SDK. 

I have the following function where likes is an array of parse profile pointers, what is the optimium way to convert these pointers to full profile objects which can be accessed client side, client side I either get an object that cant be iterated or just `like.id` for each one. 

Is there something built into parse like a mysql join that pulls this data into the query as it happens and delivers it to the client side ? or is there something client side which can parse and decode these pointer arrays.

```
async function loadTimeline(request: FunctionRequest): Promise<any> {
    
const timeline = new Parse.Query(Timeline)     
 let postsFound = await timeline.find(masterKey)
 
 let posts = postsFound.map( post => {
     return {
        id: post.id,
        likes: post.get('likes'),        
        post: post.get('post'),
        createdAt: post.createdAt 
     }
 })
 
 return posts

}
```

for reference when a user likes a post I get the profile pointer on the _User collection and store it using profile.toPointer() like so - perhaps I dont need to use toPointer() if its already a pointer but im not sure the best approach on this.

```
    let user: Parse.User = getUser(request)    
    let profile = user.get('profile')   
    likes.push(profile.toPointer())
```

**Comment by JeromeDeLeon** [comment]
You could use `include` or `includeAll` to fetch the pointed data like `pointers` or `array of pointers`.

```js
const timeline = new Parse.Query(Timeline)     
let postsFound = await timeline.include('likes').find(masterKey)
```

It allows you to access the `profile` object like so:

```js
// imagine you have firstName field living inside _User class
post.get('likes')[0].get('firstName')
```

**Comment by JeromeDeLeon** [comment]
Is `likes` an array? because I saw you just used `push` . FYI, we also have `add` families like `addUnique`, `addAll`, `addAllUnique` to add a ParseObject to particular field:

```js
let user: Parse.User = getUser(request)    
let profile = user.get('profile')

// without toPointer also works
post.add("likes", profile)
```

**Comment by rizzla22** [comment]
That’s awesome I didn’t know about add etc

**Comment by dplewis** [comment]
@rizzla22 Can this be closed?
