### ISSUE TITLE
Ability to verify password

### ISSUE THREAD

**Issue by JeromeDeLeon** [parse-community/Parse-SDK-JS#1139]
**Is your feature request related to a problem? Please describe.**
I'm having this use case where I need to verify the password first before proceeding to the next action even though the user had already logged in. This would also be useful to other use case like confirming current password before changing to new password.

**Describe the solution you'd like**
It would be better for the SDK to provide `verifyPassword` for verifying password of currently logged in user.

**Describe alternatives you've considered**
For now, I saw [verifyPassword REST API](https://github.com/parse-community/parse-server/blob/09a1dca5e3605e1e4cd2db62a9594dc0e698e663/src/Routers/UsersRouter.js#L475) and decided to use it for now.

**Comment by dplewis** [comment]
Good catch! Also `verificationEmailRequest` is missing too. Would you like to start a PR for it?

**Comment by JeromeDeLeon** [comment]
Will do. I'll update you when it’s done.

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/1144
