### ISSUE TITLE
LiveQuerySubscription "open" event does not fire as expected

### ISSUE THREAD

**Issue by travsr** [parse-community/Parse-SDK-JS#1147]
### Issue Description
When I register an `open` event for a `LiveQuerySubscription`, the event does not fire on the intial websocket `subscribed` event as you'd expect. However, if it does fire if a reconnect happens.

My guess is the fact that you now have to wait for the subscription object to be returned via promise from `query.subscribe()` may be the cause. By the time you are able to register your event, the "open" event  will already have been emitted by `LiveQueryClient`.

My quick fix was to add a slight timeout delay before the `open` event is emitted in `LiveQueryClient.js`, but that seems like more of a hack than a real solution.

Maybe I was just doing something wrong but this seemed like something potentially worth posting here.

### Test Case
```
let query = new Parse.Query("MyClass");
let subscription = await query.subscribe();

subscription.on('open', (response) => {

    // (the stuff in here will not run)
    console.log("SUBSCRIPTION OPENED"); // <-- does not print to console
   
});
```

To accurately reproduce your issue. Add your test cases [here](https://github.com/parse-community/Parse-SDK-JS/tree/master/integration/test) and read the [Contributing Guide](https://github.com/parse-community/Parse-SDK-JS/blob/master/CONTRIBUTING.md) to run the tests. 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : ^4.2.0
  - Operating System:     macOS 10.15.4
  - Localhost or remote server?: Localhost

- **JS SDK**
  - JS SDK version: ^2.12.0
  - Application?: Browser

**Comment by dplewis** [comment]
You brought up an interesting point. The point of waiting for the subscription is to ensure the connection is successful, resulting in the open event to not fire.

We should remove it from the documentation.

@acinader @davimacedo Thoughts?

**Comment by dplewis** [comment]
@travsr Can you post your quick fix? I'm curious on how you got it to work.

**Comment by davimacedo** [comment]
@dplewis what do you want to remove from the docs? The open event?

**Comment by dplewis** [comment]
@davimacedo Hmm we could add a slight delay [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/LiveQueryClient.js#L377). This will allow client time to set an Open Event.

**Comment by davimacedo** [comment]
Yes. Just `setTimeout(() => subscription.emit(SUBSCRIPTION_EMMITER_TYPES.OPEN, response));` should do the magic.

**Comment by travsr** [comment]
@dplewis @davimacedo Yep that's exactly where I added it in my code as well :) I used 200 ms  and it hasn't given me issues so far.
