### ISSUE TITLE
Callbacks for certain events

### ISSUE THREAD

**Issue by stevestencil** [parse-community/Parse-SDK-JS#1153]
**Is your feature request related to a problem? Please describe.**
I would like to be able to register a callback that can be called anytime certain events happen anywhere in the app. For example:
- An invalid session token error is thrown
- User did login
- User did logout

In the iOS SDK there are NSNotifications that can be listened to for certain events. Having the same capability in the Javascript SDK would be great.

**Describe the solution you'd like**
Being able to call something like `Parse.registerCallback('login', () => {})` or `Parse.registerCallback('invalidSession', () => {})` so that the passed in function will be called when certain events happen anywhere in the app.

**Describe alternatives you've considered**
None

**Additional context**
I can submit a PR for this if the community thinks it will be beneficial

**Comment by JeromeDeLeon** [comment]
Not sure about the iOS, but we did a global error handler that verifies for invalid session token and other errors. We put that inside `catch` of every promise or `error` callback of RxJS.

For the login/logout, is using `then(callback)` not enough?

**Comment by dplewis** [comment]
Most front end frameworks support event emitter or pub sub built in. I think this would introduce a lot of overhead.

Feel free to do a PR, we'll review it.
