### ISSUE TITLE
Unsuccessful cancellation of Parse File

### ISSUE THREAD

**Issue by JeromeDeLeon** [parse-community/Parse-SDK-JS#1162]
### Issue Description

I was trying to cancel an a PFile when I noticed in my network that it successfully cancelled the PFile but created another request to continue saving the file. I tried checking who called it the second time and to my surprise, it went another attempt to save the file because of [this](https://github.com/parse-community/Parse-SDK-JS/blob/0923c93aecd2ad46f4c0d03e8a838e5fa8eeafa2/src/RESTController.js#L129).

### Steps to reproduce

1. Create a ParseFile using JS SDK
2. Save it
3. Create a setTimeout to mimic interruption after 2s
4. Cancel it

### Expected Results

Cancel the file

### Actual Outcome

Cancel the first request, then shortly after created another request to continue the previous one.

### Test Case

I don't know how will I be able to reproduce this one on a test

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 4.2.0
  - Operating System:     Ubuntu 18.04
  - Hardware:             
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **JS SDK**
  - JS SDK version: 2.13.0
  - Application? (Browser, Node, React-Native, etc): Browser

### Logs/Trace

![image](https://user-images.githubusercontent.com/32805276/81147698-6d0e7680-8fad-11ea-8dce-2d15360acf0d.png)

**Comment by mtrezza** [comment]
That's an interesting one! Does it affect all requests to parse server or only Parse.File requests?

**Comment by baradatbiu** [comment]
@JeromeDeLeon Hello, did you figure out how to cancel a file upload?
Because I have the same problem after canceling, the Parse tries to upload the file 4 more times (if you cancel each one).

**Comment by JeromeDeLeon** [comment]
@baradatbiu Unfortunately no and I'm not even sure if it was fix now since I haven't used this lib in a long time.

**Comment by mtrezza** [comment]
I'll reopen this as the issue still seems to be exist as indicated by @baradatbiu's comment. This as been closed by the stale bot which has since been disabled.
