### ISSUE TITLE
Caching in JS SDK

### ISSUE THREAD

**Issue by srameshr** [parse-community/Parse-SDK-JS#118]
Support for caching api requests out of the box would be a good feature.  Is this anywhere on the roadmap?

**Comment by wangmengyan95** [comment]
Hi @srameshr, right now we do not have a plan for that. But we are welcome pull request if you are interested to make one and share with the community.

**Comment by florent1933** [comment]
:+1:

**Comment by srameshr** [comment]
Anybody who has done this already? Cordova apps suffer without caching on
JS SDK. Using REST API does not seem as a good solution.

**Comment by florent1933** [comment]
I am looking for something like you @srameshr. Definitely, we need caching.

**Comment by srameshr** [comment]
Yup! Cordova apps are suffering because of it. Right now I am using
angularCache to work with this.

**Comment by florent1933** [comment]
I used angularCache for another app but my current project is developed with emberJS.

**Comment by srameshr** [comment]
How are you doing it? 
When you run ```Parse.Cloud.run``` how do you let it know when to use cache or expire cache.

**Comment by florent1933** [comment]
I only used cache when the data allow to do it. We have an approach
"cacheFirst". So we don't have code in *Parse.Cloud*

2016-02-12 8:38 GMT+01:00 Siddharth Ramesh <notifications@github.com>:

**Comment by srameshr** [comment]
I did not quite get that.
