### ISSUE TITLE
.fields() doesn't work on ParseLiveQuery JS

### ISSUE THREAD

**Issue by dblythy** [parse-community/Parse-SDK-JS#1184]
Not sure if this is an issue with Parse Server, or the JS SDK.

However, [ParseLiveQuery server](https://github.com/parse-community/parse-server/blob/master/src/LiveQuery/ParseLiveQueryServer.js#L680) states:

`subscriptionInfo.fields = request.query.fields`

Yet I could not find any way to set `.fields` on the request query.

I presume `.select` is intended for this, however I don't think [ParseQuery](https://github.com/parse-community/Parse-SDK-JS/blob/824713fd9332ebbf19e3148525fd5a5adfdcb3f8/src/ParseQuery.js#L1758) ever passes `.select()` to `.fields`.

My workaround for JS was to set `query.fields = ['']`.

Happy to work on a PR if need be!

**Comment by dplewis** [comment]
It should work as the keys are passed in [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/LiveQueryClient.js#L291)

Does your live query return all keys? Can you write a test case?

**Comment by dblythy** [comment]
Will do!

**Comment by dblythy** [comment]
```
    const object = new TestObject();
    object.set('baz','qux')
    await object.save();

    const query = new Parse.Query(TestObject);
    query.select('baz')
    
    const subscription = await query.subscribe();
    subscription.on('update', async (newObject, object) => {
      fail("field 'foo' wasn't selected, create shouldn't fired.")
    });
    
    object.set({ foo: 'bar'});
    await object.save();

    setTimeout(() => {
        done();
    }, 1000);
```

**Comment by dplewis** [comment]
@dblythy I opened a PR with a test case https://github.com/parse-community/Parse-SDK-JS/pull/1203

It works for me. Let me know if it accurately represents the issue you are having

**Comment by dblythy** [comment]
Thank you mate. I might have misunderstood the [LiveQuery docs](https://github.com/parse-community/parse-server/wiki/Parse-LiveQuery-Protocol-Specification).

> Suppose the ParseObject Player contains three fields name, id and age. If you are only interested in the change of the name field, you can set query.fields to [name].

My thinking is that "update" should only fire when "name" is changed (if "fields" is selected).

Is that correct?

**Comment by dplewis** [comment]
Interesting. I actually don't know. I was focused on this part.

> when the change of a Player ParseObject fulfills the subscription, only the name field will be sent to the clients instead of the full Player ParseObject

I assumed it would function just like `.select`.  

@parse-community/core-maintainers What should the proper implementation for this be?

**Comment by dplewis** [comment]
@dblythy Oh I see what you were trying to do in your example.

**Comment by dblythy** [comment]
In my use case, I am creating a LiveQuery on the _User class, but I only need updates on the "notificationCount" field, which is incremented on an afterSave trigger.

I.e

```
const query = new Parse.Query(Parse.User);
query.select("notificationCount");

const subscription = await query.subscribe();
subscription.on('update', (object) => {
      this.notificationCount = object.get('notificationCount');
})
```

I don't want the update event to fire when "firstName" / "email" is updated.

I can easily compare originalObject and newObject but I was thinking fields would be more efficient to be implicitly choose which keys you want to listen to changes in, restricting the amount of LQ messages being sent too.

**Comment by dblythy** [comment]
@dplewis what do you think about the addition of a few more LQ triggers, `beforeCreate` and `beforeUpdate`? I'm thinking that these could be like an afterFind trigger, and maybe throwing from the triggers could be silent and just prevent the event from being called.

I could do something like:

Parse.Cloud.beforeUpdate(Parse.User, request => {
    if (!request.object.dirty('Notifications')) {
        throw "No need to run update event as notifications haven't changed."
    }
})

I can't think of too many use cases where restricting the query using `beforeSubscribe` wouldn't cover restricting the liveQuery events (other than .dirty), but maybe this way it could provide flexibility for users to decide for themselves.

**Comment by dplewis** [comment]
@parse-community/core-maintainers What do you guys think?

**Comment by davimacedo** [comment]
I'd prefer to have an additional option in the current triggers for not broadcasting the change. Or, if stop the broadcasting is the use case, wouldn't be better to improve the current logic to not broadcast when not needed by default?

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server/pull/6859
