### ISSUE TITLE
crypto-js:4.0.0 dependency crashes React Native app

### ISSUE THREAD

**Issue by WAGuerra** [parse-community/Parse-SDK-JS#1201]
### Issue Description

`crypto-js:4.0.0` dependency from `parse:>2.11.0`  is incompatible with `react-native` see [this](https://github.com/brix/crypto-js/issues/256#issuecomment-585175130). 

### Steps to reproduce

Include a parse `>2.11.0`as a dependency on a react-native project.

### Expected Results

To run app without error.

### Actual Outcome

Application crashes with error:
```
Unable to resolve module `crypto` from `node_modules/crypto-js/core.js`: crypto could not be found within the project.
```

### Environment Setup
- **JS SDK**
  - JS SDK version: >2.11.0
  - Application? (Browser, Node, React-Native, etc): React-Native

### Logs/Trace
```
error: Error: Unable to resolve module `crypto` from `node_modules/crypto-js/core.js`: crypto could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
```

**Comment by dplewis** [comment]
Can you fork the project. Downgrade crypto-js to 3.3.0. Build it and use it in your project to see if that fixes the issue?

**Comment by WAGuerra** [comment]
As soon as I can I will try that.

**Comment by WAGuerra** [comment]
I guess I am missing something on build.

 I am getting:
```
error: Error: Unable to resolve module `parse/react-native` from `app/app.tsx`: parse/react-native could not be found within the project.
```

My fork is [here](https://github.com/WAGuerra/Parse-SDK-JS)

**Comment by dplewis** [comment]
Have you tried `npm link`?

**Comment by dplewis** [comment]
@WAGuerra Any progress on this?

I'm looking at the [CryptoController](https://github.com/parse-community/Parse-SDK-JS/blob/040e8c1cbf82270aec145e1af1efd24cc53bc5dd/src/CryptoController.js) It shouldn't use crypto-js for react-native builds

**Comment by WAGuerra** [comment]
Finally got time to see this.

Downgrade to crypto 3.0.0 didn't work.

**Comment by dplewis** [comment]
Did you get the same error? Can you try 3.3.0? Can you look in your new build and see if crypto-js is used anywhere? I don't think crypto-js is a dependency of the other node packages we use.

**Comment by WAGuerra** [comment]
Same error. 
Well running `npm ls`
i've got:
```
├─┬ parse@2.14.0
│ ├── @babel/runtime@7.10.2 extraneous
│ ├── @babel/runtime-corejs3@7.10.2 extraneous
│ ├── crypto-js@4.0.0 extraneous                               <---- dep here
│ ├── react-native-crypto-js@1.0.0
│ ├── uuid@3.3.3 extraneous
│ ├── ws@7.3.0 extraneous
│ └── xmlhttprequest@1.8.0
```

**Comment by dplewis** [comment]
Why is it 2.14.0?

**Comment by WAGuerra** [comment]
Well, I don't know. I just clone the repo and changed the crypto dep to `"crypto-js": "3.3.0"`. After that I run build and then `npm ls`.

**Comment by dplewis** [comment]
Thanks for looking into this. We use parse-server as a dev dependency. 

parse-server -> parse@2.14.0 -> crypto-js@4.0.0

**Comment by WAGuerra** [comment]
You're well come.

**Comment by WAGuerra** [comment]
> Have you tried `npm link`?

By the way, I have cleaned the cache to get it to work.

```
watchman watch-del-all && rm package-lock.json && rm -rf node_modules && rm -rf $TMPDIR/metro-* && rm -rf $TMPDIR/haste-map-* && npm install
```
extracted from [here](https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d#gistcomment-2785627)

**Comment by dplewis** [comment]
I'll open a PR to downgrade crypto to 3.3.0 if it works.

**Comment by dplewis** [comment]
@WAGuerra I edited my last comment

**Comment by WAGuerra** [comment]
> I'll open a PR to downgrade crypto to 3.3.0 or does it work with 4.0.0?

[doesn't work with 4.0.0 or any version above 3.3.0 for now](https://github.com/brix/crypto-js/issues/256#issuecomment-585175130)

**Comment by dplewis** [comment]
Can you try to move crypto-js to optionalDependencies, rebuild and see if that works.

```
"optionalDependencies":{
  "crypto-js":"4.0.0"
}
```
