### ISSUE TITLE
Feature saveEventually for offline use

### ISSUE THREAD

**Issue by KAIOAVILA** [parse-community/Parse-SDK-JS#1230]
I have difficulties in implementing an offline-first application in react native, due to the lack of a very essential functionality to work well, which in the sdk of Android and iOS has to be saveEventually.  Because if not, I have to use another database to keep track of it.  Firebase has this functionality implemented in their lib.

implement something like what you have in the Android and iOS sdk.  I only talked about save, but there is also delete.  use some solution to store in storage to store these objects and when you resume the network synchronize with Parse.  https://docs.parseplatform.org/android/guide/#saving-objects-offline

**Comment by dplewis** [comment]
I tried working on something similar after I added the LDS. You can view the conversation [here](https://github.com/parse-community/Parse-SDK-JS/pull/734#issuecomment-463011648).

I'd be more that happy to discuss a strategy with you based off the existing implementation in iOS and Android.

**Comment by meepeek** [comment]
Seems there was an attempt for JS SDK saveEventually on Titanium. It may be useful for the implementation. Link as follow

https://gist.github.com/cr0ybot/001c5aafcfd35251304961670287ee21

I'm not very deep into the code. Hope this help. Also react and react native webapp quite popular nowadays, I wish this would have been implemented.

**Comment by dplewis** [comment]
@meepeek Thanks that’s really helpful. The only problem I see it how to tell if the network connection is offline / online. I would like to avoid using the RestController since its only goal should be to send requests.

**Comment by meepeek** [comment]
@dplewis 
should we make it part of livequery ? this way the client must connect ws then we can check on ws status.

**Comment by dplewis** [comment]
Not user had a Live Query server set up. But now that you mention it. We could add an emitter to the RestController to check if there is connection / deconnection
