### ISSUE TITLE
[Svelte] - ParseError: /node_modules/crypto-js/crypto.js

### ISSUE THREAD

**Issue by lamualfa** [parse-community/Parse-SDK-JS#1249]
## Problem

**Code**
```js
import Parse from 'parse';
```
Yes, the code is just that. But the code above gives an error, the error is:

```bash
ParseError: /node_modules/crypto-js/crypto.js
Error: ENOENT: no such file or directory, open '/home/lamualfa/Repository/dashboard-2/node_modules/crypto-js/crypto.js'
    at compileModule (/home/lamualfa/Repository/dashboard-2/node_modules/nollup/lib/impl/NollupCompiler.js:116:19)
```

I have also tried to install `crypto-js@^4.0.0` as `dependencies`. I have also done the same for version `crypto-js@^3.3.0`. And errors keep appearing.

I am using `rollup` and `@rollup/plugin-node-resolve` to use Node JS core library in Browser (Crypto). The following is the config for `@rollup/plugin-node-resolve` in `rollup.config.js`:

```js
{
   plugins: [
      resolve({
         browser: true,
         dedupe: (importee) => !!importee.match(/svelte(\/|$)/),
         preferBuiltins: true
      })
   ]
}
```

Is there a way to fix it?

## Environment

- `parse`: `^2.17.0`
- `svelte`: `^3.29.4`

**Comment by dplewis** [comment]
@lamualfa This doesn't look like an issue with the SDK. We released a 2.18.0 update that you can try.

I'm not familiar with rollup but if you install crypto-js can check `node_modules/crypto-js/crypto.js` that file doesn't exists. [crypto-js/src](https://github.com/brix/crypto-js/tree/develop/src).

You can try to change your config to `dedupe: [ 'crypto-js', 'crypto' ]` or `preferBuiltins: false`.

**Comment by lamualfa** [comment]
@dplewis I'm a little confused. when I don't import the `parse` library, the error won't occur. But if I do the opposite, the error will return.

After I set the options for `@rollup/plugin-node-resolve` to:

```js
{
   plugins: [
      resolve({
         browser: true,
         dedupe: ['svelte', 'crypto-js', 'crypto']
      })
   ]
}
```

The following error will appear:

```bash
ParseError: /node_modules/crypto-js/crypto.js
Error: ENOENT: no such file or directory, open '/home/lamualfa/Repository/dashboard/node_modules/crypto-js/crypto.js'
    at compileModule (/home/lamualfa/Repository/dashboard/node_modules/nollup/lib/impl/NollupCompiler.js:116:19)
```
I never use `crypto-js` library in my code. But why does the error point to the `crypto-js` library?

The same error will appear if you use the following settings:

```js
{
   plugins: [
      resolve({
         browser: true,
         dedupe: ['svelte'],
         preferBuiltins: true
      })
   ]
}
```

<hr>

and if I set the options for `@rollup/plugin-node-resolve` to:

```js
{
   plugins: [
      resolve({
         browser: true,
         dedupe: ['svelte', 'crypto-js', 'crypto'],
         preferBuiltins: false   // Line added
      })
   ]
}
```

Another error will appear:

```bash
ParseError: crypto
Error: ENOENT: no such file or directory, open '/home/lamualfa/Repository/dashboard/crypto'
    at compileModule (/home/lamualfa/Repository/dashboard/node_modules/nollup/lib/impl/NollupCompiler.js:116:19)
```
The same error will appear if you use the following settings:

```js
{
   plugins: [
      resolve({
         browser: true,
         dedupe: ['svelte'],
         preferBuiltins: false
      })
   ]
}
```
<hr>

So what can I do to solve the above error? all the above errors only appear when I import the `parse` library into my code.

**Comment by dplewis** [comment]
Can you try `import Parse from 'parse/dist/parse.min.js';`

**Comment by dplewis** [comment]
@lamualfa I opened a PR https://github.com/parse-community/Parse-SDK-JS/pull/1252 We will try to  improve the way to import the SDK into web based projects.

**Comment by lamualfa** [comment]
> Can you try `import Parse from 'parse/dist/parse.min.js';`

Work with this. Thank You.
