### ISSUE TITLE
Isomorphic javascript client library.

### ISSUE THREAD

**Issue by ravikumarmistry** [parse-community/Parse-SDK-JS#1258]
**Is your feature request related to a problem? Please describe.**
I wanted to use the parse-client with nativescript app but as far as I can see this library uses some of the javascript modules which are not available in nativescript runtime (Ex. local storage, crypto,). Can we redesign this library using only modules which are available stripdown javascript runtime. If we can do that we do not need to import different modules for different platform(like react, nativescript, node, web browsers, ionic, electron etc).

**Comment by dplewis** [comment]
@mtrezza @davimacedo @dblythy The library is nearly isomorphic. The CoreManager will allow for developers to add missing implementations for different platforms. The CoreManager is also missing documentation. Testing against react-native build would benefit from this as we would have to add missing implementations.
