### ISSUE TITLE
ParseObject: get multiple attributes with "get"

### ISSUE THREAD

**Issue by vince1995** [parse-community/Parse-SDK-JS#1259]
Would be great if it's possible to retreive multiple attributes with the `get` function in Parse Objects:

`const { foo, bar, test } = object.get(["foo", "bar", "test"]);`

**Comment by davimacedo** [comment]
you can do `const { foo, bar, test } = object.attributes`

**Comment by vince1995** [comment]
I know but I want to hold my code clean and use only official API endpoints.

**Comment by davimacedo** [comment]
Why do you believe the way you are proposing is cleaner? object.attributes is an official endpoint: https://parseplatform.org/Parse-SDK-JS/api/2.18.0/Parse.Object.html#attributes

**Comment by vince1995** [comment]
Oh man, didn't noticed that. Ok, thank you. But why are there a set and get function if it's ok to set attributes via the attributes key?
