### ISSUE TITLE
[Documentation] MasterKey in Parse.File.destroy()

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-JS#1272]
The `Parse.File.destroy()` method in the JS SDK requires the use of `masterKey` according to documentation, to destroy a file. See [JS SDK guide](https://docs.parseplatform.org/js/guide/#deleting-files).

Setting `masterKey: false` or not setting it at all has no effect and deleting the file succeeds. You can only delete files server side.

I think we need to either change the docs or the code, they are currently inconsistent.

If we change the code we can add more options like `sessionToken` in the future.

**Comment by mtrezza** [comment]
Thanks, that is very well written 😁
