### ISSUE TITLE
Do not support fieldName 'length' on Mongo 4.X

### ISSUE THREAD

**Issue by Moumouls** [parse-community/Parse-SDK-JS#1277]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Issue name

### Steps to reproduce

Run Parse SDK JS integration test with a mongo version 4.X
### Actual Outcome
Cannot save object with a field "length"

### Expected Outcome

Can save the object

###  Environment

Server
- Parse Server version: `master`
- Operating system: `macOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `Mongo`
- Database version: `4.X`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- Parse JS SDK version: `master`

### Logs

```
Failures:
1) Parse LocalDatastore Parse Query Pinning (Default) Default supports objects with length
  Message:
    Error: Invalid field name: length.
  Stack:
    error properties: Object({ code: 105 })
    Error: Invalid field name: length.
        at handleError (/Users/antoinecormouls/Desktop/OpenSource/Parse-SDK-JS/lib/node/RESTController.js:422:17)
        at <Jasmine>
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

2) Parse LocalDatastore Parse Query Pinning (React-Native) React-Native supports objects with length
  Message:
    Error: Invalid field name: length.
  Stack:
    error properties: Object({ code: 105 })
    Error: Invalid field name: length.
        at handleError (/Users/antoinecormouls/Desktop/OpenSource/Parse-SDK-JS/lib/node/RESTController.js:422:17)
        at <Jasmine>
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

3) Parse Query supports objects with length
  Message:
    Unhandled promise rejection: ParseError: 105 Invalid field name: length.
  Stack:
    error properties: Object({ code: 105 })
    Error: Invalid field name: length.
        at handleError (/Users/antoinecormouls/Desktop/OpenSource/Parse-SDK-JS/lib/node/RESTController.js:422:17)
        at <Jasmine>
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by dplewis** [comment]
This is expected behavior. 

https://github.com/parse-community/parse-server/pull/7053

I can open a PR to fix the tests.
