### ISSUE TITLE
Change default login method to POST

### ISSUE THREAD

**Issue by jjunineuro** [parse-community/Parse-SDK-JS#1283]
Hello everyone,

I really liked the application, however, I saw that the method for logging in with email and password uses the GET method.

I know that being in secure SSL connection this data is encrypted, however, according to the current Data Protection Laws, the login data is in the request log on the server, this is not at all interesting.

Imagine Parse's paid consumer services, the network administrator will have access to all users and user passwords. This is not cool.

Therefore, I hereby suggest changing the Login class with email and password to use the POST method.

The following image link of what I am explaining.

[https://ibb.co/Y0Q1j3P](https://ibb.co/Y0Q1j3P)

**Comment by jjunineuro** [comment]
Hello, thank you very much for your help.

I made the change in the Parse Javascript SDK and it worked.

But when testing on the Ass Flutter SDK, I don't have this option and I can't login using the POST method.

Could you help me with the Parse Flutter SDK too?

**In the Parse Flutter SDK**
![fluttersdk](https://user-images.githubusercontent.com/30479720/104033586-a431c900-51c7-11eb-845a-563f5edcb5c8.png)

**In the Parse Javascript SDK**
![javascriptsdk](https://user-images.githubusercontent.com/30479720/104033867-068ac980-51c8-11eb-940f-8d9f9dbd7537.png)

**Comment by dplewis** [comment]
@mtrezza @davimacedo  The login only supported GET initially which is why the SDK have a GET and not POST since POST was added later on.

It was added 3 years ago to the server, released on version [2.6.4](https://github.com/parse-community/parse-server/releases/tag/2.6.4).

PR -> https://github.com/parse-community/parse-server/pull/4268

Since it was so long ago, we can make POST the default.

What do you guys think?

**Comment by mtrezza** [comment]
Yes, POST can be default now, we should mark it as breakfast change though in case someone has a restrictive firewall based on the endpoint / http method combination.

@jjunineuro Would you please open a separate issue for in Flutter SDK repo and reference this issue?

**Comment by jjunineuro** [comment]
Yes @mtrezza, it already opens the problem in the Flutter SDK.

Thank you!!!

**Comment by mtrezza** [comment]
Thanks @jjunineuro, for pointing this issue out. Would you also want to open a PR in any of the SDKs to fix this?

**Comment by jjunineuro** [comment]
Yes @mtrezza , I appreciate the opportunity to contribute. But I have advanced knowledge, I tried to understand the code, but I didn't see the calls through the Login in the Flutter SDK. But I will dedicate a few hours to understand and implement this improvement.

**Comment by mtrezza** [comment]
Great! If you need any guidance please feel free to ask.
