### ISSUE TITLE
ParseObject:  Add callback/trigger before save() and after find()

### ISSUE THREAD

**Issue by sadortun** [parse-community/Parse-SDK-JS#1314]
**Is your feature request related to a problem? Please describe.**
We need to transform data stored in a `ParseObject` before it's sent to the server, and once again when received from the server via `find()` 

Currently, there is no way to do this that is convenient.

**Describe the solution you'd like**

```js

// This is just an example  IRL `addTrigger`,  `beforeSave` and `afterFind` 
// are terrible keywords to use since they will 100% be confused with Parse.Cloud :)

class MyObjectWithSecrets extends Parse.Object {
  constructor() {
    super('MyObjectWithSecrets')

    this.addTrigger('beforeSave', object => {
      object.set('secureField', crypto.encrypt(object.get('secureField'), key))
    })

    this.addTrigger('afterFind', object => {
      object.set('secureField', crypto.decrypt(object.get('secureField'), key))
    })
  }
}
```

```js
// 2nd idea, add an `options` param to the constructor

class MyObjectWithSecrets extends Parse.Object {
  constructor() {
    super('MyObjectWithSecrets' , {
      beforeSave: object => {
        object.set('secureField', crypto.encrypt(object.get('secureField'), key))
      },
      afterFind: object => {
        object.set('secureField', crypto.decrypt(object.get('secureField'), key))
      }
      
    })
  }
}
```

**Describe alternatives you've considered**

We will probably have to override `Parse.Object.toJSON()` and `ParseObjec.fromJSON()`. The downside of this is we dont know the `Parse.Object` internals and if this is the best solution that will also be future-proof
```js
class MyObjectWithSecrets extends Parse.Object {
  constructor() {
    super('MyObjectWithSecrets')
  }
  toJSON() {
    this.set('secureField', crypto.encrypt(this.get('secureField'), key))

    return super.toJSON(arguments)
  }
  fromJSON() {
    const object = super.fromJSON(arguments)
    object.set('secureField', crypto.decrypt(object.get('secureField'), key))

    return object
  }

}
```

**Additional context**

**Comment by dplewis** [comment]
I had a similar idea a few years ago but we decided against it. You can try something like this
https://github.com/parse-community/Parse-SDK-JS/pull/731/files#diff-1268d6624e04364bc06fce6d6d5c3aa8158c753293ee31c86a37829c6e05c8a4R1993

**Comment by sadortun** [comment]
Thanks, I'll probably do what I mentioned in the alternate solution above.

It's also what was done in https://github.com/parse-community/Parse-SDK-JS/issues/594#issuecomment-403409633

Thanks
