### ISSUE TITLE
package is too much to wechat weapp

### ISSUE THREAD

**Issue by jackyang1984** [parse-community/Parse-SDK-JS#1331]
### New Issue Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ ] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [ ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

As we knows, wechat miniprogram package size is 2mb limit, parse package size is about 400-500kb, so have any idea to make package less size?

###  Environment

Server
- Parse Server version: `4.5.0`
- Operating system: `Ubuntu 18.04.5`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local server`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.2`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- Parse JS SDK version: `3.1.0`

**Comment by davimacedo** [comment]
This is how wechat release is built: https://github.com/parse-community/Parse-SDK-JS/blob/master/gulpfile.js#L99

Maybe we could try to remove some dependencies that may not be necessary for wechat.

Also, I've never built wechat miniprogram, and I am not sure if that's possible, but maybe you can try to load the sdk from the cdn instead of embedding it in the program.

**Comment by dplewis** [comment]
Does SDK version 3.1.0 work this WeChat? If so we can close https://github.com/parse-community/Parse-SDK-JS/issues/1127

if you want you can fork the project and strip it down to use only what you need.

The REST Api is also an option

**Comment by jackyang1984** [comment]
it's a good idea, but i dont know which file can remove,  better way is keep the base functionnality for miniprogram.

**Comment by dplewis** [comment]
Here is the PR https://github.com/parse-community/Parse-SDK-JS/pull/874 if you want to see base

**Comment by jackyang1984** [comment]
@dplewis works well, thanks so much.

**Comment by dplewis** [comment]
Glad you got it to work.
