### ISSUE TITLE
`TypeError: undefined is not an object` with React Native v0.64 (EventEmitter)

### ISSUE THREAD

**Issue by JeffGuKang** [parse-community/Parse-SDK-JS#1335]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

#### Versions 
- React Native: 0.64
- Parse: 3.1.0

I get a error from metro bundler when I run iOS as below

```js
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[0], "../../../react-native/Libraries/vendor/emitter/EventEmitter").prototype.addListener')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

I think the error is related to 
`node_modules/parse/lib/react-native/EventEmitter.js`

```js
var EventEmitter = require('../../../react-native/Libraries/vendor/emitter/EventEmitter');

EventEmitter.prototype.on = EventEmitter.prototype.addListener;
module.exports = EventEmitter;
```

### Steps to reproduce

Build iOS with react native 0.64

### Actual Outcome

.

### Expected Outcome

Run without error

###  Environment

Client
- Parse JS SDK version: `3.1.0`

### Logs

```sh
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[0], "../../../react-native/Libraries/vendor/emitter/EventEmitter").prototype.addListener')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

**Comment by JeffGuKang** [comment]
I think the reason is related to module ordering. 
if I call `import Parse from 'parse/react-native'` before `import App from './App` the error message is popped up.

Error
```js
import 'react-native-gesture-handler'
import Parse from 'parse/react-native'
import {AppRegistry, LogBox} from 'react-native'
import App from './App'
import {name as appName} from './app.json'
```

No error
```js
import 'react-native-gesture-handler'
import {AppRegistry, LogBox} from 'react-native'
import App from './App'
import {name as appName} from './app.json'
import Parse from 'parse/react-native'
```

**Comment by JeffGuKang** [comment]
But I should import `Parse` first for importing parse schemas using `Parse.Object.registerSubclass('something', something)` as below.

```
// Initialize parse apis and schemas
import 'src/parse/initParse'
import 'src/parse/schemas'

import 'react-native-gesture-handler'
import {AppRegistry, LogBox} from 'react-native'
import App from './App'
import {name as appName} from './app.json'
``` 

And I found event emitter of react-native is using for live query on Parse. 

So I can resolve issues remove livequery from parse. 

`parse/lib/react-native/EventEmitter.js`, `parse/lib/react-native/LiveQueryClient.js`, `parse/lib/react-native/PLiveQuerySubscription.js`, `parse/lib/react-native/ParseLiveQuery.js`


But it is not a perfect solution.

**Comment by dplewis** [comment]
I'm glad it worked for you. Can you try an alternative solution from this [thread](https://github.com/facebook/react-native/issues/26687) with your error?

**Comment by kierancrown** [comment]
I'm also facing this issue with React Native 0.64.0. @JeffGuKang I'm struggling to reproduce your fix in my own project. Any pointers.? After deleting the files you mentioned I'm getting errors about the EventEmitter missing,

**Comment by JeffGuKang** [comment]
> I'm also facing this issue with React Native 0.64.0. @JeffGuKang I'm struggling to reproduce your fix in my own project. Any pointers.? After deleting the files you mentioned I'm getting errors about the EventEmitter missing,

I didn't delete files. Just remove codes only in the files.

**Comment by JeffGuKang** [comment]
I think it can be solved to make user can initialize livequery.

**Comment by JeffGuKang** [comment]
> I'm also facing this issue with React Native 0.64.0. @JeffGuKang I'm struggling to reproduce your fix in my own project. Any pointers.? After deleting the files you mentioned I'm getting errors about the EventEmitter missing,

I think you can remove two lines from `node_modules/parse/lib/react-native/Parse.js`

```js
Parse.LiveQuery = require('./ParseLiveQuery').default;
Parse.LiveQueryClient = require('./LiveQueryClient').default;
```

And use the [patch package](https://github.com/ds300/patch-package).

**Comment by JeffGuKang** [comment]
It can be solved to make user can control initialize  timing of `LiveQuery`.

```
Parse.LiveQuery = require('./ParseLiveQuery').default;
Parse.LiveQueryClient = require('./LiveQueryClient').default;
```

I will test it.

**Comment by JeffGuKang** [comment]
> I'm glad it worked for you. Can you try an alternative solution from this [thread](https://github.com/facebook/react-native/issues/26687) with your error?

I think the problem is importing `parse` first before importing `react-native`. LiveQuery initialize files to try to use `EventEmitter` from react native. 

It can be solved to make user can control initialize  timing of `LiveQuery`.

```
Parse.LiveQuery = require('./ParseLiveQuery').default;
Parse.LiveQueryClient = require('./LiveQueryClient').default;
```

I will test it.

**Comment by dplewis** [comment]
We should update the README.md as well with your import order solution

**Comment by kierancrown** [comment]
> > I'm also facing this issue with React Native 0.64.0. @JeffGuKang I'm struggling to reproduce your fix in my own project. Any pointers.? After deleting the files you mentioned I'm getting errors about the EventEmitter missing,
> 
> I think you can remove two lines from `node_modules/parse/lib/react-native/Parse.js`
> 
> ```js
> Parse.LiveQuery = require('./ParseLiveQuery').default;
> Parse.LiveQueryClient = require('./LiveQueryClient').default;
> ```
> 
> And use the [patch package](https://github.com/ds300/patch-package).

That did indeed work! Thank you very much.

**Comment by bduyng** [comment]
I solved the problem by replacing the first line in `node_modules/parse/lib/react-native/EventEmitter.js`

from
```
var EventEmitter = require('../../../react-native/Libraries/vendor/emitter/EventEmitter');
```
to 
```
var EventEmitter = require('../../../react-native/Libraries/vendor/emitter/_EventEmitter');
```
