### ISSUE TITLE
Implement an array of pointers as an attribute type

### ISSUE THREAD

**Issue by TravisDev** [parse-community/Parse-SDK-JS#1338]
Currently to have an object with a list of children as an attribute, as far as I am aware, you must use a relation. It would be great if we could have an object with a list of children as an attribute using a pointer array. THEN to query it, you just include("children") to get it. A lot of my code has extreme complexity due to simple lists of data "in a column".

**Comment by dplewis** [comment]
This should work try it out. Check out this conversation https://github.com/parse-community/parse-server/issues/6926

**Comment by TravisDev** [comment]
@dplewis ohhh I didnt realize that this could be done...  I was looking in the docs for an example of how to save a list of children in a pointer array in the parent. I couldnt find one for the life of me.
