### ISSUE TITLE
Fix EventEmitter error in react native

### ISSUE THREAD

**Issue by jackyang1984** [parse-community/Parse-SDK-JS#1352]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

"parse": "^3.2.0",
"react": "17.0.1",
"react-native": "0.64.0",

lib/react-native/EventEmitter.js
const EventEmitter = require('../../../react-native/Libraries/vendor/emitter/EventEmitter');
chanage to 
const EventEmitter = require('../../../react-native/Libraries/vendor/emitter/EventEmitter').default;

**Comment by davimacedo** [comment]
It looks duplicated to https://github.com/parse-community/Parse-SDK-JS/issues/1335.

Could you please test with https://github.com/parse-community/Parse-SDK-JS/pull/1351#issuecomment-825158007 and revert a feedback?

Thanks.
