### ISSUE TITLE
Setting nested fields to objects

### ISSUE THREAD

**Issue by mstniy** [parse-community/Parse-SDK-JS#1363]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
Setting nested fields to objects currently does not work.

### Steps to reproduce

1. Create a new Parse object with an empty Object field, called `data`.
```
const o = new Parse.Object('Person');
o.set('data', {});
```
2. Save the object to create it
```
await o.save();
```
3. Set `data.a` to the empty object, `{}`
```
o.set('data.a', {});
```
4. Save the object to update it
```
await o.save();
```
5. Use `Parse.Object.get('data')` to read the value back

### Actual Outcome
The call to `.get('data')` returns `{}` , effectively ignoring the update.

### Expected Outcome
The call to `.get('data')` should return `{a:{}}`

###  Environment

Server
- Parse Server version: `master`, as of 13th of May
- Operating system: `Ubuntu 20.04`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `v4.4.5`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- Parse JS SDK version: `master`, as of 13th of May

**Comment by mstniy** [comment]
Relevant pull requests: #729, #1301

Note that none of the tests added by these pull requests test the scenario where a non-existent nested field is set to an object.

**Comment by dplewis** [comment]
@mstniy Since you are looking into nested objects can help out with this issue https://github.com/parse-community/Parse-SDK-JS/pull/1343

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/1364

**Comment by mstniy** [comment]
> @mstniy Since you are looking into nested objects can help out with this issue #1343

Let's see
