### ISSUE TITLE
Enable ability to set health check polling interval

### ISSUE THREAD

**Issue by tlcaudill** [parse-community/Parse-SDK-JS#1378]
**Is your feature request related to a problem? Please describe.**
Parse server health check polling for browser clients is started as part of the Parse.initialize() call via '_EventuallyQueue.default.poll();'  The default polling interval is 2 seconds, but there doesn't appear to be a way to change that without modifying the code.  Many Parse Server hosting providers charge based on API calls so the constant polling increases the API calls count per client to the point where it becomes cost-prohibitive to use.

**Describe the solution you'd like**
It would be helpful to be able to pass a parameter to the Parse.initialize to indicate the polling interval to use for the browser client.

**Describe alternatives you've considered**

**Additional context**

**Comment by dplewis** [comment]
I believe a good place to put this would be `Parse.enableLocalDatastore()`. In the iOS SDK the eventually queue and local datastore are closely related on each other. We can add it here to ensure consistency with the other SDKs.

https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/2e4242c683e645a7d78ff37dd34398119178c0c5/Parse/Parse/Internal/ParseManager.m#L169

@mtrezza @davimacedo

**Comment by davimacedo** [comment]
Yes. It makes sense to me.

**Comment by dplewis** [comment]
@mtrezza This should be closed via https://github.com/parse-community/Parse-SDK-JS/pull/1419

**Comment by mtrezza** [comment]
Closing via #1419
