### ISSUE TITLE
User.logIn  usePost parameter show error in Typescript 

### ISSUE THREAD

**Issue by Malenconiaprincep** [parse-community/Parse-SDK-JS#1394]
### New Issue Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

User.logIn  usePost parameter show error in Typescript 
![image](https://user-images.githubusercontent.com/6262739/129480244-4059b0d4-e3c6-489a-bae0-5166ba7326f5.png)

because @types/parse Fulloptions has not usePost properties

### Expected Outcome

not error in typescript

###  Environment

Client
- Parse JS SDK version: `FILL_THIS_OUT`
version 3.3.0

**Comment by dblythy** [comment]
`@types/parse` is currently managed by the DefinitelyTyped repo. You can fix this error by creating a PR there.

I think all you'll need to do is add `usePost` to `FullOptions`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5390831a9cb6da6cda0f18be90f664a9e0fc973b/types/parse/ts3.6/index.d.ts#L95

**Comment by Malenconiaprincep** [comment]
done

**Comment by mtrezza** [comment]
I'm closing this as it does not seem to be a Parse JS SDK issue.
