### ISSUE TITLE
Can't create an object pointer without any data

### ISSUE THREAD

**Issue by alino20** [parse-community/Parse-SDK-JS#1406]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
Can't create pointers without dirty keys hence saving any object which includes these pointers results into cascade save.
This is gonna throw an error if this pointer is in another object and user does not have the permission to save this pointer's object so cascade save results into error.
Additionally can't create multiple instance of one object (with id) with different dirty keys without saving them because all of them share the same fields.

### Steps to reproduce
```
const MyClass = Parse.Object.extend("MyClass");
let newRow = new MyClass({a: 1})
newRow = await newRow.save();

// Changing the field without save
newRow.set('a', 2)

// create new pointer
let newRowPointer = new MyClass({id: newRow.id})
console.log('a:', newRowPointer.get('a')) 
console.log('new pointer dirtyKeys: ', newRowPointer.dirtyKeys()) 

// or create object without data
let newRowPointer2 = MyClass.createWithoutData(newRow.id)
console.log('a:', newRowPointer2.get('a')) 
console.log('new pointer 2 dirtyKeys: ', newRowPointer2.dirtyKeys()) 
```

### Actual Outcome
Console prints `a: 2` and the dirty keys are `['a']`

### Expected Outcome
Console prints should be `a: 1` and the dirty keys should be `[]`

###  Environment

Server
- Parse Server version: 4.10.3
- Operating system: CentOS 8
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): any host

Database
- System (MongoDB or Postgres): MongoDB
- Database version: 4.4
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): any host

Client
- Parse JS SDK version: 3.3.0

**Comment by dplewis** [comment]
See https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseObject.js#L71

This is because of the way instances are created in Parse JS depending on your enviornment.

On Web clients there are single / shared instances which means objects with the same id will have same attributes. 
On Node they are unique instances. 

I hope this helps.

**Comment by alino20** [comment]
Thanks. I changed my code according to your answer, and now it works as expected. Although I feel this should be somewhere in the documentations.
