### ISSUE TITLE
ReactNative - EventEmitter bug

### ISSUE THREAD

**Issue by camdagr8** [parse-community/Parse-SDK-JS#1412]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Unable to use Parse in React Native `0.65.1`

### Steps to reproduce

1. Create an empty React Native 0.65.1 iOS project 
2. Import Parse React Native: `import Parse from 'parse/react-native';`

### Actual Outcome

Error: 
```
/../node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:15
import type {EventSubscription} from './EventSubscription';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at
 Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/../node_modules/parse/lib/react-native/EventEmitter.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

###  Environment

- React Native iOS version: `0.65.1`

### Client
- Parse JS SDK version: `3.3.0`

**Comment by camdagr8** [comment]
Please note that I have tried **_everything_** in all the related and/or duplicated issues.

**Comment by mtrezza** [comment]
@davimacedo should this issue stay in this repo or be moved to the react repo?

**Comment by dplewis** [comment]
React-Native 0.70.0 Simplified and rewrote the EventEmitter. Can you try updating?

https://github.com/facebook/react-native/commit/e5c5dcd9e26e9443f59864d9763b049e0bda98e7

**Comment by ivnnv** [comment]
For those still having errors with this and landing here (probs because they still on an older version of Parse, like myself)
The API of the rewrote EventEmitter is the same, so it seems to work just patch-patching `EventEmitter.js` to use the default export:

```
-var EventEmitter = require('../../../react-native/Libraries/vendor/emitter/EventEmitter');
+var EventEmitter = require('../../../react-native/Libraries/vendor/emitter/EventEmitter').default
```

**Comment by mtrezza** [comment]
@camdagr8, @ivnnv could you test out https://github.com/parse-community/Parse-SDK-JS/pull/1999 and let us know whether is solves the issue before we merge?

**Comment by dplewis** [comment]
@mtrezza Their issues were solved before #1999 

@ivnnv Issue was fix by removing the hard-coded path https://github.com/parse-community/Parse-SDK-JS/pull/1930
@camdagr8 Issue should be fixed by updating to the latest version of react-native > 0.70.0. It fixed the typescript import issue.

**Comment by mtrezza** [comment]
So if this issue has been solved, can we close it? And why is #1999 pointing to this issue if it's solved?

**Comment by dplewis** [comment]
You can close it. I didn’t realized this was solved until just know. Any import issues involving live query is most likely event emitter related.

**Comment by mtrezza** [comment]
Closing, see explanation above.

So #1999 is actually a new feature that doesn't have an issue yet, right?

**Comment by mtrezza** [comment]
Closed as explained in https://github.com/parse-community/Parse-SDK-JS/issues/1412?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDI0MDcyNDY4MzY6NTY3MzY3Nw%3D%3D#issuecomment-1698205973
