### ISSUE TITLE
Many repeated health requests if a server return an error in response

### ISSUE THREAD

**Issue by igor-lemon** [parse-community/Parse-SDK-JS#1420]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
If backend return 4xx or 5xx error to `/health` request SDK makes many repeated `/health` requests per second endless.

### Steps to reproduce
Return to the `health` request 400 or 500 error.

### Actual Outcome
SDK makes many repeated requests per second

### Expected Outcome
Should make next `health` request in 2 seconds

![image](https://user-images.githubusercontent.com/14764799/137701461-c0ef8c45-b73e-4569-ae90-39a97afdd2b1.png)

**Comment by igor-lemon** [comment]
If a HTTP server return 400 or 500 code to `/health` request SDK start spam `/health` requests many times without any delay, ~4-6 requests per seconds endless

**Comment by dplewis** [comment]
@mtrezza this was fixed via https://github.com/parse-community/Parse-SDK-JS/pull/1419

**Comment by mtrezza** [comment]
Was this a Parse Server issue or a Parse JS SDK issue? If so, I'll move the issue to the JS SDK.

**Comment by dplewis** [comment]
This is the JS SDK that the issue was posted in, no need to move it

**Comment by mtrezza** [comment]
Closed via https://github.com/parse-community/Parse-SDK-JS/pull/1419
