### ISSUE TITLE
⚠️ `master` branch is now `alpha`

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-JS#1422]
# ⚠️ New branch model

The `master` branch of this repository will be renamed `alpha`, becoming the new "default" branch. This is part of [release automation](https://github.com/parse-community/parse-server/issues/7271) to implement pre-releases (alpha, beta) to mature versions before official release.

## ✔️ Steps

- If you have a clone locally or forked remotely, you will need to update your clones according to the [GitHub instructions](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes):

  ```
  git branch -m master alpha
  git fetch origin
  git branch -u origin/alpha alpha
  git remote set-head origin -a
  ```

- *When you open a pull request, make sure to open it against the new `alpha` branch.*
- For any repository you can look into the [branch list](https://github.com/parse-community/Parse-SDK-JS/branches) to find out which branch the default branch is if you are unsure.

## 🌵Branch model

- `alpha`: The working branch, replacing `master`; example release tag `1.0.0-alpha.1`.
- `release`: The official release; example release tag `1.0.0`.

**Comment by mstniy** [comment]
Note that the release branch is currently broken, as it tries to fetch the server using the master branch, which does not exist anymore.

**Comment by mtrezza** [comment]
Yes, that should be fixed on Nov 1st when `alpha` is merged into `release`. By "broken" you mean only the CI, right?

**Comment by mstniy** [comment]
See [package.json](https://github.com/parse-community/Parse-SDK-JS/blob/release/package.json#L78)
It is marked as a dev dependency, so unless one tries to install the SDK with dev dependencies, it should be fine.

**Comment by mtrezza** [comment]
Yes, that has already been corrected on `alpha` and will be corrected on `release` by end of the week. I'd rather wait than correcting this manually now, because we want to try out the release automation that should create a PR to make a stable release.
