### ISSUE TITLE
Server selection ability while making any cloud function calls

### ISSUE THREAD

**Issue by yog27ray** [parse-community/Parse-SDK-JS#1431]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

Not able to make cloud function calls to another parse server via Parse.Cloud.run('anotherServerFunctionName').

### Feature / Enhancement Description

Ability to pass server selection details with option while make cloud function calls.
```
new ParseServer({
...
serverURL: 'current server url',
masterKey: 'current server masterKey',
otherParseServer: [
  { serverName: 'anotherServer1', masterKey: 'another server1 masterKey' },
  { serverName: 'anotherServer2', masterKey: 'another server2 masterKey' },
],
...
})
```
```
Parse.Cloud.run('anotherServerFunctionName', {}, { serverName: 'anotherServer1', sessionToken, useMasterKey } );
```

### Example Use Case

1. Create Parse Server project A with cloud functions "serverACloudFunction".
2. Create Parse Server project B with cloud functions "serverBCloudFunction".
3. Server A wants to call server B cloud function "serverBCloudFunction" using the parse library function.

### Alternatives / Workarounds

ServerA can make a rest-API call to serverB to access serverBCloudFunction. But it would be better if parse can support this functionality.

**Comment by mtrezza** [comment]
Closing as duplicate of https://github.com/parse-community/Parse-SDK-JS/issues/203.
