### ISSUE TITLE
React Native (Parse JS API Issue) "Can't find variable: indexedDB"

### ISSUE THREAD

**Issue by chillaxdev** [parse-community/Parse-SDK-JS#1440]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

In a react native project, attempting to set Parse async storage using JS API (setAsyncStorage) throws an error "Can't find variable: indexedDB". The Async Storage is from @react-native-async-storage/async-storage

### Steps to reproduce

```
import AsyncStorage from '@react-native-async-storage/async-storage';

const Parse = require('parse/react-native.js');
Parse.setAsyncStorage(AsyncStorage);
```
I've reproduced the issue in this repository below with minimal code.
https://github.com/chillaxdev/RNIDbIssue

### Actual Outcome

Possible Unhandled Promise Rejection (id: 0): ReferenceError: Can't find variable: indexedDB

### Expected Outcome
No errors & warnings.

###  Environment

Client
- Parse JS SDK version: `3.4.1`

### Logs

![Issue](https://github.com/chillaxdev/RNIDbIssue/raw/master/images/issue.PNG)

**Comment by ndukachukz** [comment]
Have you been able to fix this yet. If you have pls share how you did it. 
I'm having thesame errors

**Comment by chillaxdev** [comment]
@ndukachukz You can temporarily use version 3.4.0 to avoid this issue.

**Comment by tiavina-mika** [comment]
Is there a fix about this issue? It has been here for a while

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/1569
