### ISSUE TITLE
React native SDK error: While trying to resolve module `idb-keyval` from file

### ISSUE THREAD

**Issue by zealmurapa** [parse-community/Parse-SDK-JS#1441]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
I am suddenly getting an error with the new release of parse and including the old ones too regarding `idb-keyval`. I see that the latest release sought to address that bug, however it doesn't seem to go away.

### Steps to reproduce
import Server from "parse/react-native.js";
import AsyncStorage from '@react-native-async-storage/async-storage';

Server.setAsyncStorage(AsyncStorage);
Server.initialize(Constants.APP_ID, Constants.JAVASCRIPT_KEY);
Server.serverURL = Constants.APP_API;

then try run the app in the emulator

### Actual Outcome
Check the logs below

### Expected Outcome
that the react native build should run as usual following: (import Server from "parse/react-native.js";)

###  Environment
Node JS 12 on Mac iOS Big sur

Server
- Parse Server version: `5.0.0-beta.4`
- Operating system: `Mac OS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.2`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

Client
- Parse JS SDK version: `3.4.1`

### Logs
iOS Bundling failed 10162ms
While trying to resolve module `idb-keyval` from file `/node_modules/parse/lib/react-native/IndexedDBStorageController.js`, the package `/node_modules/idb-keyval/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/idb-keyval/dist/compat.cjs`. Indeed, none of these files exist:

  * /node_modules/idb-keyval/dist/compat.cjs(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * /node_modules/idb-keyval/dist/compat.cjs/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)

**Comment by mtrezza** [comment]
Does this issue belong to https://github.com/parse-community/parse-react?

**Comment by zealmurapa** [comment]
> Does this issue belong to https://github.com/parse-community/parse-react?

parse/react-native.js is a under parse sdk

**Comment by stage88** [comment]
I got this same issue since upgrading to 3.4.1, its only a problem when used in a react-native project.

**Comment by mtrezza** [comment]
The [changelog](https://github.com/jakearchibald/idb-keyval/blob/main/CHANGELOG.md#v6) says:

> dist no longer committed.

Maybe that explains the error log:

> However, this package itself specifies a main module field that could not be resolved (/node_modules/idb-keyval/dist/compat.cjs. Indeed, none of these files exist:


See [this change](https://github.com/jakearchibald/idb-keyval/commit/b3a45b2418be550502bf84dc08cdcb522d33b6e5) and the [readme](https://github.com/jakearchibald/idb-keyval#all-bundles).

**Comment by chillaxdev** [comment]
@zealmurapa I got the same issue recently and have fixed it using this.
https://github.com/facebook/metro/issues/535#issuecomment-970443661

If it worked, it should bring you a new error "Can't find variable: indexedDB", which I've opened [here](https://github.com/parse-community/Parse-SDK-JS/issues/1440).

**Comment by ndukachukz** [comment]
I am having the same error with expo & typescript and I have no metro config. Do I create a metro.config.ts file or .js file then add support for .cjs and .mjs?

**Comment by ndukachukz** [comment]
> @zealmurapa I got the same issue recently and have fixed it using this. [facebook/metro#535 (comment)](https://github.com/facebook/metro/issues/535#issuecomment-970443661)
> 
> If it worked, it should bring you a new error "Can't find variable: indexedDB", which I've opened [here](https://github.com/parse-community/Parse-SDK-JS/issues/1440).

Have you been able to fix this? I'm having the same errors

**Comment by anhtuank7c** [comment]
@ndukachukz I having the same issue.
Best solution at this time is to use Parse `version 3.4.0`

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/1569
