### ISSUE TITLE
Cannot create role with `:` in name

### ISSUE THREAD

**Issue by dblythy** [parse-community/Parse-SDK-JS#1480]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

When creating a new role, using `:` in the string prevents "name" from being set. I am not sure why this is.

### Steps to reproduce

`await new Parse.Role(`Test:Test`, new Parse.ACL()).save(null, {useMasterKey: true});`

### Actual Outcome

`Error: name is required.`

### Expected Outcome

Role to save

###  Environment

Server
- Parse Server version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- Parse JS SDK version: `FILL_THIS_OUT`

**Comment by cbaker6** [comment]
Does the server allow a `:` in the role name? The error in the code in this SDK says it limits the characters on purpose: https://github.com/parse-community/Parse-SDK-JS/blob/e2bd6be145f55fab322633a8f144be34e7fcb202/src/ParseRole.js#L131-L135

I remember the other SDKs having similar code when I was adding Role to the Swift SDK: 

- Swift SDK: https://github.com/parse-community/Parse-Swift/blob/c57fc2e1e923c2373fcfcd52eac213a7c618ff92/Sources/ParseSwift/Objects/ParseRole.swift#L118-L125
- Objective C SDK: https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/21de5089f0b09662c06c972c487b1d5731238bff/Parse/Parse/PFRole.m#L70-L71
- Android SDK: https://github.com/parse-community/Parse-SDK-Android/blob/3cd4581f4be4bf34759f43a5ca41619a2190904f/parse/src/main/java/com/parse/ParseRole.java#L25

**Comment by dblythy** [comment]
It doesn't allow it, trying to set an invalid key as a role name simply results in the name being unset, which causes `Error: name is required`

**Comment by mtrezza** [comment]
> trying to set an invalid key as a role name simply results in the name being unset

Could you elaborate on this?

**Comment by dblythy** [comment]
Yes, the following code:

```
await new Parse.Role(':%#', new Parse.ACL()).save()
```
rejects on the server side with "Error: name is required"

Where it should reject on the client side with "invalid role name"

**Comment by mtrezza** [comment]
Got it, so the solution will still deny roles names with colon.
