### ISSUE TITLE
Parse Cloud `beforeConnect` and `beforeSubscribe` errors should throw in `ParseQuery.subscribe`

### ISSUE THREAD

**Issue by dblythy** [parse-community/Parse-SDK-JS#1489]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

To listen to a Parse Cloud beforeSubscribe error, you have to create an error.on listener. The error for beforeConnect and beforeSubscribe should trigger on `query.subscribe`

https://github.com/parse-community/parse-server/blob/443a5099059538d379fe491793a5871fcbb4f377/spec/ParseLiveQuery.spec.js#L594

### Feature / Enhancement Description

Throw on `await query.subscribe()`

### Example Use Case

-

### Alternatives / Workarounds

Leave as is

**Comment by mtrezza** [comment]
Is this a feature or a fix? And would changing this be a breaking change?

**Comment by dblythy** [comment]
I guess it’s a feature (although it’s expected behaviour) and breaking because any query.subscribe that throws using beforeConnect/beforeSubscribe will throw

**Comment by mtrezza** [comment]
How can be best explain the "breaking" aspect of this change?

> Calling `Parse.Query.subscribe()` will return a rejected promise if an error is thrown in Cloud Code Triggers `beforeConnect` or `beforeSubscribe`; in previous releases it was necessary to create an `error.on` listener for that.
