### ISSUE TITLE
Add Bytes type to Parse.Schema

### ISSUE THREAD

**Issue by MrMartinR** [parse-community/Parse-SDK-JS#1503]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
Is not possible to add a field using Bytes filetype.
VS Code throws an error on the 'Bytes' parameter
`Argument of type '"Bytes"' is not assignable to parameter of type 'TYPE | undefined'.ts(2345)`

### Steps to reproduce
```typescript
  const schema = new Parse.Schema('Contact')
  schema.addField('bytesField', 'Bytes')
  schema.update().then((result) => {
    console.log(result)
  })
```

I guess we need something like [Parse-Swift](https://github.com/parse-community/Parse-Swift/pull/190) feature.

### Actual Outcome
On console.log `Uncaught (in promise) Error: Bytes is not a valid type.`

### Expected Outcome
Not get the error and return the object

###  Environment
Local environment, using parse-server from the npm

Server
- Parse Server version: `latest`
- Operating system: `macOS Monterrey`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `Postgres`
- Database version: `14`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- Parse JS SDK version: `latest`

### Logs
https://community.parseplatform.org/t/saving-byte-data-to-parseobject/1804/4
https://github.com/parse-community/Parse-Swift/pull/190
https://github.com/parse-community/Parse-SDK-JS/blob/ffc523f9cd0fa2dd3fcc9754d5f15c3c1c78314f/integration/test/ParseObjectTest.js#L1365-L1379

**Comment by mtrezza** [comment]
Where is the `Bytes` field type documented, I think that documentation is still missing? Parse Dashboard doesn't even seem to support that field type?

**Comment by MrMartinR** [comment]
mmm I assumed that Parse-server supports that, Baker did some implementation in Swift https://github.com/parse-community/Parse-Swift/pull/190 and the test sample creates an object type Bytes ` object.set('bytes', { __type: 'Bytes', base64: 'ZnJveW8=' });` 
and this guy did something too  https://community.parseplatform.org/t/saving-byte-data-to-parseobject/1804/8

the parse js sdk schema shows the `addField('newField', 'ANewDataType')` (which I think is redundant if we have the rest of the add<Type>() methods...
https://docs.parseplatform.org/js/guide/#schema
```
mySchema
  .addString('stringField')
  .addNumber('numberField')
  .addBoolean('booleanField')
  .addDate('dateField')
  .addFile('fileField')
  .addGeoPoint('geoPointField')
  .addPolygon('polygonField')
  .addArray('arrayField')
  .addObject('objectField')
  .addPointer('pointerField', '_User')
  .addRelation('relationField', '_User');

// new types can be added as they are available
mySchema.addField('newField', 'ANewDataType')
```

**Comment by mtrezza** [comment]
Yes, the type is there, but I don't know how widely it is supported; it doesn't seem to be documented and how would Parse Dashboard even display that field if the field type does not seem to exist there? These are more general questions, not necessarily related to your new issue.

**Comment by MrMartinR** [comment]
the guy who was played with it, explained that parse-dashboard shows it as encoded base64 but is stored in Bytes, the type of the field shows as Bytes

![image from the post in the forum](https://parse-community-forum-uploads.s3.dualstack.us-east-1.amazonaws.com/original/1X/ef3249725842fcf549f8abdaaffe80d0de5f952d.png)

**Comment by mtrezza** [comment]
I see, so it shows just the raw JSON data, like a custom data type - neat.

**Comment by MrMartinR** [comment]
I personally not sure if I need/will ever use Bytes, I just saw something that "was missing" and I wanted to report it, just in case someone had free time to implemented it..

**Comment by mtrezza** [comment]
You'd need to look into Parse Server if there is a `Bytes` data type at all. It's not in the [docs](https://docs.parseplatform.org/js/guide/#data-types), so I'm not sure there is something missing in the docs or it's supposed to be handled in a special way.

**Comment by MrMartinR** [comment]
Not even know how to check that? 
I did find "something" [here](https://github.com/parse-community/parse-server/blob/4c29d4d23b67e4abaf25803fe71cae47ce1b5957/spec/Schema.spec.js) and [here](https://github.com/parse-community/parse-server/blob/4c29d4d23b67e4abaf25803fe71cae47ce1b5957/spec/ParseObject.spec.js)
So I guess is supported? I am gonna try to summon @cbaker6 here to see if he can throw some light...

**Comment by cbaker6** [comment]
I think the benefits of `ParseBytes` are highlighted in the link you already shared: https://community.parseplatform.org/t/saving-byte-data-to-parseobject/1804

My guess would be `Bytes` was simply overlooked by the other SDKs, Dashboard, and docs when open-sourcing. I wasn’t aware of it until @davimacedo mentioned it in the linked thread. It was an easy implementation in the Swift SDK, so I suspect the same for other SDKs.

It definitely works as I tested it when adding it to the Swift SDK.

**Comment by cbaker6** [comment]
> I see, so it shows just the raw JSON data, like a custom data type - neat.

@mtrezza I believe there are additional benefits as the data is stored in the DB as bytes. See here: https://community.parseplatform.org/t/saving-byte-data-to-parseobject/1804/8?u=cbaker6

**Comment by mtrezza** [comment]
I think you are right with it being overlooked, it's been there for a long time, presumably since open-sourcing looking at git blame.

We need some care when expanding / building upon this half-implemented feature. At least Parse Dashboard seems to be able to handle this field type, but an SDK may crash if the data type is unknown and not properly handled.

Something we could do immediately is adding this type to the docs with a note that it's not fully implemented across client SDKs and Parse Dashboard (can only display but not set field type), use at own risk. 

So the fact that Parse.Schema doesn't support it is an actual issue. Well uncovered, @MrMartinR! Would you want to open a docs PR to add a note about this data type? This could bring some clarity for people who are researching this.

**Comment by cbaker6** [comment]
Implementing this into Schema for the JS SDK would require looking here: https://github.com/parse-community/Parse-SDK-JS/blob/8115e959533d1676fe5e5551bc81888b21fc12ef/src/ParseSchema.js#L18-L30

The Swift SDK counterpart is [here](https://github.com/parse-community/Parse-Swift/blob/4ccb8a6222c1c5607a328c6be64932b47191e3fb/Sources/ParseSwift/Types/ParseField.swift#L18-L46):

```swift
/// Field types available in `ParseSchema`.
    public enum FieldType: String, Codable {
        /// A string type.
        case string = "String"
        /// A number type.
        case number = "Number"
        /// A boolean type.
        case boolean = "Boolean"
        /// A date type.
        case date = "Date"
        /// A file type.
        case file = "File"
        /// A geoPoint type.
        case geoPoint = "GeoPoint"
        /// A polygon type.
        case polygon = "Polygon"
        /// An array type.
        case array = "Array"
        /// An object type.
        case object = "Object"
        /// A pointer type.
        case pointer = "Pointer"
        /// A relation type.
        case relation = "Relation"
        /// A bytes type.
        case bytes = "Bytes"
        /// A acl type.
        case acl = "ACL"
    }
```

Of course tests will be needed in the JS SDK side. You should be able to copy/modify this test for Bytes: https://github.com/parse-community/Parse-SDK-JS/blob/8115e959533d1676fe5e5551bc81888b21fc12ef/src/__tests__/ParseSchema-test.js#L95-L105

**Comment by mtrezza** [comment]
So I'll label this as a feature request if we assume that `Bytes` is simply not supported everywhere yet.

**Comment by cbaker6** [comment]
`Bytes` has been in the Objective-C SDK for years. The SDK can [encode](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/2e4242c683e645a7d78ff37dd34398119178c0c5/Parse/Parse/PFEncoder.m#L36-L43) and [decode](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/386f659fb7c20c78d4adf386f3978fed8c9c2293/Parse/Parse/PFDecoder.m#L43-L55) Bytes.

**Comment by mtrezza** [comment]
Even more interesting that it's not in the JS SDK, which is usually the most complete one.

**Comment by cbaker6** [comment]
If my memory serves me correct, the JS SDK has only been more complete than the Objective-C and Android SDK's in recent years due to open-source maintainers beefing it up and limited contributions to the others. Before that, the other SDKs were more complete than JS.

**Comment by dplewis** [comment]
I can open a PR for this.

Should we all so add support for [ParseBytes](https://github.com/parse-community/parse-php-sdk/blob/master/src/Parse/ParseBytes.php) like in the PHP SDK in the future?
