### ISSUE TITLE
Creating a Parse.File with base64 string fails

### ISSUE THREAD

**Issue by Fouadktb** [parse-community/Parse-SDK-JS#1510]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
When Calling new Parse.File with the versions 3.4.1 upwards the process takes a few mins then actually throws an error saying 
"Cannot create a Parse.File without valid data URIs or base64 encoded data."

### Steps to reproduce
Calling Parse.file with the file blob will reproduce the issue

### Actual Outcome
an error gets thrown saying: "Cannot create a Parse.File without valid data URIs or base64 encoded data."

### Expected Outcome
getting a Parse File back

###  Environment
not a server issue but => 

Server
- Parse Server version: `n/a`
- Operating system: `n/a`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `n/a`

Database
- System (MongoDB or Postgres): `n/a`
- Database version: `n/a`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `n/a`

Client
- Parse JS SDK version: `3.4.3`

### Logs
![Screenshot 2022-07-14 at 15 29 26](https://user-images.githubusercontent.com/42405091/178995984-00ab7c6e-4c19-4926-baa1-5e54f2e5184e.png)

**Comment by mtrezza** [comment]
Could you submit a PR with a failing test to reproduce the issue?

**Comment by dblythy** [comment]
It seems this is the issue that is causing the issues [here](https://github.com/parse-community/parse-server/pull/8110). Trying to save a Parse File with a base64 string of `SGVsbG8gV29ybGQh` (`Hello World!`) fails the regex.

Failing test can be as simple as:

```js
it('can create basic files', async () => {
    const buffer =  Buffer.from('Hello World!');
    const file = new ParseFile('hello.txt', {base64: buffer.toString('base64')}, 'text/plain');  // fails here
    expect(file._source.base64).toBe('SGVsbG8gV29ybGQh');
    expect(file._source.type).toBe('text/plain');
})
```

The problematic regex is:

`/([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))|^data:([a-zA-Z]+\/[-a-zA-Z0-9+.]+(;[a-z-]+=[a-zA-Z0-9+.-]+)?)?(;base64)?,(([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=)))*$/i`

**Comment by mtrezza** [comment]
Did you find out what the problem is with the regex?

**Comment by justinlettau** [comment]
@mtrezza Here is a PR with failing unit test: https://github.com/parse-community/Parse-SDK-JS/pull/1517

I believe the issue is related to the required padding characters `=` in the regex. I have an example [here](https://stackblitz.com/edit/node-fu5sbs) to demonstrate.

**Comment by mtrezza** [comment]
It seems you are right, but the regex in your [example](https://stackblitz.com/edit/node-fu5sbs) does not seem correct, because we'd still strictly expect padding when encoding a 16 bit group. The issue with the current regex seems to be that it doesn't expect to encode a string that is exactly a multiple of 3:

```
([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))
```

The fixed regex that accounts for that would be:

```
([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=)|([0-9a-zA-Z+/]{4}))
```

If we want to be even stricter, we can use the following, because padding assumes a defined set of prefixes:

```
([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/][AQgw]==)|([0-9a-zA-Z+/]{2}[AEIMQUYcgkosw048]=)|([0-9a-zA-Z+/]{4}))
```

I think we should also make sure that we have tests which encode a string:
- without padding (`abc` = `YWJj`)
- with 1 padding (`ab` -> `YWI=`)
- with 2 padding (`a` -> `YQ==`)

If you could add the regex fix to your PR and add the tests, we should be able to close this issue.

**Comment by justinlettau** [comment]
@mtrezza Regex updated and unit tests added [here](https://github.com/parse-community/Parse-SDK-JS/pull/1517), thanks.

**Comment by SebC99** [comment]
I don't know the reason, but this caused our parseServer to hang with 100% CPU on line 212 of ParseFile.js at startup.

**Comment by DennisVanAcker1** [comment]
issue is still occurring: https://stackoverflow.com/questions/73870210/cannot-create-a-parse-file-without-valid-data-uris-or-base64-encoded-data

**Comment by mtrezza** [comment]
@DennisVanAcker1 Please make sure you are using the Parse JS SDK version which contains the fix, see https://github.com/parse-community/Parse-SDK-JS/pull/1543. If the issue still exists despite you using the alpha version, please open a new issue.

**Comment by DennisVanAcker1** [comment]
Will do! thanks again, should have looked into this abit more before posting.
