### ISSUE TITLE
Cannot create a Parse.File without valid data URIs or base64 encoded data.

### ISSUE THREAD

**Issue by manikandankumaran** [parse-community/Parse-SDK-JS#1512]
Kindly advice me to resolve that issue. Please provide the solution.
### New Issue Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ ] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [ ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

I am using Parse version - 3.4.3. I am trying to parse file with base64. The Base64 file should be large. When I try with large base64 string it will throw this error. 

Cannot create a Parse.File without valid data URIs or base64 encoded data.

### Steps to reproduce

Parse large base64 string you will get this error 
Filesystem.readFile({
            path: path
          })
            .then(res => {
               let ParseFile = new Parse.File(filename, { base64: basefile }); // Issue Occur here
              console.log('fs: ', res.data);
            })
            .catch(err => console.log('fs err: ', err));

### Actual Outcome
Cannot create a Parse.File without valid data URIs or base64 encoded data.

### Expected Outcome
Need to save the file.

###  Environment

Parse version - 3.4.3
Ionic @latest 
NPM Latest LTS 
Capacitor

Server
- Parse Server version: ``
- Operating system: `Mac OS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

Client
- Parse JS SDK version: `3.4.3`

### Logs

<img width="889" alt="Screenshot 2022-07-22 at 9 56 28 PM" src="https://user-images.githubusercontent.com/29038141/180482963-76cceccf-5c40-4b0a-9e4e-3e8334f6bd3f.png">

I have attached the screenshot for your reference.

**Comment by manikandankumaran** [comment]
>

**Comment by manikandankumaran** [comment]
I have updated the query Please let me know if you need any other information...

**Comment by mtrezza** [comment]
Could you please submit a PR with a failing test?

**Comment by shashi-chemist2u** [comment]
I am also getting this issue with 3.4.4 version, for any valid base64 string it's throwing Cannot create a Parse.File without valid data URIs or base64 encoded data, however with version 3.4.1 it's fine.

attached screenshot for error

![image](https://user-images.githubusercontent.com/109643447/195495807-9a61b5c7-eed5-4dd9-84aa-0c7ee0be95a4.png)

**Comment by mtrezza** [comment]
The fix has been implemented in [3.5.0-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.0-alpha.2). If the issue still exists there, please let us know and we can re-open this issue.

Closing via https://github.com/parse-community/Parse-SDK-JS/pull/1543
