### ISSUE TITLE
Parse.File base64 validation causes runaway regular expression

### ISSUE THREAD

**Issue by justin-mclaren** [parse-community/Parse-SDK-JS#1541]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
Using the Parse.file constructor with some base64 strings causes the browser to hang indefinitely. I believe this is a case of a runaway regular expression, probably caused by the use of Regex constructors instead of Regex string literals. 

### Steps to reproduce
Create a new Parse.File with the base64 string here: https://github.com/chinapalace/base64-string/blob/main/README.md
ex. `new Parse.File({base64: <sample string above>})`

### Actual Outcome
The browser hangs indefinitely when I try to instantiate a ParseFile with certain base64 strings.

### Expected Outcome
A ParseFile is instantiated successfully.

###  Environment
Chrome Version 105.0.5195.102 (Official Build) (arm64)

Client
- Parse JS SDK version: 3.4.4

**Comment by mtrezza** [comment]
Closing as duplicate of https://github.com/parse-community/Parse-SDK-JS/issues/1532
