### ISSUE TITLE
AddField with type date and default value not working

### ISSUE THREAD

**Issue by mohamedGamalAbuGalala** [parse-community/Parse-SDK-JS#1545]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

When adding a new field with type `Date` and with `defaultValue` it complains that the `defaultValue` should be with type date.

### Steps to reproduce

```


    const newLocalSchema = new Parse.Schema('BlaSchema')
    newLocalSchema.addField('bla', 'Date', { defaultValue: new Date() })
    await newLocalSchema.save()


```
### Actual Outcome

```
error: Parse error:  schema mismatch for BlaSchema.bla default value; expected Date but got String {"code":111,"stack":"Error: schema mismatch for BlaSchema.bla default value; expected Date but got String\n    at SchemaController.addClassIfNotExists
```
![image](https://user-images.githubusercontent.com/14947957/137818537-c9f99328-9acb-4ded-866d-d30435e0adf0.png)

### Expected Outcome

It should work.

###  Environment

Server
- Parse Server version: `^4.10.2`
- Operating system: `Windows`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `Mongo`
- Database version: `v5.0.2`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `docker`

Client
- Parse JS SDK version: `3.3.0`

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/92439533/162271531-323e34c6-b855-4bd7-97a9-68633b2903a5.png)

Please reference above content!
Thank you

**Comment by dblythy** [comment]
@mtrezza after some tedious debugging I can confirm this is an SDK issue.

`addDate('fieldName', {defaultValue})` works
`addField('fieldName', 'Date', {defaultValue})` does not work

It will be a simple fix once transferred
