### ISSUE TITLE
withinKilometers withinMiles withinRadians not working with LocalDatastore

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-JS#1571]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Unsorted distance queries aren't supported on the LocalDatastore. Unsorted distance queries uses the `$centerSphere` + `$geoWithin` operators found [here](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/src/ParseQuery.js#L1644)

### Steps to reproduce

```
it(`LocalDatastore support unsorted distance queries`, async () => {
      const object = new TestObject();
      const firstPoint = new Parse.GeoPoint({ latitude: 40.0, longitude: -30.0 });
      object.set({ location: firstPoint });
      await object.save();
      await object.pin();

      const sorted = false;
      const query = new Parse.Query(TestObject);
      query.withinKilometers(
        'location',
        new Parse.GeoPoint({ latitude: 40.0, longitude: -30.0 }),
        2,
        sorted
      );
      query.fromLocalDatastore();
      const results = await query.find();
      assert.equal(results.length, 1); // Returns 0 objects
});
```
### Actual Outcome

No objects are returned

### Expected Outcome

Should return objects within a certain radius and distance

###  Environment

Server
- Parse Server version: `5.3.0-alpha.27`
- Operating system: `Mac OS 12.6`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Localhost`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Localhost`

Client
- Parse JS SDK version: `3.4.4`

**Comment by mtrezza** [comment]
Is this a feature or a bug fix? This issue uses the bug template but the descriptions seems more like a feature. The PR says `feat`, so I've changed this to feature for now.
