### ISSUE TITLE
Add Node 16 and 18 support

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-JS#1597]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

The SDK is currently not tested with Node 16 and 18, despite Parse Server supporting these Node versions. So we should add the same CI test environments here.

### Suggestion

Add Node 16, 18 environments to CI.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.4](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0)
