### ISSUE TITLE
Removal of _this# variables in JS SDK v3.5.0

### ISSUE THREAD

**Issue by aarondill** [parse-community/Parse-SDK-JS#1599]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases).

### Issue Description

**Removal of \_this# variables in JS SDK v3.5.0**

Within the Parse JS SDK, variables intended to capture the context of _this_ in certain contexts are generally called \_this, optionally followed by a number(i.e. \_this1), for the purpose of this report, I will call them \_this variables, ignoring the number, to increase readability and shorten length.

Using simple find tools(i.e. searching for var \_this), I found that **17 \_this** variables were removed from the Javascript SDK between v3.4.4 and v3.5.0. At first glance, this change seems positive, as it reduces memory required by the Parse SDK module, however, as can be seen in [issue #1596](https://github.com/parse-community/Parse-SDK-JS/issues/1596) and my discovery of [the issue causing it](https://github.com/parse-community/Parse-SDK-JS/issues/1596#issuecomment-1305038379) the removal of some of these \_this variables create issues that can halt functions and throw errors.

It seems possible that the contributor(s) related to the removal of these \_this variables was mistaken in the implementation of the _this_ keyword in (at least) functions passed to Promise.then() and therefore errors are thrown by the environment attempting to read properties of _this_, at times where _this_ evaluates to undefined in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#no_this_substitution).

It is greatly recommended that each removal of these \_this variables is reevaluated and that any necessary variables are reinstantiated into the SDK to avoid futher errors and issues.

Due to insufficient time and understanding of the code base of the Parse SDK, I am incapable of checking each and every removal, however the recent errors caused by these removals should certainly be considered and every precaution should be taken to prevent further issues from arising.

### Steps to reproduce

Due to the large scale of this issue, and the potential for some removals to be valid, I will not produce STP, however STP for the errors in the Query.first and Query.subscribe functions can be seen in [issue #1596](https://github.com/parse-community/Parse-SDK-JS/issues/1596).

### Actual Outcome

For certain functions, typeErrors are thrown and the program is halted.
(Potentially) For others, evaulation is continued and in incorrect value is returned or saved.

### Expected Outcome

Correct return values and database writes, without any errors thrown.

### Environment

Database

- Local or remote host: back4app (once more irrelevant)

Client

- Parse JS SDK version: v3.5.0

### Note

Due to the format of this issue, it does not quite fit the issue format, however, for lack of better location, I am placing this under generic issues. Please let me know if there is a better location for this issue.

**Comment by dblythy** [comment]
We don't actually directly write any of the distributed code, it is a complied version of the source code in this repo. The compiled code is generated by running `npm run build` and looking at the `/dist` directory

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.5.1-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.1-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.5.1-beta.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.1-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.5.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/3.5.1)
