### ISSUE TITLE
Parse.User.current() will not be saved after upgrade from 3.4.4 to 3.5.0

### ISSUE THREAD

**Issue by medialwerk** [parse-community/Parse-SDK-JS#1620]
### New Issue Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [X] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
The save function of the current user does not trigger a http request anymore. The user is returned without an exception but it is still marked as "dirty".  It was working with parse@3.4.4.

### Steps to reproduce
This code was working with Parse@3.4.4 and is not working anymore with Parse@3.5.0:
```
const user = Parse.User.current();
user.set('propertyKey', propertyValue)
const updatedUser = await user.save()
```

### Actual Outcome
The "updatedUser" is still marked as "dirty" an no request was sent to the server.

### Expected Outcome
The "updatedUser" is not marked as "dirty" anymore and a http request to update the user is sent to the server.

###  Environment
See above

Server
- Parse Server version: `3.5.0`
- Operating system: `OSX`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `MongoDB 6.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- Parse JS SDK version: `3.5.0`

### Logs
There a no Logs.

**Comment by mtrezza** [comment]
Please see https://github.com/parse-community/Parse-SDK-JS/issues/1615

**Comment by medialwerk** [comment]
Oh that's heavy... Thank you for the quick reply, I did not see the issue #1615!

**Comment by mtrezza** [comment]
I think we should mark that package version as deprecated on npm.
