### ISSUE TITLE
Include installationId in Parse.User.become(SessionToken)

### ISSUE THREAD

**Issue by REPTILEHAUS** [parse-community/Parse-SDK-JS#1629]
### New Feature / Enhancement Checklist

- [ X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ X] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation
I created a 3rd party auth mechanism, I am using parse session returned from cloud code after user is validated to the client side which then auth's the user by using ` await Parse.User.become(user.getSessionToken())`

### Feature / Enhancement Description
The problem is that if the user logs in via another platform his session is killed and as we dont use Parse.User.login we cant make use of installationId which would mitigate this issue.

**Comment by REPTILEHAUS** [comment]
adding this other issue in here as it is kind of related to custom auth and maybe these 2 features would be complimentary

https://github.com/parse-community/Parse-SDK-JS/issues/1528

**Comment by mtrezza** [comment]
This doesn't seem to be neither a bug nor a feature request, as it merely states a problem with a custom auth process. To keep this issue open, we'd need a specific feature request that outlines the behavior you expect. Otherwise I'd suggest you open a discussion in the community forum to maybe come up with a more specific feature request statement.

**Comment by REPTILEHAUS** [comment]
@mtrezza i have a topic open on the community forum also which im hoping someone has a fix for my immediate needs without having to resort to implementing `Parse.User.login()` 

The feature request is that Parse.User.become() could or should accept 2 parameters, because people can become a user in different contexts i.e in an app, a website or even via a cloud function so that they can have multiple sessions running rather than logging out of other active sessions:

My proposal is to somehow have this functionality.

```
Parse.User.become({ sessionToken,, InstanceID }) 
```

**Comment by mtrezza** [comment]
I'm trying to understand the underlying issue - do you mean that a user's existing sessions are deleted when a new session is created? And could you share the link to the forum discussion?

**Comment by REPTILEHAUS** [comment]
@mtrezza Yes exactly, Im building a lot of interconnected parse powered client apps, seems when we login on 1 and we try to use one of the other platforms the accounts are logged out, I was hoping we could use the following format for users `Parse.User.become({ sessionToken,, InstanceID }) ` or for my use case specifically all the below are 1 user who can have many active sessions.

`Parse.User.become({ "r:1BVXE3fss2...",, "app1" }) `
`Parse.User.become({ "r:2222121211...",, "web" }) `
`Parse.User.become({ "r:bhwhsk2122...",, "admin_portal" }) `
`Parse.User.become({ "r:xx3asdasd3...",, "intranet" }) `

I provided pseudo code in the below on parse community, basically i have a custom auth mechanism with a custom build wordpress api that generates a JWT sends back to parse, validate it on parse and link the user get the session token and return to the client were we can "become" that token.

https://community.parseplatform.org/t/multiple-sessions-on-different-platforms/2963

**Comment by mtrezza** [comment]
Thanks, I'd say let's continue in the forum to keep the discussion in 1 place until we come up with a concrete change request.
