### ISSUE TITLE
Prepare for Parse Server 6

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-JS#1637]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

The SDK needs to be prepared for the breaking changes coming with Parse Server 6.
As we can see in https://github.com/parse-community/Parse-SDK-JS/pull/1636, the tests are failing.

A PR to fix this may break compatibility with Parse Server <6; a compatibility table needs to be added to the README for Parse Server.

### Feature / Enhancement Description
n/a

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.6](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.6)
