### ISSUE TITLE
Add Node 19 support

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-JS#1638]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

Node 19 has been officially released.

### Feature / Enhancement Description

Add Node 19 support

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by mtrezza** [comment]
I'm beginning to doubt whether we should officially support a Node.js intermediary version like 19 which is off the LTS release line.

It makes sense to add it to the CI so we are can transition easier to Node 20. But if we officially support it, we'll have to support it 6 months after it's support from Node.js ended. From June onwards it's outdated and won't receive security updates, so it's not even a version that is recommended to use anymore.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/5673677/210893537-db7173bb-3b81-4680-8fef-31cdedef83fd.png">

(gantt from https://github.com/nodejs/release)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.5](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0)
