### ISSUE TITLE
Dependabot only upgrading Parse Server

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-JS#1671]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Dependabot is only upgrading Parse Server due to a config file added to fix an issue described in https://github.com/parse-community/Parse-SDK-JS/pull/1546. The side effect is that the config disabled security upgrades of all other dependencies. This isn't a major issue since Snyk is also opening PRs for security issues. But since dependabot sometimes opens a PR for an issue that Snyk didn't detect yet, it reduces the overall security coverage.

The challenge is to figure out how to upgrade parse server with every commit (which the current config file does) while also allowing upgrades for all other repos.

### Steps to reproduce

Dependabot didn't open security patches in this repo anymore as reported in https://github.com/parse-community/Parse-SDK-JS/pull/1525#issuecomment-1405949002.

### Actual Outcome

n/a

### Expected Outcome
n/a

###  Environment
n/a

**Comment by dplewis** [comment]
Running `npm outdated` on the repo shows that a lot of our packages are out of date. Dependabot or Snyx should open PR's for those not just security patches. I would love for Jasmine 4.5.0 to run against our test suites.

**Comment by mtrezza** [comment]
They did / should open PRs, for example https://github.com/parse-community/Parse-SDK-JS/pull/1524. The reason could be that these bots only open a limited number of PRs. If there are open, unmerged PRs they may stop new PRs being opened. That's why after closing or merging a PR almost immediately we see a new one being opened sometimes.

**Comment by dplewis** [comment]
If we close those old PRs would new PRs open. Lets try it out

**Comment by mtrezza** [comment]
I've closed the old ones, Snyk settings look normal, checked 7 hours ago.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/5673677/215142235-714a1bfe-c642-49cf-bd99-78f57849a78d.png">


I'll try to re-add the project in Snyk, maybe it's checking a wrong branch because it doesn't find any issues.

**Comment by mtrezza** [comment]
Reimported the repo in Snyk; the dependencies are detected correctly. It doesn't show any vulnerabilities in the dependencies:

<img width="876" alt="image" src="https://user-images.githubusercontent.com/5673677/215145167-65002ff8-08dc-4c4d-867a-0bb73f735245.png">

The repo uses the org setting which has update out-of-date dependencies enabled:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/5673677/215145346-30e600cb-a2c9-429a-9f91-06d197399159.png">

**Comment by mtrezza** [comment]
@dplewis responding to your https://github.com/parse-community/Parse-SDK-JS/pull/1678#issuecomment-1407067261:

Reading the [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow) I assumed that `all` means only direct dependencies for npm. The docs also say:

> Use the allow option to customize which dependencies are updated. This applies to both version and security updates. 

So it seems to not be possible to differentiate between "security" and "outdated" upgrades. Maybe let's observe this a bit more. There are no new dependabot PRs being opened, so maybe it was just an initial flood of PRs.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.0-alpha.7](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.0-alpha.7)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.1-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.1-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.0.1)
