### ISSUE TITLE
Obsolete line in documentation _id in aggregations

### ISSUE THREAD

**Issue by andreisucman** [parse-community/Parse-SDK-JS#1726]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation
With the release of parse-server 6.0. the _id parameter in aggregation functions is available directly. No need to use objectId instead.

Therefore this line in JS SDK docs should be deleted to avoid confusion.

`Note: Most operations in Mongo Aggregate Documentation will work with Parse Server, but _id doesn’t exist. Please replace with objectId.`

**Comment by mtrezza** [comment]
Could you add a link to the docs? This issue may belong to the [docs](https://github.com/parse-community/docs) repository.

**Comment by andreisucman** [comment]
Here is the link, see section Aggregate. https://docs.parseplatform.org/js/guide/#aggregate

**Comment by dplewis** [comment]
@mtrezza A PR was already created for this https://github.com/parse-community/docs/pull/836

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/docs/pull/836
