### ISSUE TITLE
Node 14 CI takes long to finish

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-JS#1730]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

- The mongodb runner dependency takes 3x as long to download in the Node 14 environment compared to other environments of the CI.
- mongodb runner is a prod dependency (for unknown reasons) but it should be a dev dependency

The issue doesn't seem to occur in the Parse Server CI, so maybe the CI is set up differently here; needs to be looked at.

See https://github.com/parse-community/Parse-SDK-JS/actions/runs/4089983465/jobs/7053083540

It should finish in a comparable time to the other Node environments.

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/1729
