### ISSUE TITLE
Github Pages docs not generated for 4.0.1

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-JS#1748]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

The API reference routes to 4.0.0 instead of 4.0.1. Looks the CI didn't publish it on release. This may cause problems with future releases

https://parseplatform.org/Parse-SDK-JS/api/

https://github.com/parse-community/Parse-SDK-JS/actions/runs/4050002848/jobs/6966997870

**Comment by mtrezza** [comment]
Link to the failed build: https://github.com/parse-community/Parse-SDK-JS/actions/runs/4050093923/jobs/6967225528

It seems to fail because of branch permissions. I guess the docs action needs to run with an explicit GitHub token.

**Comment by mtrezza** [comment]
Fixed via repo settings:
https://github.com/parse-community/Parse-SDK-JS/actions/runs/4050093923/jobs/7137275546

Also added #1755 to re-trigger docs in case publishing fails during release.
