### ISSUE TITLE
Parse.Query.containedIn documentation issue

### ISSUE THREAD

**Issue by richardgroves** [parse-community/Parse-SDK-JS#1783]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
The Parse.Query.containedIn documentation (https://parseplatform.org/Parse-SDK-JS/api/4.0.0/Parse.Query.html#containedIn) lists the value parameter as type * but it needs to be an array otherwise error as reported in https://community.parseplatform.org/t/error-parse-error-bad-in-value/562 happens

### Steps to reproduce
Read the documentation, try a Query with
`let query = new Parse.Query(SomeObject);
query.containedIn("arrayColumn", "someValue");
`
Server will throw an error - Error 107: bad $in value

### Actual Outcome
Error 107: bad $in value

### Expected Outcome
A working query

###  Environment
Parse server 4.5.0, cloud code

Server
- Parse Server version: `4.5.0`
- Operating system: `Server`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Remote: Back4App`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Remote: Back4App`

Client
- Parse JS SDK version: `Don't know - any way I can query it from the cloud code? `

**Comment by richardgroves** [comment]
I suspect that `notContainedIn` will have the same problem too, but have never used that.

**Comment by mtrezza** [comment]
Would you want to open a PR? Seems to be a quick fix.

**Comment by richardgroves** [comment]
I'll have a go. Adding the type specifier in the method definition will be a guess, but plenty of examples to base it on (`Array<mixed>` seems likely). I also wouldn't know how to run a) the document generation, b) the code change on a server

But happy to submit something with those caveats.

**Comment by mtrezza** [comment]
Great, no worries, (a) will run automatically when we merge the PR. For Cloud Code you are correct that (b) will only appear once Parse Server will be released with a new version of the JS SDK.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.1.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.1.0)
