### ISSUE TITLE
Retrieving related and pinned entities doesn't work

### ISSUE THREAD

**Issue by jcarloshorus** [parse-community/Parse-SDK-JS#1810]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
After pin objects following the steps https://github.com/parse-community/Parse-SDK-JS/issues/1118,  i try recovery objects using Parse.Query and fetchFromLocalDatastore() and get the error 'Error: Cannot create a pointer to an unsaved ParseObject'. If you refresh the browser and do the same you'll get the error 'Error:Uncaught (in promise): TypeError: object._getId is not a function'.

### Steps to reproduce
```
async recovery() {
    const qry  =  new Query(ClassB).fromLocalDatastore()
    const objs = await qry.find()
    for (const o of objs) {
      const obj = await o.fetchFromLocalDatastore()
      console.log(obj)
    }
  }
```

### Actual Outcome
The instance of ClassB cannot be retrieved with all of it's attributes using the fetchFromLocalDataStore() with the error 'Cannot create a pointer to an unsaved ParseObject'. If you refresh the browser and do the same you'll get the error 'Uncaught (in promise): TypeError: object._getId is not a function'.

### Expected Outcome
The recovered object instance of ClassB should be retrieved with all of the saved attributes and it's pointer to ClassA points to the local instance of ClassA.

###  Environment

Server
- Parse Server version: 5.4.2
- Operating system: Docker Linux Alpine
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc):  Google Cloud

Database
- System (MongoDB or Postgres): Postgres
- Database version: 13
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Google Cloud

Client
- Parse JS SDK version: 4.01, 4.1.0, alpha

### Logs
ERROR Error:Uncaught (in promise): TypeError: object._getId is not a function

ERROR Error: "Uncaught (in promise): Error: Cannot create a pointer to an unsaved ParseObject

**Comment by dplewis** [comment]
@mtrezza I believe this was fixed in https://github.com/parse-community/Parse-SDK-JS/pull/1662

**Comment by mtrezza** [comment]
Closing, @jcarloshorus if the issue exists after the fix mentioned above, please let us know and we can reopen.
