### ISSUE TITLE
Allow a easy override of Request handler and Error messages

### ISSUE THREAD

**Issue by R3D347HR4Y** [parse-community/Parse-SDK-JS#1838]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

When used in production many security problems may arise from using a very standard and easy to recognize as well as spoof REST architecture, as you know when using the browser network console it is easy to see what is sent and received to the server as well and so to recognize that the server is using Parse, from then on it's going to be easy to find flaws in Cloud Code and general security, especially on complex backends...

### Feature / Enhancement Description

Having a way to override the Request handle on Client and Server Side (on the Server it may be possible to just run it behind an express server) to implement multiple obfuscation techniques:
By overriding the functions that send out messages between server and client we could encode any of the messages content sent back and fourth with AES (transform the message into JSON, gzip the message and then encrypt the content using a known key using with that changes every hour or so for example)

At the same time, a setting that allows to override error messages as well as simple the mention of "Parse server" to be replaced with the name of your service so as not to hint you are using Parse Server would certainly make it harder to figure out for a malicious actor who doesn't already know this framework and this precise setting!

Also, allowing the override of the Request handler would mean we could incorporate some verification of say a Google ReCaptcha on every request, making sure requests are made in the clients you have chosen only and excluding most possible Bots, this would be a nice plugin btw...

### Alternatives / Workarounds

The only alternative I could think of would be to modify requests on the express side and to use the REST Api directly though this is not very practical in JS

**Comment by dplewis** [comment]
You can create your own [RESTController](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/src/RESTController.js) to control the http request layer and error messages in the SDK.

`Parse.CoreManager.setRESTController(MyRESTController)`
