### ISSUE TITLE
Second call of Parse.User.logIn() on node destroys previous session token

### ISSUE THREAD

**Issue by stefanraffeiner** [parse-community/Parse-SDK-JS#194]
_I originally posted this issue in parse-cloud-express and moved it here as requested by @gfosco. We are running this code on server side with nodeJS. I think the here explained behavior is expected in a client environment, but should not be expected in a server environment._

We use a set up similar to AnyPhone, where we generate sessionTokens on server side (nodeJS on Heroku).

Users who have two devices log in on the first one, then on the second one, after that they see the error "invalid session token" on the first device. The first session is deleted from Parse.

As far as I could reproduce the error is caused, because Parse.User.logIn() passes an installationId to Parse, even if it runs on server side. Using or not using masterKey makes no difference. It looks like there can be only one session per installation and user.
When I restart node it gets a new installationId and everything works.

To work around this issue I copied the network request from Parse.User.logIn() and created a custom login method using the Parse.Cloud.httpRequest(), wich sends the exact same request without "installationId". That way it works, I get new sessionTokens for each device and the old ones remain active.

```
var logIn = function (username, password) {
    return Parse.Cloud.httpRequest({
        method: 'POST',
        url: 'https://api.parse.com/1/login',
        headers: {
            'Content-Type': 'text/plain',
            'User-Agent': 'node-XMLHttpRequest, Parse/1.6.9 (NodeJS 4.1.2)',
            'Accept': '*/*'
        },
        body: {
            "username": username,
            "password": password,
            "_method": "GET",
            "_ApplicationId": process.env.PARSE_APP_ID,
            "_ClientVersion": "js1.6.9",
            "_MasterKey": process.env.PARSE_MASTER_KEY,
            "_RevocableSession": "1"
        },
        json: true
    });
} 
Parse.User.logIn(username, password); //-> destroys previous session token
logIn(username, password); //-> does not destroy previous session token
```

Is it the desired behavior, that server side code passes an installationId? If yes: is there any parameter I can use to avoid this session token issue? 
For now my workaround works, but I don't think this is the ideal way. How would you solve this to run AnyPhone on nodeJS?

**Comment by andrewimm** [comment]
Hmm, I can see why this is a problem, but I'm not exactly sure what the best solution is. I'll think about this and get back to you.

**Comment by andrewimm** [comment]
I'm not convinced that there's any value in knowing the installationId of a server, so it might just be that we disable the installationId for the Node.js build of the SDK

**Comment by andrewimm** [comment]
The ability to pass an installationId override on `logIn` and `logOut` will land in 1.8.0. That would be enough to support this, without changing default behavior. You can pass the original installation id from the device making the request. I'll mark this as resolved when 1.8.0 is published.

**Comment by aitchkhan** [comment]
I have the same issue.

**Comment by flovilmart** [comment]
The issue has been closed for 2 years, can you open a new issue with proper details? 

Thanks!

**Comment by Code-Crash** [comment]
@aitchkhan 

I faced the same issue, it is because the login code was on the server side and it was generating installation id same for same users and that's the reason the last session was getting destroyed.

So, we added UUID for each time when user will try to do login, and it worked.

Here is the codebase snippet: 

```javascript
const uuid = require('uuid'); 
exports.login = function (req, res) { // login api getting called form express route
    Parse.User.logIn(req.body.username, req.body.password, {"installationId": uuid.v4()}).then(async function (user) {
        if (!user.get('isActive')) {
            throw 'User is inactive.';
        } else {
            res.send({result: user});
        }
    }).catch(function (error) {
        res.status(300).send({ result: null,
            error: {
                message: (error && error.message || error),
                stack: error.stack || ''
            }
        });
    });
};
```

Maybe this will help someone.
Thanks.

**Comment by MrSMAK** [comment]
> @aitchkhan
> 
> I faced the same issue, it is because the login code was on the server side and it was generating installation id same for same users and that's the reason the last session was getting destroyed.
> 
> So, we added UUID for each time when user will try to do login, and it worked.
> 
> Here is the codebase snippet:
> 
> ```js
> const uuid = require('uuid'); 
> exports.login = function (req, res) { // login api getting called form express route
>     Parse.User.logIn(req.body.username, req.body.password, {"installationId": uuid.v4()}).then(async function (user) {
>         if (!user.get('isActive')) {
>             throw 'User is inactive.';
>         } else {
>             res.send({result: user});
>         }
>     }).catch(function (error) {
>         res.status(300).send({ result: null,
>             error: {
>                 message: (error && error.message || error),
>                 stack: error.stack || ''
>             }
>         });
>     });
> };
> ```
> 
> Maybe this will help someone.
> Thanks.

Thanks, this solution helped!
