### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-JS#1950]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

The code base does not have native TypeScript support but relies on 3rd part TypeScript definitions. These 3rd party definitions are often inconsistent, leading to complaints from developers and support cases being opened in Parse Platform resources, even though Parse Platform is not responsible for managing these definitions.

There have been discussions and attempts in the past about strategies, sometimes trying to use the existing (not 100% coherent) JSDoc annotation as a basis to transition to TypeScript. As usual, without a committed lead pushing the topic forward, such a large scale change becomes stale over time and don't get implemented.

- https://github.com/parse-community/Parse-SDK-JS/pull/388
- https://github.com/parse-community/Parse-SDK-JS/pull/1390
- https://github.com/parse-community/parse-server/issues/7334

### Feature / Enhancement Description

Develop a strategy to gradually implement TypeScript support.

It would be beneficial to develop for a strategy where a TypeScript migration can be implemented gradually, in tiny PRs and over time. This makes the presence of a lead less relevant, as the efforts is split up into manageable tasks that be picked up by the community over time. That could mean that we won't take advantage of the existing JSDoc annotations, requiring more work in total, but that seems preferable compared to a large effort that never comes to fruition.

This issue closes with a strategy for gradual TypeScript implementation and a first, small PR that begins the implementation. We can then start to give out bounties for individual scopes to facilitate the migration to TypeScript in the long run.

**Comment by mtrezza** [comment]
cc @sadortun, @parse-community/js-sdk, @parse-community/server

**Comment by mtrezza** [comment]
@dblythy What's the strategy in #1954?

Shouldn't types be part of the code comment of the respective function rather than in a separate file? If the types are defined separately, they need to be maintained separately from the code itself or they'll deviate, same issue as we're having now with 3rd party types, right? Some of the DefinitelyTyped types are also incorrect.

Is there a way we can actually add types gradually to the code comments (replacing JSDoc) without requiring major PRs?

- Could we just start with a file, change it to `.ts` and begin typing the functions properly by hand, i.e. moving from JSDoc to TS?
- What would that mean for our API docs generation? Would that still work if we have mixed JSDoc and TS?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.5](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.2.0-alpha.5)

**Comment by dplewis** [comment]
(Contributing instructions and progress tacking moved to https://github.com/parse-community/Parse-SDK-JS/issues/2012)

**Comment by mtrezza** [comment]
@dplewis This issue is closed, I suggest to move your comment to a new issue for better visibility; I'll be happy to pin it so hopefully others join in.

**Comment by dplewis** [comment]
I’ll just leave it here since it’s already pinned, you can move it if you want to.

**Comment by mtrezza** [comment]
I'll move it, discussions on closed issues are generally discouraged due to low visibility.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.3.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/4.3.0)
