### ISSUE TITLE
`Error: crypto.getRandomValues()` When i try to create anything

### ISSUE THREAD

**Issue by YousefAlsbaihi** [parse-community/Parse-SDK-JS#1973]
- [ X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X ] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [X ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
When i try to create anything Class, User, any kind of data i get the error

`[Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported]`

### Steps to reproduce
```
const Parse = require('parse/react-native.js');
import AsyncStorage from '@react-native-async-storage/async-storage';
Parse.setAsyncStorage(AsyncStorage);
    Parse.initialize('XXX', 'XXX');
    Parse.serverURL = 'https://parseapi.back4app.com/'
    try {
        const newPerson = new Parse.Object('Person');
        newPerson.set('name', 'John');
        newPerson.set('email', 'john@back4app.com');
        await newPerson.save();
    } catch (error) {
        console.log('Error saving new person: ', error);
    }
```

###  Environment
Server
- Parse Server version: `4.5.0`
- Operating system: `MacOs`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `back4app`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6`

Client
- Parse JS SDK version: `4.1.0 React Native`

**Comment by YousefAlsbaihi** [comment]
after hours of searching i actually solved it by 

npm i -s import react-native-get-random-values

and then import it before initialize Parse

```
import 'react-native-get-random-values';
const Parse = require('parse/react-native.js');
import AsyncStorage from '@react-native-async-storage/async-storage'
....
```
i'm sure this is uuid library issue

**Comment by dplewis** [comment]
I'm glad you were able to resolve this issue. The latest version of node has `crypto` globally available now. https://github.com/uuidjs/uuid/issues/708

**Comment by andre-sonect** [comment]
Unfortunately I still suffer from this using latest node LTS with parse server and dashboard. Tried the above solution on react-native just to find another issue `Native module not found`. 
Anyone looking into this you also need to `npx react-native link`. After that all good.

**Comment by mtrezza** [comment]
Closing, as Parse Server 4 is not under LTS anymore. If you experience the issue with Parse Server 5.x or 6.x, please let us know and we can re-open this issue.
