### ISSUE TITLE
Tests fail with Parse Server upgrade

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-JS#1979]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Upgrading Parse Server for integration testing fails in https://github.com/parse-community/Parse-SDK-JS/pull/1975.

### Steps to reproduce

Failing tests in https://github.com/parse-community/Parse-SDK-JS/actions/runs/5633637975/job/15262758943?pr=1975:

> 1) Parse.File can get file data from base64 (saved)
>   - Error: File upload of extension plain is disabled.
> 
> 2) Parse.File can get file data from byte array
>   - Error: File upload of extension plain is disabled.
> 
> 3) Parse.File can save file to localDatastore
>   - Error: File upload of extension plain is disabled.
> 
> 4) Schema set multiple required and default values
>   - Error: File upload of extension plain is disabled.

### Actual Outcome

Tests fail.

### Expected Outcome

Test pass.

**Comment by dblythy** [comment]
This seems to be as a result of an unexpected breaking change, fixed in https://github.com/parse-community/parse-server/issues/8698

**Comment by mtrezza** [comment]
Possibly related to https://github.com/parse-community/parse-server/issues/8818
