### ISSUE TITLE
`Query.findAll()` doesn't use `exclude`/`excludeKeys`

### ISSUE THREAD

**Issue by sadortun** [parse-community/Parse-SDK-JS#1990]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Hi!!

When using `findAll()` to execute a query, the `exclude` parameter is omited.

You can see here that `include` and `select` are copied from  the local `this` to `query`, but  `exclude` is omited 

https://github.com/parse-community/Parse-SDK-JS/blob/549b7b3e6e25732ff44a4dcda4f070134be818f6/src/ParseQuery.js#L951-L953

Not sure if it's the expected behaviour, if so, it should be documented.

### Steps to reproduce

```js
const q1  = Parse.Query('Player')
q1.include('team')
q1.exclude('team.logo')

q1.limit(999999)
const players = q1.find() //  Fast, logo is excluded


const q2  = Parse.Query('Player')
q2.include('team')
q2.exclude('team.logo')

const players = q1.findAll()  //  Slow, logo is present
```

side note:   `q1.toJSON()` and `q2.toJSON()` produce expected output

### Actual Outcome

- q1 :  Contains Teams, **without**  logos
- q2:  Contains teams   **WITH** logos

### Expected Outcome

- q1 :  Contains Teams, **without**  logos
- q2:  Contains teams   **without** logos

###  Environment

Server
- Parse Server version: `6.2.1`
- Operating system: `windows 🤡`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `mongo`
- Database version: `recent`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- Parse JS SDK version: `4.0.1`

**Comment by mtrezza** [comment]
Looks like a bug to me, would you want to open a PR with a test?
