### ISSUE TITLE
Add context container in `Parse.Cloud.beforeLogin` and `Parse.Cloud.afterLogin`

### ISSUE THREAD

**Issue by valerycolong** [parse-community/Parse-SDK-JS#1991]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation
It is currently not possible to access context data in Parse.Cloud.beforeLogin and Parse.Cloud.afterLogin hook triggers.

### Feature / Enhancement Description
Similar to Parse.Cloud.beforeSave and Parse.Cloud.afterSave triggers, where it is possible to get context data feom the context object via the request parameter of the trigger callback.

### Example Use Case
1. This could help facilitate MFA authentication such as in cases when an email verification needs to be passed alongside parse email auth data before login is permitted.
2. It may also come in handy in context switching during or after login such as in case of performing certain actions based on context data after login.

### Alternatives / Workarounds
In my project, I was forced to use Redis cache and making additional request to the server which wasn't really necessary. 
Also, lack of this feature resulted in extra code.

### 3rd Party References
None

**Comment by dplewis** [comment]
I believe this needs to be added to the server first before the SDK.
