### ISSUE TITLE
Parse.Cloud.httpRequest is not a function

### ISSUE THREAD

**Issue by AbubakarSiddique** [parse-community/Parse-SDK-JS#2004]
### Issue Description

Parse.Cloud.httpRequest is not a function while executing cloud code in Local Development.

### Steps to reproduce

Run cloud code in local development and trigger any function having Parse.Cloud.httpRequest

### Actual Outcome

Should execute my HttpRequest

### Expected Outcome

Error 141 : Parse.Cloud.httpRequest is not a function

###  Environment

Server
- Parse Server version: `4.5.0`
- Operating system: `Windoows 11`
- Local or remote host : `LOCAL`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `0.6.4`
- Local or remote host : `LOCAL`

Client
- Andoroid SDK version: `Andorid 13`

**Comment by dplewis** [comment]
It’s highly recommended that you use another HTTP module instead of Parse.Cloud.httpRequest.

https://github.com/parse-community/parse-server/pull/7595
