### ISSUE TITLE
saveEventually - "code":209,"stack":"Error: Session token is expired"

### ISSUE THREAD

**Issue by sjxuereb** [parse-community/Parse-SDK-JS#2008]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

I am using saveEventually and have noted the following:

> Data is pinned(saved locally on the device) correctly during a valid session when no network is found.
> I noted data is not saved at all locally if a session expires...
> Upon the network connection returning data gets sent correctly [ although receiving doubles or multiples ] the data is at least found on parse server.
> However if the connection returns and meanwhile the session has expired an attempt is still made and essentially the data gets transmitted and discarded, never saved to parse server and getting essentially lost. 

I have checked the code in the SDK for saveEventually and it seems the server only polls for status ok..... and then attempts to send the queue.

### Steps to reproduce

to reproduce one has to set a very short session expiry on parse server.
### Actual Outcome

The outcome is lost data upon session expiry both locally and on parse server.

### Expected Outcome

I expected the data to live locally until a user gets logged in again(not just network restored again) and has a valid session. 
I expected the data to still be saved locally on the device even if the session expires. 

###  Environment

Server
- Parse Server version: 5.1.0
- Operating system: n/a
- Local or remote host Local

Database
- System (MongoDB or Postgres): n/a
- Database version: n/a
- Local or remote host n/a

Client
- Parse JS SDK version:  parse@4.1.0

### Logs

info: Create new client: f5e9c41b-2378-4d16-a167-d849dbef9d9c
error: Session token is expired. {"code":209,"stack":"Error: Session token is expired.\n    at Object.getAuthForSessionToken (/usr/local/parse-server/node_modules/parse-server/lib/Auth.js:132:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async handleParseSession (/usr/local/parse-server/node_modules/parse-server/lib/middlewares.js:292:21)"}

**Comment by dplewis** [comment]
@sjxuereb Thank you for the feedback. Besides connection retries `saveEventually` should act exactly as `save` should. 

Can you `save` when a session expires? What should happen if one user session expires but a completely different user logs in and `saveEventually` runs?

**Comment by sjxuereb** [comment]
@dplewis Thank you for your reply. 

I correct myself I can **save** locally when the session expires. I think given the multiple use cases, the best solution is to just mention "the data will become invalidated by the server upon session expiry" in the saveEventually documentation.

This should help any developer, if they find they are missing data for which the user is 100% sure they saved..

**Comment by dplewis** [comment]
Let me see if I can replicate your issue first with a few test cases. If the data is invalid by the server then we update the docs. If the data is discarded by the SDK then we will introduce a fix if possible to match ‘save’ functionality

**Comment by dplewis** [comment]
@sjxuereb You are right the object shouldn't be discarded on invalid session. I'll so a PR for it shortly. I did find something interesting. If a session is invalid you can still save an object until the server restarts.

```
fit('saving object with expired session', async () => {
    Parse.User.enableUnsafeCurrentUser();
    await Parse.User.signUp('cuser', 'somepass', null);

    const readOnly = Parse.Session.readOnlyAttributes();
    Parse.Session.readOnlyAttributes = null;
    const expiresAt = new Date(new Date().setYear(2015));
    const session = await Parse.Session.current();
    session.set('expiresAt', expiresAt);
    await session.save();

    const object = new TestObject();
    object.set('foo', 'bar');
    await object.save(); // Can save on invalid session. Why?
    expect(object.get('foo')).toBe('bar');

    await reconfigureServer();

    await expectAsync(object.save({ 'foo': 'baz'})).toBeRejectedWithError(
      'Session token is expired.'
    );
    Parse.Session.readOnlyAttributes = function () {
      return readOnly;
    };
  });
```

**Comment by sjxuereb** [comment]
My crude workaround was as follows. Commented out in the sdk the poll function in EventuallyQueue.js

    // polling = setInterval(function () {
    //   var RESTController = _CoreManager.default.getRESTController();
    //   RESTController.request('GET', 'health').then(function (_ref) {
    //     var status = _ref.status;
    //     if (status === 'ok') {
    //       _this.stopPoll();
    //       return _this.sendQueue();
    //     }
    //   }).catch(function (e) {
    //     return e;
    //   });
    // }, ms);


Then used  await Parse.EventuallyQueue.sendQueue() after I get the user logged in. It looks like its working. I also noted I am not getting doubles or multiples of the same data as much as with the original function. 

I also agree with your answer that it is not straight forward "What should happen if one user session expires but a completely different user logs in and saveEventually runs?"

In my use case I don't care. I just need that the data gets to the server with no losses.

This is why I suggested documentation.

**Comment by mtrezza** [comment]
> "What should happen if one user session expires but a completely different user logs in and saveEventually runs?"
> In my use case I don't care. I just need that the data gets to the server with no losses.

That's an important question. I'd say if the session token cannot be stored securely, without the new users having access to it (e.g. via inspecting the queue of pending `...eventually` operations, then they cannot succeed, because there is no session token information. Same goes for the queue itself; if the queue cannot be sealed off securely from the current user, then the queue needs to be emptied when the user logs out. Otherwise the newly logged in user could inspect the previous user's data in the pending ops.

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/docs/pull/938
