### ISSUE TITLE
SDK throws error in web contexts where calling into `window.indexedDB` is prohibited, but not undefined on the window

### ISSUE THREAD

**Issue by westhom** [parse-community/Parse-SDK-JS#2038]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
In a web context where `window.indexedDB` is protected from use but not undefined, Parse SDK throws an error on initial import. For example, in a [Figma](https://www.figma.com/) Plugin web context, `window.indexedDB` API is defined, but once an indexedDB API function is called an error is thrown:

```
Uncaught DOMException: Failed to execute 'open' on 'IDBFactory': access to the Indexed Database API is denied in this context.
```

Parse is an initializing an indexedDB store in [this file](https://github.com/parse-community/Parse-SDK-JS/blob/43f621863224768e2023ca896677fe9c0c2bcb21/src/IndexedDBStorageController.js#L9), to store at top level property `Parse.IndexDB`, even if the user never sets the Parse storage controller to indexedDB.

3 fix options immediately come to mind:

1. Wrap line linked above in try/catch, and set `Parse.IndexedDB` to undefined if it throws
2. Don't initialize `Parse.IndexedDB` store by default, since it isn't used by default.
3. Remove IndexedDBStorageController from Parse SDK to a plugin module, or example file. It would also clean up the unused `idb-keyval` dependency.

### Steps to reproduce

Create a figma plugin and import the Parse library:

```js
import Parse from 'parse/dist/parse.min.js' // error thrown
```

### Actual Outcome
Parse cannot be imported.

### Expected Outcome
Parse can be imported.

###  Environment

Server
- Parse Server version: `n/a`
- Operating system: `n/a`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `n/a`

Database
- System (MongoDB or Postgres): `n/a`
- Database version: `n/a`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `n/a`

Client
- Parse JS SDK version: `4.2.0`

**Comment by dplewis** [comment]
@westhom I submitted a PR for this https://github.com/parse-community/Parse-SDK-JS/pull/2039
