### ISSUE TITLE
`Parse.User.verifyPassword` does not pass request options to server

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-JS#2077]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

`Parse.User.verifyPassword` does not pass request options to server. It filters out all but the `useMasterKey` option. This means options such as `context` or other options have no effect.

### Actual Outcome

Removes all but the `useMasterKey` option.

### Expected Outcome

Send all options to server.

###  Environment

Server
- Parse Server version: `7.0.0-alpha.10`

Client
- Parse JS SDK version: `4.3.1-alpha.1`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.4](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.0.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0)
