### ISSUE TITLE
Missing test for `Parse.User.verifyPassword` option `ignoreEmailVerification`

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-JS#2101]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

https://github.com/parse-community/Parse-SDK-JS/pull/2076 introduced ignoreEmailVerification option on Parse.User.verifyPassword a unit test is missing. Code coverage has dropped. I was slightly confused when I saw it was added to the payload over the options when passing into the AJAX request.

### Steps to reproduce

https://github.com/parse-community/Parse-SDK-JS/blob/5.1.0-alpha.1/src/RESTController.js#L253-L255

### Actual Outcome

Test doesn't exist

### Expected Outcome

100% code coverage

###  Environment

Server
- Parse Server version: `6.1.0`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `Mongo`
- Database version: `6.0.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `lcoal`

Client
- Parse JS SDK version: `4.1.0`

**Comment by mtrezza** [comment]
Obsolete thanks to https://github.com/parse-community/Parse-SDK-JS/pull/2107
