### ISSUE TITLE
Installation support for JS SDK

### ISSUE THREAD

**Issue by mortenmo** [parse-community/Parse-SDK-JS#2112]
### New Feature / Enhancement Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Current Limitation

Other Parse SDKs (Swift/Kotlin, etc) supports the `Installation` object to handle push notifications etc. There seems in the JS SDK there is just a minimal implementation.

* For React Native/Expo, this is limiting, ideally it should work similar to build a RN app vs Swift/Kotlin.
* Web browsers also support notifications now, so supporting this in the SDK even for just web might be useful to some users.

### Feature / Enhancement Description

Similar to the phone SDKs, handle maintaining the Installation object per installation. Things like device type, tokens etc could be handled in similar ways probably relying on react native libraries for react native at least.

This isn't really asking for new functionality beyond what is available in other SDKs.

### Alternatives / Workarounds

You could probably handle this all manually today.

### 3rd Party References

In the other SDKs built for Mobile.

**Comment by dplewis** [comment]
@mortenmo Good idea, getting this working for the web should be easy. For react-native / expo as long as a deviceToken and deviceType are set it should work with `Parse.Push` out of the box.

**Comment by dplewis** [comment]
@mortenmo I added Push notification for web support if you want to check it out

https://github.com/parse-community/parse-server-push-adapter/pull/239

**Comment by mortenmo** [comment]
@dplewis nice! looking forward to try it out. I'm using Expo push (https://docs.expo.dev/push-notifications/sending-notifications/) on React Native/Expo for mobile so I'll migrate my custom notification code to use the push adapter there too when this all merges.
