### ISSUE TITLE
LocalDatastore tests fail

### ISSUE THREAD

**Issue by mstniy** [parse-community/Parse-SDK-JS#2122]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
ParseQuery LocalDatastore tests fail when run in isolation.  
They pass when run together with the rest of the ParseQuery tests.  
They fail when the ParseQuery test that call `jest.dontMock('../ParseObject');` are all disabled, strong evidence that the mocks are broken and the tests only pass in the CI pipeline because the rest of the ParseObjects tests (which run before the localdatastore tests) undo them.

### Steps to reproduce
- Open latest alpha (aff0a00a6f5d507166dbfc14d1b695002399913b) in VSCode
- `npm install`
- Run only the tests for ParseQuery LocalDatastore

### Actual Outcome
The following tests fail:
- can query offline
- can query offline with localId
- can query offline sort multiple
- can query offline select keys

### Expected Outcome
- The tests should pass, even when run in isolation.

###  Environment

Server
- Parse Server version: irrelevant
- Operating system: `Ubuntu 22.04`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): irrelevant
- Database version: irrelevant
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): irrelevant

Client
- Parse JS SDK version: `aff0a00a6f5d507166dbfc14d1b695002399913b`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.10](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-alpha.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.1](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/Parse-SDK-JS/releases/tag/5.1.0)
