### ISSUE TITLE
Parse.Installation doesn't handle deleted Installation objects on server

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-JS#2124]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

Deleted an installation in the database and it gets into a state where nothing works and it doesn't seem to be a way to get out of it.

The InstallationController never checks for server changes to object, so save() just fails since the local object has an id. And beyond cleaning the cache keys manually out of storage, there is no way to reset the installation locally.

### Steps to reproduce

1) Save the current installation
2) Delete it via Parse Dashboard
3) Try to get the current installation and save it.

### Approach
Parse Installation in the iOS SDK and this SDK should have similar functionaility.

[Installations cannot be deleted](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Parse/Internal/Installation/Controller/PFInstallationController.m#L88)

[We always want [currentInstallation fetch] to succeed.](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Parse/Internal/Installation/Controller/PFInstallationController.m#L59)

[We always want [currentInstallation save] to succeed.](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Parse/Source/PFInstallation.m#L249)

### Actual Outcome

The cache has a mismatch with the server and fails.

### Expected Outcome

Should properly save, fetch the installation always.

**Comment by mtrezza** [comment]
Hans't this been discussed somewhere before opening this issue? Could you link the other issue?

**Comment by dplewis** [comment]
@mtrezza It was in an already merged PR. https://github.com/parse-community/Parse-SDK-JS/pull/2119#issuecomment-2104824622
