### ISSUE TITLE
Change fields in LiveQueryClient.resubscribe to keys

### ISSUE THREAD

**Issue by akichim21** [parse-community/Parse-SDK-JS#2180]
### Issue Description
Change fields in LiveQueryClient.resubscribe to keys

https://github.com/parse-community/Parse-SDK-JS/blob/alpha/src/LiveQueryClient.ts#L303

### Steps to reproduce
* execute resubscribe
* parse-server logs
  - error | Connect message error Additional properties not allowed
  - info | Create new client: xxxx
  - many connection

### Actual Outcome
* no error

###  Environment

Server
* fields is removed
https://github.com/parse-community/parse-server/commit/38983e8e9b5cdbd006f311a2338103624137d013#2160

**Comment by dplewis** [comment]
Please update Parse Server and JS SDK to the latest version, this should fix your issue.

**Comment by akichim21** [comment]
@dplewis 
Hi.
In 5.2.0-alpha.2 it was still fields.
Which version?
The resubscribe one, not the subscribe one.

https://github.com/parse-community/Parse-SDK-JS/blob/56bc655e2a090cf8200dc22eba7732b09c7bcaff/src/LiveQueryClient.ts#L303

**Comment by dplewis** [comment]
Oh I see. This is a bug. Would you like to open a PR to fix it?

**Comment by akichim21** [comment]
I tried to respond, but could not take the time to respond to the CI.
https://github.com/parse-community/Parse-SDK-JS/pull/2182

I have addressed this with PATCH, but I hope it will be addressed on the library side.

When the server error occurred, the client would make multiple connections and the DISCONNECT did not occur immediately.
The server stopped working due to the large number of connections.

**Comment by dplewis** [comment]
Thanks for the feedback. Thats a major issue, i'll see if I can write a test for it.

**Comment by dplewis** [comment]
@akichim21 I opened a PR for this https://github.com/parse-community/Parse-SDK-JS/pull/2184 if you want to check it out.

**Comment by akichim21** [comment]
Thank you for your response.
I check it.
