### ISSUE TITLE
Parse error in vite ( back4app ) on Parse.initialize: EventEmitter is not a constructor

### ISSUE THREAD

**Issue by sorooshjaberi** [parse-community/Parse-SDK-JS#2181]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description

When calling Parse.initialize with the proper arguments in my vite react application, I get this error:  **EventEmitter is not a constructor**

This is the corresponding code: 
![parse-code](https://github.com/parse-community/Parse-SDK-JS/assets/93154421/2a40870b-519d-4f03-9b20-f9c930bb962b)

### Steps to reproduce

1. Create a vite app ( mine was a react-ts one )
2. Try to initialize parse SDK in the app
3. You will get the error below

### Actual Outcome

![parse-error](https://github.com/parse-community/Parse-SDK-JS/assets/93154421/5914f0ad-08f0-4a0b-aab5-aca557bff261)

### Expected Outcome

No errors

### Workaround
Install the events package  `pnpm install events`

###  Environment

Server
- Operating system: `Ubuntu 23.10`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `back4app`

Client
- Parse JS SDK version: `5.1.0`

**Comment by dplewis** [comment]
Duplicate https://github.com/parse-community/Parse-SDK-JS/issues/1766

You need to polyfill the event emitter.

We could replace the node event emitter with a custom isomorphic event emitter.
