### ISSUE TITLE
Upgrade to puppeteer 22

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-JS#2247]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).

### Issue

Merge https://github.com/parse-community/Parse-SDK-JS/pull/2244

**Comment by abdullateef97** [comment]
@mtrezza opened a PR for this [here](https://github.com/parse-community/Parse-SDK-JS/pull/2297)
