### ISSUE TITLE
`Parse.User.loginAs` method not available

### ISSUE THREAD

**Issue by rjcodedev** [parse-community/Parse-SDK-JS#2255]
### New Issue Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
"I tried to log in a user directly using the `Parse.User.loginAs` method in the Parse JS SDK, but it is not available. However, this feature was merged from version 4.2.0 as shown in this issue: [Parse JS SDK Issue #1875](https://github.com/parse-community/Parse-SDK-JS/pull/1875)."

### Actual Outcome
Not able to import from Parse JS SDK

### Expected Outcome
It must be available in the Parse JS SDK version 5.3.0, and users can log in with the master key using this method.

Server
- Parse Server version: `7.1.0`
- Operating system: `windows`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `mongodb`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- Parse JS SDK version: `5.3.0`

**Comment by mtrezza** [comment]
What do you mean by "not available"?

**Comment by rjcodedev** [comment]
<img width="621" alt="Screenshot 2024-08-01 140937" src="https://github.com/user-attachments/assets/e038aaac-a4e6-4a8e-993c-4594d6f3053d">


hey @mtrezza , see this image when i try to import it is not available

**Comment by mtrezza** [comment]
This seems to be just the IDE auto-complete, but does the method work? Also, which Parse JS SDK version is your IDE using here?

Related: https://github.com/parse-community/Parse-SDK-JS/issues/2012

**Comment by rjcodedev** [comment]
@mtrezza how do I check Parse js sdk version in my IDE
In my project I am using Parse : 5.3.0, Parse-server: 7.2.0

**Comment by rjcodedev** [comment]
hey @mtrezza , `Parse.User.loginAs` method is working but not available in suggestion. 
If you know how to update a package from suggestions, please let me know.

I am using VS-code

Thank you

**Comment by mtrezza** [comment]
@dplewis did a lot of the typescript conversion in this repo, maybe he could take a look...

**Comment by dplewis** [comment]
@rjcodedev You can submit a PR to [@types/parse](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/parse) to add this missing method.

**Comment by mtrezza** [comment]
~~@dplewis wasn't the purpose of https://github.com/parse-community/Parse-SDK-JS/issues/2012 to remove the reliance on @types/parse and instead use the TS definition that is generated by us?~~

Explained in https://github.com/parse-community/Parse-SDK-JS/issues/2012#issuecomment-2273656431

**Comment by mtrezza** [comment]
Closing as duplicate of https://github.com/parse-community/Parse-SDK-JS/issues/2012.
