### ISSUE TITLE
Exception in ParseLiveQuery in react-native

### ISSUE THREAD

**Issue by farwayer** [parse-community/Parse-SDK-JS#232]
`getSessionToken()` in `ParseLiveQuery` calls **sync** `currentUser()` and throw exception in react-native (with **async** storage)

**Comment by andrewimm** [comment]
@peterdotjs @wangmengyan95 is it possible for you to make the method in question, and whatever's calling it async? All current user fetching internally should be using the async methods, to support async storage systems.

**Comment by peterdotjs** [comment]
@andrewimm I'll make the change to use `currentUserAsync`.

**Comment by andrewimm** [comment]
Okay, my concern is that the caller functions might be synchronous, and APIs would need to change to adjust for this.

**Comment by peterdotjs** [comment]
Currently we're using `currentUser` to init the `DefaultLiveQueryClient` [here](https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/ParseLiveQuery.js#L116).  But we are using the sessionToken again [here](https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/ParseLiveQuery.js#L143). Assuming we want to query for the token on each subscribe the interface for LiveQueryClient.subscribe will need to change. @wangmengyan95

**Comment by farwayer** [comment]
Thanks for fast response guys. I found one more bug with WebSockets implementation in react-native. Look like live queries are not very popular functionality in RN :)
PR #233
