### ISSUE TITLE
Set query descending order from another class

### ISSUE THREAD

**Issue by kwstasna** [parse-community/Parse-SDK-JS#235]
I have this simple example in Parse.com Javascript SDK in the site that i'm building.

The Classes are the following

**_User Structure:**
- objectId
- username
- password
- name - string

**Posts Structure:**
- objectId
- postName - string
- postMsg - string
- postAuthor - Pointer< _User > (Pointer to the User Class)

**Comments Structure:**
- objectId
- msg - string
- post - Pointer< Posts > (Pointer to the Posts Class)
- user - Pointer< _User > (Pointer to User Class)

And i make this query to the Comments Class to take all the comments and also the Author's name and some other stuff.

```
var Comments= Parse.Object.extend("Comments");
var query = new Parse.Query(Comments);
/*Get the Post's Info*/
query.include("post");
/*Get the Post Author's Info*/
query.include("post.postAuthor");
/*Get the Comment's Author Info*/
query.include("user");
query.find().then(function(results){
    /* Go Through Each Comment*/
    var commentsArray = new Array();
    for(i in results){
        /* Set obj to current comment*/
        var obj = results[i];
        /* Get Post's Name */
        var postName = obj.get("post").get("postName");
        /* Get Post's Message */
        var postMsg = obj.get("post").get("postMsg");
        /* Get Post Author's Name */
        var authorName = obj.get("post").get("postAuthor").get("name");
        /* Get Comment's Message */
        var commentMsg = obj.get("msg");
        /* Get Comment's Author*/
        var commentAuthor = obj.get("user").get("name");

        /* Let's Put the Comment Information in an Array as an Object*/
        commentsArray.push({
            post:{
                name: postName,
                msg: postMsg
            },
            author: authorName,
            comment: {
                author: commentAuthor,
                msg: commentMsg
            }
        });
    }
})
```

So my question is, in this query how can i make the order of the results to be descending by "createdAt" from POSTS Class, and not from the Comments Class that the main query is?

Is there any way to do that?
Something like 

```
query.descending("post.createdAt");
```

Any idea?

**Comment by Quaggie** [comment]
It could be better to do a 
```javascript
query.exists('post')
query.descending("post.createdAt");
```
just to guarantee that it will always work. But yes, that should definitely work.

p.s. The recommended way of initialising an array is with:
```javascript
 var commentsArray = []
```

**Comment by kwstasna** [comment]
@Quaggie  nope its giving an 105 error that post.createdAt is not a valid field name

**Comment by chrismatheson** [comment]
Yeah, this is a problem for me also. The Only solution i can think of personally is to use a cloud function, fetch everything, and the do sort, limit & skip "manually"
