### ISSUE TITLE
Cannot get back the full object from the relational field after saving an object

### ISSUE THREAD

**Issue by carmenlau** [parse-community/Parse-SDK-JS#251]
We set a complete object to object's relation field, but there is only id leave after saving. Following is the testing code and the output comparison between parse.com and parse-server.

**The testing cloud code:**

```
Parse.Cloud.define("testQuery", function(request, response) {
  var objectQuery = new Parse.Query(ObjectClass);
  var Object;

  objectQuery.include('user');
  objectQuery
  .get("_<object_id>_", {useMasterKey: true})
  .then(function(_object) {
    object = _object;
    object.set('user', request.user);
    console.log("1 ======> " + JSON.stringify(object.get("user")));
    console.log("1 ======> " + object.get("user").getUsername());
    return object.save(null, {useMasterKey: true});
  })
  .then(function() {
    console.log("2 ======> " + JSON.stringify(object.get("user")));
    console.log("2 ======> " + object.get("user").getUsername());
    response.success("");
  }, function(error) {
    response.error(error);
  });
});
```

**console log of parse.com:**
1 ======> {**< full user object >**}
1 ======> username
2 ======> {**< full user object >**}
2 ======> username

**console log of parse-server:**
1 ======> {**< full user object >**}
1 ======> username
2 ======> {"objectId":"**< user id >**"}
2 ======> undefined

**Comment by andrewimm** [comment]
Which of the two outputs is cloud code, and which is from parse-server. You wrote parse.com twice :)

**Comment by andrewimm** [comment]
Also, please provide which version of the Parse SDK you are using (`console.log(Parse.CoreManager.get('VERSION'))`)

**Comment by carmenlau** [comment]
@andrewimm sorry for confusion! I just updated my comment :P

The first one is parse.com and second one is parse-server

The parse SDK version is `js1.8.1`

**Comment by andrewimm** [comment]
Very peculiar. Saving the object shouldn't have side effects on its children. I'll investigate this

**Comment by Quaggie** [comment]
```javascript
Parse.Cloud.define("testQuery", function(request, response) {
  var objectQuery = new Parse.Query(ObjectClass);
  var Object; // <-- upperCase `O` and a reserved Javascript constructor

  objectQuery.include('user');
  objectQuery
  .get("_<object_id>_", {useMasterKey: true})
  .then(function(_object) {
    object = _object; // <-- lowerCase `o` and a leaked global since it´s not declared with var
    object.set('user', request.user);
    console.log("1 ======> " + JSON.stringify(object.get("user")));
    console.log("1 ======> " + object.get("user").getUsername());
    return object.save(null, {useMasterKey: true});
  })
  .then(function() {
    console.log("2 ======> " + JSON.stringify(object.get("user")));
    console.log("2 ======> " + object.get("user").getUsername());
    response.success("");
  }, function(error) {
    response.error(error);
  });
});
```
I'm guessing your parse server configuration isn't injecting globals even though Parse.com probably does. Try to run this code with `'use strict';`

**Comment by airdrummingfool** [comment]
@carmenlau do you have a `beforeSave` function defined for the `ObjectClass` class? And what Parse.com SDK version did you use to run the test cloud code?
