### ISSUE TITLE
Parse.User.logIn or UserSubclass.logIn does not return a subclass instance

### ISSUE THREAD

**Issue by codebreach** [parse-community/Parse-SDK-JS#263]
``` es6
    class CustomUser extends ParseUser {
      customMethod() {
        return 'a';
      }
    }
    ParseObject.registerSubclass(ParseUser.className, CustomUser);
    CustomUser.logIn('username', 'password').then((u) => {
      expect(u instanceof CustomUser).toBe(true);
      expect(u.customMethod()).toBe('a');
    });
```

Failing test case:
https://github.com/drinklynk/Parse-SDK-JS/commit/0a9fa9cfeee1dd9d2e47a356849ee67ae161e97a

**Comment by andrewimm** [comment]
Interesting. Seems like rather than instantiating a new ParseUser directly, we want to use the className approach and create a `new ParseObject('_User')`.
This might get a little tricky with the user class rewrite flag, but I'll look into this.

**Comment by dpoetzsch** [comment]
Same problem seems to exist with `User.become`

**Comment by fmendoza** [comment]
Any workaround for this issue?

**Comment by flovilmart** [comment]
This hasn’t been addressed yet, but further investigation would be appreciated

**Comment by fmendoza** [comment]
I found a way to do it

```
let user = new MyCustomUserClass;
user.username = 'johndoe';
user.password = 'secret';
user.logIn(null).then(obj => {
/// obj is an instance of MyCustomUserClass
```

**Comment by gcysne** [comment]
Thanks fmendoza, this workaroud is really helpfull.

**Comment by awgeorge** [comment]
This workaround seems to no longer work with parse server v3 as we get `username/email is required`, @fmendoza can you confirm?

**Comment by fmendoza** [comment]
Still working on my end with Parse Server v3 and Parse SDK JS 2.1
