### ISSUE TITLE
Returning a string and not XHR when XHR request fails.

### ISSUE THREAD

**Issue by shivangagarwal** [parse-community/Parse-SDK-JS#292]
Hi,

In RESTController.js, for uniformity the return if xhr.status == 0 should be a xhr and not string. Please find the code below:

```
    if (xhr.status >= 200 && xhr.status < 300) {
      var response;
      try {
        response = JSON.parse(xhr.responseText);
      } catch (e) {
        promise.reject(e.toString());
      }
      if (response) {
        promise.resolve(response, xhr.status, xhr);
      }
    } else if (xhr.status >= 500 || xhr.status === 0) { // retry on 5XX or node-xmlhttprequest error
      if (++attempts < CoreManager.get('REQUEST_ATTEMPT_LIMIT')) {
        // Exponentially-growing random delay
        var delay = Math.round(
          Math.random() * 125 * Math.pow(2, attempts)
        );
        setTimeout(dispatch, delay);
      } else if (xhr.status === 0) {
        promise.reject('Unable to connect to the Parse API'); //Here the return should be a xhr so that it can be handled in the application in a better way.
      } else {
        // After the retry limit is reached, fail
        promise.reject(xhr);
      }
    } else {
      promise.reject(xhr);
    }
  };
```

Let me know if you require some more details.

**Comment by andrewimm** [comment]
I understand why you might see uniformity as ideal here, but follow through on the code that uses `RESTController.ajax()`: https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/RESTController.js#L220

The expectation is that `.ajax` does any specifics related to HTTP requests, and `.request` wraps that interpretation in something usable. When the Promise returned from `.ajax` is rejected, we need to fork the error statement based upon whether it was generated externally or internally. The easiest way to suggest a response comes from the XHR is just to return the XHR itself; anything that isn't shaped like a XHR get JSON-stringified and passed as an error. That alternate case could be a string, a number, an Array, an Object... it's open-ended, and designed to be stable for all corner cases. That said, looking at this code, the Flow typing in the header should be updated to be `{responseText: string} | string`

Is this breaking something for you? I'm curious why you feel it needs to be changed, other than for style.

**Comment by shivangagarwal** [comment]
Its not breaking anything for us. We are tacking errors on the based of XHR returned, and in this particular case we have to handle the string as well. Just for the uniformity.
