### ISSUE TITLE
When adding 2 relations in a row, the second relation is not added successfully

### ISSUE THREAD

**Issue by refre5h** [parse-community/Parse-SDK-JS#300]
Originally reported here: https://github.com/ParsePlatform/parse-server/issues/2121
### Issue Description

When adding 2 relations in a row (one after the other, NOT both at the same time), the second relation is not added successfully. This happens in our iOS app, and confirmed in cloudcode.

Example: I add a friend in the app, this friend will be added to my "friends" relation in my user object. I then find another friend, add this new friend. This new friend will not be added to my "friends" relation, our app actually crashes. The sample snippet below shows how to replicate this case in the cloudcode.
### Steps to reproduce
1. add a relation
2. save the object
3. check db, the above relation is added
4. Add another relation
5. Save the object again
6. check db, the second relation is not added

``` javascript
Parse.Cloud.define("addFriends", function(request, response) {
    var user = new Parse.Object("_User");
    user.id = "IMEIcGMzHK";
    var friend1 = new Parse.Object("_User");
    friend1.id = "zhukOmQMwZ";
    var friend2 = new Parse.Object("_User");
    friend2.id = "ycaor1Xqrq";

    var relation = user.relation("friends");
    relation.add(friend1);
    user.save(null, {useMasterKey:true}).then(function(updatedUser){
        // friend1 relation is successfully added
        var relation = updatedUser.relation("friends");
        relation.add(friend2);
        return updatedUser.save(null, {useMasterKey:true});
    }).then(function(user){
        //friend2 is not added
        response.success(user);
    }, function(error){
        response.error(error)
    })
})
```
#### Expected Results

Both relations should be added.
#### Actual Outcome

Only the first relation is added
### Environment Setup
- **Server**
  - parse-server version: ~2.2.10
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku
### Logs/Trace

```
verbose: POST /parse/functions/addFriends { host: 'localhost:1337',
  'user-agent': 'curl/7.43.0',
  accept: '*/*',
  'x-parse-application-id': 'myAppId',
  'x-parse-rest-api-key': 'myRESTAPIKey' } {}
verbose: PUT /parse/classes/_User/IMEIcGMzHK { 'user-agent': 'node-XMLHttpRequest, Parse/js1.8.5 (NodeJS 4.3.1)',
  accept: '*/*',
  'content-type': 'text/plain',
  host: 'localhost:1337',
  'content-length': '265',
  connection: 'close' } {
  "friends": {
    "__op": "AddRelation",
    "objects": [
      {
        "__type": "Pointer",
        "className": "_User",
        "objectId": "zhukOmQMwZ"
      }
    ]
  }
}
verbose: {
  "response": {
    "updatedAt": "2016-06-23T23:50:43.509Z"
  }
}
verbose: PUT /parse/classes/_User/IMEIcGMzHK { 'user-agent': 'node-XMLHttpRequest, Parse/js1.8.5 (NodeJS 4.3.1)',
  accept: '*/*',
  'content-type': 'text/plain',
  host: 'localhost:1337',
  'content-length': '155',
  connection: 'close' } {}
verbose: {
  "response": {
    "updatedAt": "2016-06-23T23:50:44.938Z"
  }
}
verbose: {
  "response": {
    "result": {
      "friends": {
        "__type": "Relation",
        "className": "_User"
      },
      "updatedAt": "2016-06-23T23:50:44.938Z",
      "objectId": "IMEIcGMzHK",
      "__type": "Object",
      "className": "_User"
    }
  }
}
```

**Comment by dpoetzsch** [comment]
https://github.com/parse-community/Parse-SDK-JS/issues/300


I can confirm this behavior and created a failing test:

```javascript
  it('can add two wheels to a relation while saving in between', () => {
    const Wheel = Parse.Object.extend("Wheel");
    const Car = Parse.Object.extend("Car");

    return new Wheel().save().then(w1 =>
      new Wheel().save().then(w2 =>
        new Car()
          .save()
          .then(c => {
            c.relation('wheels').add(w1);
            return c.save();
          })
          .then(c => c.fetch())
          .then(c => {
            c.relation('wheels').add(w2);
            return c.save();
          })
          .then(c => c.relation('wheels').query().find())
          .then(wheels => {
            assert.equal(wheels.length, 2);
            assert.equal(wheels.map(i => i.id).sort()[0], [w1.id, w2.id].sort()[0]);
            assert.equal(wheels.map(i => i.id).sort()[1], [w1.id, w2.id].sort()[1]);
          })
      )
    )
  });
```

**Comment by rorz** [comment]
I'm still getting this issue when, for a given `Parent` with a `children` relation of `Child`, the following does not work:

- Re-initialising the `Parent` via `.save` in between each `.get('children').add(Child)` call
- Adding the children as an array, e.g. `Parent.get('children').add([Child1, Child2, Child3])`

The only way I can get it to reliably work is by initialising a *new query* every time I want to add a relation. This does not scale well for adding an arbitrary number of children to a relation.

Just wondering if anyone knows what's going on with this, since it's been open for 2 years?

Still love Parse :)

**Comment by flovilmart** [comment]
We haven’t had the time to investigate it. We’ll have a look then :)

**Comment by rorz** [comment]
Thanks :) Will have a look at the source myself too, instead of just coming on here to moan!

**Comment by flovilmart** [comment]
@rorz thanks! That’s appreciated ;)

**Comment by vmkudrin** [comment]
Have same issue with current version.

**Added friend1 only:**
```
user.relation("friends").add(friend1);
user.relation("friends").add(friend2);
user.save();
```

**Added both friend1 and friend2:**
```
let relation = user.relation("friends");
relation.add(friend1);
relation.add(friend2);
user.save();
```

**Comment by franalt** [comment]
This is still an issue, any update on this?

**Comment by franalt** [comment]
I can confirm @vmkudrin method works!
