### ISSUE TITLE
Losing sessionToken on Parse.Cloud.run

### ISSUE THREAD

**Issue by ericraio** [parse-community/Parse-SDK-JS#306]
The getSessionToken call here is returning undefined after the user is already logged in. When calling currentUserAsync(), the cache user is returned and it's a valid parse object but the sessionToken is missing.

I was able to write a hack in the application by calling Parse.User._clearCache()

What's a better solution for this?

node_modules/parse/lib/browser/RESTController.js:201

```
      return userController.currentUserAsync().then(function (user) {
        if (user) {
          return _ParsePromise2['default'].as(user.getSessionToken());
        }
        return _ParsePromise2['default'].as(null);
      });
```

**Comment by andrewimm** [comment]
Can you explain the scenario where your code gets in this state? The code is written the way it is because what you describe typically shouldn't happen, and you can be sure that we have plenty of tests around this behavior.

**Comment by ericraio** [comment]
@andrewimm I'll have to investigate this some more. I know that the query I am making is a more unusual query
