### ISSUE TITLE
No Response when using Parse.Object.saveAll()

### ISSUE THREAD

**Issue by ryanemax** [parse-community/Parse-SDK-JS#328]
- parse-server version 2.2.17

There is No Response when use Parse.Object.saveAll() to save Members: Array()

``` js
// @params MembersArray
// about 68 records in this Array

Parse.Object.saveAll(MembersArray, {
success: function(objs) {
            console.log(objs)
            console.log("DONE!")
            // no done occurred...
},
error: function(err) {
            console.log(err)
            console.log("ERROR!")
            // no error occurred...
        }
});
```

But it works when I use MembersArray.forEach(m=>(m.save)).

``` js
let count =0
 MembersArray.forEach(m=>{
            m.save().then(data=>{
                        count++
                        console.log("Progress",count," of ", Members.length)
                        if(count == Members.length){
                                                console.log("All Done!")
                        }
            })
})
```

log like this

``` sh
Progress 1 of 68
Progress 2 of 68
Progress 3 of 68
......
Progress 68 of 68
All Done!
```

I'm Shocked! save() one-by-one works, But take me about 2 minites to save 68 records to mongodb.

**Comment by ryanemax** [comment]
Is there any function like the insertmany() in Parse.Object? to help save multiple records into mongodb

**Comment by andrewimm** [comment]
When you run saveAll, can you confirm which network requests are actually sent? SaveAll tries to attempt batches of 20 objects, so ideally you should see 4 different network requests.

**Comment by ryanemax** [comment]
@andrewimm I run this in server-end node script, I don't know how to see requests of batches.
how to dump all of this requests to debug?

I use this and get nothing:
``` sh
httpry -i eno1
```

**Comment by ryanemax** [comment]
where does saveAll() send post requests to? my parse-server or mongodb? 
If that, I think I should write an request function using REST API, instead of saveAll(), for temprary?

**Comment by andrewimm** [comment]
The SDK sends requests to your parse-server, it doesn't know anything about your backing database.

Unfortunately, I don't know anything about your specific setup, so I can't provide any deeper advice on how to debug your network connection. Some well-placed logging or debugger breakpoints might help, but I can't do much without a reproducible case or a stack trace

**Comment by suathh** [comment]
I belive this problem is still alive I have 2-4k objects to update and a new save for each of 2-4k objects. This takes about 50-80mins to complete.
I am doing this in that way.

`guessQuery.each(
    function(guessItem){    
      return processGuess(guessItem,match_result,match_home_score,match_away_score);
    }` 

And this function returns

```
return guessResult.save().then(
        function(guessResult){
          guess.set("checked",true);
          return guess.save();
        }
```
Before I was doing this with promises arrays `Parse.promise.when()` but it not seems to be working correctly because I was getting multiple same records and non-updated records.

Is there any better way to do this ? 

Thanks.

**Comment by ryanemax** [comment]
@suathh I'm using **mongoose lib** for temporary, there are methods to handle multi save & update.
But it's need you to write custom RESTful API for access mongodb directly.
- insertMany() https://docs.mongodb.com/manual/reference/method/db.collection.insertMany/
- updateMany() https://docs.mongodb.com/manual/reference/method/db.collection.updateMany/
- bulkWrite() https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/

I hope parse-server will support these feature for mongodb.
