### ISSUE TITLE
Two chained Parse.Object.saveAll() results in last objects NOT having their properties available

### ISSUE THREAD

**Issue by MobileVet** [parse-community/Parse-SDK-JS#331]
### Issue Description

If I chain together 2 saveAlls, I would expect to be able to access the objects saved in the second call.  However, strangely, those objects do not respond to `object.get("property")` instead returning undefined.
### Steps to reproduce
1. `Parse.Object.saveAll(obj)`
2. `.then(Parse.Object.saveAll(otherObjs)`
3. `.then(function(otherObjs) {});`
#### Expected Results

Currently experiencing this issue in Cloud Code.

I should be able to call **.get("property")** on one of the objects returned.  This works fine if I don't chain the saveAlls but instead move the first one elsewhere in the code.
#### Actual Outcome

```
  function something() {
    var logs = new Array();
    var receipts = new Array();

    // fill the arrays with valid Parse.Objects

    return Parse.Object.saveAll(logs,{sessionToken: token})
            .then(Parse.Object.saveAll(receipts,{sessionToken: token}));

  }).then(function(receipts) {
    console.log(receipts[0].id);                          // will print valid objectId if length > 0
    console.log(receipts[0].get("property");    // prints UNDEFINED, despite 'property' being valid
    console.log(JSON.stringify(receipts[0]));   // prints out the object like I would expect
  });
```
### Environment Setup
- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.1.15
  - Operating System:     OS X 10.11.6
  - Hardware:                   MBP
  - Localhost or remote server? Localhost

**Comment by andrewimm** [comment]
I'm having trouble reproducing this with just a bare Parse SDK, without the Cloud Code environment, so I'll need some more information to help debug. Can you clarify one thing for me? It sounds like `.get('property')` does not work, but calling `JSON.stringify(receipts[0])` *contains* the `property` key? They get the value from the exact same location

**Comment by MobileVet** [comment]
Hey Andrew... definitely recognize this might cross the boundaries between the server and the Javascript land.

Yes... you are correct.  `JSON.stringify(receipts[0])` was showing the various `properties`, including the one I was after.  Frankly I was at a total loss, as you say, they come from the same place.
