### ISSUE TITLE
Subclassing Parse.User

### ISSUE THREAD

**Issue by futureinapps** [parse-community/Parse-SDK-JS#335]
import Parse from 'parse';
class CustomUser extends Parse.Object{
    static name(){
        return 'haha';
    }
    constructor(){
        super('_User');
        this.hahah = 'sadad';
    }
}
export default CustomUser;

and i have registerSubclass in index file.

Other classes a normaly subclassing, but user not 

when i do query:

let newUser = new CustomUser();
let query = new Parse.Query(newUser)

and in callback i have _User object without hahah

**Comment by tsvetann** [comment]
Did you try to extend the Parse.User object directly?

```
Parse.User.allowCustomUserClass(true);
class UserModel extends Parse.User.....
```

**Comment by RaschidJFR** [comment]
I think this is related to parse-community/parse-server#5521
