### ISSUE TITLE
LiveQueries not returning subclass of ParseObject 

### ISSUE THREAD

**Issue by DeDuckProject** [parse-community/Parse-SDK-JS#340]
Hi,
I'm pretty sure this is an issue:
I have extended ParseObject (doing all it takes including registersubclass etc..)
When I do a regular query I get the proper subclass of ParseObject.
However, when I get a LiveQuery update for one of these object I get it as a ParseObject, while inside it DOES hold the subclasses of ParseObject:

(res is the result from the server, notice "to" field, which is a DbLocation object (my subclass for ParseServer)

<img width="383" alt="screenshot 2016-08-30 18 14 19" src="https://cloud.githubusercontent.com/assets/10045034/18094854/99993536-6edd-11e6-94a0-577cc40d18b5.png">

**Comment by dpoetzsch** [comment]
duplicate of #372

**Comment by dplewis** [comment]
Closed via https://github.com/parse-community/Parse-SDK-JS/pull/662
