### ISSUE TITLE
User changed by cloud function when queried from client side returns stale data

### ISSUE THREAD

**Issue by pushparajsamant** [parse-community/Parse-SDK-JS#341]
Opening a issue on JS SDK as suggested by flovimart as its not related to the parse server.
Link to issue. https://github.com/ParsePlatform/parse-server/issues/2614

**Comment by pushparajsamant** [comment]
This should affect a lot of users. The flow of the issue is this. 
1. The basic issue is the client code calls the cloud function. 
2. The cloud function makes some changes on the user using the same session code. 
3. But once the cloud function returns to client side, if we query the User table to get the new data, it will keep returning the old data until the app is closed and opened again.

**Comment by pushparajsamant** [comment]
When is this issue going to be fixed.

**Comment by pushparajsamant** [comment]
Absolutely no updates since 22 days on this. Is no one facing this issue. It seems like a bug which will happen in most app scenarios.

**Comment by pushparajsamant** [comment]
@andrewimm Could you please respond on this issue. I am desperately waiting for a response from you guys since one month now.

**Comment by andrewimm** [comment]
@pushparajsamant I tried reproducing this case, but was unable to create the behavior you described. Is it possible to put together a small code sample that consistently reproduces this? It will help me debug. Otherwise, there isn't much I can do.

**Comment by pushparajsamant** [comment]
@andrewimm I feel its true for situations when you add pointers to objects not primitive data. So if the pointer object did not exist before the call, and if it was created and attached in the cloud function, it doesnt reflect on the client side. Adding the code in parse sdk where I can point the issue

```
{
    key: '_finishFetch',
    value: function _finishFetch(serverData) {
      if (!this.id && serverData.objectId) {
        this.id = serverData.objectId;
      }
      ObjectState.initializeState(this.className, this._getStateIdentifier());
      var decoded = {};
      for (var attr in serverData) {
        if (attr === 'ACL') {
          decoded[attr] = new _ParseACL2['default'](serverData[attr]);
        } else if (attr !== 'objectId') {
          decoded[attr] = (0, _decode2['default'])(serverData[attr]);
          if (decoded[attr] instanceof _ParseRelation2['default']) {
            decoded[attr]._ensureParentAndKey(this, attr);
          }
        }
      }
      if (decoded.createdAt && typeof decoded.createdAt === 'string') {
        decoded.createdAt = (0, _parseDate2['default'])(decoded.createdAt);
      }
      if (decoded.updatedAt && typeof decoded.updatedAt === 'string') {
        decoded.updatedAt = (0, _parseDate2['default'])(decoded.updatedAt);
      }
      if (!decoded.updatedAt && decoded.createdAt) {
        decoded.updatedAt = decoded.createdAt;
      }
      ObjectState.commitServerChanges(this.className, this._getStateIdentifier(), decoded);
    }
  }
```
I can see the latest changes in the decoded object. But in the next call it is not able to commit the server changes.
```
function commitServerChanges(className, id, changes) {
  var state = initializeState(className, id);
  for (var attr in changes) {
    var val = changes[attr];
    state.serverData[attr] = val;
    if (val && typeof val === 'object' && !(val instanceof _ParseObject2['default']) && !(val instanceof _ParseFile2['default']) && !(val instanceof _ParseRelation2['default'])) {
      var json = (0, _encode2['default'])(val, false, true);
      state.objectCache[attr] = JSON.stringify(json);
    }
  }
}
```
In the above code I see it in changes object but it gets lost if the pointer didnt exist before on the Parseobject. 
Is the below code not useful. Are you not able to replicate with it either.
Sure here it is.
This is the call to the cloud function which is inside a promise

```
Parse.Cloud.run("notification_update", params))
    .then(function(obj) {
        dfd.resolve(obj);
    }, function onError(err) {
        console.error(err)
        dfd.reject(err);
}
```
The relevant code in cloud function

```
currentUser.set("team", team);
console.log("Session token ");
console.log(currentUser.getSessionToken());
promises.push(currentUser.save(null, { sessionToken: currentUser.getSessionToken() }));
```
Once the cloud function returns the promise I call this function to get the latest data. 
```
var refresh = function onRefresh(dfd) {
      console.debug("Refresh user was triggered..");
     var currentUser = Parse.User.current();
     var q = new Parse.Query(Parse.User);
     q.include("team");
     q.get(currentUser.id)
        .then(function success(user) {
        currentUser.set({
            team: user.get("team"),           //Here the data is not updated
        });
        if (dfd && dfd.resolve) {
            dfd.resolve(currentUser);
        }
    }, function onError(error) {
        if (dfd && dfd.reject) {
            dfd.reject(error);
        }
    });
}
```

**Comment by pushparajsamant** [comment]
@andrewimm One thing I forgot to mention is this only happens for the User ParseObject.

**Comment by pushparajsamant** [comment]
@andrewimm Please help me on this issue. Badly stuck with it. No way out.

**Comment by pushparajsamant** [comment]
@andrewimm At least let me know if there is a way to disable the query caching. I am waiting for you guys for 2 months now. Just fed up of this.
