### ISSUE TITLE
How to read the full _Installation object?

### ISSUE THREAD

**Issue by AndrewLane** [parse-community/Parse-SDK-JS#344]
I feel like I'm missing something simple.  I know I can save the installation object just using Parse.Installation, but is there a way to just retrieve the "current" installation object (if it's stored in Parse)?  I know that Parse disallows a query to be done on the installations class without a master key.  But if I know the installation id (from just Parse._getInstallationId()), how can I fetch all the data already stored in Parse for a given installation?

**Comment by AndrewLane** [comment]
Following up on this...

**Comment by danielmartinprieto** [comment]
I'm wondering about this as well, given that you can get the current Installation with the native SDKs (Android, iOS...) with a class method, but not in JavaScript.

**Comment by AndrewLane** [comment]
@danielmartinprieto don't think we're going to get an answer since this issue is a couple years old now :-)

**Comment by danielmartinprieto** [comment]
@AndrewLane yeah, I've seen that, let's see if we're lucky! I've created a new one here in case this one gets buried: https://github.com/parse-community/Parse-SDK-JS/issues/693
