### ISSUE TITLE
Any plans to implement file upload progress?

### ISSUE THREAD

**Issue by TAProgramming** [parse-community/Parse-SDK-JS#347]
Hello,

I think having a file upload progress callback is an essential feature, especially considering many users will have varying internet upload speeds and may thing that the upload is stuck.
I have a continuous loading animation, but that doesn't show real progress of the file upload.

If it's not impossible, please could you consider it. I may try to contribute if no one is interested, but being a front end developer it may take some time for me.

Thanks. :)

**Comment by didierfranc** [comment]
Rest and especially fetch who become the new standard, doesn't implement a way to do that ...

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/373
