### ISSUE TITLE
getSessionToken() on queried user object is always undefined

### ISSUE THREAD

**Issue by danepowell** [parse-community/Parse-SDK-JS#379]
I'm trying to implement an authentication function in Cloud Code that (for the sake of argument) should accept a pairing code and return a new valid session token for the corresponding user.

According to the documentation, this should be as easy as querying for the user and then returning getSessionToken(). However, getSessionToken() always seems to return undefined.

At first I thought this was because I needed to use the master key (according to the docs), but even with that it still fails: https://github.com/ParsePlatform/Parse-SDK-JS/blob/v1.9.2/src/ParseUser.js#L346

Am I missing something? Is there any way at all (even with a master key in Cloud Code) to generate a new session for a user without logging in with a password?

````
var query = new Parse.Query(Parse.User);
query.equalTo("code", request.params.code);
query.first({
  useMasterKey: true,
  success: function(user) {
    if (user !== null && typeof user === 'object') {
      var token = user.getSessionToken();
      // token is always undefined here
      response.success(token);
    }
    else {
      console.log("User not found.");
    }
  },
  error: function(error) {
    console.log("Query error: " + error);
  }
});
````

**Comment by danepowell** [comment]
I'm starting to suspect this is actually a gap with ParseServer and opened an issue there, although we should update the documentation for the JS SDK if this is no longer supported.

**Comment by Ryqsky** [comment]
I have also encountered this problem.
I found that only the user has been logged in (at the same time， the parse server has created the Session of the user), then I can use the getSessionToken() funtion. 

![image](https://cloud.githubusercontent.com/assets/8382136/20550870/2d28071c-b175-11e6-9a88-c2967edd573e.png)

so , you can set random password and use Parse.User.logIn() or **[Parse.User_logInWith()](https://parseplatform.github.io/Parse-SDK-JS/api/classes/Parse.User.html#methods__linkWith)** from the Facebook SDK

method 1:
```
var query = new Parse.Query(Parse.User);
query.equalTo("code", request.params.code);
query.first({
  useMasterKey: true,
  success: function(user) {
    if (user !== null && typeof user === 'object') {
      var randomPassword = '123123'
      user.set("password", randomPassword)
        .save()
        .then(user => {
           Parse.User.logIn(user.get("username"), randomPassword)
           .then(user => {
              var token = user.getSessionToken();
              // token is always undefined here
              response.success(token);
           })
        })
    }
    else {
      console.log("User not found.");
    }
  },
  error: function(error) {
    console.log("Query error: " + error);
  }
});
```

method 1:

but the better method is use **[Parse.User_logInWith()](https://parseplatform.github.io/Parse-SDK-JS/api/classes/Parse.User.html#methods__linkWith)** from the Facebook SDK: 

before use _logInWith, you should read the [**Oauth**](https://github.com/ParsePlatform/parse-server/wiki/OAuth) and Configuration options for these 3rd-party modules is done with the oauth option passed to Parse Server:

```
const authData = {
   id: request.params.code,
   access_token: util.md5(request.params.code),
   expiration_date: new Date(90 * 24 * 60 * 60 * 1000 + (+new Date())).toJSON()
}
Parse.User._logInWith("facebook", {
   authData
})
  .then(user => {
    var token = user.getSessionToken();
    console.log(token)
  }
  .catch(e => console.log(e))
```
