### ISSUE TITLE
flow-type support for parse-sdk-js

### ISSUE THREAD

**Issue by mmazzarolo** [parse-community/Parse-SDK-JS#387]
FYI I submitted a [PR](https://github.com/flowtype/flow-typed/pull/555#issuecomment-268773481) to [flow-typed](https://github.com/flowtype/flow-typed) that enables the flow support for the Parse-SDK-JS.  
It is still a WIP, but I tried to put there the most common parts of the SDK (picking them directly from the SDK source code).  
Hope you can find it useful, contributions are welcome :)  

P.S.: Another way for enabling the flow support is to simply bundle Parse-SDK-JS with flow definitions (in the format: `xxx.flow.js`)

**Comment by andrewimm** [comment]
This is great, thanks for doing this.
