### ISSUE TITLE
React-Native error with connection 

### ISSUE THREAD

**Issue by futureinapps** [parse-community/Parse-SDK-JS#390]
Hi, i have 2 apps web js and swift iOS that succesfully connecting to parse server. But on React-Native android app, when i 'll trying to do some request  returns error: XMLHttpRequest failed:"Unable to connect to the Parse API"

**Comment by markmssd** [comment]
hey @futureinapps , I'm having the exact same issue. How did you end up solving it?

Thanks!

**Comment by markmssd** [comment]
In my case, it was working on Android when I changed `https` to `http`. I suppose further configuration is needed to support `https`.
