### ISSUE TITLE
[New Feature] Add 'withinPolygon' to ParseQuery

### ISSUE THREAD

**Issue by tarekskr** [parse-community/Parse-SDK-JS#391]
In addition to the existing 'ParseQuery.withinGeoBox', we also need a 'withinPolygon' function so that we could search inside a polygon of GeoPoints. 

AFAIK, this is supported by MongoDB, but I have no idea how to implement it myself in Parse :)

**Comment by tarekskr** [comment]
Here is the MongoDB documentation: https://docs.mongodb.com/manual/reference/operator/query/polygon/#op._S_polygon

**Comment by dplewis** [comment]
Added in Parse Server 2.5.0
