### ISSUE TITLE
Parse.User.Logout() can't be run if in node environment, while Login() can

### ISSUE THREAD

**Issue by bdbaddog** [parse-community/Parse-SDK-JS#393]
This leaves sessions hanging valid.
I have an express app next to my parse-server and parse-dashboard.
Ideally I'd like to see Logout check for a session token and not just bail out because it's running under node.
Then it could delete the session token and return?

```javascript
    // You could have a "Log Out" link on your website pointing to this.
    app.get('/logout', function (req, res) {
        res.locals.loggedIn = 0;
        res.locals.isAdmin = 0;

        if (req.session && req.session.token) {
            Parse.User.logOut({ sessionToken: req.session.token }).then(function () {
                req.session = null;
                res.redirect('/');

            }, function (err) {
                handleParseError(err);
            });
        } else {
            res.redirect('/');
        }
    });
```

**Comment by mcvendrell** [comment]
Yep, same problem here, `logOut `does nothing. I did some tests and seems that problem could be in that `Parse.Session.current()` is not working (and `logOut `code depends on that function).

To workaround it, the REST function is working fine. I tested it and session is deleted right (so user cannot use the token anymore):

```
curl -X POST \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
  -H "X-Parse-Session-Token: r:pnktnjyb996sj4p156gjtp4im" \
  https://api.parse.com/1/logout
```
