### ISSUE TITLE
Basic Login via js api not working

### ISSUE THREAD

**Issue by hydex86** [parse-community/Parse-SDK-JS#396]
I'm opening a new issue to track it as a new one, but it seems I'm having the same problem than: https://github.com/ParsePlatform/Parse-SDK-JS/issues/262

The point is everything works well if my parse-server is version 2.2.23 or below. But if I upgrade my server to version 2.2.24 my JS client gets this response: {"error": "unauthorized"}

My iOS client works fine both in version 2.2.23 and 2.2.24. I've tested with parse-server versions 2.2.24 and 2.3.1.

I had to rollback my parse-server version to 2.2.23 to keep working.

I'm using parse-sdk-js version 1.9.2 (npm package).

**Comment by henninghorn** [comment]
Hi @hydex86 

I've just deployed the latest Parse Server (2.3.2) to Heroku and I'm using the Parse npm package (1.9.2).

I've only implemented a simple login/logout and sign up flow, and everything works great.
To me it sounds like a configuration problem causing your problem.
Or maybe the problem have been "fixed" in 2.3.2?

**Comment by nikolausii** [comment]
Hi @hydex86,

i've got the same problem. I updated my parse server from 2.2.16 to 2.3.2 and i get the same response:  {"error": "unauthorized"} - 403 Forbidden.
I'm also using parse-sdk-js version 1.9.2 (npm package).

Have you already found a solution?

**Comment by henninghorn** [comment]
@nikolausii Have you checked that the SDK is making the right request to the right endpoint?

You can inspect your network request in your browser. It sounds like some settings aren't configured correctly.

**Comment by nikolausii** [comment]
We solved it. The parse-server was up to date, but the parse npm had the version 1.8. After an update to 1.9.2 everything works fine.

**Comment by adlondon** [comment]
@hydex86 did you ever figure out a solution? I'm upgrading my parse server  from 2.2.7 and am getting the same  {code: undefined, message: "unauthorized"}. Everything has been working fine up until now
