### ISSUE TITLE
Unable to call Parse Cloud functions after hosting on Heroku  error XMLHttpRequest failed: "Unable to connect to the Parse API"

### ISSUE THREAD

**Issue by willyyang** [parse-community/Parse-SDK-JS#401]
So I am sure the cloud function works because I am able to hit the function by using curl.
This is what I ran and it works.
```
curl -X POST -H "X-Parse-Application-Id: myAppId" -H "Content-Type: application/json" -d '{}' https://xxxx.herokuapp.com/parse/functions/upsert
```

Here is my client configuration code
```
import Parse from 'parse/react-native';
Parse.initialize('myAppId');
Parse.serverURL = 'https://xxxx.herokuapp.com/parse/';
```

I am getting a ` 100: XMLHttpRequest failed: "Unable to connect to the Parse API"` error most likely due to issues with `https`

Please let me know what else I can do. thanks!

**Comment by GGross5213** [comment]
+1
I might be experiencing a similar issue. I just updated my parse-server and parse js sdk that is being hosted on Heroku, and now all my cloud code is failing. It works up until I have to query the database for something and then it throws this error 'XMLHttpRequest failed: "Unable to connect to the Parse API"'.

**Comment by GGross5213** [comment]
I think I figured something out. At the top of the main.js in cloud code, I put ```Parse.serverURL = process.env.SERVER_URL``` where SERVER_URL is the heroku url and it seems to work now.

**Comment by stevenanthonyrevo** [comment]
I had a similar issue.  

Solved it with the following code:
 
```
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || 'xxxx', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'https://xxxx.herokuapp.com' + mountPath, 
}); 
```

```
// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
```
