### ISSUE TITLE
How to get Parse Server version?

### ISSUE THREAD

**Issue by pewh** [parse-community/Parse-SDK-JS#402]
1. I'm trying to fetch Parse Server version then store the value to `_Installation` model via Cloud Code. Is there any way to do it?

2. By default, when create `_Installation` model via Parse Dashboard, it will generate some fields automatically such as `parseVersion`. Should I store Parse version manually to `parseVersion`? Or maybe Parse have some mechanism to store the value automatically? Thanks.

**Comment by rgdagir** [comment]
Use the following command to open your parse dashboard: "parse-dashboard --appId yourAppId --masterKey yourMasterKey --serverURL yourServerURL". Once it is activated, open it and check for the server version on the "homepage".
