### ISSUE TITLE
Failing to get the JS SDK from parsecdn.com

### ISSUE THREAD

**Issue by adrianchifor** [parse-community/Parse-SDK-JS#407]
I don't know if it has anything to do with the Parse shutdown but my service started failing since yesterday because it couldn't get the Parse JS SDK from parsecdn.com. Did you guys shut that down as well? Moved stuff to cdnjs.cloudflare.com for now. Do you recommend a better cdn?

**Comment by andrewimm** [comment]
Yes, ParseCDN was part of the Parse shutdown. For a while now, we've been encouraging users to switch to unpkg.com (formerly npmcdn). The npm packages are fully compatible with this service, and in my experience it's been a great host.

**Comment by andrewimm** [comment]
(Leaving open in case others have the same question.

**Comment by NatanRolnik** [comment]
In case anyone needs it. What I'm using is:

`https://unpkg.com/parse/dist/parse.min.js`
