### ISSUE TITLE
Strip out table data in Parse.Cloud.afterFind trigger

### ISSUE THREAD

**Issue by natario1** [parse-community/Parse-SDK-JS#411]
I believe that a reasonable use case for the afterFind callback is to strip out table data from the result objects. You might often have fields just used for indexing and querying, but not really needed by the client, e.g.

    text                 textArray
    "Hi, foo bar!”       [“H”, “Hi”, “F”, “Fo”, “Foo”, “b”, “ba”, “bar”]

textArray is useful for quering, but after that, these are just useless bytes sent to the client. I’d like to strip them out.

    Parse.Cloud.afterFind(‘TestTable’, (req, res) => {
        var objs = req.objects;
        _.forEach(objs, (obj) => {
            // Strip textArray
        });
        res.success(objs);
    });

I have seen `obj.set(‘textArray’, [])` around, but it does not look good, in that if later the client calls `save()` on any of these objects, the textArray field will be cleared.
I myself have tried different stuff like `delete obj[‘textArray’]` or `obj.unset(‘textArray’)` (I think it has the same issue, plus it make the dashboard hang).

Is there a way to do this? Another way would be to use `query.unselect(‘unwantedKey’)` in the `beforeFind` hook, but we only have `query.select(‘wantedKey')`.

**Comment by mrmarcsmith** [comment]
I use this function to remove unwanted keys. Simply pass the object and an array of keys you want to be removed

```
function objectWithoutTheseAttributesFromObject(array,object)
{

  var thisUserJSON = object.toJSON();

  for (var i = array.length - 1; i >= 0; i--) {
    var thisAttributeToDelete = array[i];
    delete thisUserJSON[thisAttributeToDelete];

  };
  thisUserJSON.className = object.className;
  return Parse.Object.fromJSON(thisUserJSON);

}
```

Here is an example of how to use
```
return objectWithoutTheseAttributesFromObject(["birthday","phoneNumber","otherSecretKey"],userToScrub);
```

**Comment by natario1** [comment]
@mrmarcsmith thanks! Looks nice, I hope it won’t slow things down.

How does this behave with nested objects that were `include`d in the query? Are they serialized into JSON? I mean if you query for `Post`s and include the `Author`. Will the final object have author data as well, or just a pointer?

**Comment by mrmarcsmith** [comment]
great question! Currently no.  you could create a custom function that handles that behavior with a few if statements like like the example below but unfortunately without a "beforeFetch" (+1 for that feature request!) there isn't a clean solution that works out of the box.
Here is an UNTESTED example of what you could do
 
```
function objectWithoutTheseAttributesFromObject(array,object)
{

  var thisUserJSON = object.toJSON();

  for (var i = array.length - 1; i >= 0; i--) {
    var thisAttributeToDelete = array[i];
    if(thisAttributeToDelete == "postAuthor" && object.className == "Post"){
        thisUserJSON["postAuthor"] = objectWithoutTheseAttributesFromObject(["birthday","phoneNumber","otherSecretKey"],thisUserJSON["postAuthor"])
    }else{
         delete thisUserJSON[thisAttributeToDelete];
    }
    

  };
  thisUserJSON.className = object.className;
  return Parse.Object.fromJSON(thisUserJSON);

}
```

**Comment by flovilmart** [comment]
There is a beforeFind hook that let you mutate the query, and you can apply/force selecting / rejecting fields

**Comment by natario1** [comment]
Thanks @flovilmart , but how do you do that (rejecting)?

We have `query.select()` but you can only add. Is there a private array we can remove from? Also what about queries that do not select anything (meaning return all)?

**Comment by flovilmart** [comment]
Nah, you can't at the moment, it's just passing all keys minus the ones you want to exclude. We could probably add support for that in the future. 
In the beforeFind you can apply this and it will override the client's.
