### ISSUE TITLE
How do you use master key?

### ISSUE THREAD

**Issue by dylankbuckley** [parse-community/Parse-SDK-JS#413]
I want to use my master key, however none of the documentation even mentions it. How can I use it to call .save() and over-ride permissions on an object

**Comment by andrewimm** [comment]
There's a bunch of information on the master key in the security section of the documentation: http://parseplatform.github.io/docs/js/guide/#client-vs-server

To summarize:
 - Only use it on the server; distributing the master key to your client means anyone can edit your data
 - To use it, it needs to be provided at initialization: `Parse.initialize(applicationKey, optionalJSKey, masterKey);`
 - To use it for all requests, call ` Parse.Cloud.useMasterKey()`
 - To use it for a single request, provide `useMasterKey: true` in the optional permissions object passed as the final parameter to any server call, eg: `myObject.save({}, {useMasterKey: true})`

**Comment by jaimeagudo** [comment]
⚠️  `Parse.Cloud.useMasterKey()` is deprecated @dylankbuckley

**Comment by giusecapo** [comment]
@jaimeagudo What should I use instead?

**Comment by flovilmart** [comment]
@giusecapo please see @andrewimm's response
