### ISSUE TITLE
Include doesn't work while querying

### ISSUE THREAD

**Issue by palluau** [parse-community/Parse-SDK-JS#420]
Hello i am trying to use include method for a request like this:

        var Role = Parse.Object.extend('_Role');
        var User = Parse.Object.extend('_User');
        var innerQuery = new Parse.Query(User);
        innerQuery.equalTo('objectId', user.id);
        var query = new Parse.Query(Role);
        query.matchesQuery("users", innerQuery);
        query.include("partner");
        query.find({
          success: (results) => {
            console.log(results[0].get('partner'));
          },
          error: (error) => {
            console.error(error);
          }
        });
      }

![capture d ecran 2017-04-04 a 15 44 58](https://cloud.githubusercontent.com/assets/15381928/24659682/b1621ba4-194d-11e7-9bee-41be60796595.png)
but when i receive the request i only get the relation object so i need to do a second request to fetch  partner's table. Is their a way to do only one request to fetch all my data

**Comment by henninghorn** [comment]
@palluau 

Why do you believe you haven't received the data you requested?

Look at your network tab and see the actual requests. There won't be any extra requests, because you "parent" property is populated with the related object. Just try expanding the "attributes" property seen on your screenshot.

**Comment by flovilmart** [comment]
Relations are never included from the server. You need to query those manually after receiving the object owning the relation.
