### ISSUE TITLE
Parse JS SDK and RequireJS or Webpack

### ISSUE THREAD

**Issue by camdagr8** [parse-community/Parse-SDK-JS#421]
I'm trying to include the Parse Javascript SDK (1.9.2) via npm (https://www.npmjs.com/package/parse) and I keep getting the following error in the browser:

```
Uncaught ReferenceError: require is not defined
    at Object.<anonymous> (external "events":1)
    at __webpack_require__ (bootstrap 8ca8db8…:19)
    at Object.root (EventEmitter.js:14)
    at __webpack_require__ (bootstrap 8ca8db8…:19)
    at Object.defineProperty.value (ParseLiveQuery.js:7)
    at __webpack_require__ (bootstrap 8ca8db8…:19)
    at Object.defineProperty.value (Parse.js:152)
    at __webpack_require__ (bootstrap 8ca8db8…:19)
    at Object.defineProperty.value (index.js:1)
    at __webpack_require__ (bootstrap 8ca8db8…:19)
```

## Things I've Looked at:

- I have other packages being included via require() and they are working fine. 
- I insured that the package is being installed when I run `npm install parse --save`
- If I load the SDK from CDN (https://cdnjs.cloudflare.com/ajax/libs/parse/1.9.2/parse.min.js) it works fine. 

## So..
Can someone point me in the right direction as to what could be causing this error? 

Thanks!

**Comment by camdagr8** [comment]
Is this somehow related to this: 
https://github.com/ParsePlatform/Parse-SDK-JS/issues/238

**Comment by ChrisGrant** [comment]
@camdagr8 I'm having the exact same issue. Did you manage to fix this or work around it somehow?

**Comment by camdagr8** [comment]
Sort of. I just included it the old fashioned way into my `<head>` tag

**Comment by Etto91** [comment]
same problem solved by importing the version on dist folder it's ok? 

`import Parse from '../../node_modules/parse/dist/parse.min';`

**Comment by cleever** [comment]
I use it by importing from the dist folder as well:

`import Parse from 'parse/dist/parse.js';`

**Comment by camdagr8** [comment]
@cleever your method works for me. Thanks!
