### ISSUE TITLE
Docs links are not working

### ISSUE THREAD

**Issue by amol-c** [parse-community/Parse-SDK-JS#425]
Docs link are not working below:

http://parseplatform.org/docs/js/guide

**Comment by montymxb** [comment]
@amol-c   You can still get the guides at [docs.parseplatform.org](http://docs.parseplatform.org), albeit it looks rather ugly at the moment due to some missing assets.

The source for the docs is on github [here](https://github.com/parse-community/docs). You can check those out and view them, or save them offline while things are being sorted out.

**Comment by flovilmart** [comment]
Seems that the base domain redirect that I put out is breaking the relative links. I'll workout a quick fix on the docs repo

**Comment by flovilmart** [comment]
Just finished fixing the docs.parseplatform.org, this should be good now. Thanks @montymxb !

**Comment by montymxb** [comment]
@flovilmart glad to hear it!

Do you happen to know what's going to happen with the links on just [parseplatform.org](http://parseplatform.org)? Looks like most of everything that doesn't link to github is an out of date link now. Considering that most of the sdks end up linking to this page (until they are updated) this could be a problem.

Not sure if this is something we can change though, it looks like the domain is hosted separately from the sub domain of `docs`.

**Comment by flovilmart** [comment]
so for those links, I'm opening a PR on that repo too (that is still private) and hopefully we'll get it merged soon.

Ideally, we'll reclaim parseplatform.org (a domain that I own) that is still linked in github on that private repo. We'll likely make a new home on the new organization. Things are a bit bumpy, but it isn't as bad as it could have been :)

**Comment by montymxb** [comment]
That's good to hear, once those links are updated we should be alright. Glad to know that the domain is in good hands too 👍 .

**Comment by flovilmart** [comment]
eheh, hopefully the docs.parseplatform.org's link should all work now, if you don't mind doing a quick round up, in case I forgot something

**Comment by flovilmart** [comment]
I believe we should be all good and back up, merged the new links in the parseplatform.org repo!

**Comment by montymxb** [comment]
Links look to be all good on both sites @flovilmart 👍 . If there's anything we missed someone will probably bring it up. 

The only thing I can think of is on `parseplatform.org` under `REST Api` there are two sets of guides, one for **Parse Server** and one for **Parse.com**. Looks like the **Parse.com** is a dead link now, just loops back. Not too big of a deal, and other than that everything seems to be good.

**Comment by flovilmart** [comment]
Awesome! Thanks @montymxb !
