### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by simpleshadow** [parse-community/Parse-SDK-JS#427]
Hey all! Looks like all the Parse guides were taken down? (e.g. https://parseplatform.github.io/docs/js/guide/) 🙃

For better or worse, we're still using Parse for stuff so hoping someone knows if these will be back or they are somewhere else?

**Comment by simpleshadow** [comment]
Found them... 👉  http://parseplatform.org/

**Comment by flovilmart** [comment]
I should probably let the /docs forward to docs.parseplatform.org :)

**Comment by simpleshadow** [comment]
Thanks for keeping the lights on @flovilmart! 👊💥

**Comment by flovilmart** [comment]
let me tell you something, it's shining brighter than ever!

**Comment by oallouch** [comment]
It's great. The only thing that bugs me is that it starts by saying "Goodbye and good luck!" instead of "but it's better than ever with its open source implementation and its community" :)

**Comment by flovilmart** [comment]
Yeah, I need to fix that :)
