### ISSUE TITLE
Unable to save array of pointers in cloud code

### ISSUE THREAD

**Issue by nirvana74v** [parse-community/Parse-SDK-JS#434]
`      var planobjar = [];
      for(var item of plansel) {
            var planob = {"objectId": item.planid, "__type": "Pointer", "className": "Plans"};
            var pobj = {"planid": planob, "qty": item.qty, "unit":item.unit};
            planobjar.push(planob);
      }
      var nClass = Parse.Object.extend("myClass");
      var robj = new nClass();
      robj.set ( 'planSelection', planobjar);
      robj.save({
        success: function(planres) {
            // code
        },
        error:function(error) {
            // code
        }
      });
`

If I try to save this array into an array field it doesn't save, but if it's an array without pointer it saves properly

**Comment by flovilmart** [comment]
can you provide the server logs when running with VERBOSE=1&

**Comment by nirvana74v** [comment]
verbose=1 throws huge log messages, 

`verbose: REQUEST for [POST] /parse/classes/Content: {
  "title": "Greasy Brown Goulash",
  "subheading": "This new dish is all the rage in France right now. Similar to pig slop, the gritty texture and uncommon ingredients really make your mouth cry. Pretty gross."
  "blocks": [
    {
      "title": "Cook beans and crickets",
      "block": "In a large stockpot, heat 1 cup kale until boiling and add the spice. Add ¼ lb live crickets and stir well. Cook until mushy and fully dead, about 30 minutes. Add 2 cans of pinto beans and pig’s feet. Bring to a boil.",
      "bigimage": "https://res.cloudinary.com/lettuce/image/upload/v1494627032/recipeimages/open-mind.jpg",
      "thumbimage": "https://res.cloudinary.com/lettuce/image/upload/c_thumb,h_324,w_432/v1494627032/recipeimages/open-mind.jpg",
      "at": "05:00",
      "it": "15:00"
    },
    {
      "title": "Cook beans and crickets",
      "block": "In a large stockpot, heat 1 cup kale until boiling and add the spice. Add ¼ lb live crickets and stir well. Cook until mushy and fully dead, about 30 minutes. Add 2 cans of pinto beans and pig’s feet. Bring to a boil.",
      "bigimage": "https://res.cloudinary.com/lettuce/image/upload/v1494627914/recipeimages/address.jpg",
      "thumbimage": "https://res.cloudinary.com/lettuce/image/upload/c_thumb,h_324,w_432/v1494627914/recipeimages/address.jpg",
      "at": "05:00",
      "it": "15:00"
    },
    {
      "title": "Cook beans and crickets",
      "block": "In a large stockpot, heat 1 cup kale until boiling and add the spice. Add ¼ lb live crickets and stir well. Cook until mushy and fully dead, about 30 minutes. Add 2 cans of pinto beans and pig’s feet. Bring to a boil.",
      "bigimage": "https://res.cloudinary.com/lettuce/image/upload/v1494631765/recipeimages/lavender_cake.jpg",
      "thumbimage": "https://res.cloudinary.com/lettuce/image/upload/c_thumb,h_324,w_432/v1494631765/recipeimages/lavender_cake.jpg",
      "at": "10:00",
      "it": "5:00"
    }
  ]
} method=POST, url=/parse/classes/Content, x-real-ip=173.244.48.93, x-forwarded-for=173.244.48.93, x-nginx-proxy=true, host=parseapp.myserver.com, content-length=2520, accept=*/*, x-parse-application-id=RymBj0w6s7QMgq3asP63GsGAEdOYaW31kDvguyBU, x-parse-client-version=php1.2.2, x-parse-session-token=r:1e6518cf23139185edf1fc321a0dca2d, x-parse-rest-api-key=cYhINt9A2sP1yPyg8vd441uq5MDGQNhQDToSDJoK, content-type=application/json, title=Greasy Brown Goulash, subheading=This new dish is all the rage in France right now. Similar to pig slop, the gritty texture and uncommon ingredients really make your mouth cry. Pretty gross., blocks=[title=Cook beans and crickets, block=In a large stockpot, heat 1 cup kale until boiling and add the spice. Add ¼ lb live crickets and stir well. Cook until mushy and fully dead, about 30 minutes. Add 2 cans of pinto beans and pig’s feet. Bring to a boil., bigimage=https://res.cloudinary.com/lettuce/image/upload/v1494627032/recipeimages/open-mind.jpg, thumbimage=https://res.cloudinary.com/lettuce/image/upload/c_thumb,h_324,w_432/v1494627032/recipeimages/open-mind.jpg, at=05:00, it=15:00, title=Cook beans and crickets, block=In a large stockpot, heat 1 cup kale until boiling and add the spice. Add ¼ lb live crickets and stir well. Cook until mushy and fully dead, about 30 minutes. Add 2 cans of pinto beans and pig’s feet. Bring to a boil., bigimage=https://res.cloudinary.com/lettuce/image/upload/v1494627914/recipeimages/address.jpg, thumbimage=https://res.cloudinary.com/lettuce/image/upload/c_thumb,h_324,w_432/v1494627914/recipeimages/address.jpg, at=05:00, it=15:00, title=Cook beans and crickets, block=In a large stockpot, heat 1 cup kale until boiling and add the spice. Add ¼ lb live crickets and stir well. Cook until mushy and fully dead, about 30 minutes. Add 2 cans of pinto beans and pig’s feet. Bring to a boil., bigimage=https://res.cloudinary.com/lettuce/image/upload/v1494631765/recipeimages/lavender_cake.jpg, thumbimage=https://res.cloudinary.com/lettuce/image/upload/c_thumb,h_324,w_432/v1494631765/recipeimages/lavender_cake.jpg, at=10:00, it=5:00]
verbose: RESPONSE from [POST] /parse/classes/Content: {
  "status": 201,
  "response": {
    "objectId": "bfMHBz7TUI",
    "createdAt": "2017-05-16T17:27:39.892Z"
  },
  "location": "https://parseapp.myserver.com/parse/classes/Content/bfMHBz7TUI"
} status=201, objectId=bfMHBz7TUI, createdAt=2017-05-16T17:27:39.892Z, location=https://parseapp.myserver.com/parse/classes/Content/bfMHBz7TUI
verbose: REQUEST for [POST] /parse/functions/updaterecipe: {
  "objectId": "bfMHBz7TUI",
  "plans": [
    {
      "planid": {
        "objectId": "r0PXyUh9pT",
        "__type": "Pointer",
        "className": "plans"
      },
      "qty": "2",
      "unit": "lb"
    },
    {
      "planid": {
        "objectId": "UJSMwcmiT4",
        "__type": "Pointer",
        "className": "plans"
      },
      "qty": "2",
      "unit": "lb"
    },
    {
      "planid": {
        "objectId": "xMYB6lFzCe",
        "__type": "Pointer",
        "className": "plans"
      },
      "qty": "8",
      "unit": "oz"
    },
    {
      "planid": {
        "objectId": "aFiBsSxf3F",
        "__type": "Pointer",
        "className": "plans"
      },
      "qty": "8",
      "unit": "oz"
    },
    {
      "planid": {
        "objectId": "MpSVZbNAQ6",
        "__type": "Pointer",
        "className": "plans"
      },
      "qty": "8",
      "unit": "oz"
    }
  ]
} method=POST, url=/parse/functions/updaterecipe, x-real-ip=173.244.48.93, x-forwarded-for=173.244.48.93, x-nginx-proxy=true, host=parseapp.myserver.com, content-length=536, accept=*/*, x-parse-application-id=RymBj0w6s7QMgq3asP63GsGAEdOYaW31kDvguyBU, x-parse-client-version=php1.2.2, x-parse-session-token=r:1e6518cf23139185edf1fc321a0dca2d, x-parse-rest-api-key=cYhINt9A2sP1yPyg8vd441uq5MDGQNhQDToSDJoK, content-type=application/json, objectId=bfMHBz7TUI, plans=[objectId=r0PXyUh9pT, __type=Pointer, className=plans, qty=2, unit=lb, objectId=UJSMwcmiT4, __type=Pointer, className=plans, qty=2, unit=lb, objectId=xMYB6lFzCe, __type=Pointer, className=plans, qty=8, unit=oz, objectId=aFiBsSxf3F, __type=Pointer, className=plans, qty=8, unit=oz, objectId=MpSVZbNAQ6, __type=Pointer, className=plans, qty=8, unit=oz]
verbose: REQUEST for [GET] /parse/classes/Content: {
  "where": {
    "objectId": "bfMHBz7TUI"
  },
  "limit": 1
} method=GET, url=/parse/classes/Content, user-agent=node-XMLHttpRequest, Parse/js1.9.2 (NodeJS 7.6.0), accept=*/*, content-type=text/plain, host=localhost:1337, content-length=231, connection=close, objectId=bfMHBz7TUI, limit=1
verbose: RESPONSE from [GET] /parse/classes/Content: {
  "response": {
    "results": [
      {
        "objectId": "bfMHBz7TUI",
        "title": "Greasy Brown Goulash",
        "subheading": "This new dish is all the rage in France right now. Similar to pig slop, the gritty texture and uncommon ingredients really make your mouth cry. Pretty gross."
        "blocks": [
          {
            "title": "Cook beans and crickets",
            "block": "In a large stockpot, heat 1 cup kale until boiling and add the spice. Add ¼ lb live crickets and stir well. Cook until mushy and fully dead, about 30 minutes. Add 2 cans of pinto beans and pig’s feet. Bring to a boil.",
            "bigimage": "https://res.cloudinary.com/lettuce/image/upload/v1494627032/recipeimages/open-mind.jpg",
            "thumbimage": "https://res.cloudinary.com/lettuce/image/upload/c_thumb,h_324,w_432/v1494627032/recipeimages/open-mind.jpg",
            "at": "05:00",
            "it": "15:00"
          },
          {
            "title": "Cook beans and crickets",
            "block": "In a large stockpot, heat 1 cup kale until boiling and add the spice. Add ¼ lb live crickets and stir well. Cook until mushy and fully dead, about 30 minutes. Add 2 cans of pinto beans and pig’s feet. Bring to a boil.",
            "bigimage": "https://res.cloudinary.com/lettuce/image/upload/v1494627914/recipeimages/address.jpg",
            "thumbimage": "https://res.cloudinary.com/lettuce/image/upload/c_thumb,h_324,w_432/v1494627914/recipeimages/address.jpg",
            "at": "05:00",
            "it": "15:00"
          },
          {
            "title": "Cook beans and crickets",
            "block": "In a large stockpot, heat 1 cup kale until boiling and add the spice. Add ¼ lb live crickets and stir well. Cook until mushy and fully dead, about 30 minutes. Add 2 cans of pinto beans and pig’s feet. Bring to a boil.",
            "bigimage": "https://res.cloudinary.com/lettuce/image/upload/v1494631765/recipeimages/lavender_cake.jpg",
            "thumbimage": "https://res.cloudinary.com/lettuce/image/upload/c_thumb,h_324,w_432/v1494631765/recipeimages/lavender_cake.jpg",
            "at": "10:00",
            "it": "5:00"
          }
        ],
        "createdAt": "2017-05-16T17:27:39.892Z",
        "updatedAt": "2017-05-16T17:27:39.892Z"
      }
    ]
  }
} results=[objectId=bfMHBz7TUI, title=Greasy Brown Goulash, subheading=This new dish is all the rage in France right now. Similar to pig slop, the gritty texture and uncommon ingredients really make your mouth cry. Pretty gross., blocks=[title=Cook beans and crickets, block=In a large stockpot, heat 1 cup kale until boiling and add the spice. Add ¼ lb live crickets and stir well. Cook until mushy and fully dead, about 30 minutes. Add 2 cans of pinto beans and pig’s feet. Bring to a boil., bigimage=https://res.cloudinary.com/lettuce/image/upload/v1494627032/recipeimages/open-mind.jpg, thumbimage=https://res.cloudinary.com/lettuce/image/upload/c_thumb,h_324,w_432/v1494627032/recipeimages/open-mind.jpg, at=05:00, it=15:00, title=Cook beans and crickets, block=In a large stockpot, heat 1 cup kale until boiling and add the spice. Add ¼ lb live crickets and stir well. Cook until mushy and fully dead, about 30 minutes. Add 2 cans of pinto beans and pig’s feet. Bring to a boil., bigimage=https://res.cloudinary.com/lettuce/image/upload/v1494627914/recipeimages/address.jpg, thumbimage=https://res.cloudinary.com/lettuce/image/upload/c_thumb,h_324,w_432/v1494627914/recipeimages/address.jpg, at=05:00, it=15:00, title=Cook beans and crickets, block=In a large stockpot, heat 1 cup kale until boiling and add the spice. Add ¼ lb live crickets and stir well. Cook until mushy and fully dead, about 30 minutes. Add 2 cans of pinto beans and pig’s feet. Bring to a boil., bigimage=https://res.cloudinary.com/lettuce/image/upload/v1494631765/recipeimages/lavender_cake.jpg, thumbimage=https://res.cloudinary.com/lettuce/image/upload/c_thumb,h_324,w_432/v1494631765/recipeimages/lavender_cake.jpg, at=10:00, it=5:00], createdAt=2017-05-16T17:27:39.892Z, updatedAt=2017-05-16T17:27:39.892Z]`

**Comment by flovilmart** [comment]
and what object is supposedly saves as a pointers array? I don't see any pointer arrays, but plain old objects.

**Comment by nirvana74v** [comment]
Sorry for the wrong log, I've updated the previous log

**Comment by flovilmart** [comment]
This is not an array of pointers, if I loot at a single element:

```
{ "planid": { "objectId": "r0PXyUh9pT", "__type": "Pointer", "className": "Plans" }, "qty": "2", "unit": "lb" }
```

Also, it saves just fine.

**Comment by nirvana74v** [comment]
any extra information along with pointer like the one posted above makes it save as 
[{"planid":{"objectId":"r0PXyUh9pT"},"qty":"2","unit":"lb"}]
you can check it,

Create an array field
create a pointer object for class
add that as JSON object noted above and save
`, "__type": "Pointer", "className": "Plans" `
will get removed

**Comment by flovilmart** [comment]
is it an issue with the JS SDK or parse-server? AFAICT this seems to be on parse-server. 

Can you provide the verbose log for a fetch of that object?

**Comment by nirvana74v** [comment]
I think the issue seem to be with parse server, as I am not able to save the pointer details along with any other meta information even while saving from PHP. Should I post this issue under parse-server?

**Comment by flovilmart** [comment]
Yes that would be better, please also fill completely the issue template from the parse-server issue report.

**Comment by nirvana74v** [comment]
Sure will do .. thanks
