### ISSUE TITLE
Array of Pointers return full parse objects by default (without using include)

### ISSUE THREAD

**Issue by coryshaw** [parse-community/Parse-SDK-JS#439]
I have a column on the User table that is an Array. To that Array I've added some pointer objects. When I query the user table, the data that comes back from the Array of pointers is the full parse objects, not the pointers.

As I understand it, this should only happen if i use `include` as part of the query, which I am not.

I can see that the ajax request from parse server correctly returns the pointer objects, which is why I think this is a bug with the SDK.

**Steps to reproduce**

Create a column of type Array called PointerTest
Add some pointers to PointerTest
Query the class with PointerTest

``` javascript
const UserTable = Parse.Object.extend('User');
const usersQuery = new Parse.Query(UserTable);
usersQuery.find().then(function (users) {
  // users results Array of Pointers include full parse objects here
});
```

**Expected Results**

The results of the PointerTest column should be pointers

**Actual Outcome**

The results the PointerTest column are full parse objects (not pointers)

**Environment Setup**

parse-server version: 2.3.3
parse js sdk version: 1.9.2
MongoDB version: 3.2.12

**Comment by jcguarinpenaranda** [comment]
I gues you should do 

```js
// first allow custom user class
Parse.User.allowCustomUserClass(true)

// extend Parse.User
const UserTable = Parse.Object.extend(Parse.User);
const usersQuery = new Parse.Query(UserTable);
usersQuery.find().then(function (users) {
  // users results Array of Pointers include full parse objects here
});
```

**Comment by Dygerati** [comment]
@coryshaw Are you using the react-native version of the SDK by chance? I've encountered the same issue while using it in a React Native environment. If I run the exact same query using the *node* version I have no issue. I actually had an issue open on Parse Server before I narrowed it down to the SDK: 
https://github.com/parse-community/parse-server/issues/4214

This is pretty clearly incorrect behavior.

**Comment by cinder92** [comment]
try
```
const usersQuery = new Parse.Query("_User");
usersQuery.find().then(function (users) {
  // users results Array of Pointers include full parse objects here
});
```

**Comment by flovilmart** [comment]
@coryshaw A pointer is a ParseObject. There is no such thing as a Pointer object. When you run your query, all the objects are transformed into unfetched Parse Objects. You can then fetch the full objects with `.fetch()` or leave it as is. Those objects don't have any property from the server.

**Comment by ArkeshGKalathiya** [comment]
> @coryshaw A pointer is a ParseObject. There is no such thing as a Pointer object. When you run your query, all the objects are transformed into unfetched Parse Objects. You can then fetch the full objects with `.fetch()` or leave it as is. Those objects don't have any property from the server.

Issue is valid, I have seen this in back4app, when I save array of pointers it saves correctly in database ( confirmed via directly connecting to mongodb ), but when viewing in dashboard it shows already fetched objects and api also returns whole fetched objects instead of just pointers.

**Comment by ArkeshGKalathiya** [comment]
> > @coryshaw A pointer is a ParseObject. There is no such thing as a Pointer object. When you run your query, all the objects are transformed into unfetched Parse Objects. You can then fetch the full objects with `.fetch()` or leave it as is. Those objects don't have any property from the server.
> 
> Issue is valid, I have seen this in back4app, when I save array of pointers it saves correctly in database ( confirmed via directly connecting to mongodb ), but when viewing in dashboard it shows already fetched objects and api also returns whole fetched objects instead of just pointers.

This is security bug too, because we don't want to send full user detail or any other field of pointers every time.
