### ISSUE TITLE
Works with React.js ? 

### ISSUE THREAD

**Issue by ghost** [parse-community/Parse-SDK-JS#441]
I can use it with React.js, I have see with React Native but not with react.js, 

I can use it for a react.js project ?

**Comment by jcguarinpenaranda** [comment]
To work with react.js you should use the normal parse library as it is plain javascript

If you are using a module bundler:
```js
let Parse = require('parse');
```

On ES6:
```js
import Parse from 'parse';
```

on Typescript:
```ts
import * as Parse from 'parse';
```
