### ISSUE TITLE
Is this alive?

### ISSUE THREAD

**Issue by jcguarinpenaranda** [parse-community/Parse-SDK-JS#442]
Hello,

I see there are several PRs pending, and I also see the last release was on 2016. I wonder if this project is still alive?

**Comment by montymxb** [comment]
Very much so. Besides the releases a PR was merged just [2 days ago](https://github.com/parse-community/Parse-SDK-JS/pull/440). I would suspect a new release to be coming out at some point in the near future to address this. 

@flovilmart might know about a new release rolling out for this sdk.

**Comment by jcguarinpenaranda** [comment]
Thank you so much, I am very excited wih Parse and I thank you for mantaining this excelent sdk

**Comment by montymxb** [comment]
Do you still need this open?

**Comment by jcguarinpenaranda** [comment]
No
