### ISSUE TITLE
Upgrading from 1.4.2 to 1.9.2

### ISSUE THREAD

**Issue by athahersirnaik** [parse-community/Parse-SDK-JS#447]
I didn't find any upgrade guide for updating my parse js sdk. We are using 1.4.2. We had moved from hosted parse.com to our own AWS server.

Is there any breaking change?

**Comment by flovilmart** [comment]
There should not be for client side code, did you encounter any issue?

**Comment by athahersirnaik** [comment]
Uncaught TypeError: Cannot read property 'extend' of undefined

`Parse.View.extend`

**Comment by flovilmart** [comment]
I believe hij’re Still using the backbone APi’s that were deprecated a while ago

**Comment by flovilmart** [comment]
Also, the first open source version is 1.6.3, https://github.com/parse-community/Parse-SDK-JS/commit/a6cf75646321e0789b9b087a6f58f06d1cd379be#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R3

**Comment by athahersirnaik** [comment]
Thanks
