### ISSUE TITLE
What to use _linkWith vs FacebookUtils.logIn ?

### ISSUE THREAD

**Issue by ahetawal-p** [parse-community/Parse-SDK-JS#453]
Hello,
I am trying to integrate `Facebook login with Parse` on a `react-native app`.
And I am able to successfully receive the `authData` from a Facebook  new user login.
Now I am trying to link this user with a Parse user. 

And reading the docs and other threads I see two ways of this linking of Facebook user to parse user to work. 

1. Using `FacebookUtils.logIn` which looks something like this : 
```
var authData = {
      id: token.userID,
      access_token: token.tokenString,
      expiration_date: token.expirationDate()
    };
    Parse.FacebookUtils.logIn(authData, {
      success: (user) => {
        if (user.existed()) {
          // login: nothing to do
          this.setState({isLoadingCurrentUser: false});
        } else {
          // signup: update user data, e.g. email
          var data = user.get('authData').facebook;
          console.log("[data]: ", data);
        }

```

2. Using `_linkWith` method : 
```
let myAuthData = {
  id: "123456789",
  "access_token": "SaMpLeAAibS7Q55FSzcERWIEmzn6rosftAr7pmDME10008bWgyZAmv7mziwfacNOhWkgxDaBf8a2a2FCc9Hbk9wAsqLYZBLR995wxBvSGNoTrEaL",
  "expiration_date": "2012-02-28T23:49:36.353Z"
}
let user = new Parse.User();
user._linkWith("facebook", myAuthData).then(function(user){
  // user is linked now
});
```

Could someone please tell me which way should I be using for such kind of integration. And if there are any pitfalls which I should be aware of using vs the other.

Thank you,

**Comment by flovilmart** [comment]
Login should create a new user while linkWith should let the authenticated user save the Facebook login information for later logout/ login. In your case, because you don’t have a user, you should use the login method

**Comment by ahetawal-p** [comment]
Thanks @flovilmart. According to the '_linkWith' docs and my above code snippet. I can still create a new user when it doesn't exists and then use it to link to FB data. Am I missing something here ?

**Comment by flovilmart** [comment]
If it works, you should go for it!
