### ISSUE TITLE
Parse Object set 'id' issue.

### ISSUE THREAD

**Issue by zeerorg** [parse-community/Parse-SDK-JS#454]
my parse database has an 'id' column which I can set from android sdk perfectly but javascript doesn't allow that. My id field is number type by the way. I tracked the issue here
https://github.com/parse-community/Parse-SDK-JS/blob/30cc5fc8090c3bda38441382847cd3a3d2b48b39/src/ParseObject.js#L648

**Comment by flovilmart** [comment]
You should probably not use the if/objectId column in either js or android as the object id’s are managed for you.
