### ISSUE TITLE
Parse.FacebookUtils.login strips options, does not allow for masterkey, etc.2

### ISSUE THREAD

**Issue by jjdp** [parse-community/Parse-SDK-JS#478]
We can't use `Parse.FacebookUtils.login` on cloud code if I want to disable the create ACL on User Class.
see [#4103](https://github.com/parse-community/parse-server/issues/4103).

It is stripped as @flovilmart said https://github.com/parse-community/Parse-SDK-JS/blob/293e2e13fa8eb1c62786fecf6aa6cd4458670b7f/src/ParseUser.js#L79

What If I want to handle signup and login on the cloud code for security reasons?

**Comment by flovilmart** [comment]
also take into consideration that sessionTokens are bound by installationId, so you'd need to be also required to pass the installationId on which you want the session to be created.

**Comment by sunshineo** [comment]
Is the problem actually from this line not using 'useMasterKey'? https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseUser.js#L1022

**Comment by flovilmart** [comment]
You can always use the save method setting the authData on the user. 
You can also open a PR With the fix and appropriate tests.

**Comment by sunshineo** [comment]
Note: when using save method on authData using 'useMasterKey', it automatically handles multiple 3rd parties. It will add to the list if it is a new one and it will replace if an old one already exists.
