### ISSUE TITLE
Remove Query Limit Completely

### ISSUE THREAD

**Issue by calhouncole** [parse-community/Parse-SDK-JS#479]
It appears that the default query limit is set to 100 objects. I can change that limit to anything I'd like via `query.limit(config.QUERY_LIMIT);` 

Is there any way to remove the limit completely?

**Comment by TimNZ** [comment]
Setting to 0 == no limit.

Parse Server code
```
      if (body.limit || body.limit === 0) {
        options.limit = Number(body.limit);
      } else {
        options.limit = Number(100);
      }
```

**Comment by TimNZ** [comment]
There's also a parse server option 'maxLimit' which overrides the query limit if query limit > maxLimit.

This seems like a reasonable safe guard from a malicious person do a request against a table with 00000000s of records.

**Comment by flovilmart** [comment]
Setting 0 always returns an empty array, it’s useful when running counts.

In the JS SDK, there is no way to set the default limit for all queries, if it’s a feature you’d like, please open an issue on the JS SDK.
