### ISSUE TITLE
RFE: Parse.Cloud.runJob

### ISSUE THREAD

**Issue by oallouch** [parse-community/Parse-SDK-JS#486]
Hi,
It would be great to be able to call a Job using the js sdk (using the masterkey, so from a Cloud hook or Function). It would remove the need to use a lib like 'request-promise' and simplify the way we send params.

Thx,
Olivier

**Comment by oallouch** [comment]
If anyone needs a Node.js example, here is my (modest) REST code:

`const rp = require('request-promise');

async function runJob(jobName, params) {
	const options = {
		url: Parse.serverURL + '/jobs/' + jobName,
		headers: {
			'X-Parse-Application-Id': Parse.applicationId,
			'X-Parse-Master-Key': Parse.masterKey
		}
	};
	if (params) {
		options.json = params;
	}
	return rp.post(options);
}`

**Comment by dplewis** [comment]
@flovilmart Where is Parse.Cloud.job defined in the JS SDK? I can do a PR for this.

**Comment by flovilmart** [comment]
The job is not defined in the JS SDK, but by the server. If you plan to expose it, please make it only available for node and only with master Key

**Comment by dplewis** [comment]
That won't be needed thanks.
