### ISSUE TITLE
Parse.User.logOut() does not clean currentUser in LocalStorage

### ISSUE THREAD

**Issue by leftluoyi** [parse-community/Parse-SDK-JS#493]
I am using Parse javascript sdk. I can signup and login successfully. However, when logout using the following code 
```
const logoutHandler = ({ key }) => {
    if(key == "logout") {
      Parse.User.logOut().then(() => {
          var currentUser = Parse.User.current();
          console.log(currentUser)
          window.location = "/"
          }
        )
      });
    }
  }
```
According to the documentation [here](http://docs.parseplatform.org/js/guide/#users), after the user successfully logout, the `Parse.User.current()` should be `null`. However, it shows that `currentUser` is not `null`. I checked the LocalStorage, `Parse/test/currentUser` and `Parse/test/installationId` are still there. And according to the code of Parse-SDK-JS, when user logout, the `currentUser` is not set to be `null`.

**Comment by elvis7449** [comment]
Same problem. I've tried wid different releases. Still did not succeed. The session class gets crowded since the user logout did not destroy the session. Any idea?

**Comment by ma0ho** [comment]
Confirmed!
