### ISSUE TITLE
Promise is never resolved in case of server-side error when invoking Parse.Object.saveAll

### ISSUE THREAD

**Issue by nrchandan** [parse-community/Parse-SDK-JS#494]
We have a node process that works on multiple batches of Parse objects. Each batch is saved through Parse.Object.saveAll. However, as soon as a batch errors out, the node process stops immediately and none of the subsequent batches get processed. We found that an error handling component was missing. 

Raising a PR shortly. It adds just two lines of code.

**Comment by toddheslin** [comment]
@nrchandan did you open a pull request for this? I'm facing the same issue

**Comment by alexander-alzate** [comment]
Why don't you just throw an exception if there is not an error handler like [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) does?

**Comment by nrchandan** [comment]
@toddheslin I'm sorry but I have moved between projects and am no longer using this library. If the workaround suggested by @alexander-alzate works for you, would you recommend closing this issue?
