### ISSUE TITLE
Subclassing parse object

### ISSUE THREAD

**Issue by BenBenz** [parse-community/Parse-SDK-JS#498]
Hello,

I've try to make a subclass of Parse.Object for a custom class, but for iOS and Android in the documentation they tell how to create a subclass, but nothing in javascript, it is possible to do that in Javascript ES6 ?

**Comment by flovilmart** [comment]
See http://docs.parseplatform.org/js/guide/#objects

**Comment by BenBenz** [comment]
Thank you, sorry to have asking that

**Comment by flovilmart** [comment]
No problem, we’re here to help!

**Comment by yingmu52** [comment]
@flovilmart 

I am trying to use a custom class in `Parse.Query`, but it doesn't seem to work for me, not sure what that is happening. 

```
class Merchant extends Parse.Object {
	constructor() {
		super('Merchant');
	}
	hello() {
		console.log(`wtf it works!!! ${this.id}`);
	}
}
Parse.Object.registerSubclass('Merchant', Merchant);

async function fetch(): Promise<Merchant[]> {
	try {
		const merchants = await new Parse.Query(Merchant)
			.limit(10)
			.find({ useMasterKey: true });
		return merchants;
	} catch (error) {
		console.error(error);
		return [];
	}
}

fetch().then(merchants => {
	for (const m of merchants) {
		m.hello();
	}
});
```

I am getting this error 
```
TypeError: Class constructor ParseObject cannot be invoked without 'new'
```

**Comment by yingmu52** [comment]
I also tried this way with no luck 
```
	const merchants = await new Parse.Query<Merchant>('Merchant')
			.limit(10)
			.find({ useMasterKey: true });
```

**Comment by flovilmart** [comment]
This is an issue that’s been resolved for over a year, so unlikely that you are affected. Please open a new issue with all relevant informations. Also, check the docs.
