### ISSUE TITLE
ParseObject.clone() not copying object id

### ISSUE THREAD

**Issue by jaeggerr** [parse-community/Parse-SDK-JS#501]
I am not sure if this is a bug or the expected behaviour, but I think that the clone method of ParseObjet should return an identical object and thus copy the object id.
http://parseplatform.org/Parse-SDK-JS/api/classes/Parse.Object.html#methods_clone
Other attributes seem to be correctly copied but the object id is missing.

```js
async function testClone () {
  let myObject = new MyObject()
  myObject = await myObject.save()
  console.log(myObject.id)  // Returns an id
  myObject = myObject.clone()
  console.log(myObject.id)  // id is now undefined
}
```

I am using Parse 1.10.1 with Postgres.

**Comment by natanrolnik** [comment]
I believe this is the intended behavior: `Creates a new model with identical attributes to this one.`
Imagine you want to save a **new** object with the same attributes as `myObject`, but you might change one or other attribute before saving it.

**Comment by natanrolnik** [comment]
Yes, this is correct. Check here:

https://github.com/parse-community/Parse-SDK-JS/blob/293e2e13fa8eb1c62786fecf6aa6cd4458670b7f/src/__tests__/ParseObject-test.js#L2069

The object id is expected to be `null` by design.

**Comment by jaeggerr** [comment]
The documentation could be a bit more clear about it.
Is there a specific git to update it?

**Comment by natanrolnik** [comment]
This is a good question, I'm not sure - I believe the docs are generated from inline comments.
@flovilmart can you help here?

**Comment by flovilmart** [comment]
All documentation is inline, you can provide a Pr for it. I need to investigate the documentation génération on the gh-pages branch or docs folder
