### ISSUE TITLE
Uncaught (in promise) Error: Tried to encode an unsaved file.

### ISSUE THREAD

**Issue by Rera01** [parse-community/Parse-SDK-JS#505]
I'm getting this error in db class where the "unsaved" file is and in the app when I try to query all the objects in the class.

The problem occurred after putting a .save inside of a foreach. I was trying to use a multi upload input to upload many images at the same time into, turning them into parse.files and then taking the _name and _url given to the file to save it into an array in the database instead. Now I can't even see the rest of the objects in the class unless i filter them.

how can i finish saving (if possible) or just delete or revert that unsaved object?

**Comment by ephrimlawrence** [comment]
I know this is late but I encountered this recently and this is how is solved it.

Copy MongoDB URL (the Database URL) used in the Parse Server code, open it in any database client.

Go to the table/collection which represents the Parse Server class and find the column to which the files are being saved.
In my case, the File object was being saved like below (only 2 documents had this issue): 

```json
{
   "code": 209,
    "error": "Invalid session token",
    "__type": "File"
}
```

I simply set the column to null and saved the changes.

**Comment by mtrezza** [comment]
@ephrimlawrence I can't read from your comment whether you are describing a Parse Server / JS SDK issue, or whether this was an issue with your custom code. If it was a Parse related issue, could you please open a new issue and provide more details so we can look into this?
