### ISSUE TITLE
Remove dangling pointers

### ISSUE THREAD

**Issue by shkesar** [parse-community/Parse-SDK-JS#507]
I've tried various ways to delete all dangling pointers in array of pointers.
I have a database of 12k objects each having an "equipments" column which contains a pointers to an equipment. I want to remove all pointers which don't exist. But it hasn't worked out.

I'm using this to find out all such pointers. But it gives no result but I can check in the database that there are some dangling pointers.

var addressQ = (new Parse.Query("AddressInfo"))
        .equalTo("company", company)
        // .include('equipments')
        .exists('equipments')
        .notEqualTo('equipments', [])
        .equalTo("isBillingAddress", false)
        .limit(limit)
        .skip(skip)

    var promises = [];

    addressQ.find(function (addresses) {
        _.each(addresses, function (address) {
            var equipments = address.get('equipments');
            //equipments[0].get('serviceAddress');
            if (equipments.length > 0) {
                var newEquipments = [];
                // console.log(JSON.stringify(equipments, null, 2));
                _.each(equipments, function (equipment) {
                    var q = new Parse.Query(Equipment);
                    promises.push(q.get(equipment.id, {
                        success: function (equipment) {
                            console.log(equipment.id);
                        },
                        error: function () {
                            console.log(equipment.id);
                        }
                    }));
                });
                // address.set('equipments', newEquipments);
                // promises.push(address.save());
            } else {
                console.log("Not Here")
                // address.unset('equipments');
                // address.save();
            }
        });

        return Parse.Promise.when(promises);
    }).then(function (a) {
        console.log(a.length);
        console.log("Completed running");
    });

**Comment by montymxb** [comment]
@shkesar I would recommend you use relations instead of managing this by yourself. Although you _can_ do it this way, issues like you're having here are taken care of when you use relations. Additionally you may want to save all your objects at once using Parse.Object.saveAll.
