### ISSUE TITLE
Improve release package

### ISSUE THREAD

**Issue by neophob** [parse-community/Parse-SDK-JS#509]
I checked what exactly is downloaded from the parse sdk:

```
dist:
-rw-r--r-- 1 root root 460269 Oct 21 17:00 parse.js
-rw-r--r-- 1 root root 168782 Oct 21 17:00 parse.min.js

lib:
drwxr-xr-x 2 root root 4096 Nov 19 19:47 browser
drwxr-xr-x 2 root root 4096 Nov 19 19:47 node
drwxr-xr-x 2 root root 4096 Nov 19 19:48 react-native
```

some questions:
- whats the difference between dist and lib? is the dist only a concatenated version of the node version?
- why we don't include only the .min.js file?

**Comment by neophob** [comment]
I checked again how the npm pack looks like:

```
drwxr-xr-x   2 root root 4096 May 23 12:06 dist
-rw-r--r--   1 root root   52 Mar  6 18:14 index.js
drwxr-xr-x   5 root root 4096 May 23 12:07 lib
-rw-r--r--   1 root root   49 Mar  6 18:14 node.js
-rw-r--r--   1 root root 2780 May 23 12:08 package.json
-rw-r--r--   1 root root   57 Mar  6 18:14 react-native.js

# cat index.js
module.exports = require('./lib/browser/Parse.js');
```

This means:
- the dist folder contains `parse.js` and `parse.min.js`
- `lib` contains the unminimized source
- so the npm package contains the whole parse api 3 times

Proposal:
- include only the `dist/parse.min.js` in the published npm release
- use `package.json` `main` entry to define exposed lib

if someone agrees i'll do a PR, @flovilmart maybe?

**Comment by flovilmart** [comment]
I believe the 3 builds serve different purposes, for node, react and pure JS. I’m not sure i’s change that now if the main concern is the size of the downloaded Data.

**Comment by neophob** [comment]
That I understand, question is does it make sense to include `parse.js` and `parse.min.js` in the distribution package?

About the 3 different purposes/use cases:

**1. NodeJS**
For a node app I include the parse SDK like this: `const Parse = require('parse/node');` - this file references the files in `parse/lib/node/`(non-concatenated and unminimised)

`module.exports = require('./lib/node/Parse.js');`

**2. React**
uses `react-native.js` that references `module.exports = require('./lib/react-native/Parse.js');` (non-concatenated and unminimised)

**3. VanillaJS/Browser**
uses `index.js` that references `./lib/browser/Parse.js`

Unclear:
- the `dist` directory is not referenced in those 3 use cases, plus it contains a unminimised and a minimised version of the library. -> can we remove this directory?
- none of the 3 use cases provides a minimised / concatenated versions. does it make sense to use webpack to build a single, minimised and concatenated package?

**Comment by flovilmart** [comment]
I would warrant that if anyone references those, any change in the build system would break. I am not in favour of changing the build system unless if fixes a serious issue. 

I don't believe that having multiple occurences of the source code in the npm package, is an issue, as you mention webpack and other tools that are way more massive than a duplicated dist folder.

The dist folder contains the script to be used in plain JS, minmized for production or not for debug. so no I'd rather not remove it.

The lib folder, contains the build results of the sources, which is a 1..1 mapping of the source files BUT with compilation flags and environment flags properly processed.

> none of the 3 use cases provides a minimised / concatenated versions. does it make sense to use webpack to build a single, minimised and concatenated package?

Nope it doesn't minmization / obfuscation should happen at the last step, and is highly dependant on your build system in your final project. I don't see any benefit of publishing minimized packages for react / node / bower, besides not helping the users by obfuscating code early.
