### ISSUE TITLE
LiveQuery lost connection in node, not reconnecting, no close event

### ISSUE THREAD

**Issue by TimNZ** [parse-community/Parse-SDK-JS#514]
Parse Server: 2.7.0
Parse: 1.10.2

I'm testing live query and regularly find that my node sample app loses connection and it is not restored.    It is likely to be happening after some idle period, I've not instrumented it yet to monitor for a pattern.

No subscription.on('error') is emitted, nor a Parse.LiveQuery.on('close')

Restarting the node client app results in LQ events.
The LiveQuery subscription in a Chrome extension is rock solid.
So thinking the server must be ok.

Anyone else have a reliability issue, and suggestions for debugging this?  
If I don't get the events, and underlying websocket is not exposed, I can't do much without hacking code

**Comment by flovilmart** [comment]
The JS SDK should always reconnect automatically after a connection loss, unless specifically closed (as the swift SDK does)

**Comment by TimNZ** [comment]
That's how I read the guide, but it's not doing so reliably, in Node at least.

Not urgent, I'll dig into it next week.
