### ISSUE TITLE
Cloud Code - Include doesn't work on every object (Parse Server 2.6.3)

### ISSUE THREAD

**Issue by Samigos** [parse-community/Parse-SDK-JS#520]
There's an issue I came up with recently in my cloud functions, where I use the nested include method - `query.include(["user.profilePhoto"])` - and for an unexpected reason, some `profilePhoto`s are not fetched and others are!

Does anyone know why that happens? Keep in mind that all `profilePhoto`s exist!

PS: I've also used separated includes:

```
query.include("user");
query.include("user.profilePhoto");
```

**Comment by Samigos** [comment]
Today it happened to an object brought by a `find` call... (no `include` needed)
It seems to be a general SDK bug! Any fix out there?

**Comment by flovilmart** [comment]
Can you provide the server logs when running with VERBOSE=1?

**Comment by Samigos** [comment]
Not sure how to use/enable VERBOSE... I guess I have to put it on `index.js` but I don't know what or how... Can you help me out?

**Comment by flovilmart** [comment]
When you configure your server with the appId/masterKey, you can additionally pass an option verbose: true. If you’re using environment variables, you can pass set VERBOSE=1

**Comment by Samigos** [comment]
I tried finding what's wrong from the logs, with verbose, but it's a ton of logs to find something off!
Has anyone reported something similar? Could it actually be an SDK bug?

**Comment by dplewis** [comment]
@flovilmart I ran into this issue. It occurred when I used promises instead of callbacks.

This Fails, It actually returns both child and parent even though I query for `Container`
```
  it("include relation", function(done) {
    const child = new TestObject();
    const parent = new Container();
    child.set("foo", "bar");
    parent.set("child", child);
    Parse.Object.saveAll([child, parent], function() {
      const query = new Parse.Query(Container);
      query.include("child");
      return query.find();
    }).then((results) => {
        equal(results.length, 1);
        done();
    });
  });
```
This Passes
```
  it("include relation", function(done) {
    const child = new TestObject();
    const child2 = new TestObject();
    const parent = new Container();
    child.set("foo", "bar");
    parent.set("child", child);
    Parse.Object.saveAll([child, parent], function() {
      const query = new Parse.Query(Container);
      query.include("child");
      query.find({
        success: function(results) {
          equal(results.length, 1);
          done();
        }
      });
    });
  });
```
Maybe I'm missing something?

**Comment by flovilmart** [comment]
This is a misusage of the saveAll function. 

In the first case, you’re returning a promise inside a callback, which won’t be waited upon, the continuation is ran with the saveAll results. Not with the promise returned inside the function passed as a second argument. Also this form is undocumented : http://parseplatform.org/Parse-SDK-JS/api/v1.11.1/Parse.Object.html#.saveAll

**Comment by dplewis** [comment]
@flovilmart Thanks, I got it
