### ISSUE TITLE
Support DevDocs for documentation

### ISSUE THREAD

**Issue by TimNZ** [parse-community/Parse-SDK-JS#526]
I find the API documentation slow to navigate - navigating and locating things and getting to them quickly.

Getting into DevDocs would be awesome, and seems reasonably straight forward, especially since already using JSDocs tooling.

https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs

A task to add to the todo list?

Applies to other APIs as well.

**Comment by flovilmart** [comment]
Feel free to add them here if it's possible for you :)

**Comment by TimNZ** [comment]
Ok, on my todo list.

**Comment by flovilmart** [comment]
Thanks! Real appreciated!

**Comment by TimNZ** [comment]
I know a negative amount of Ruby, that's how much I know.
There's the start of implementing the Parse JS SDK in branch 'parse' that I'd like an opinionated hand with if you have any Ruby experience.

https://github.com/TimNZ/devdocs

https://github.com/Thibaut/devdocs/wiki/Adding-documentations-to-DevDocs

Running 'thor docs:generate parse_js_sdk' gets the index and then it fails.

**Comment by montymxb** [comment]
@TimNZ I'm not too sure if we have any devs familiar with ruby on the team atm. Personally I'm in the same boat as you regarding ruby.

**Comment by flovilmart** [comment]
I have enough ruby under my belt to write basic scripts, nothing too crazy. What I lack is time :)

**Comment by TimNZ** [comment]
Me too, but I'm a glutton for punishment.

Will park for now as I scanned a bunch of DevDoc doc rules trying to find one with a similar structure to quickly copy, couldn't, so I would have to dig deeper and learn DevDoc system and some ruby.

But if you review the doc system again, liking Vue - the search is great.
https://vuejs.org/v2/api/
Also, Lodash:
https://lodash.com/docs/4.17.4

My preference is for all doc on the same page instead of spread across different pages.
Faster navigation for one.
Load time is not a factor, I'm not going to open and close the page each time once I'm in there.

Should we keep this issue open as a todo or close?

**Comment by flovilmart** [comment]
It would be indeed very nice to have all api docs at one place, i’ve Been working hard making sure we have doc generation on the main repos, we can further down later
