### ISSUE TITLE
support WeChat small program

### ISSUE THREAD

**Issue by xingyinbuli** [parse-community/Parse-SDK-JS#530]
hi~when can you support WeChat small program?
please😭

**Comment by flovilmart** [comment]
What do you expect? We already support wechat on Parse server and building an client authentication module should be straight forward with the examples of Facebook and Twitter. Are you stuck somewhere along that process?

**Comment by einsqing** [comment]
Need

**Comment by einsqing** [comment]
@xingyinbuli @zhaojiee https://github.com/qingful/Parse-SDK-JS 支持微信小程序
