### ISSUE TITLE
Unable to connect to the Parse API (iOS only remotely)

### ISSUE THREAD

**Issue by RCorsino** [parse-community/Parse-SDK-JS#534]
Not working on iOS!

React Native Parse Error:
XMLHttpRequest failed: "Unable to connect to the Parse API"

Works perfectly in Android both in local parse and remotely parse.
Works in iOS if connected to local parse only and unable to connect in remotely parse.

"parse": "1.10.0",
"react": "^16.0.0",
"react-native": "^0.49.3",

**Comment by montymxb** [comment]
@RCorsino are you talking about the iOS sdk or the JS sdk? Please clarify and provide details, and if possible, the code that is failing.

**Comment by dplewis** [comment]
I’ll close this one, Please reopen the issue if it persists.

Make sure your keys and serverURL are correct. Also ensure that ports / firewalls / hosting config etc. allow for connections.
