### ISSUE TITLE
Parse.User.signUp doesn't pass installationId

### ISSUE THREAD

**Issue by smassin** [parse-community/Parse-SDK-JS#536]
As the title suggests, using
```
Parse.User.signUp(null, {useMasterKey: true, installationId: '...'})
```
does not actually pass the installationId.

I spent more time than I probably should tracking down the issue here https://github.com/parse-community/parse-server/issues/3996

The short answer is Parse.User.signUp actually does a ParseObject.save() at its core which does not send an installationId. Inserting the following code just before this line 
 solves the problem:
https://github.com/parse-community/Parse-SDK-JS/blob/ee33c48e4a19f9264fd4301cb1dd3250dc7550a7/src/ParseObject.js#L1085
```
if (options.hasOwnProperty('installationId')) {
  saveOptions.installationId = options.installationId;
}
```

**Comment by samuelantonioli** [comment]
@smassin I don't know if this is still a problem. Maybe you can add a PR with a fix for it.
