### ISSUE TITLE
React Native: login throws Cannot read property of 'getItem' of undefined

### ISSUE THREAD

**Issue by MiLeung** [parse-community/Parse-SDK-JS#537]
calling this method

```js
  login = (email, password) => {
    Parse.User.logIn(email, password, {
      success: user => {
        Alert.alert('success!');
      },
      error: (user, error) => Alert.alert(error.message)
    });
  }
```
gives me this error.

![simulator screen shot - iphone 6 - 2017-12-22 at 21 06 22](https://user-images.githubusercontent.com/9166324/34317095-f9b5a272-e75b-11e7-854d-8ac6445206df.png)

I looked at the source code and it looks like [`AsyncStorage` is undefined](https://github.com/parse-community/Parse-SDK-JS/blob/2e117801ecd00896698621f7fce9e1facd76434c/src/StorageController.react-native.js#L24).

**Comment by Amphaal** [comment]
Hi, 

I'll just be quoting the latest release patch note : 

> ⚠️ Starting 1.11.0, the Parse SDK does not provide automatically the AsyncStorage for ReactNative.
> Please call Parse.setAsyncStorage(AsyncStorage) in order to restore the functionality. 

You should be fine knowing that ;) I'll do a PR to make it clearer in the docs.

**Comment by MiLeung** [comment]
@Amphaal  Thanks! Saved my Winter Break side project!
