### ISSUE TITLE
React Native: A syncrhonous StorageController must implement getItem()

### ISSUE THREAD

**Issue by jcguarinpenaranda** [parse-community/Parse-SDK-JS#539]
I am testing the following example on React Native 0.50 +, and Parse >= 1.11.0 without success

![captura de pantalla 2017-12-26 a las 5 43 06 p m](https://user-images.githubusercontent.com/7200821/34366199-a005659c-ea66-11e7-9300-6e72cdf20bab.png)

What happens is that when I try to import this file I wrote, I get an error stating that StorageController must implement getItem()

![captura de pantalla 2017-12-26 a las 5 43 15 p m](https://user-images.githubusercontent.com/7200821/34366207-c00400c4-ea66-11e7-8722-00c9529184e9.png)

I supposed that stating `setAsyncStorage(AsyncStorage)` was going to be ok, but I can't find more documentation.

I read the code and found that in `CoreManager.js` there's a method for setting the async storage controller, but I don't understand why I am getting this error if the `AsyncStorage` class from `react-native` already has a `getItem` function implemented

**Comment by flovilmart** [comment]
How did you solve the issue?

**Comment by jcguarinpenaranda** [comment]
Well, I managed to solve it, but it was my fault.

I was using old version of parse (1.10.x) and I had written a script for the `postbuild` section in my `package.json`

The `postbuild` script referenced a file I created that was called `correct-parse.sh`, which I copied from one amazing man who posted it on one of these Github Issues.

correct-parse.sh:
```
#!/bin/bash
PARSE_FILENAME='./node_modules/parse/lib/react-native/StorageController.react-native.js'

sed -i '' -e '16,21d' $PARSE_FILENAME
sed -i '' -e 's|let AsyncStorage|let AsyncStorage = require("react-native/Libraries/Storage/AsyncStorage")|g' $PARSE_FILENAME

```

Removing the `postbuild` script, and then writing `rm -rf node_modules && yarn` solved my issue.
