### ISSUE TITLE
subscribe() method in angular 4

### ISSUE THREAD

**Issue by ljunokas** [parse-community/Parse-SDK-JS#540]
Hi, 

Does anyone face the problem like this:

```
  let theMessages = Parse.Object.extend("Message");
    let queryMessages = new Parse.Query(theMessages);
    queryMessages.equalTo('pointer', message);
    this.subscription = queryMessages.subscribe();
```
and what i get is this error.

Property 'subscribe' does not exist on type 'Query<Object>'.

any info would be appreciated

Thanks

**Comment by simonaberry** [comment]
I had this, but can't remember exactly how I resolved it!!!!!

Could it be the way you are importing the Parse Library.

dont use `import {...} from`

try `const Parse: any = require('parse');`

**Comment by ljunokas** [comment]
I dont know what was the issue, but i just upgraded my angular to version 5 and its ok now :)

**Comment by montymxb** [comment]
Closing as it seems like you figured it out.
