### ISSUE TITLE
Documentation for Aggregate Queries

### ISSUE THREAD

**Issue by montymxb** [parse-community/Parse-SDK-JS#543]
Someone noted in [#4197](https://github.com/parse-community/parse-server/issues/4197) on the parse server repo that we do not have documentation for aggregate queries in the docs. I'm opening this up to make this issue known until we get proper documentation in place for this functionality.

**Comment by dplewis** [comment]
@montymxb I opened a PR https://github.com/parse-community/docs/pull/497
