### ISSUE TITLE
Framework or Website with Parse SDK JS

### ISSUE THREAD

**Issue by JulienLevallois** [parse-community/Parse-SDK-JS#545]
Hi,

Are there any examples of open source, framework websites that work with the JS Parse SDK?
I am looking to create an admin panel for an IOS app with Parse Server

Thanks :)

**Comment by flovilmart** [comment]
@JulienLevallois yes, the Parse Dashboard :)

**Comment by srameshr** [comment]
Frills uses parse server and parse js sdk https://itunes.apple.com/us/app/frills/id1288180352?ls=1&mt=8
