### ISSUE TITLE
And Query constraints

### ISSUE THREAD

**Issue by gaoljie** [parse-community/Parse-SDK-JS#546]
I tried to use 'and' query by following the guidance [http://docs.parseplatform.org/js/guide/#and-ed-query-constraints](url)
`var mainQuery = Parse.Query.and(
  Parse.Query.or(age16Query, age18Query),
  Parse.Query.or(friends0Query, friends2Query)
);`

but it throws the error
`vue.runtime.esm.js?23ec:1695 TypeError: __WEBPACK_IMPORTED_MODULE_1_parse___default.a.Query.and is not a function`

and I did not find 'and' method in [http://parseplatform.org/Parse-SDK-JS/api/v1.11.0/](url) either.

**Comment by dplewis** [comment]
@gaoljie There is an open PR. https://github.com/parse-community/Parse-SDK-JS/pull/367

It should be merged soon

**Comment by gaoljie** [comment]
Thank! @dplewis

**Comment by dplewis** [comment]
Parse.Query.and was add in `1.11.1`. Please update to the latest version of Parse-Server.
