### ISSUE TITLE
Support fullTextSearch in 1.11.0

### ISSUE THREAD

**Issue by srameshr** [parse-community/Parse-SDK-JS#548]
Here is a thread discussing it.
https://github.com/parse-community/Parse-SDK-JS/pull/541

**Comment by montymxb** [comment]
Thanks, and we would probably be looking at **1.12.0** for the new features.
 
Speaking of new features #367  is just about done, just rerunning CI before we give it a final look. If that get merged we'll probably put that in as well.

**Comment by srameshr** [comment]
Yes, please.
And please remember to update ```parse```, the **JS-SDK** version for the ```parse-server``` dependencies.
Thanks for your prompt reply. Hope this gets done by the end of this week.

**Comment by montymxb** [comment]
Definitely, when we do put a release out for the JS sdk, and if we don't get to the parse-server `parse` dependency, notify us with an issue/pr. We're bouncing around among all the notifications for the server & various sdks, helps to let us know if we need to get back to something 👍 .

**Comment by flovilmart** [comment]
We could also be a bit less aggressive on parse server with the semver or our maintained dependencies, this would
decouple the releases of parse-server and the JS SDK

**Comment by srameshr** [comment]
@montymxb Any updates on this?

**Comment by montymxb** [comment]
Yeah, #367 was merged not too long ago. I need to double check that there
isn't anything else outstanding. Probably Thursday or this weekend.

**Comment by srameshr** [comment]
Please dont push it to weekend.  Please try by this Wednesday PST.

**Comment by flovilmart** [comment]
@srameshr this is not how it works, nobody is paid to run this open source project, if you’re in a hurry, you can always fork the project(s) and use intermediate versions.

**Comment by srameshr** [comment]
@flovilmart I did it. The problem is, when uploaded to AWS EBS, the package.json with the link to github forked project never picks up at all. I tried few things to but to no avail.
I just don't want to fork and create an actual npm package of the fork to make EBS run.
I don't mean to push anybody.

**Comment by montymxb** [comment]
It's alright. Just try to understand that, being a community, we all have
commitments besides what we do for parse.

We will put out a release, but it will be when we are ready and when we are
able. Not trying to backlog things or put this aside, but it's not the only
thing on our plates right now.

**Comment by srameshr** [comment]
@montymxb

**Comment by srameshr** [comment]
You guys should be so proud of yourselves.
Well done.

**Comment by montymxb** [comment]
@srameshr not sure why you closed this. Although we haven't been able to address as soon as you may have liked this is still a relevant issue. It should remain open until resolved.

We're not ignoring this, if that's your perception. The simple answer is that we do not have the time to address this currently. When we get time, and when we get to this issue, we'll take care of it.

**Comment by SebC99** [comment]
@srameshr you just have to fork the project on github with your own version/branch, and link to your github repo in the package.json file to use it on aws elb.

**Comment by dplewis** [comment]
Full Text Search was add in `1.11.1`. Please update to the latest version of Parse Server.
