### ISSUE TITLE
problems with date object

### ISSUE THREAD

**Issue by lucamorelli** [parse-community/Parse-SDK-JS#550]
I have a cordova application that uses a few parse entities: I have a few dates inside these classes, but I find date parse objects  instead standard date objects, and I don't know how to convert from object to date value. 
where can I find infos about this?

**Comment by dplewis** [comment]
Have you found a solution?

Can you post your logs VERBOSE=1

**Comment by mullwaden** [comment]
I think the parse dates have a field called .iso that you can use
