### ISSUE TITLE
Can't get full fields. Only id is shown.

### ISSUE THREAD

**Issue by Nisthar** [parse-community/Parse-SDK-JS#551]
I am using react native. I have a class named "Foods" in my parse server.

I can find all the objects. But the result is not giving me full fields. It only gives me the id and some other fields.

```js
[ { _objCount: 4, className: 'Foods', id: 'hazm2Cj7UQ' }]
```
I set the class level permission in my parse server to public read and write. Still can't get the fields.
am i doing something wrong?

**Comment by flovilmart** [comment]
What you probably see here is the short form of the object. If you want the full JSON représentation, you probably need to use `.toJSON()` to access particular values for known keys, you should use `.get(‘key ‘)`
