### ISSUE TITLE
Parse Collections

### ISSUE THREAD

**Issue by shkesar** [parse-community/Parse-SDK-JS#556]
I'm migrating my parse-server from 1.4.2 to the lateset
Seems like the collections are no longer a part of parse sdk. But I have a lot of parse collections in use.

Can I convert my parse collection to backbone collections?
How did others move out of collections? @flovilmart

**Comment by flovilmart** [comment]
I'm not sure by what you mean by collections. Also parse-server started at version 2.0, so I'm not sure if you're refering to the JS SDK or something else.
