### ISSUE TITLE
Parse.File upload problems

### ISSUE THREAD

**Issue by EnricoMonese** [parse-community/Parse-SDK-JS#558]
I've been trying this approach as described in the docs
```js
var fileUploadControl = $("#profilePhotoFileUpload")[0];
if (fileUploadControl.files.length > 0) {
  var file = fileUploadControl.files[0];
  var name = "photo.jpg";

  var parseFile = new Parse.File(name, file);
  parseFile.save();
} 

```
But when I try to do `.save()`  it throws this error a bunch of times
`error: Invalid file upload. code=130, message=Invalid file upload. `

This only happens when using `File`,  if I use base64 data it works albeit being slower.

**Comment by samuelantonioli** [comment]
Most likely it has something to do with the file adapter you're using in parse-server. Add some logs of the HTTP requests or similar so we can help you better.

**Comment by EnricoMonese** [comment]
I'm no longer using Parse, but the PR above seems to address the problem.
