### ISSUE TITLE
ParsePromise has no finally method

### ISSUE THREAD

**Issue by MiLeung** [parse-community/Parse-SDK-JS#559]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

Confusing having a different API for ParsePromise and regular Promises because there is no distinction between the two in the docs.

**Comment by flovilmart** [comment]
The parse SDK implements A+ Promises (and have been implementing them before promises were actually a thing in JS). This is the expected behavior.

Also note that `finally` is not available on many platforms like `Node` or `Safari`
