### ISSUE TITLE
Users can run parse query from browser console

### ISSUE THREAD

**Issue by shkesar** [parse-community/Parse-SDK-JS#563]
Running Parse SDK on the frontend allows anyone to make Parse.Query calls to the Parse Backend from the browser console. The user can now fetch any data from his browser, even delete it. How is everyone using Parse SDK to prevent this?

**Comment by oallouch** [comment]
There's no need to prevent it.
If he can delete data, it's because he has the credentials to do so.

**Comment by flovilmart** [comment]
@shkesar you should check the documentation around ACL and class level permissions as they are explicitely designed to address those concerns

**Comment by shkesar** [comment]
Thanks for the help!
