### ISSUE TITLE
Current user cache keeping outdated data, results in intermittent "209: invalid session token" errors

### ISSUE THREAD

**Issue by pgiguere1** [parse-community/Parse-SDK-JS#564]
### Issue

There appears to be something wrong with `ParseUser.js`'s current user caching system not staying in sync with the current user on disk (in your browser's local storage). Your local storage will be up-to-date with the latest data for the current user, while the Parse JS SDK may use outdated data from the current user cache.

### Details

When a new session starts, a new `Session` object will be created on Parse with a session token that correctly matches the one saved to disk in the browser's local storage.

However, sometimes the session token used by the Parse JS SDK (as found in request headers and `Parse.User.current().getSessionToken()`) will be an outdated one and not match the most recent one found in your browser's local storage and in the newest Session object for that user.

This will result in failed requests with error `209: invalid session token`, until the user is logged out and logged in again, at which point the Parse JS SDK will correctly update its session token instead of using the invalid cached one.

This happens very frequently for me, roughly 1 in 5 new session will face that bug, forcing users to log in again every time.

I made sure my code wasn't making weird use of authentication, such as calling `logIn()` multiple times in a row or when unnecessary. I also dropped my entire `_Session` table in case this was the culprit but it didn't help.

### Temporary workaround

My workaround has been to [fork the Parse JS SDK and disabling the current user cache](https://github.com/pgiguere1/Parse-SDK-JS/commit/3f9e81ce983d816443d21b449c978500b2f2c9e4) in `ParseUser.js`, so that the SDK always loads the current user from disk. This solves my issue but is obviously not an actual fix.

### Environment

I'm using the latest version of the JS SDK (1.11.1) in a React project. I can reproduce this issue in any browser on different machines. I'm using the latest version of parse-server (2.7.4) on Heroku/mLab.

**Comment by adlondon** [comment]
Thanks for the thorough bug report @pgiguere1 . I'm having the same issue here with 1.11.0.
