### ISSUE TITLE
unset properties on objects responded by server from Parse.Cloud.run are not properly handled

### ISSUE THREAD

**Issue by zgec** [parse-community/Parse-SDK-JS#566]
When running a cloud function and it returns some (updated) objects, the Parse.Cloud.run function automatically transforms them to objects, parses the json returned to class instances (ParseObject.fromJSON method behind the scenes).

**However**, when it transforms them, it includes properties that may have been UNSET by the server... Meaning, it will include property A in the transformed client object, even though server removed it, saved object and responded with it without property A.

*After checking the code, it looks like the method ["fromJSON" inside ParseObject.js](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseObject.js#L1349)
Accepts override parameter, which as far as I can tell, makes the function behave exactly the way I was expecting it to behave. Issue is, this parameter is not "reachable" when calling Parse.Cloud.run unless I am missing something?*

**To replicate:**

On Client
```
var BlogPost = Parse.Object.extend("BlogPost");
var post = new BlogPost();
post.set('title','Hello world');
post.save().then((post) => {
    Parse.Cloud.run('removeTitle', { postID: post.id }).then(returnedPost => {
        // This will show the title even though it was removed by the server, and its not included in the response
        console.log(returnedPost.get('title'))
    })
})
```

On Server
```
Parse.Cloud.define("removeTitle", function(request, response) {
    var query = new Parse.Query('BlogPost');
    query.get(request.params.postID).then(post => {
        post.unset('title');
        response.success(post);
    })
})
```

**Comment by zgec** [comment]
Sorry in the example I forgot the save, but the issue remains even if you save the object on the serverside. JSON that server responds is correct, the client side parsing/transforming to ParseObjects is not.

**Comment by mullwaden** [comment]
Hmm then no clue... not something I have experienced myself. Could you post the new code and the response you get from the server?

**Comment by hajjarjoseph** [comment]
Same issue here!

**Comment by dplewis** [comment]
@hajjarjoseph Can you open a new issue?
