### ISSUE TITLE
JS SDK - Live query on specific fields within class

### ISSUE THREAD

**Issue by dpatel20** [parse-community/Parse-SDK-JS#567]
I'm using Parse live queries with the Javascript SDK. I can get events when a class (table) on the server side is updated. Is it possible to have a live query subscribe to changes to specific fields rather than the whole class?

For example, I have a `Results` class but I only want to be notified when `score` within there changes. This way I know what has changed and can use it appropriately. Otherwise, I have no idea which of the fields has changed.

The documentation [here](https://github.com/parse-community/parse-server/wiki/Parse-LiveQuery-Protocol-Specification) suggests it can be done but I have no idea how to use that with the JS SDK!

>     The query.fields field is optional. It is an array of field names of a ParseObject. Suppose the ParseObject Player contains three fields name, id and age. If you are only interested in the change of the name field, you can set query.fields to [name]. In this situation, when the change of a Player ParseObject fulfills the subscription, only the name field will be sent to the clients instead of the full Player ParseObject.

**Comment by dpatel20** [comment]
I think I figured it out...

```
let livequeryFixtures = new Parse.Query('Fixtures_and_results');
livequeryFixtures.select("TEAM1SCORE");
let subscribe_FixturesResults = livequeryFixtures.subscribe();
```

But I had misread what it does...I had understood that it would tell me only if `TEAM1SCORE` had been updated but actually any update to `Fixtures_and_results` will still trigger an event but that event will now only include `TEAM1SCORE`. Is this the correct understanding now?

**Comment by mullwaden** [comment]
I would think so - as far as i know the live updates server looks for updates on the object level (e.g. a change to the last updated field) not if individual fields have changed.
