### ISSUE TITLE
ParseFile.saveFile failed if javascriptKey is not set

### ISSUE THREAD

**Issue by alvinthen** [parse-community/Parse-SDK-JS#569]
As state by [parse-server](https://github.com/parse-community/parse-server/)'s README, `javascriptKey` is no longer necessary but without setting it, using ParseFile will fail.

In this [line](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseFile.js#L246), `X-Parse-JavaScript-Key` will be `undefined`, and when the xhr is finally sent, NodeJS will throw a `ERR_HTTP_INVALID_HEADER_VALUE` [the line here](https://github.com/nodejs/node/blob/master/lib/_http_outgoing.js#L458)

The easy fix should look like this

```js
var jsKey = CoreManager.get('JAVASCRIPT_KEY');
if (jsKey) {
 headers[ 'X-Parse-JavaScript-Key'] = jsKey;
}
```

I'll be glad to send in a PR if the fix is as easy as above.

This is referencing to Parse SDK JS v1.11.1 and NodeJS v9.11.1

**Comment by flovilmart** [comment]
Feel free to open a PR, this looks like a bug :)
