### ISSUE TITLE
Using React native CLI app with parse ( back4app)

### ISSUE THREAD

**Issue by Hypothesis-github** [parse-community/Parse-SDK-JS#576]
I am unable to install Parse on my react application and it no longer renders to the screen saying the development server has stopped working when parse is imported.

can you please tell how I can use Parse and import it in react native without facing issues ?

**Comment by flovilmart** [comment]
Without more informations about your issue that’s impossible to give proper guidance. Can you provide more context? Logs, code that is failing for example?

**Comment by vivekp9690** [comment]
This line of code break my existing app and say Can't find variable: localStorage

```
 let install = new Parse.Installation();
        install.set("deviceType", navigator.userAgent);
   install.save().then((resp) => {
       console.log('Created install object', resp); })

this.setState({
          result: 'New object created with objectId: ' + resp.id
        })
      }, err => {
        console.log('Error creating install object', err);

        this.setState({
          result: 'Failed to create new object, with error code: ' + err.message
        })
      })
```
