### ISSUE TITLE
`npm run build` script fails

### ISSUE THREAD

**Issue by alexander-alzate** [parse-community/Parse-SDK-JS#577]
I've just downloaded the project to propose a patch but it couldn't be built.
## System (uname -a)
> Linux arch-laptop-workstation 4.15.15-1-ARCH #1 SMP PREEMPT Sat Mar 31 23:59:25 UTC 2018 x86_64 GNU/Linux

## Npm --version
> 6.0.1

## Output:
> > parse@1.11.1 build ${PROJECT_PATH}/Parse-SDK-JS
> >
> > ./build_releases.sh
>
> Building JavaScript SDK v1.11.1...\n
> Cleaning up old builds...\n
> Browser Release:
> gulp[30297]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
>  1: node::Abort() [gulp]
>  2: 0x55acc570329b [gulp]
>  3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
>  4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [gulp]
>  5: 0x55acc590de97 [gulp]
>  6: 0x55acc590e68f [gulp]
>  7: 0x21e7fc00427d
> ./build_releases.sh: line 10: 30297 Aborted                 (core dumped) PARSE_BUILD=browser gulp compile
> Node.js Release:
> gulp[30310]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
>  1: node::Abort() [gulp]
>  2: 0x560f8535229b [gulp]
>  3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
>  4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [gulp]
>  5: 0x560f8555ce97 [gulp]
>  6: 0x560f8555d68f [gulp]
>  7: 0x2017adc0427d
> ./build_releases.sh: line 12: 30310 Aborted                 (core dumped) PARSE_BUILD=node gulp compile
> React Native Release:
> gulp[30323]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
>  1: node::Abort() [gulp]
>  2: 0x561aa715b29b [gulp]
>  3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
>  4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [gulp]
>  5: 0x561aa7365e97 [gulp]
>  6: 0x561aa736668f [gulp]
>  7: 0x19d09dc0427d
> ./build_releases.sh: line 14: 30323 Aborted                 (core dumped) PARSE_BUILD=react-native gulp compile
> Bundling and minifying for CDN distribution:
> gulp[30335]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
>  1: node::Abort() [gulp]
>  2: 0x55af4022f29b [gulp]
>  3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
>  4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [gulp]
>  5: 0x55af40439e97 [gulp]
>  6: 0x55af4043a68f [gulp]
>  7: 0x117b44a0427d
> ./build_releases.sh: line 16: 30335 Aborted                 (core dumped) gulp browserify
> gulp[30357]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
>  1: node::Abort() [gulp]
>  2: 0x55f721c9a29b [gulp]
>  3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
>  4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [gulp]
>  5: 0x55f721ea4e97 [gulp]
>  6: 0x55f721ea568f [gulp]
>  7: 0x33631c80427d
> ./build_releases.sh: line 17: 30357 Aborted                 (core dumped) gulp minify
> npm ERR! code ELIFECYCLE
> npm ERR! errno 134
> npm ERR! parse@1.11.1 build: `./build_releases.sh`
> npm ERR! Exit status 134
> npm ERR!
> npm ERR! Failed at the parse@1.11.1 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
> npm ERR! A complete log of this run can be found in:
> npm ERR!

**Comment by flovilmart** [comment]
@alexander-alzate what is you `node version`
