### ISSUE TITLE
Is there a query limit on Cloud code?

### ISSUE THREAD

**Issue by monajafi** [parse-community/Parse-SDK-JS#580]
I've used cloud code to calculate total fee  also I put maxLimit to a number less than 100 in parseserver configuration. 
it seams  maxLimit does not affect the query on cloud code. Is there a 100 default limit in cloud code or it's unlimited.

**Comment by flovilmart** [comment]
Do you have an example of what you're saying? Can you provide logs etc...

**Comment by monajafi** [comment]
In cloud code the default limit is 100 like js sdk . I forgot to limit query by query.limit(); 
meanwhile what is the best way to calculate some column's total rows sum? 
one way is to set a very large number in maxLimit and set a big limit on query another way is to retrieve 
all rows using limit and skip what way is best?

**Comment by flovilmart** [comment]
You can probably use aggregation pipelines or fetch the objects with the each() operator and add them all locally.

http://parseplatform.org/Parse-SDK-JS/api/v1.11.1/Parse.Query.html#aggregate

http://parseplatform.org/Parse-SDK-JS/api/v1.11.1/Parse.Query.html#each

For additional help, please use stackoverflow as we use github issues for reporting bugs.
