### ISSUE TITLE
CLP needs an API

### ISSUE THREAD

**Issue by oallouch** [parse-community/Parse-SDK-JS#583]
Hi,
CLP is an amazing feature, but without an easy API to set it, I can't use it. It's too easy to forget to check the dashboard.
I don't know which form it can take (is it Schema-related ?), but I'm sure you'll figure it out.

What do you think about it ?

Thx,
Olivier

**Comment by flovilmart** [comment]
It makes sense, a masterKey only API on the SCHEMA would be nice.

**Comment by mullwaden** [comment]
Would be very nice! Currently I do something like this in lieu of a proper API: 

```
const setCLP = ({ className, clp }) => {
  if (!clp) {
    return Promise.resolve();
  }

  // this approach is used by the dashboard.
  // see: https://github.com/parse-community/parse-dashboard/blob/master/src/lib/stores/SchemaStore.js
  return Parse._request(
    'PUT',
    'schemas/' + className,
    { classLevelPermissions: clp },
    { useMasterKey: true }
  );
};
```

Where the clp object is defined something like: 

```
    clp: {
      get: { requiresAuthentication: true },
      find: {},
      create: { '*': true },
      update: { requiresAuthentication: true },
      delete: {},
      addField: {},
    },
```

**Comment by kosssi** [comment]
@mullwaden I don't understand how I can set good CLP with your function I would like to make this:

![capture d ecran 2019-01-15 a 23 19 03](https://user-images.githubusercontent.com/1135513/51213781-2b6f3d80-191c-11e9-9447-1f9a7eb899cf.png)

Can you describe `clp` object for this example?

**Comment by oallouch** [comment]
I really like the new protectedFields CLP.
It would still be great to have it in a future CPL API :)
