### ISSUE TITLE
Wrong Flow typing on Parse.ACL() constructor

### ISSUE THREAD

**Issue by jlpiedrahita** [parse-community/Parse-SDK-JS#584]
`Parse.ACL` class constructor [docs](http://parseplatform.org/Parse-SDK-JS/api/v1.11.1/Parse.ACL.html) states:

> Creates a new ACL. **If no argument is given**, the ACL has no permissions for anyone. **If the argument is a Parse.User**, the ACL will have read and write permission for only that user. **If the argument is any other JSON object**, that object will be interpretted as a serialized ACL created with toJSON().

But the actual Flow typing for the [class](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseACL.js#L39) is:

```javascript
constructor(arg1: ParseUser | ByIdMap) {

  //...

}
```

Which clearly doesn't allow to call the constructor without any arguments as the docs suggest.

I was about to submit a PR to the [flow-typed](https://github.com/flowtype/flow-typed) repo but I'm not sure which path to follow: patch the flow-typed repo for the Parse SDK [libdef](https://github.com/jlpiedrahita/flow-typed/blob/master/definitions/npm/parse_v1.9.x/flow_v0.30.x-/parse_v1.9.x.js) or if this is something that should be fixed here as the SDK has the Flow type definitions and should be use to extract the libdef files (not sure if this is the case now).

Some guidance would be appreciated.

Thanks.

**Comment by flovilmart** [comment]
What does the underlying code show?

**Comment by jlpiedrahita** [comment]
Not sure what you mean by _underlying code_, if you're talking about the concrete Flow error here it's an example:

```
Cannot call Parse.ACL because:
 • Either undefined [1] is incompatible with $npm$parse$ParseUser [2].
 • Or undefined [1] is incompatible with $npm$parse$ByIdMap [3].

        src/file.js
         15│
    [1]  16│   const acl = new Parse.ACL();
         17│   acl.setPublicReadAccess(false);
         18│   acl.setPublicWriteAccess(false);
         19│   unnaxRequest.setACL(acl);

        flow-typed/npm/parse_v1.9.x.js
 [2][3] 231│   constructor(arg1: $npm$parse$ParseUser | $npm$parse$ByIdMap): $npm$parse$ParseACL;
```

This usage of `Parse.ACL()` was taken directly from the official guide: http://docs.parseplatform.org/js/guide/#object-level-access-control

**Comment by flovilmart** [comment]
I am talking about the code of the constructor. Perhaps the annotation should be an optional instead of an or type.

**Comment by jlpiedrahita** [comment]
I think so. According to the docs it should be like: 

```javascript
constructor(arg1: ParseUser | ByIdMap | void) {

  //...

}
```

**Comment by flovilmart** [comment]
Can you open a PR / propose a fix for it?

**Comment by flovilmart** [comment]
The PR should be opened here as well. Actually, it should have been opened here first

**Comment by jlpiedrahita** [comment]
Understood, just give me a couple of days.
