### ISSUE TITLE
Investigate possible issue when setting Parse.masterKey from client libraries

### ISSUE THREAD

**Issue by flovilmart** [parse-community/Parse-SDK-JS#591]
If anything, the SDK should HCF if this happens as it will lead to security issues or worst.

I've noticed someone doing it: https://stackoverflow.com/questions/40223311/parse-js-sdk-cannot-use-the-master-key-it-has-not-been-provided

**Comment by samuelantonioli** [comment]
So just throw an error [here](https://github.com/parse-community/Parse-SDK-JS/blob/2e117801ecd00896698621f7fce9e1facd76434c/src/Parse.js#L101) (in the setter function for `Parse.masterKey`)?  

Or maybe just a warning. I don't know how parse-dashboard handles the `masterKey` and if they rely on this.

**Comment by flovilmart** [comment]
Parse dashboard indeed uses this feature but we.can probably work around it.

**Comment by PokoGroot** [comment]
hope this feature have progress soon

**Comment by dplewis** [comment]
@flovilmart Welcome back! (Temporarily)
