### ISSUE TITLE
Remove write access from _User

### ISSUE THREAD

**Issue by Samigos** [parse-community/Parse-SDK-JS#602]
`Parse Server version: 2.7.4`

I'm trying to remove the write access from users, as a security measure. This is the acl I use:

```
var custom_acl = new Parse.ACL();
			
custom_acl.setReadAccess(userObject, true);
custom_acl.setPublicWriteAccess(false);

userObject.setACL(custom_acl);

userObject.save(null, {useMasterKey: true});
```

But it doesn't work! After that, I have the read access set correctly, and it continues to have a write access for that user.

Any idea on why this is happening?

**Comment by flovilmart** [comment]
See https://github.com/parse-community/parse-server/pull/4860abs related issues. You can use the master branch of parse server to try out if it fixes the issue .

**Comment by Samigos** [comment]
The link is invalid...

**Comment by flovilmart** [comment]
@Samigos sorry about that, I just updated it
