### ISSUE TITLE
Add custom headers

### ISSUE THREAD

**Issue by alexblack** [parse-community/Parse-SDK-JS#603]
Is there a way to add additional headers (on the fly, per request) to each http request made by the parse sdk?

I'd love to add a couple headers to identify which of our apps is making the request, and other info like that.

This can be done today with the Android SDK by configuring a network interceptor.

https://stackoverflow.com/questions/47372894/parse-com-android-sdk-okhttp-interceptor

**Comment by paulovitin** [comment]
How can we do this?

```
// like axios?
Parse.interceptors('request', request => {
	request.headers['foo'] = 'bar';
	return request;
});
```

**Comment by paulovitin** [comment]
@flovilmart if you have any ideas and need help, let me know...

**Comment by flovilmart** [comment]
On the other end; that could work, perhaps using an event emitter somewhere that emits the request object and let a consumer mutate it

**Comment by paulovitin** [comment]
Something like this:

```
Parse.on('request', mutator);
```

**Comment by REPTILEHAUS** [comment]
Also interested in this feature. Is there any way to hook into parse to add custom header to every request from the app ?

**Comment by taivo** [comment]
+1 on this. This feature would add a lot of flexibility.

**Comment by mogita** [comment]
Upvote for this. In my case, I can easily distinguish requests from my custom express API handlers and the ones made by Parse itself in my Parse hooks. Now they are simply identical.
