### ISSUE TITLE
Missing operations from parse-server

### ISSUE THREAD

**Issue by seriph** [parse-community/Parse-SDK-JS#604]
Is there any way of calling the following operations from parse-server?
aggregate
upsertOne
updateMany

**Comment by seriph** [comment]
Bump

**Comment by flovilmart** [comment]
Aggregate is supported http://parseplatform.org/Parse-SDK-JS/api/v1.11.1/Parse.Query.html#aggregate

The two others aren’t and are not likely to be publicly exposed any time soon.
