### ISSUE TITLE
Download docs as PDF

### ISSUE THREAD

**Issue by macklus** [parse-community/Parse-SDK-JS#605]
Is there any way to download docs as PDF ? where are docs written ?

**Comment by flovilmart** [comment]
@macklus for now it's impossible, the API docs are generated and you can generate them for yourself by cloning the repository and run:

```
git clone https://github.com/parse-community/Parse-SDK-JS
cd Parse-SDK-JS
npm install
npm run docs
```

The documentaton will be in the `out` folder.

From there you have the offline HTML docs.
