### ISSUE TITLE
Lack of API doc: Parse.User.logInWith method

### ISSUE THREAD

**Issue by mfkenson** [parse-community/Parse-SDK-JS#611]
Is it intented to prefer _linkWith instead of logInWith ?
http://parseplatform.org/Parse-SDK-JS/api/v1.11.1/Parse.User.html#_linkWith

The apidoc of _linkWith exists while logInWith does not.

Though I failed to go with _linkWith approach, the logInWith method is fine.

Client Side using logInWith (Success):
```
    var options = {
      authData: {
        "id": 'VALID_ACCOUNTKIT_USERID',
        "access_token": 'VALID_ACCOUNTKIT_TOKEN'
      }
    };
    Parse.User.logInWith('facebookaccountkit',options).then(r=>{
      console.log(r);// new user signed up.
    })

```

Client Side using logInWith (Fail):
```
    var myAuthData= {
        "id": 'VALID_ACCOUNTKIT_USERID',
        "access_token": 'VALID_ACCOUNTKIT_TOKEN'
    };
    var  user = new Parse.User();
    user._linkWith('facebookaccountkit', myAuthData).then(function (user) {
          console.log(user)
          // user
        });

**Comment by flovilmart** [comment]
The api doc should definitely be added for the logInWith method, _linkWith being ‘private-ish’, it is discouraged to use.
