### ISSUE TITLE
toJSON() Documentation

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-JS#613]
I noticed that toJSON takes a parameter but the documentation doesn't state what it does.

http://parseplatform.org/Parse-SDK-JS/api/v1.11.1/Parse.ACL.html#toJSON

[JS SDK toJSON()](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseObject.js#L413)

Also `toJSON` doesn't return `className`, is that by design? I could use [_fullJSON()](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseObject.js#L267)?

**Comment by flovilmart** [comment]
Yeah, I mean thst’s Tricky, as className should not be used when you create an object, unless you want the className key to be set, which is kinda backwards. 

toJSON is fine as it’s used to sérialité the payloads, and the className is never part of it.

**Comment by dplewis** [comment]
We can set the `className` key once the object is saved and has an `ObjectId`.

New Object
```
{}
```
Saved Object
```
{
  createdAt: ...,
  updatedAt: ...,
  objectId: ...,
  className: ...
}
```

If I store `object.toJSON()` in localStorage and retrieve it, I can't use `fromJSON()` as I don't know the class.

**Comment by flovilmart** [comment]
You should keep the class name part of the pin/key name?

**Comment by dplewis** [comment]
Thats a workaround, it would be nice to have in the `toJSON` return don't you agree?

**Comment by flovilmart** [comment]
You can’t actually as it would put className into all payloads therefore saving a key on each object with the clsssName value :/

Because yoi’re Doing something internal, you can use _toFullJSON

**Comment by dplewis** [comment]
Thanks for the feedback.

PS: I posted a message on Slack
