### ISSUE TITLE
save is too smart

### ISSUE THREAD

**Issue by oallouch** [parse-community/Parse-SDK-JS#617]
Hi,
When I call 'save' on an Object, I only expect this Object to be saved. Now, I know I was wrong.
I often modify Objects for UI only. I don't want them to be saved. But if they're pointed by the Object I save, they're also saved in a 'batch' query.
I think it would be great to have a 'shallow' property for the 'save' method. The default can be false, but it would also make clear that the Object attributes are 'traversed'.
What do you think ?

Thx,
Olivier

**Comment by fmendoza** [comment]
A workaround is to call `.revert()` if for some reason the object was modified in your UI but not saved.
