### ISSUE TITLE
Add aditional data on relation

### ISSUE THREAD

**Issue by macklus** [parse-community/Parse-SDK-JS#626]
Hi!
I need to add more data on a relation, something like:

``` 
let relation = room.relation('played');
room.increment('playedCount', 1);
relation.add(user);
relation.set('status', 'pending');
relation.set('date', Date.now());
relation.set('points', -1);
```

is there any way to do that ?

thanks in advance.

**Comment by flovilmart** [comment]
The relation represents the join table. In this case, you should store it as another object which will represent the your related object, like a new Class Play, with the objects’s properties being status, user, etc...
