### ISSUE TITLE
Using toJSON to clone Parse.Query objects does not work

### ISSUE THREAD

**Issue by mullwaden** [parse-community/Parse-SDK-JS#627]
Currently cloning a query is a bit of a hassle. Using ``_.clone`` does not work (as it contains objects inside of it), for some strange reason neither does ``_.cloneDeep``. Currently I have had to implement it like this in my code: 
```
export const beforeFind = (query, user, master) => {
    const query1 = _.clone(query);
    query1._where = _.clone(query._where);
    return Parse.Query.or(
      query.equalTo('limitACLToOrganization', false),
      query1.equalTo('commenterOrg', user.get('organization'))
    );
};
```

To me the obvious solution is to use toJSON, i.e. ``const query1 = Parse.Query.fromJSON(className, query.toJSON())``. However toJSON seems broken to me as it reuses existing objects inside the query. Currently in ParseQuery.js: 

```
  toJSON(): QueryJSON {
    var params: QueryJSON = {
      where: this._where
    };
    ...
```

This causes _where (which contains all the interesting query parameters) to be the same for both query and query1 leading to some funky results.

Happy to submit a PR that copies _where if this makes sense (how do we typically do deep copies in that case?)

**Comment by flovilmart** [comment]
@mullwaden feel free to open a PR with the proposed fix. 

One word of advice, `toJSON()` methods can't be changed as they are used internally to serialize the  queries and the objects in a server compatible format, so I hope you can have another workaround.

**Comment by flovilmart** [comment]
I usually would recommend to use the factory pattern to generate similar queries instead of cloning existing ones. The query may hold an internal state that would make the cloned one not working as expected
