### ISSUE TITLE
API doc: link to v2 migration guide is broken

### ISSUE THREAD

**Issue by Eyesiah** [parse-community/Parse-SDK-JS#646]
The API docs at http://parseplatform.org/Parse-SDK-JS/api/v2.0.1/ have a section "Upgrading to Parse SDK 2.0.0" that links to a migration guide at http://parseplatform.org/Parse-SDK-JS/api/v2.0.1/2.0.0.md . However, that link doesn't work.

A working URL is https://github.com/parse-community/Parse-SDK-JS/blob/master/2.0.0.md

**Comment by flovilmart** [comment]
Can you open a PR on the docs repo please?

**Comment by Eyesiah** [comment]
Ahh sure, well I've opened an issue there instead.

**Comment by flovilmart** [comment]
Thanks, the issue is in the README.md file, as it uses relative links.

**Comment by Tom-Fox1** [comment]
This is still broken, should we change it from a relative link to be ‘hardcoded’?
