### ISSUE TITLE
Support for Nativescript Angular

### ISSUE THREAD

**Issue by Jai-Krish** [parse-community/Parse-SDK-JS#655]
It seems like [nativescript-angular](https://github.com/NativeScript/nativescript-angular) doesn't have `XMLHttpRequest ` since it uses its own [HTTP module](https://docs.nativescript.org/ns-framework-modules/http).
`ERROR Error: Uncaught (in promise): ParseError: 100 XMLHttpRequest failed: {"originalStack":"Error: Cannot make a request: No definition of XMLHttpRequest was found.\n at new ZoneAwareError...`

This [Issue](https://github.com/NativeScript/nativescript-angular/issues/1494) has also been reported to the [nativescript-angular](https://github.com/NativeScript/nativescript-angular) repo.

I've modified the [RESTController.js](https://gist.github.com/Jai-Krish/e162f0346324a16c91f8322200ec0963) to use the `http` module and it works fine.

I would like to know if you guys are open to adding new platform builds or is there any other way to override the `RESTController` as it is right now.

**Comment by flovilmart** [comment]
Do you wish to provide support for it?

**Comment by Jai-Krish** [comment]
So we should decouple the request logic from the `RESTController` into a separate module and add something similar to `Parse.CoreManager.setStorageController` so that the user can swap the request module at runtime.
So should I start wrapping the `XHR` and `XDomainRequest` into a `http` that works with promises than a call back? if so do you propose any prototype that I should follow for this module?

**Comment by flovilmart** [comment]
Yep something similar, the best interface for the newly created module is one that makes it easy / trivial to use with the one you need :)
