### ISSUE TITLE
Save file on subdirectory

### ISSUE THREAD

**Issue by macklus** [parse-community/Parse-SDK-JS#656]
Not sure if this is possible.
I use local image store, and got a big number of them.
To improve load speed i wish to use subdirectories, like:
```
let parseFile = new Parse.File('elements' + slug + '_wide.jpg', {
                base64: base64
            });
```
but it dont work 

is this possible to do ?

**Comment by flovilmart** [comment]
It’s not possible at this time. If you wish to implement this feature, it will need to be on parse-server as well as the relevant adapters.
