### ISSUE TITLE
aggregate function is not called

### ISSUE THREAD

**Issue by leftluoyi** [parse-community/Parse-SDK-JS#657]
Windows 10
react": 16.4.1

Well, having  a aggregate query:

```
    Parse._initialize('test', 'test', 'test', true);

    const query = new Parse.Query("Meter");
      const pipeline = {
        group: {
          location: 'location',
          num: { sum: 1 },
        },
      };
      console.log('query');
      yield query
        .aggregate(pipeline)
        .then(results => {
          console.log('results', results);
          for (const e of results) {
            distribution.push({
              x: String(e.location),
              y: e.num,
            });
          }
        })
        .catch(err => {
          handleParseError(err);
        });
```

It works in `1.11.1`. 

Today just upgraded to `2.0.2`, all the other queries are fine but the ones with **aggregate** is not exectued. For example, the `consol.log()` above is not reached.

The console shows:

```
ParseError {code: 100, message: "XMLHttpRequest failed: "SyntaxError: Unexpected end of JSON input""}
```

**Comment by flovilmart** [comment]
THere are tests covering aggregates, and the case you're describing look covered.

https://github.com/parse-community/Parse-SDK-JS/blob/69b2e73/integration/test/ParseQueryAggregateTest.js#L26

Can you open a PR with a failing integration test in the file I just referenced above?

**Comment by dplewis** [comment]
Please update to the latest version of Parse Server as well and reopen if issue persists.

**Comment by dplewis** [comment]
Please update to the latest version of Parse Server
