### ISSUE TITLE
dirty and dirtyKeys return true even if value has not changed

### ISSUE THREAD

**Issue by mstephano** [parse-community/Parse-SDK-JS#660]
From the docs
- dirty(attr): Returns true if this object has been modified since its last save/refresh. If an attribute is specified, it returns true only if that particular attribute has been modified since the last save/refresh.
- dirtyKeys(): Returns an array of keys that have been modified since last save/refresh.

I thought that the meaning of "modified" is when the value is different between the new value I set and the current value. So my expected result for dirty was false, but that is not the case. Dirty return always true anytime we use set(..)

example:
```
myCar.set("color", "red");
console.log(myCar.dirty("color"));  //return true because first set
myCar.save();
..
myCar.set("color", "red");
console.log(myCar.dirty("color"));  //still return true, but I tought it would have returned false because value of color is the same
..
if (myCar.dirtyKeys().length > 0) {
  myCar.save(); // I don't want to save if color has not really changed
}
```

However, If anyone needed the same behavior as me, check my merge here: https://github.com/mstephano/Parse-SDK-JS/commit/1f5bc02219c16e086c39eae80c1886909e211774

I have tested it in my project and that works. This commit saves me a compare of each value in my project because the sdk does it for me.

**Comment by flovilmart** [comment]
In this case, you have mutated the value on purpose. This is the expected behaviour.
