### ISSUE TITLE
Destroy An Object Client Side

### ISSUE THREAD

**Issue by Kemsty2** [parse-community/Parse-SDK-JS#674]
I can't delete an object on the client side, using the destroy function, I created an admin role and gave it all the necessary rights, but unfortunately I am always sent object not found when I want to delete an object. Voila Mon code.
`

        user = getCurrentParseUser();
        sessionToken = user.getSessionToken();
        query = new Parse.Query(BillingPackage);
        billingPackage = await query.get(billingPackageId);

        console.log("billingPackage",billingPackage); //the object is retrieve here

        if(billingPackage){
          await billingPackage.destroy({sessionToken:sessionToken});
          return {status: true, message: "The Billing Package Has Been Deleted"}
        }else{
          return {status: false, message: "The Billing Package Already Deleted"}
        }`

**Comment by JacobJT** [comment]
www.stackoverflow.com

When you post there, be sure to include the CLP for the class in question, and consider verifying the ACL of a specific object you're trying to delete.

**Comment by Kemsty2** [comment]
Okay Thanks
