### ISSUE TITLE
Broken code after Latest JS SDK update

### ISSUE THREAD

**Issue by GoGross** [parse-community/Parse-SDK-JS#676]
JS SDK: Parse 2.1.0
PARSE SERVER: 2.7.4
I recently update my parse and I can't help notice that most of my code is broken. Have you done away with `success : function ( user ) {` 
if favor of 
`await etc`

Please help, I am a bit lost:

the following wont fly at all

try {
  await user.signUp();
  // Hooray! Let them use the app now.
} catch (error) {
  // Show the error message somewhere and let the user try again.
  alert("Error: " + error.code + " " + error.message);
}

**Comment by flovilmart** [comment]
What do you mean it won’t fly at all?

**Comment by GoGross** [comment]
I am getting an error, a server error for that if on successful response only

eceived an error with invalid JSON from Parse: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>

**Comment by GoGross** [comment]
Just updated to 3.0 and still the same problem

**Comment by GoGross** [comment]
Received an error with invalid JSON from Parse: <html>
 <head><title>502 Bad Gateway</title></head>
 <body bgcolor="white">
 <center><h1>502 Bad Gateway</h1></center>
 <hr><center>nginx/1.14.0 (Ubuntu)</center>
 </body>
 </html>

**Comment by flovilmart** [comment]
Can you provide both client and server logs?

**Comment by GoGross** [comment]
[gross-framework.log](https://github.com/parse-community/Parse-SDK-JS/files/2476091/gross-framework.log)

**Comment by GoGross** [comment]
ParseError: Received an error with invalid JSON from Parse: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>









    at https://local.grossframework.com/libs/parse-server/parse.js:12738:19

**Comment by flovilmart** [comment]
It says invalid username/password at one point in the logs, did you check that?

**Comment by GoGross** [comment]
This may help someone, but I was including the Session class in the liveQuery array
