### ISSUE TITLE
Method Parse.Config.save(param,value) (with masterKey)

### ISSUE THREAD

**Issue by Moumouls** [parse-community/Parse-SDK-JS#681]
Allow to save a new parameter in Parse.Config when we are in a Node.js Env or a masterKey is set
To avoid use of  : 
```javascript
Parse._request('PUT',
	'config',
	{ params: { [param]: Parse._encode(value) } },
	{ useMasterKey: true })
```

**Comment by barper** [comment]
Was wondering what was going on with this method in my cloud function. The solution worked but a dedicated method could be nice.

**Comment by dplewis** [comment]
@barper A PR was already submitted https://github.com/parse-community/Parse-SDK-JS/pull/684

It should be included in the next release
