### ISSUE TITLE
[Docs] JS API docs root path should show the latest version, instead of just redirecting

### ISSUE THREAD

**Issue by alvinthen** [parse-community/Parse-SDK-JS#683]
The JS API docs https://parseplatform.org/Parse-SDK-JS/api/ is redirected to https://parseplatform.org/Parse-SDK-JS/api/2.1.0/, which causes 404 links from other docs.

Example, in cloud-code.md, ({{ site.apis.js }}classes/Parse.User.html) is resolved into https://parseplatform.org/Parse-SDK-JS/api/classes/Parse.User.html, which is 404.

I'm not sure what's the appropriate way to fix this, guide me and I may open a PR for this.

**Comment by flovilmart** [comment]
The issue is on the docs repo. The appropriate fix could either be to change the version / root URL for the API docs to include the version or ‘master’
