### ISSUE TITLE
How do use '$where'

### ISSUE THREAD

**Issue by alejonext** [parse-community/Parse-SDK-JS#685]
Well, in the documentation never say for [`$where`](https://docs.mongodb.com/manual/reference/operator/query/where/)

```
const hash = "9b53e667f30cd329dca1ec9e6a83e994";
const GameScore = Parse.Object.extend("GameScore");
const query = new Parse.Query(GameScore);
query.$where("(hex_md5(obj.name) == " + hash );
const results = await query.find();
```

**Comment by flovilmart** [comment]
You don’t because it’s not supported neither on the client or the server.

If you wish to use advanced mongodb features, then you can use a mongodb client directly
