### ISSUE TITLE
Unable to Login with node.js

### ISSUE THREAD

**Issue by Ant248** [parse-community/Parse-SDK-JS#690]
Hi i've had a problem for a few days now completely stumped :(
I have been trying to create a bot to pull some data off my existing parse server however im unable to login.

I have check all the dependencies seems like everything is correctly set up but i get this error:
![12](https://user-images.githubusercontent.com/23380077/47718315-fec25880-dc3f-11e8-842e-57cdfba99f05.png)

My initialisation:

var Parse = require('parse');
Parse.serverURL = "https://myserver";
Parse.initialize("myappID", "myJavascriptKey");
var lo = myUsername;
var pw= myPassword;

function validate(){
  Parse.User.logIn(lo, pw, {
    success: function(user) {
        UPricesLoading();
    },
    error: function(user, error) {
      console.log("Unable to login2", error);
    }
  });
}

Can any one see what is going on? Thanks

**Comment by coryshaw** [comment]
Hi there, I believe you need to need to require the node version of Parse, like so:

`var Parse = require('parse/node').Parse;`

**Comment by Ant248** [comment]
Thanks! Seems there are no errors now, but it seems to crash on Parse.User.logIn :(
My code:

var Parse = require('parse/node').Parse;
Parse.serverURL = "https://myServer";
Parse.initialize("myappID", "myJavaScriptKey");

function validate(){
console.log("Validating");
var pw = "myPass";
var lo = "myLogin";
console.log("ready");
  Parse.User.logIn(lo, pw, {
    success: function(user) {
      console.log("success");
      var iatlo = user.get("metricsAccess");
      console.log(iatlo);
      if (iatlo === "Yes"){
        console.log("Logged In Loading Prices");
        UPricesLoading();
      } else {
        console.log("Unable to login1")
      }
    },
    error: function(user, error) {
      console.log("Unable to login2", error);
    }
  });
}

console.log("Starting");
validate();

Logs:
![bug2](https://user-images.githubusercontent.com/23380077/47852282-331a4e00-ddd3-11e8-8dbe-5e42f0ff4c41.jpg)

Seems to execute the code up to the `console.log("ready");` 🈂️ 
Has that method of logging in been deprecated?

**Comment by flovilmart** [comment]
You’re likely using the SDK in a version > 2 and I can see you are still using the old callbacks way. You should migrate your code to use Promises instead as they are natively supported now.

**Comment by Ant248** [comment]
Thanks so much!! 
Seems like parse sdk has changed a lot since i first started using it...

My code now for any one stuck works great:

`
const validateParse = async function(){
console.log("Validating");
const user = await Parse.User.logIn("mylogin", "pass")
.then((results) => {
  var iatlo = results.get("metricsAccess");
  console.log(iatlo);
  if (iatlo === "Yes"){
    console.log("Logged In Loading Prices");
    UPricesLoading();
  } else {
    console.log("Unable to login no access to class")
  }
})
.catch((error) => {
  console.log("Unable to login", error);
});
}
`
