### ISSUE TITLE
Getting user info after FacebookUtils.logIn

### ISSUE THREAD

**Issue by Jauny** [parse-community/Parse-SDK-JS#691]
Hi,

I'm setting up Facebook auth into my app. I'm testing the login flow right now, and after successfully calling `Parse.FacebookUtils.logIn('public_profile,email')` the user returned doesn't have the scope information, only `id` and `token` inside `authData.facebook`.

Look at `FacebookUtils` this is expected - but then I'm wondering what is the recommended way to query for the user information (email, name, etc) once the user is authenticated? I would have expected this info to be included in the response and included in the user created by Parse.

Thanks

EDIT: Now that I've spend more time on this, here is more context and what I'm doing. It still feels pretty wrong to me, because I don't see the pros of using the FacebookUtils instead of the facebook lib, since I end up using it anyways.

When a user authenticates with Facebook for the first time, we still redirect them to our signup form to get more data. Information that can be retrieved from Facebook is prefilled.
Because of this, I'd like to make use of the `user.existed()` function to know if it's a new Facebook user or not and decide if we redirect them to signup or not.

When I do
```
const user = Parse.FacebookUtils.logIn()

if (user.existed()) {
  if (Parse.FacebookUtils.isLinked(user)) {
```
user.existed() seems to always be true. I've made sure to clear all my cookies, delete the users created in my parse dashboard (and the Session), but I always get true here.
So not sure what I'm doing wrong here. (Are there more stuff I should delete in my parse dashboard?).

The second one I'm confused about is `isLinked`.
In the case of an user already existing, I understand isLinked is used to linked 2 accounts. This case is interesting for us, because we'd like to allow users to signup with their email and later on be able to login with Facebook.
This function also seems to always return true. How is it looking for a non-linked user through this?

The last thing that confuses me, is that when the facebook user is created by the `Parse.FacebookUtils.logIn()` process, it is created with no information from facebook, except the facebookId and user_token.
This confuses me about why FacebookUtils is even a thing (no offence).

Right now I am using FB.api('/me' ... to retrieve the user info after the facebook login and then check is the user returned by FacebookUtils.logIn() has an email, in which case it tells me that it is an existing user, else that it's a new account.

I'm obviously hacking it right now because I can't figure how to properly use isLinked/existed/etc.

Some guidance would be great, thanks :)

**Comment by flovilmart** [comment]
Did you consider using stackoverflow for implementation questions? We use github to report issues. I don’t seem to see what the bug or the issue is in this case.

**Comment by Jauny** [comment]
@flovilmart my bad didn't now SO was where to ask questions 👍

**Comment by Jauny** [comment]
@flovilmart looking at "parse.com" question on SO, very few have any answers. Is this the correct tag to use for questions? I'm wondering if it's the best place to ask question, if most are not getting answered.

For context, my question: https://stackoverflow.com/questions/53088132/using-parse-facebookutils-login

**Comment by flovilmart** [comment]
There are many reasons why a question is not answered.
Perhaps it is too long, too broad, too general, not stating the problem etc...

In your case, I fail to understand what the question actually is, or the problem is either here or on stackoverflow.

You talk about at least 3 differnent topics, without asking any clear question about any of those.

I reckon there is perhaps a bug, (user.existed()) but i fail to see the steps to reproduce, the context, what is expected.

So it’s not likely the tags being the issue, but the way you ask questions.

**Comment by pferder** [comment]
Hi @flovilmart I'm having the same issue.

`Parse.FacebookUtils.logIn().then((user) => {
	console.log(user);
}`

And my user is created with a random username, no firstName, no lastName or email. This is generating many problems.

**Comment by flovilmart** [comment]
You are confusing Facebook login and Parse login, the user variable in your code is the parse user object (Parse.User). If you want to read properties of a Facebook user, refer to the Facebook SDK

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pferder** [comment]
Thanks for the quick response.

You're suggesting that Parte.FacebookUtils.login won't return any Facebook user data?

**Comment by flovilmart** [comment]
> Are you suggesting that Parte.FacebookUtils.login won't return any Facebook user data?

It is not a suggestion, it's how it's implemented, the method only attempts to acquire a facebook access token and perform a login on your Parse API with it.

**Comment by pferder** [comment]
Sorry, I've mixed English with my native language.

So, after the login de should use the FB api to get user data anda then update the saved user with this data? Or is there a Parse method to do this at once?

**Comment by flovilmart** [comment]
There is no method to do it, you need to call the Facebook API’s in order to get info from it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
