### ISSUE TITLE
Current Installation class method is missing

### ISSUE THREAD

**Issue by danielmartinprieto** [parse-community/Parse-SDK-JS#693]
I'm working in a couple of React Native apps so I need to use this SDK also in the client side. In order to handle `Installation`s, we're creating instances of this class manually either on the client or the server, and neither of these seem right; instead, we should be able to use the SDK to ask for the current installation stored in the client and update/save.

Here it's the related code in the iOS SDK: https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/master/Parse/Parse/PFInstallation.h#L52

Is this code missing in the JavaScript SDK for any reason? Should we handle this scenario in any other way I'm not aware of?

**Comment by flovilmart** [comment]
Installation is used solely for push notifications and make sense in a react native environment (as server doesn’t support web push). As you need this feature, would you want to implement it similarly as the current _User?

**Comment by danielmartinprieto** [comment]
I would love to try to do that! Would you mind helping me creating a list of high level tasks in order to accomplish it so I don’t miss anything? I’m not super familiar with the code base.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by flovilmart** [comment]
I wish I could, as I am not the original author of those code based, I would need to refer to the existing implementations on iOS and Android. We can go through it together. There are multiple components:

- persistance (like the User, it always restore)
- unicity (thé installation identifiés a unique installation of an app on a device)
- purpose: the purpose of the installation object is to be able to be targeted by a Push.

From there, we should look into the iOS SDK (or android) depending your comfort level, to infer what we should do. 

@dplewis’s work on the localStorage May also be of help

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
