### ISSUE TITLE
Making a Class and content of it inBack4App

### ISSUE THREAD

**Issue by euxicius** [parse-community/Parse-SDK-JS#694]
I am new to programming and i am a student trying to make a program that saves username and able to log in. I have downloaded the template (https://www.back4app.com/docs/android/login-android-tutorial) and it work well. I have already made a Class inside the Parse Dashboard and able to login and do registers thanks to the layout. But I tried to import the class that i made in back4app but i dont know how I tried using "import com.parse.ParseClass" and It wont work for some reason. Can someone please tell me what do I need to do to make a object inside the class in back4app? and use it in the android studio

**Comment by dplewis** [comment]
You should open this in the Android SDK

**Comment by euxicius** [comment]
How? Isnt Android SDK a like a plugin for gradle?

**Comment by flovilmart** [comment]
This question is not a bug, but rather a question which is better suited to be asked on http://stackoverflow.com

Thanks!
