### ISSUE TITLE
Parse.Query not returning custom subclass 

### ISSUE THREAD

**Issue by yingmu52** [parse-community/Parse-SDK-JS#700]
@flovilmart 

I am trying to use a custom class in `Parse.Query`, but it doesn't seem to work for me, not sure why that is happening. 

```js
class Merchant extends Parse.Object {
	constructor() {
		super('Merchant');
	}
	hello() {
		console.log(`hello!!! ${this.id}`);
	}
}
Parse.Object.registerSubclass('Merchant', Merchant);

async function fetch(): Promise<Merchant[]> {
	try {
		const merchants = await new Parse.Query(Merchant)
			.limit(10)
			.find({ useMasterKey: true });
		return merchants;
	} catch (error) {
		console.error(error);
		return [];
	}
}

fetch().then(merchants => {
	for (const m of merchants) {
		m.hello();
	}
});
```

I am getting this error from `registerSubclass` and `new Parse.Query(Merchant)`
```
TypeError: Class constructor ParseObject cannot be invoked without 'new'
```

I also tried this way with no luck 
```js
	const merchants = await new Parse.Query<Merchant>('Merchant')
			.limit(10)
			.find({ useMasterKey: true });
```

**Comment by flovilmart** [comment]
Can you provide your node version, SDK version, platform and all relevant informations? 

Also `Parse.Query<Merchant>` doesn’t make sense in javascript I believe

**Comment by yingmu52** [comment]
node -v: `v8.9.4`
tsc -v: `Version 3.1.6`

```
  "@types/parse": {
      "version": "2.1.0",
      "resolved": "https://registry.npmjs.org/@types/parse/-/parse-2.1.0.tgz",
      "integrity": "sha512-Wvc1tjgRT83tS9+bIqSnxzjdtYg19dptCgdllMM8ed18+yqcSe9bkNbXGSxnoHs4leQK4l8FtYBXb3PddK7GXw==",
      "requires": {
        "@types/node": "10.12.10"
      }
```

in the database, I have a table called `Merchant` which I subclassed from `Parse.Object` and I am trying to see if `Parse.Query` could return the custom subclass objects.

**Comment by flovilmart** [comment]
We do not offer direct support for typescript, is it working with pure javascript or not?

**Comment by dplewis** [comment]
const merchants = await new Parse.Query(Merchant)
			.limit(10)
			.find({ useMasterKey: true });

Try

const merchants = await (new Parse.Query(Merchant))
			.limit(10)
			.find({ useMasterKey: true });

Please post logs VERBOSE=1.

Did you receive any errors?

**Comment by yingmu52** [comment]
> We do not offer direct support for typescript, is it working with pure javascript or not?

It does.

**Comment by yingmu52** [comment]
> ```
> const merchants = await new Parse.Query(Merchant)
> 			.limit(10)
> 			.find({ useMasterKey: true });
> ```
> Try
> 
> ```
> const merchants = await (new Parse.Query(Merchant))
> 			.limit(10)
> 			.find({ useMasterKey: true });
> ```
> Please post logs VERBOSE=1.
> 
> Did you receive any errors?

same error. 
```
TypeError: Class constructor ParseObject cannot be invoked without 'new'
    at new Merchant (/Users/xinyi/Desktop/ts/greeter.js:58:23)
    at Function.fromJSON (/Users/xinyi/Desktop/ts/node_modules/parse/lib/node/ParseObject.js:1800:27)
    at response.results.map.data (/Users/xinyi/Desktop/ts/node_modules/parse/lib/node/ParseQuery.js:556:37)
    at Array.map (<anonymous>)
    at controller.find.then.response (/Users/xinyi/Desktop/ts/node_modules/parse/lib/node/ParseQuery.js:540:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Tonys-MBP:ts xinyi$
```

I don't think adding `()` around `new Parse.Query(Merchant)` matter, it works for pure js

**Comment by flovilmart** [comment]
So this is while tranpiling from typescript. You should make sure your settings in typescript do not erase the classes.

From now on, this is not an issue with this SDK, but with the typescript configuration IIUC as it works in node.js.
