### ISSUE TITLE
Parse.User.logIn says Invalid username/password from Cloud Code

### ISSUE THREAD

**Issue by step4** [parse-community/Parse-SDK-JS#706]
I have set up a Parse server accordingly and created a user with username "jon" and password "doe".
When I try to login from a browser with
```
const user = await Parse.User.logIn("jon","doe")
```
everything works fine and I get a ParseUser as a result.

For future SAML SSO reasons I want to try logging in via Cloud Code so I tried this simple example:
```
Parse.Cloud.define("user_login", async (request) => {
  const user = await Parse.User.logIn("jon", "doe")
  return user
})
```

now when I run
```
const u = await Parse.Cloud.run("user_login")
```
I get the error `Uncaught (in promise) Error: Invalid username/password. ParseError: Invalid username/password.`

I also tried the API Console from the Dashboard with a POST request to functions/user_login with the error
```
{
    "code": 101,
    "error": "Invalid username/password."
}
```

Maybe it is related to #189

**Comment by step4** [comment]
After hours of searching I found the root of the error.
In fact I create to API endpoints in my express app:
```
var api = new ParseServer({
  appId: "SocialCapital",
  masterKey: "socialcapitaldevelop",
  serverURL: `https://localhost/parse`,
  databaseURI: "mongodb://localhost/socialcapital",
  cloud: __dirname + "/cloud/main.js"
});
var api2 = new ParseServer({
  appId: "StudyQuiz",
  masterKey: "studyquizdevelop",
  serverURL: `https://localhost/parse2`,
  databaseURI: "mongodb://localhost/studygraph",
  allowClientClassCreation: false,
  enableAnonymousUsers: false
});
```

It turns out that the Cloud Code for my first api sends it request to the second api2.
Unfortunately I am not very good at backend development, but I had a quick look at the ParseServer class and found that at the beginning it requires:
```
Parse = require('parse/node').Parse,
```

and in line 87 [ref](https://github.com/parse-community/parse-server/blob/master/src/ParseServer.js#L87) the serverURL is set.

so maybe it is a problem with a 'static'-ish parse sdk node client?

A workaround is to just have one API created with new ParseServer.
Or maybe I didn't read a part in the docs and shouldn't create two API's in the beginning 😄

**Comment by flovilmart** [comment]
Parse server does not support running 2 instances within the same runtime, because of the state of the JS SDK.
