### ISSUE TITLE
Session token not removed on browser close...

### ISSUE THREAD

**Issue by LilMoke** [parse-community/Parse-SDK-JS#708]
Hello,

I am using the Parse SDK for JS and notice that when I bring up a log in page and the user logs in with their username and password I can then access my parse db objects.  I also notice a session object is created in the DB.

However, when the user closes the browser and launches it again they still have access to all objects.  The do not need to log in again.

Why doesn't the session go away when the user closes the browser?

**Comment by dplewis** [comment]
That is the main purpose of session / local storage, they last forever unless you clear them. 

Closing as this isn't an issue.

**Comment by LilMoke** [comment]
So wait, one last question... is there a way to tell parse server to not remember the session.  I do see that the info seems to be stored in window.localStorage.

Ideally, wouldn't a user want the web page to prompt for log in every time it is launched, unless specifically told to remember it?

**Comment by LilMoke** [comment]
Lol, ahh, duh!!   Great, thank you!!

**Comment by flovilmart** [comment]
Or you could make sessions that simply last a very short time, or pass the session token manually to all your calls. No need to login in cloud code
