### ISSUE TITLE
Why the aggregate $in operation requires a pointer prefix?

### ISSUE THREAD

**Issue by liangminhua** [parse-community/Parse-SDK-JS#711]
``` javascript
  const pipeline = [{
       match: {
         'electricMeter': {
           $in: [
             'ElectricMeter$VphyBPDp14', 'ElectricMeter$mbyIGbiDKE',
             'ElectricMeter$ax1XDXwzBn'
           ]
         }
       }
     },
  ];
```
If remove the pointer prefix, result is empty.
``` javascript
const pipeline=[{
      match: {
        $or: [
          {electricMeter: 'VphyBPDp14'},
          {electricMeter: 'mbyIGbiDKE'}, {electricMeter: 'ax1XDXwzBn'}
        ]
      }
    }];
```
But use $or operation work fine.

**Comment by dplewis** [comment]
I can give it a look

**Comment by dplewis** [comment]
Looking at the source code you'll find your answer

https://github.com/parse-community/parse-server/blob/de92ce5c49c178cebbc046b4c09cf0f22dc5940e/src/Adapters/Storage/Mongo/MongoStorageAdapter.js#L825-L834

In your $or example you have { field: value }. If we have the field we can tell its a pointer and transform the value.

In your $in example the field name is at the top level. { field: { operator: array of values } }.

Feel free to open a PR or keep the working solution you have
