### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jlnquere** [parse-community/Parse-SDK-JS#715]
Hi there, 

Since 9/08 (date of the 2.1.0 release), a lot of good stuff and fixes has been added to Parse JS SDK. I think that would be a good moment to publish a new release. So we will be able to enjoy theses stuff in production. 

What do you think about that ?

**Comment by jlnquere** [comment]
UP ? Is there something we can do to help on this ? 

It will allow us to access to all the good work (and fixes) made since last release in September.

**Comment by flovilmart** [comment]
cc @natanrolnik @dplewis

**Comment by dplewis** [comment]
A new release would be awesome. I can help close out the opened PR's

**Comment by jlnquere** [comment]
Awesome! Thanks 🎉
