### ISSUE TITLE
query.limit with ascending createdAt Issue

### ISSUE THREAD

**Issue by MMSSolutions** [parse-community/Parse-SDK-JS#724]
The following code I would presume I would receive the last 20 entries in the MainLog class sorted by createdAt, most recent at the top. But what I actually receive is the first 20 entries in MainLog sorted by createdAt.

This code works fine in iOS and Android but my issue is with Web Javascript, is there a bug or am I doing something wrong?

`const query = new Parse.Query("MainLog");`
`query.ascending("createdAt");`
`query.limit(20); `
`const results = await query.find(MASTER_KEY);`

**Comment by flovilmart** [comment]
Ascending dates go from the oldest to the newest, because time increases. So most recent dates have a higher value than dates in the past. You should use descending. And no, this should not work either on IOS or Android 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
