### ISSUE TITLE
Setting authResponse is not supported

### ISSUE THREAD

**Issue by durunvo** [parse-community/Parse-SDK-JS#726]
Hi, I wonder if anyone else face this issue when try to login with facebook?
Also happens when trying to login with email/password for facebook authenticated users.

The `/login` request was succeed. It returns status code 200 with users data.
However, the javascript sdk rejects the request and returns an error. `Setting authResponse is not supported`

I have tested in js version 2.0.2.

**Comment by durunvo** [comment]
Found out that this is an error from Facebook sdk.

**Comment by durunvo** [comment]
For more information, I have comment out `Parse.FacebookUtils.init` and the problem is gone.

**Comment by durunvo** [comment]
This is weird but problem seems to be a conflict between Parse.FacebookUtils and Facebook official sdk.

Please see this line of code from unminified js.

https://github.com/nfriedly/facebook-js-sdk/blob/cd1f144d334e7e200b2ba6c7ca0e51636063a9b6/debug.js#L14268

It checks for `authResponse` and returns an error.

Please also look at this line of code of this project.

https://github.com/parse-community/Parse-SDK-JS/blob/8e0f00c5a3dd6043718fec1af1ddc1106058d5e1/src/FacebookUtils.js#L61

`authResponse ` is assigned to an option intentionally.

---

I solve this by change the facebook sdk url from `//connect.facebook.net/en_US/sdk.js` to `//connect.facebook.net/en_US/all.js`

The different is `sdk.js` and `all.js`

So maybe somebody can look into this issue, Thanks~

**Comment by schurch** [comment]
I'm also seeing this issue.

**Comment by Jauny** [comment]
Same for me, started to see this, our facebook login is broken because of this.

**Comment by flovilmart** [comment]
The PR don’t add any test and the resolution doesn’t match with what was described (changing the SDK URL). So That’s what I’d least expect. Cc @dplewis, can you then review, merge and release please?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RadianSmile** [comment]
> I solve this by change the facebook sdk url from `//connect.facebook.net/en_US/sdk.js` to `//connect.facebook.net/en_US/all.js`

this works for me

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/728
