### ISSUE TITLE
Is it possible to update an array at a specific index? 

### ISSUE THREAD

**Issue by farhansyed9** [parse-community/Parse-SDK-JS#732]
I went through the docs to see if theres a way to update an existing array at a specific index, can't seem to find anything on it. Wondering if it's possible I missed something?

**Comment by dannywolfmx** [comment]
Sorry for my bad english.

Maybe i am wrong, but i think this functionality is not already implemented in the sdk.

The Parse sdk js is pretty similar to the backbone.js style.

when you want to update your array you need something like this
```JAVASCRIPT
var superheros= new Parse.Object("SuperHero");

var superList = list.get("list");

//superList === ["Superman","IronMan"];

//to update the list:

//Set the new super
superList[0] = "BatMan";

//Set the list with the changes
superheros.set("list",superList)

//Save the changes
superheros.save();

This will send the whole array to the server, not just the index that you changed
```
Now, if your Array is a list of pointers you just need to update the referenced object.

Maybe the backbone style is not the best today, but we are a community and we can change this if we want

**Comment by dplewis** [comment]
From a quick glance, I believe this can be done on the server side as a new feature.

Mongo has [$ positional operator](https://docs.mongodb.com/manual/reference/operator/update/positional/?_ga=1.12567092.1864968360.1429722620#up._S_)
Postgres has [element[index]](https://www.postgresql.org/docs/9.5/arrays.html)

**Comment by dplewis** [comment]
Opened a feature request https://github.com/parse-community/parse-server/issues/5440
