### ISSUE TITLE
Cannot create a pointer to an unsaved Object issue.

### ISSUE THREAD

**Issue by Code-Crash** [parse-community/Parse-SDK-JS#736]
Hi Team,

I'm using 1.4.2 and I have this feature (save an unsaved Parse object and assign to parent Parse Object), I know its too late to upgrade the library, and I have recently started upgrading the Parse JS SDK to 2.1.0 and now I'm facing this issue in my existing code base.

I have already gone through the StackOverflow, and issue list but not found any specific solution.

So, Is there any way to allow unsaved Parse Object to save as old version was already doing that?

Can I do something which disabled this error?

I can see there is a function in SDK (unsavedChildren) and it gets the param (namely allowDeepUnsaved), is there is any way to disable this and allow deep save parse object?

Thanks.

**Comment by Code-Crash** [comment]
For now, I did some hack, like overridden the `allowDeepUnsaved` in unsavedChildren() in `parse-2.1.0.js`.

`allowDeepUnsaved = true;`

It will be great if we can make it more configuration, like when we do initialize the JS SDK.

`Parse.initialize(<ApplicationID>, <JavascriptKey>);`

Or this is already there with some changes?
Please let me know.
Thanks

**Comment by dplewis** [comment]
allowDeepUnsaved is true [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseObject.js#L2101)

Try to use `Parse.Object.saveAll()` with both / all objects.

**Comment by Code-Crash** [comment]
@dplewis Thanks for the response, 

Are you suggesting, I can add `allowDeepUnsaved = true` in save() function below [here](https://github.com/parse-community/Parse-SDK-JS/blob/ecdadbcd987ef8db27387e841701068588ad0f2d/src/ParseObject.js#L2103) ?

Also, where I can put in the parse server on node js module, any idea? 
Because I'm facing the same issue on the server end.

Thanks.

**Comment by dplewis** [comment]
I was suggesting that the feature you want already exists.

You can try to write a failing test using saveAll.
