### ISSUE TITLE
Unable to Connect to Parse 2.2

### ISSUE THREAD

**Issue by grantespo** [parse-community/Parse-SDK-JS#737]
I have to use: `<script type="text/javascript" src="http://npmcdn.com/parse@2.0.0/dist/parse.min.js"></script>`

Instead of: `<script type="text/javascript" src="https://npmcdn.com/parse/dist/parse.min.js"></script>`

**Comment by dplewis** [comment]
A `2.2.1` release came out. Please try it out.

Also its best practice to specify version of your dependencies.
