### ISSUE TITLE
@type/parse mismatch

### ISSUE THREAD

**Issue by howardwkim** [parse-community/Parse-SDK-JS#745]
Using `parse@2.1.1`.

Trying to use `Parse.enableLocalDatastore()`, but there is no definition for `enableLocalDatastore`.

When I look at the `package.json` from `Library/Caches/typescript/3.3/node_modules/@types/parse`, I see `"_from": "@types/parse@2.1.1"`.

The `index.d.ts` file has `Type definitions for parse 2.1.0` in the comments. No sign of `enableLocalDatastore`. 

Should that definition be included in `index.d.ts` file?

**Comment by dplewis** [comment]
Duplicate: https://github.com/parse-community/Parse-SDK-JS/issues/528

**Comment by dplewis** [comment]
I opened a PR to address this https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33981

**Comment by dplewis** [comment]
Closing via https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33981
