### ISSUE TITLE
JSON.parse() error on Object.destroy()

### ISSUE THREAD

**Issue by howardwkim** [parse-community/Parse-SDK-JS#747]
parse@2.2.1
react-native@0.58.6

When I call `.destroy()`, I receive `SyntaxError: Unexpected token b in JSON at position 0`.
The object is destroyed on the server and the app still functions as expected, but I keep getting the error.

The error comes from a `JSON.parse()` located at `parse/lib/react-native/LocalDatastoreController.react-native.js:65`.
The key for `Parse/MY-PARSE-APP-ID/installationId` returns a string without curly brackets (like  `b94c0ed9-4a24-49af-b57b-d48e6a230db1` ).
 
Is this a bug in the code? Am I setting something incorrectly? Thanks!

Some of my code for setting up Parse:
```
import Parse from 'parse/react-native';
import { AsyncStorage } from 'react-native';
...

Parse.setAsyncStorage(AsyncStorage);
```

**Comment by vrazn** [comment]
Getting the same error when calling `Parse.dumpLocalDatastore()`.
It looks like `async getAllContents()` also gets my Redux data stored in the Async storage when calls `const keys = await RNStorage.getAllKeys();` and fails to parse them later.

**Comment by dplewis** [comment]
Thanks for reporting. Can you guys debug and submit a PR?
