### ISSUE TITLE
Query broken on release build for react native

### ISSUE THREAD

**Issue by moulie415** [parse-community/Parse-SDK-JS#748]
I have a query that I'm works on android/ios on debug builds but is returning an empty array on release builds, when I log out the query I can see the issue cause the className is completely wrong but I have no idea why here's the debug query log vs the release query log

```
{ className: 'UserDailyPoints',
      _where: { userId: { __type: 'Pointer', className: '_User', objectId: 'nJAUO1Ho6o' } },
      _include: [],
      _limit: 7,
      _skip: 0,
      _queriesLocalDatastore: false,
      _localDatastorePinName: null,
      _extraOptions: {},
      _order: [ '-timestamp' ] }

{ className: 'h',
      _where: { userId: { __type: 'Pointer', className: '_User', objectId: 'nJAUO1Ho6o' } },
      _include: [],
      _limit: 7,
      _skip: 0,
      _queriesLocalDatastore: false,
      _localDatastorePinName: null,
      _extraOptions: {},
      _order: [ '-timestamp' ] }
```

**Comment by moulie415** [comment]
The problem seemed to be caused by the way I was registering sublclasses, I think I needed to register them individually, not sure if this is a TypeScript issue or not

```
ParseModels.forEach(model => {
      Parse.Object.registerSubclass<Parse.Object>(model.name, model)
})
```

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/issues/700#issuecomment-442663424
