### ISSUE TITLE
 Documentation incorrectly describes Twitter login as supported by the SDK.

### ISSUE THREAD

**Issue by bezi** [parse-community/Parse-SDK-JS#771]
### Issue Description
Documentation incorrectly describes Twitter login as supported by the SDK.

Issue confirming it doesn't in this repo: https://github.com/parse-community/Parse-SDK-JS/issues/138

Documentation: https://docs.parseplatform.org/js/guide/#twitter-authdata

### Steps to reproduce

Go to documentation, see that Twitter is described as a log in option.
Check out repository, see that there is no code for Twitter (specifically that `_registerAuthenticationProvider` is only called for Facebook and Anonymous).

### Expected Results
Twitter is supported. (To be clear, I mostly just want the documentation cleaned up, not calling for Twitter login to be supported).

### Actual Outcome
Twitter is not supported.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : ^3.2.1
  - Operating System:     N/A
  - Hardware:             N/A
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): N/A

- **JS SDK**
  - JS SDK version: ^2.3.1
  - Application? (Browser, Node, React-Native, etc): Browser

### Logs/Trace
```
TypeError: provider.getAuthType is not a function
    at ParseUser.value (ParseUser.js:138)
    at _callee$ (index.js:25)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:282)
    at Generator.prototype.(:3000/anonymous function) [as next] (http://localhost:3000/static/js/1.chunk.js:1302:21)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at processAuth (index.js:22)
    at setAuthState (GoogleAuth.js:34)
    at GoogleAuth.js:90
    at cb=gapi.loaded_0:236
    at h.r2 (cb=gapi.loaded_0:120)
    at xs (cb=gapi.loaded_0:123)
    at Wq (cb=gapi.loaded_0:123)
    at _.C.uea (cb=gapi.loaded_0:123)
    at Ap (cb=gapi.loaded_0:115)
```

**Comment by dplewis** [comment]
Looks like the JS Docs is an example for `_linkWith` with Twitter.

**Comment by dplewis** [comment]
@bezi @acinader I created a [branch](https://github.com/parse-community/Parse-SDK-JS/compare/link-twitter?expand=1) to play around with linking with twitter and got it working.

1. I didn't know server configuration was required (not documented). I assumed it worked out of the box.
2.Multiple server configuration (not documented).

I think we should register a basic auth provider internally if it doesn't exist.

And document `Parse.User._registerAuthenticationProvider()` for advanced API.

```
const authProvider = {
   restoreAuthentication() {
     return true;
   },

  getAuthType() {
    return 'twitter';
  },
};
```

What do you guys think?

**Comment by acinader** [comment]
@dplewis this sounds great.

if you can fix it up so twitter works out of the box, it would be a nice improvement!

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/docs/pull/615 and https://github.com/parse-community/Parse-SDK-JS/pull/810 You no longer need to worry about Registering Auth Providers.
