### ISSUE TITLE
Object from Parse in LocalDatastore with the local id doesn't update when I execute the pin function again

### ISSUE THREAD

**Issue by natalio** [parse-community/Parse-SDK-JS#792]
### Issue Description
I did a search in local Datastore for an object with the local id and try to update one of its attributes, but instead of customizing it it adds a new object in the localDatastore when I execute the pin function again.

### Steps to reproduce
```javascript
const query = new Parse.Query("Todos");
query.fromLocalDatastore();
let todos = await query.find()
for(let i=0; todos.length;i++){
  if(todos[i].get("done") == false){
   todos[i].set("done", true);
   todos[i].pin();
  }
}
```

### Environment Setup

- **Server**
  - parse-server version  : 3.2.3
  - Operating System:     Linux/Ubuntu
  - Localhost or remote server? : Localhost

- **JS SDK**
  - JS SDK version: 2.3.2
  - Application?: React-Native

**Comment by dplewis** [comment]
I think I see what you are trying to do.

Can you write a failing test [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/integration/test/ParseLocalDatastoreTest.js#L71)?

**Comment by natalio** [comment]
When saved, don't save attributes 
```
const query = new Parse.Query("Todos");
query.fromLocalDatastore();
let todos = await query.find()
for(let i=0; todos.length;i++){
  if(todos[i].get("done") == false){
   todos[i].set("done", true);
   todos[i].set("foo", true);
   todos[i].pin();
  }
}
```
