### ISSUE TITLE
Want to support Wechat applet

### ISSUE THREAD

**Issue by einsqing** [parse-community/Parse-SDK-JS#793]
Want to support Wechat applet !!!
doc https://developers.weixin.qq.com/miniprogram/en/dev/index.html?t=19041222

**Comment by dplewis** [comment]
Duplicate https://github.com/parse-community/Parse-SDK-JS/issues/530

Have you read the guide [Supported 3rd Party Authentication](http://docs.parseplatform.org/parse-server/guide/#supported-3rd-party-authentications)? If it is unclear please let us know.

```
const user = await new Parse.User()._linkWith('wechat', {
  authData: {
    id: '',
    access_token: '' // get your own access token
  }
});
```

**Comment by einsqing** [comment]
@dplewis Not this one，Read the document, please https://developers.weixin.qq.com/miniprogram/en/dev/index.html?t=19041222。

The reference for sending requests from the Wechat miniprogram is as follows: XHR cannot be used。
```
wx.request({
  url: 'test.php', // 仅为示例，并非真实的接口地址
  data: {
    x: '',
    y: ''
  },
  header: {
    'content-type': 'application/json' // 默认值
  },
  success(res) {
    console.log(res.data)
  }
})
```

**Comment by einsqing** [comment]
@dplewis Need to adapt localStorage and request

**Comment by dplewis** [comment]
When you say support are you referring to linking with / authentication? I can try to look into that and write a test

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/874
