### ISSUE TITLE
pinAllWithName fails when saving User objects

### ISSUE THREAD

**Issue by vlad-fylp** [parse-community/Parse-SDK-JS#796]
### Issue Description
When running Parse Query on User objects and trying to pin them with name, the following error is thrown:
```
TypeError: Cannot read property '__type' of undefined at Object._getChildren
```

It looks like it tries to access the `__type` property of User's `sessionToken` in `LocalDatastore.js -> _getChildren` and throws the error because `sessionToken` is undefined.

### Steps to reproduce
```javascript
const users = await new Parse.Query('User').find();
await Parse.Object.pinAllWithName('users', users);
```

### Expected Results

Objects should be saved successfully and be available using the specified pin name.

### Actual Outcome

An Error is being thrown.

### Environment Setup

- **Server**
  - parse-server version 3.2.3
  - AWS hosted server

- **JS SDK**
  - JS SDK version: 2.3.2
  - React native 0.59.4

**Comment by vlad-fylp** [comment]
Also, looks like calling `unPinAllObjectsWithName` does not actually delete any objects from the local datastore, but it does delete the pin though.
So the only way to remove objects from the storage is to get all of them first and then call `unPinAllWithName`. Is that an expected behavior?

**Comment by dplewis** [comment]
@vlad-fylp It would remove the object automatically once its removed from all pin names. 

`unPinAll` will remove the object since it doesn't specify a pin name.

**Comment by dplewis** [comment]
Thanks for reporting. I'll submit a PR soon. I also a separate issue too.
