### ISSUE TITLE
Can't get Parse JS SDK Working with Node.js

### ISSUE THREAD

**Issue by gateway** [parse-community/Parse-SDK-JS#797]
### Steps to reproduce
Can't seem to get parse to work on a simple node.js app.  Following this guide and then adding the parse npm package along with initializing throws a error on missing module uuid/v4

Simple express app with ejs templates just was testing to pull in parse.

https://medium.com/@bhanushali.mahesh3/creating-a-simple-website-with-node-js-express-and-ejs-view-engine-856382a4578f

### Environment Setup

- **Server**
  - parse-server version (2.8.4'.) 
  - Operating System:     OSX
  - Hardware:             macbook pro
  - Localhost or remote server? localhost

- **JS SDK**
  - JS SDK version: 2.3.2
  - Application? (Browser, Node, React-Native, etc): Node Version 10.15.3

### Logs/Trace

Part of the top of the code for app.js

```
var createError = require('http-errors');
var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var logger = require('morgan');
var uuid = require('uuid-v4');
var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');

const Parse = require('parse/node');
Parse.initialize('our app id')
//javascriptKey is required only if you have it on server.

Parse.serverURL = 'ourserverurl'
//Parse.User.enableUnsafeCurrentUser();

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');
```
parse is installed in the node_modules section as well as uuid-4 package.

```
atewaysmacpro:mywebsite gateway$ node app.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'uuid/v4'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/gateway/Documents/Web Development/node-js/templates/mywebsite/node_modules/parse/lib/node/AnonymousUtils.js:27:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
gatewaysmacpro:mywebsite gateway$ node -v
v10.15.3```

this is the error.

If I comment out parse section it all works fine.

Any ideas?
<!--- Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment. --->

**Comment by gateway** [comment]
resolved.. installed uuid and added const uuidv4 = require('uuid/v4'); 

I also deleted package-lock.json and removed the node_modules then ran npm install to get them again.

**Comment by jlnquere** [comment]
I think this issue should be reopened. 

I have the same issue, and had to install `uuid` package in my project. 

Since this update: https://github.com/parse-community/Parse-SDK-JS/pull/750/files/0e989595ea7a52f08c732f0701e8a4abcb2a61ad#diff-eb5301eb626ada590014b10c10f01c70 , Parse uses `uuid` package. But it has not been added as Parse SDK dependencies. 

I think `uuid` should be added to the `package.json`. Or maybe I've missed something ...

**Comment by jlnquere** [comment]
@gateway could you reopen it ?

**Comment by acinader** [comment]
@dplewis

**Comment by acinader** [comment]
@dplewis odd that tests don't trip this?

**Comment by dplewis** [comment]
A Dev-Dependency must use that uuid module

**Comment by gateway** [comment]
Thanks guys for updating this!
