### ISSUE TITLE
Parse.Object.saveAll error handling

### ISSUE THREAD

**Issue by foobar8675** [parse-community/Parse-SDK-JS#799]
**Is your feature request related to a problem? Please describe.**
When doing `await Parse.Object.saveAll(objectsToUpdate, { useMasterKey: true });` if it fails I don’t know which `objectToUpdate` failed.

**Describe the solution you'd like**
An error telling me which object failed. That would allow me to write some code to properly handle the error.

**Comment by dplewis** [comment]
Can you post logs? Running server with VERBOSE=1

**Comment by foobar8675** [comment]
thanks for writing back @dplewis . I've always been a bit challenged when it came to the logs. I have the VERBOSE=1 set in my .env but never have seen verbose logs written out to the console.

i have a snippet here to recreate the issue
```
  try {
    ideas[1].id = "abc"
    const updatedIdeas = await Parse.Object.saveAll(ideas, { useMasterKey: true });
    return { updatedIdeas };
  } catch (e) {
    throw e;
  }
```
where the exception looks like

```
[[StableObjectId]]:8
code:101
message:"Object not found."
stack:"Error: Object not found.\n    at batchReturned.then (/Users/mattc/Documents/DecorMatters/dm_server/Server/node_modules/parse-server/node_modules/parse/lib/node/ParseObject.js:2299:35)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
__proto__:Error {constructor: , toString: }

```

is it possible to let me know the `1` index is the one that failed?

**Comment by dplewis** [comment]
@foobar8675 Look at the [test suite](https://github.com/parse-community/Parse-SDK-JS/blob/master/integration/server.js#L26) for logging example

**Comment by foobar8675** [comment]
got it. i re-ran and here is what i see in the logs. was thinking it would be nice if we knew which object was causing the error.

```
{"functionName":"deleteIdeas2","error":{"message":"Object not found.","code":101},"params":{"objectIds":["u9mm18znMo","VlxBdBCfPN"]},"user":"v5qg9E6sM3","level":"error","message":"Failed running cloud function deleteIdeas2 for user v5qg9E6sM3 with:\n  Input: {\"objectIds\":[\"u9mm18znMo\",\"VlxBdBCfPN\"]}\n  Error: {\"message\":\"Object not found.\",\"code\":101}","timestamp":"2019-04-25T18:02:33.606Z"}
{"message":"Object not found.","stack":"Error: Object not found.\n    at batchReturned.then (/Users/mattc/Documents/DecorMatters/dm_server/Server/node_modules/parse-server/node_modules/parse/lib/node/ParseObject.js:2299:35)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","code":101,"level":"error","timestamp":"2019-04-25T18:02:33.609Z"}

```

**Comment by dplewis** [comment]
Saving them individually will tell you which one is not found.

I don't think there is a way to tell which one is missing with saveAll. If you want to try look [here](https://github.com/parse-community/parse-server/blob/d83a0b680854f52ce30205d3558c0133d7f8cf19/src/Controllers/DatabaseController.js#L577)
