### ISSUE TITLE
How do you handle session with a custom node.js express app? Redis?

### ISSUE THREAD

**Issue by gateway** [parse-community/Parse-SDK-JS#804]
Hi, we have been in the process of building out our custom node.js express app with ejs as our template engine.  I know node.js is stateless and its been very hard to find how to properly deal with the user session once logged in.  

For example in PHP you have a $_SESSION variable that has all the parse data and during the whole session until the user logs out or the session expires (we store session data in redis to allow for scalability) we can make proper queries to the db without having to use Parse.User.become(SESSION) for each call in our node.js app

Right now we are storing the Parse Session into a cookie on the client, and then using that cookie to run the functions we need with Parse.  However this doesn't seem very secure to me, its almost like having a cookie with someones user name and password.

How do people handle this type of situation?

I have been looking at express-sessions, with redis which I hope I could store the parse session key and any other data I want onto redis and use the sesssion express-sessiosn creates and hit redis to get the data I need.  However this still leads to do I need to always run this type of code when I get the data back.

```
/* GET home page. */
router.get('/main', async function(req, res) {
   // prob should do a check if id empty or not.
  var id = req.query.id;
  // get cookie 
  const cookie = req.cookies['cooky'];
  // check if cookie exists, in some cases removing a cookie
  // still allows the session to continue.
  if (cookie === undefined) {
    return res.redirect('/');
  }
  // lets call the function to get the orgs 
  try {
    await Parse.User.become(cookie)
    console.log(req.headers);
    //TODO Run some parse query functions return data and return something to the route.
  } catch (error) {
      res.redirect('/');
  }

  res.render('home', {page:'Main Home Page', menuId:'home', id : id, list: list});
});
```

I'm coming from the PHP side of things where once the user was logged in magic happened and all the queries that the user could do would just happen.

Just looking for advice or directions to see whats possible.

**Comment by davimacedo** [comment]
I'd use express-session to store the session token but you should not use Parse.User.become in the server side. Instead, you should use sessionToken option in each operation. For example:

To run a cloud function:
Parse.Cloud.run('functionname', inputparams, { sessionToken: yoursessiontoken });

To save an object:
object.save(null, { sessionToken: yoursessiontoken });

To run a query:
query.find({ sessionToken: yoursessiontoken }).then(...);

**Comment by gateway** [comment]
> I'd use express-session to store the session token but you should not use Parse.User.become in the server side. Instead, you should use sessionToken option in each operation. For example:

What the issue or why should we not use Parse Become on the server side? Just curious.. We are still trying to wrap our head around the best way to handle users and also make sure it scales.  If we store various data about the user in redis with the session token your suggestions every query that the user should do should use the token instead?

**Comment by davimacedo** [comment]
Imagine you have the following code:

```
app.post('/someroute', (req, res) => {
  Parse.User.become(req.sessionToken); // Line A
  Parse.Cloud.run('somefunction'); // Line B
});
```

This is not an atomic operation and you will suffer with concurrent requests. Imagine two requests from two different users at this route at the same time. It can occur:
1) Request 1 runs line A
2) Request 2 runs line A
3) Server responds line A for request 1 and Parse SDK becomes user 1
4) Server responds line A for request 2 and Parse SDK becomes user 2
5) Request 1 runs line B as user 2
6) Request 2 runs line B as user 2

This is actually the same reason why you should not use Parse.User.become() at a cloud code function.

You definitively need to pass the session token at each request. But you can do a cache in Redis to save some user data in your server and reduce the amount of requests you send to the Parse API.

**Comment by gateway** [comment]
Ok, I think I'm following.  We are not really doing any cloud code calling .. but things like this..

1. Request 1 hits the route and lets say it pulls in a list of comments.

are you saying if 2 different people hit that route and we use Become that User B could get Users A comments?

**Comment by davimacedo** [comment]
Yes. It can happen.

**Comment by gateway** [comment]
> Yes. It can happen.

Ok thanks, it does make sense, just need to use token in the calls.  I want to use Redis to store that and use the express-sessions session id to pull the token from the redis storage.  Any issues you see with that?

**Comment by davimacedo** [comment]
I think you are fine using the approach.
