### ISSUE TITLE
In Parse Unable to query each nested relation on a single call.

### ISSUE THREAD

**Issue by gotyet9** [parse-community/Parse-SDK-JS#807]
I am currently working with parse in react native. I have a query that fetches data from a collection which has a property with relation to other collection. Now I want to fetch all these relational data in a single call rather than calling each relation separately.

Currently, I get one collection then get its relational data separately in a new call.

```
const data1 = await result
      .get("data1")
      .query()
      .descending("createdAt")
      .find();
const data2 = data1.relation("test");
const data3 = await data2.query().find();
```

Now I want to fetch the relational data along with the data1 in the very first call.

I would like to know is it even possible in parse. If yes how? I have been trying to fetch relational data all day but no success. Any help would really be appreciated.

**Comment by davimacedo** [comment]
Have you tried the include method? Please take a look in this section here:
https://docs.parseplatform.org/js/guide/#relational-queries

**Comment by gotyet9** [comment]
yes @davimacedo i have already tried that. Both include and dot notation options.

**Comment by dplewis** [comment]
The github issues are for bugs and feature requests.

If you would like help, [StackOverflow[(https://stackoverflow.com/questions/tagged/parse-javascript-sdk) is a good resource.

Also include a [test case](https://github.com/parse-community/Parse-SDK-JS/blob/master/CONTRIBUTING.md) as a code level example.

You could probably use `containedIn` with a custom mapper.
