### ISSUE TITLE
Mistakes in JSDocs

### ISSUE THREAD

**Issue by yagotome** [parse-community/Parse-SDK-JS#830]
### Issue Description

There are some mistakes in JSDocs. These are some examples I've seen:

The following `override` param is optional.
https://github.com/parse-community/Parse-SDK-JS/blob/f38f88242f68c18f7f4ed81be045a9fd011388c9/src/ParseObject.js#L1602

The following return value type is `ParseObject | boolean`.
https://github.com/parse-community/Parse-SDK-JS/blob/f38f88242f68c18f7f4ed81be045a9fd011388c9/src/ParseObject.js#L627

**Comment by dplewis** [comment]
Would you like to open a PR for fix this?

**Comment by yagotome** [comment]
@dplewis For sure! I'll open a PR fixing that as soon as I can.
