### ISSUE TITLE
Parse.FacebookUtils.logIn() always have existed() true

### ISSUE THREAD

**Issue by fatbattk** [parse-community/Parse-SDK-JS#831]
### Issue Description

New Facebook account signups are always set as an existing users. Hence there is no way to differentiate a new sign up vs a returning log in.

http://docs.parseplatform.org/js/guide/#login--signup

### Steps to reproduce

```
Parse.FacebookUtils.logIn("email").then(function(user) {
  console.log(user.existed());  // always returns true.
});
```
- log in as a new Facebook user.
- check console logs.

### Expected Results

returns `false` when new Parse user.
returns `true` when existing Parse user.

### Actual Outcome

returns `true` on both cases.

### Environment Setup

- **JS SDK**
  - JS SDK version: 2.4.0
  - Application? (Browser, Node, React-Native, etc): Browser

**Comment by dplewis** [comment]
Thanks for reporting. Would you like to submit a PR to address this issue?

**Comment by fatbattk** [comment]
Finally had some time to dive into this and found the problem.

`ParseObject._handleSaveResponse()` never gets any `status` because
`RESTController.request()` returns `response` only.
https://github.com/parse-community/Parse-SDK-JS/blob/2.4.0/src/RESTController.js#L259

Had to modify a `ParseUser` unit test because a new option was introduced as part of fix while not affecting other unit tests too much.
