### ISSUE TITLE
Stateless user controller for server-side user handling

### ISSUE THREAD

**Issue by yagotome** [parse-community/Parse-SDK-JS#833]
**Is your feature request related to a problem? Please describe.**
Yes. I am using this SDK on a NodeJS app which is an API Gateway that handles multiple user sessions in a stateless way (server side). Therefore, it would be nice if the SDK provided a stateless `UserController`, however the `UserController` seems to have been designed to be used in client side handling single user session.

**Describe the solution you'd like**
Methods related to `currentUser` shouldn't be part of a general `UserController`. Methods like `logout` should receive `sessionToken` as parameters. Perhaps `DefaultController` should be chosen according to platform (browser or node).

**Describe alternatives you've considered**
It is also possible to have at least another kind of User Controller. What do you think?

**Additional context**
- _UserController_:
https://github.com/parse-community/Parse-SDK-JS/blob/05e8c79e17c8d7f30280303c41848dcd15b6d5cb/src/CoreManager.js#L116-L130

- _DefaultController_:
https://github.com/parse-community/Parse-SDK-JS/blob/d4eb736ce9ab6cc2fd3c4c0221fba1e0a42763d1/src/ParseUser.js#L810

- Related issue:
https://github.com/parse-community/Parse-SDK-JS/issues/424

**Comment by dplewis** [comment]
Current user doesn't exist on server-side by default. 

Does `become` with sessionToken work for you?

You could also create your own UserController and use `CoreManager.setUserController()`

**Comment by yagotome** [comment]
@dplewis `become` works, but I think `logOut` should work similarly as a convenience method so I could use `singUp`, `logIn`, `become` and `logOut` on server-side instead of handle HTTP requests to _Parse Server_. Would it be possible?

I understand `CoreManager.setUserController()` is available, however as mentioned earlier some method signatures are not general enough (e.g. `logOut` does not receives `sessionToken`, `currentUser` doesn't apply to a server-side app).

**Comment by yagotome** [comment]
@dplewis adding more information. I've tested `become` (from `DefaultController` defined in `ParseUser`) in a server environment and received this exception:

```log
Error: It is not memory-safe to become a user in a server environment
    at Function.become (/mystic-market/node_modules/parse/lib/node/ParseUser.js:762:13)
    at Object.sessionTokenToUser (/mystic-market/build/utils/parse.js:227:45)
    at app.use (/mystic-market/build/app.js:22:46)
    at Layer.handle [as handle_request] (/mystic-market/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/mystic-market/node_modules/express/lib/router/index.js:317:13)
    at /mystic-market/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/mystic-market/node_modules/express/lib/router/index.js:335:12)
    at next (/mystic-market/node_modules/express/lib/router/index.js:275:10)
    at compression (/mystic-market/node_modules/compression/index.js:220:5)
    at Layer.handle [as handle_request] (/mystic-market/node_modules/express/lib/router/layer.js:95:5)
```

It calls `setCurrentUser` at the end, so it is not possible to use the current `become` implementation, although its current signature allows me to write my own implementation that wouldn't be coupled to the user's local store. However, it smells like a design issue, the library does not work finely for server-side nodejs :confused:.  Couldn't that be redesigned somehow?

**Comment by dplewis** [comment]
Redesigns are always welcome.

You could add the following in become and add the changes you requested in a PR.

```
if (canUseCurrentUser) {
  return DefaultController.setCurrentUser(user);
}
return user;
```
