### ISSUE TITLE
LiveQuery on "update" has identical attributes for original and new

### ISSUE THREAD

**Issue by rickdzekman** [parse-community/Parse-SDK-JS#835]
### Issue Description

A LiveQuery `"update"` event accepts two arguments `(original,object)` as per the [docs](http://parseplatform.org/Parse-SDK-JS/api/2.3.2/Parse.LiveQuerySubscription.html).

But `original` and `object` have identical properties:
```
testSubscription.on("update", (original, object) => {
    console.log(original.toJSON());
    console.log(object.toJSON());
  });
```

### Steps to reproduce

1. Set up a subscription to any query and create a listener for an update event:

```
  const testQuery = new Parse.Query("SomeClass");
  const testSubscription = await testQuery.subscribe();
  testSubscription.on("update", (original, object) => {
    console.log(original.toJSON());
    console.log(object.toJSON());
  });
```

2. Use another session to update an object in that query

### Expected Results

That `original` would have the attributes of the object from the local data store, and `object` would have the attributes sent from the server via the websocket.

### Actual Outcome

Both `original` and `object` have identical attributes (both objects have the new attributes from the server).

They are different objects (`original !== object` returns `true`) but the actual attributes themselves are identical down to `updatedAt`.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.4.0
  - Operating System:     Windows 10 Pro (running a docker container with node:10-alpine)
  - Hardware:             A pretty generic windows laptop
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **JS SDK**
  - JS SDK version: 2.4.0
  - Application? (Browser, Node, React-Native, etc): React web-app (tested in both Chrome and Firefox)

### Logs/Trace

N/A

**Comment by dplewis** [comment]
I wrote a test case and it passed. 

https://github.com/parse-community/Parse-SDK-JS/tree/test-original

**Comment by rickdzekman** [comment]
I added a breakpoint to `_handleWebSocketMessage` in [LiveQueryClient.js](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/LiveQueryClient.js) and checked the raw data coming out of the `event`. Even in there the `object` and `original` are the same for me.

Does this sound like it's something server side that's the issue?

**Comment by dplewis** [comment]
Can you post server logs?

**Comment by rickdzekman** [comment]
I updated `parse-server` to 3.4.0 before posting.

I turned on verbose=1 and tested a simple update on my current setup. These are my logs:
```
web_1  |   Result: {"object":{"order":0}} {"className":"ContainerJoin","triggerType":"beforeSave","user":"l7K1HgbHim"}
web_1  | verbose: RESPONSE from [PUT] /api/classes/ContainerJoin/m4qeVAUqUz: {
web_1  |   "response": {
web_1  |     "updatedAt": "2019-06-11T23:08:31.910Z"
web_1  |   }
web_1  | } {"result":{"response":{"updatedAt":"2019-06-11T23:08:31.910Z"}}}
web_1  | verbose: Raw request from cloud code current : %j | original : %j
web_1  | verbose: Subscribe messsage %j
web_1  | verbose: S8ikb2KHRCaCMaPEdezy4qacf5zhe7VcCxXfg4B8afterSave is triggered
web_1  | verbose: ClassName: %s | ObjectId: %s
web_1  | verbose: Current client number : %d
web_1  | verbose: Original %j | Current %j | Match: %s, %s, %s, %s | Query: %s
web_1  | verbose: Push Response : %j
web_1  | PUT /api/classes/ContainerJoin/m4qeVAUqUz 200 10.298 ms - 40
```

**Comment by dplewis** [comment]
Which field are you updating? 

Does it work on the client if you change a value in the dashboard?

**Comment by rickdzekman** [comment]
I was updating the field "order" with the value 0.
The logs were formatted with the `%` already

I started digging into this a little more and now things are starting to get weird.

Once I removed my cloud code (`beforeSave` and `afterSave`) it did seem to fix the problem - but only up until `LiveQueryClient.js`. It seems there was something in my cloud code that caused an issue with the server sending `object` and `original` as the same. Which I will have to dig into shortly.

BUT in the JS SDK I'm still having an issue.  (That I'm having two problems related to this same thing seems like an unusual coincidence). 

Once the code reaches this line in `LiveQueryClient.js`:
`var parseObject = _ParseObject.default.fromJSON(data.object, override);`

It seems to modify the `original` as well. 

I've tried to replicate your test code in my environment and I do not get the same results

```
  const TestObject = Parse.Object.extend("Test");
  const object = new TestObject({ foo: "bar" });
  await object.save();
 
 //NOTE: If I don't add this timeout here I don't actually get an event emitted, but if I remove it and modify the object in the dashboard it has the same effect
  const timeout = ms => new Promise(resolve => setTimeout(resolve, ms));
  await timeout(2000);

  const query = new Parse.Query(TestObject);
  query.equalTo("objectId", object.id);
  const subscription = await query.subscribe();

  subscription.on("update", (object, original) => {
    console.log(original.get("foo") !== object.get("foo"));
  });
  object.set({ foo: "baz" });
  await object.save();
```

Console outputs `false` - both when I change in dashboard and on initial load.

**Comment by rickdzekman** [comment]
I just did a fresh `create-react-app` and added `parse` as the only dependency (`2.4.01`).

I also set up a new `parse-server` running on Express. Tested it with the following code and it has the same result, original and object have identical properties:

```
import React from "react";
import Parse from "parse";

const test = async () => {
  Parse.initialize("S8ikb2KHRCaCMaPEdezy4qacf5zhe7VcCxXfg4B8");
  Parse.serverURL = "http://localhost:3001/api";
  Parse.liveQueryServerURL = "ws://localhost:8000/";

  const TestObject = Parse.Object.extend("Test");
  const object = new TestObject({ foo: "bar" });
  await object.save();

  const query = new Parse.Query(TestObject);
  query.equalTo("objectId", object.id);
  const subscription = await query.subscribe();

  subscription.on("update", (object, original) => {
    console.log(original.get("foo") !== object.get("foo"));
    console.log(original.toJSON());
    console.log(object.toJSON());
  });

  const timeout = ms => new Promise(resolve => setTimeout(resolve, ms));
  await timeout(2000);

  object.set({ foo: "baz" });
  await object.save();
};

function App() {
  test();
  return <div className="App" />;
}

export default App;

```

**Comment by dplewis** [comment]
Can you create a sample repository?

**Comment by rickdzekman** [comment]
Let's try this: https://github.com/rickdzekman/parse-test-repo

**Comment by dplewis** [comment]
@rickdzekman Sorry for the late reply. The JSK has a SingleInstanceState for web clients, this mean any objects with the same ObjectId will be synchronized and have the same data.

You can disable this by [Parse.Object.disableSingleInstance()](https://github.com/parse-community/Parse-SDK-JS/blob/b6bc90cab7f25d1377f90e9cff921ed2715c34cc/src/ParseObject.js#L1781)

You can read more about it [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseObject.js#L67)
