### ISSUE TITLE
Ability to filter LiveQuery events to exclude current client

### ISSUE THREAD

**Issue by rickdzekman** [parse-community/Parse-SDK-JS#836]
**Is your feature request related to a problem? Please describe.**

Whenever a client makes an update to an object it receives a LiveQuery event about that very same update. We use optimistic updates so that the UI doesn't wait for confirmation from the server before showing the user the changes. 

There's no way of knowing if an update is done by another client or if it's the update the user just performed. As I describe [here](https://community.parseplatform.org/t/is-there-a-way-to-ignore-livequery-events-caused-by-the-current-client/445), if we apply every update without knowing which client did it and then the user does multiple consecutive updates then this can happen:

1. User re-orders a list (updated in Redux) and the client updates are pushed to the server
2. User re-orders the list again (updated in Redux), pushing more updates to the server
3. LiveQuery triggers an event from update (1) which reverts the Redux update from (2)
4. LiveQuery triggers an event from update (2), which brings Redux back in line with (2)

**Describe the solution you'd like**
Ideally when subscribing to the query you would be able to include a flag to ignore updates from the current client, e.g:

    query.subscribe({ignoreThisClient: true})

**Describe alternatives you've considered**

My workaround is to generate a UUID for each client. Whenever a Parse object is saved I do `obj.set("updateClient",thisClientId)`. I am already using `rxjs` to buffer updates from LiveQuery so I apply a filter which goes through every event and checks to see if `obj.get("updateClient" !== thisClientId)`.

**Comment by dplewis** [comment]
Closing via https://community.parseplatform.org/t/is-there-a-way-to-ignore-livequery-events-caused-by-the-current-client/445/3
