### ISSUE TITLE
Ability to exclude keys from Query

### ISSUE THREAD

**Issue by RaschidJFR** [parse-community/Parse-SDK-JS#839]
**Is your feature request related to a problem? Please describe.**
[`Parse.Query.selec()`](https://parseplatform.org/Parse-SDK-JS/api/2.4.0/Parse.Query.html#select) lets us minimize the data retrieved by choosing only the keys of interest. But when we need to leave out just a couple of keys from a large property list -for example, when removing sensitive data fields from unlogged users- we need to input a very long array of keys in the `select()` method. 

The issue scales when you're still developing the class models and later on you add more properties to registered classes, so you could easily skip to add the new properties to the `select()` method or you could misspell any of them as the list is still growing.

**Describe the solution you'd like**
A method that instead of "whitlisting" the properties to retrieve, it "blacklists" the properties not to. It could be called something like `Parse.Query.exclude()` or `Parse.Query.unselect()`.

**Describe alternatives you've considered**
As I said, the current alternative is to type in all the properties but one, being susceptible to errors.

**Additional context**
I'm having this problem currently when trying to filter data inside the `beforeFind` hook on cloud code.

**Comment by dplewis** [comment]
I made a post about the same thing. https://github.com/parse-community/parse-server/issues/4948

It’s still up for grabs and a good first issue for a PR. Would you like to implement this feature?

**Comment by RaschidJFR** [comment]
Sure, I'd love to! So, how does it work? I just fork, trace, test, implement and then PR, right? nothing special about it. Do we have anything like a deadline? I'm not familiar with the repo yet so it may take me a while this first time.
