### ISSUE TITLE
Option to prevent cascade saving

### ISSUE THREAD

**Issue by RaschidJFR** [parse-community/Parse-SDK-JS#864]
**Is your feature request related to a problem? Please describe.**
When saving an object in which properties there's a pointer to another object, the SDK launches a batch operation to save all modifications made to all nested objects, which is great but... when you don't have write access to any of those (for example when you're saving a Message object pointing to another user's profile) you need to **make sure nested objects are not `dirty`** or call `rever()` in order **not to get the `Object not found` error**.

**Describe the solution you'd like**
A parameter in the saving options, something like `ParseObject.save(null, {cascadeSave: false})` would address this issue.

**Describe alternatives you've considered**
A workaround for now is to call `Parse.Object.revert()` on all objects to which you know this user does not have write permissions.

**Comment by davimacedo** [comment]
@RaschidJFR would you be willed to tackle this one?

**Comment by RaschidJFR** [comment]
I'd love to but currently I've got my hands full. Hopefully I'll work on the [docs](https://github.com/parse-community/docs/issues/632#issuecomment-511478057) next week. If this task is still untaken by then I will take it.

**Comment by RaschidJFR** [comment]
Is this still untaken? I’m taking it

**Comment by RaschidJFR** [comment]
Hey guys. So I've implemented this option, but as I was discussing with @davimacedo , we need to make sure this parameter's scope is clear.

What I intend to do here is give an option not to save the whole chain of nested objects when you call `Parse.Object.save()`, so you don't get data saved which you didn't explicitly intended to, just the object on which you called the function.

I think it is important that **new objects always get saved despite this parameter's value** in order to keep the relational data and leverage the simplicity of the default behaviour, which is great.

Opinions?

P.S. take a look at the [test case ](https://github.com/parse-community/Parse-SDK-JS/pull/881/files#diff-c16d57d974cbd35f9d6b393dea2074d3)so you can clearly understand the proposed behaviour

**Comment by RaschidJFR** [comment]
Related to this, I've noticed that `Parse.Object.revert()` affects also nested objects, same way. Do you think it's worth opening an issue for it?

**Comment by davimacedo** [comment]
Are sure it affects the nested objects? Could you write a test case?

**Comment by RaschidJFR** [comment]
False alarm. It does not affect nested objects.
