### ISSUE TITLE
Add count flag to Parse.Query.find

### ISSUE THREAD

**Issue by BufferUnderflower** [parse-community/Parse-SDK-JS#865]
REST api supports adding &count=true.
Using JS SDK one needs to run a separate query.count() to get this number

Would be nice to have some optional flag like query.withCount(true/false) to avoid
making separate async calls

**Comment by davimacedo** [comment]
I like the idea. We'd need two changes
- In Parse Server side, to receive the additional option and return both results in the same request;
- In JS side, to include the new option in Parse.Query.

@BufferUnderflower this is something that you would be willed to tackle?

**Comment by BufferUnderflower** [comment]
@davimacedo I've read through js sdk, and stumbled upon in what form should the ```count``` be sent back to client. Since query returns the array of  ```Parse.Object```s - it's not a good idea to break current api and wrap count and objects array in another object. The only option i see so far is response header like it's done for example in wordpress api

**Comment by davimacedo** [comment]
The API currently returns in the following format:

```
{
    "results": [ ... ]
}
```

We could add a `count` field and return in the body instead of the header.

```
{
    "results": [ ... ],
    "count": 30
}
```
