### ISSUE TITLE
subscription.on is not a function

### ISSUE THREAD

**Issue by lybaiyy123** [parse-community/Parse-SDK-JS#866]
### Issue Description
TypeError: subscription.on is not a function

code:
let query = new Parse.Query('Message');
query.equalTo('level', 1);
let subscription = query.subscribe();

subscription.on('open', () => {
 console.log('subscription opened');
});

-----
i can connect to server ,but the Firefox and Google show the error
TypeError: subscription.on is not a function

### Steps to reproduce
**step1：**
let query = new Parse.Query('Message');
query.equalTo('level', 1);
let subscription = query.subscribe();

**the server has connect，**
server log： info: Create new client: 03b534a7-ddb7-46e3-85a5-c8b0651cdbaa
 **step 2:**
Parse.LiveQuery.on('open', () => {
  console.log('socket connection established');
});
console show the log .

**step 3:**

subscription.on('open', () => {
 console.log('subscription opened');
});

the firefox and google show error 

test.html:25 Uncaught (in promise) TypeError: subscription.on is not a function

### Actual Outcome
do it like https://docs.parseplatform.org/js/guide/#standard-api

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [FILL THIS OUT]----use nmp install
  - Operating System:     [FILL THIS OUT]   centos7.2
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [FILL THIS OUT] remote server

- **JS SDK**
  - JS SDK version: [FILL THIS OUT]    2.51
  - Application? (Browser, Node, React-Native, etc): [FILL THIS OUT]  Browser

**Comment by dplewis** [comment]
Subscribe returns a promise.

`let subscription = await query.subscribe();`

**Comment by lybaiyy123** [comment]
queryMessages.subscribe().then(subscription=>{
subscription.on('create',(data)=>{console.log(data.get('name')+':'+data.get('message'))});
subscription.on('delete',(data)=>{console.log(data.id)})
})

i know how to use it ,tkanks
