### ISSUE TITLE
For WeChat miniprogram

### ISSUE THREAD

**Issue by xianhaosui** [parse-community/Parse-SDK-JS#892]
为什么文件上传，提示：[system] TypeError: Cannot create a Parse.File with that data.
				wx.chooseImage({
					success: (chooseImageRes) => {
						console.log(chooseImageRes)
						const parseFile = modal.file('photo.jpg', chooseImageRes.tempFilePaths[0])
						parseFile.save().then(function(response) {
							console.log(response)
						}, function(error) {
							console.log(error)
						});
					}
				});

**Comment by dplewis** [comment]
`Parse.File` only accepts base64 objects, Blob Files or absolute uri.

https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseFile.js#L26

You can convert your image to base 64 to save it.

**Comment by xianhaosui** [comment]
> `Parse.File` only accepts base64 objects, Blob Files or absolute uri.
> 
> https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseFile.js#L26
> 
> You can convert your image to base 64 to save it.

This is Blob Files. (blob:http://localhost:8080/183e6abe-2ec5-49ab-9dec-8473aa8d0264)

**Comment by dplewis** [comment]
A blob file would contain binary data. That looks like a path. Regardless, convert it to a base64 object should do the trick.

**Comment by xianhaosui** [comment]
> A blob file would contain binary data. That looks like a path. Regardless, convert it to a base64 object should do the trick.

try, thank you

**Comment by dplewis** [comment]
You could try the following as it will convert it to base 64 for you.

```
const file = new Parse.File('fileName', { uri: '......' });
await file.save();
```

**Comment by xianhaosui** [comment]
> You could try the following as it will convert it to base 64 for you.
> 
> ```
> const file = new Parse.File('fileName', { uri: '......' });
> await file.save();
> ```


Already solved, thank you

**Comment by xianhaosui** [comment]
> > You could try the following as it will convert it to base 64 for you.
> > ```
> > const file = new Parse.File('fileName', { uri: '......' });
> > await file.save();
> > ```
> 
> Already solved, thank you

can you speak Chinese?

**Comment by dplewis** [comment]
No, I wish I did but @einsqing does and implemented WeChat.

**Comment by einsqing** [comment]
@xianhaosui 我明天给你发demo

**Comment by xianhaosui** [comment]
谢谢，来起




------------------ 原始邮件 ------------------
发件人: "einsqing"<notifications@github.com>; 
发送时间: 2019年8月17日(星期六) 晚上10:35
收件人: "parse-community/Parse-SDK-JS"<Parse-SDK-JS@noreply.github.com>; 
抄送: "岁月无痕"<842630388@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [parse-community/Parse-SDK-JS] For WeChat miniprogram (#892)




@xianhaosui 我明天给你发demo
