### ISSUE TITLE
TypeError: Parse.setAsyncStorage is not a function

### ISSUE THREAD

**Issue by FahadAlbukhari** [parse-community/Parse-SDK-JS#895]
I am building Expo CLI and SDK web app and I get this error

×
TypeError: Parse.setAsyncStorage is not a function
../../../../../../../../Documents/T's/app/Ts/src/API.js
src/API.js:4

  1 | const Parse = require('parse/react-native');
  2 | // On React Native >= 0.50 and Parse >= 1.11.0, set the Async
  3 | const AsyncStorage = require('react-native').AsyncStorage;
> 4 | Parse.setAsyncStorage(AsyncStorage);
  5 | 
  6 | 
  7 | Parse.initialize("d");

__webpack_require__
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

../../../../../../../../Documents/T's/app/Ts/src/Screens/Coupon.js
src/Screens/Coupon.js:4

  1 | import React, { Component } from "react";
  2 | import { ActivityIndicator, Alert, Dimensions, FlatList, View, StyleSheet} from "react-native";
  3 | import { Avatar, Divider, Icon, Text, ListItem } from "react-native-elements";
> 4 | const Parse = require("../API");
  5 | var {height, width} = Dimensions.get('window');
  6 | 
  7 | var hasOne = false

__webpack_require__
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

../../../../../../../../Documents/T's/app/Ts/src/navigation/AppNavigator.js
src/navigation/AppNavigator.js:1

> 1 | import { createAppContainer, createSwitchNavigator } from 'react-navigation';
  2 | 
  3 | import Coupon from "../Screens/Coupon";
  4 | import Netinfo from "../Screens/Netinfo";

__webpack_require__
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

../../../../../../../../Documents/T's/app/Ts/App.tsx
http://192.168.1.79:19006/static/js/bundle.js:827:87
__webpack_require__
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

../../../../../../../../Documents/T's/app/Ts/node_modules/expo/AppEntry.js
node_modules/expo/AppEntry.js:1
__webpack_require__
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

fn
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:101

   98 | 		);
   99 | 		hotCurrentParents = [];
  100 | 	}
> 101 | 	return __webpack_require__(request);
      | ^  102 | };
  103 | var ObjectFactory = function ObjectFactory(name) {
  104 | 	return {

0
http://192.168.1.79:19006/static/js/bundle.js:154086:18
__webpack_require__
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:724

  721 | };
  722 | 
  723 | // Execute the module function
> 724 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  725 | 
  726 | // Flag the module as loaded
  727 | module.l = true;

(anonymous function)
/Users/alghreeb/Documents/T's/app/Ts/webpack/bootstrap:791

  788 | 
  789 | 
  790 | // Load entry module and return exports
> 791 | return hotCreateRequire(0)(__webpack_require__.s = 0);
      | ^  792 | 

(anonymous function)
http://192.168.1.79:19006/static/js/bundle.js:795:10
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by dplewis** [comment]
What version of the JS SDK are you running?

**Comment by FahadAlbukhari** [comment]
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.21",
    "@fortawesome/free-solid-svg-icons": "^5.10.1",
    "@fortawesome/react-native-fontawesome": "^0.1.0",
    "@react-native-community/netinfo": "^4.1.4",
    "expo": "^34.0.1",
    "expo-asset": "~6.0.0",
    "parse-server": "^3.7.2",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-google-places-autocomplete": "^1.3.9",
    "react-native-modal-datetime-picker": "^7.5.0",
    "react-native-phone-input": "^0.2.4",
    "react-native-reanimated": "~1.1.0",
    "react-native-sticky-parallax-header": "^0.0.59",
    "react-native-svg": "^9.6.2",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.11.1"
  },
  "devDependencies": {
    "@types/react": "^16.8.23",
    "@types/react-native": "^0.57.65",
    "babel-preset-expo": "^6.0.0",
    "typescript": "^3.4.5"
  },
  "private": true
}

**Comment by dplewis** [comment]
Try

```
$ npm install parse --save
$ nom install @types/parse --save-dev
```

**Comment by FahadAlbukhari** [comment]
nothing changed

**Comment by dplewis** [comment]
Its located [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/Parse.js#L59) in the sdk.

Check your node_modules folder to see if it compiled.
` /node_modules/parse/lib/react-native/parse.js`

You could also clean install your packages (remove node_modules + package-lock.json)

**Comment by FahadAlbukhari** [comment]
nothing changed

**Comment by dplewis** [comment]
You aren’t providing enough information. What did you try and what have you found out? Without this information we can’t help debug this issue.

**Comment by FahadAlbukhari** [comment]
Thank you for trying to help me out. I am building Expo web app and I get this error

TypeError: Parse.setAsyncStorage is not a function

  1 | const Parse = require('parse/react-native');
  2 | // On React Native >= 0.50 and Parse >= 1.11.0, set the Async
  3 | const AsyncStorage = require('react-native').AsyncStorage;
> 4 | Parse.setAsyncStorage(AsyncStorage);
  5 | 
  6 | 
  7 | Parse.initialize("3");


What do you need more?

**Comment by dplewis** [comment]
Did you check the node_modules folder? Was it there?
What SDK Version? Posting your package.json told me nothing.

**Comment by FahadAlbukhari** [comment]
node_modules is there. package.json told you "parse": "^2.6.0",

**Comment by dplewis** [comment]
Is setAsyncStorage in `/node_modules/parse/lib/react-native/parse.js`?

**Comment by FahadAlbukhari** [comment]
/**
   * Call this method to set your AsyncStorage engine
   * Starting Parse@1.11, the ParseSDK do not provide a React AsyncStorage as the ReactNative module
   * is not provided at a stable path and changes over versions.
   * @param {AsyncStorage} storage a react native async storage.
   * @static
   */
  setAsyncStorage(storage
  /*: any*/
  ) {
    CoreManager.setAsyncStorage(storage);
  },

**Comment by dplewis** [comment]
Looks like its there.

What version of @types/parse are you running? Perhaps typescript can't find it.

Can you check if its in your node_modules/@types/parse/index.d.ts?

I'm not a typescript expert.

**Comment by FahadAlbukhari** [comment]
yes
// Type definitions for parse 2.2.1

/Users/alghreeb/Documents/'s/app/t/node_modules/@types/parse/index.d.ts

**Comment by dplewis** [comment]
I honestly don't know. Does querying and saving objects work without it?

As a workaround you can try the following instead.

```
Parse.CoreManager.setAsyncStorage(storage);
```

**Comment by FahadAlbukhari** [comment]
The expo web app is in beta. I think this is the problem. However expo with parse is working perfectly but when I try expo web I get this problem. Thank you anyway.

**Comment by dplewis** [comment]
If you could set up a simple sample repo so that we can replicate this issue that would help.

**Comment by FahadAlbukhari** [comment]
I will

**Comment by dplewis** [comment]
@FahadAlbukhari someone is also using expo with async storage and has it working.

Check out https://github.com/parse-community/Parse-SDK-JS/issues/943
