### ISSUE TITLE
unset value give a null instead of undefined when registerSubclass

### ISSUE THREAD

**Issue by Basone01** [parse-community/Parse-SDK-JS#908]
### Issue Description

When call obj.unset('xfield') from sub class object,
it give me a **null** value to 'xfield' field.

But when I remove **Parse.Object.registerSubclass('Class', Class)**  (I call it after intitialze),
it give me an **undefined** value to 'xfield' field.

### Steps to reproduce
first initialize Parse like this
`Parse.initialize(PARSE_APP_ID);
 Parse.serverURL = PARSE_SERVER_URL;
 Parse.Object.registerSubclass('ClassX', ClassX)`

and then query some object from ClassX

call objX.unset('some field')

if you log objX , value of 'some field' will be **null**

and when save it, value of 'some field' in objX in cloud will be **null** too.

### Expected Results

It should give an **undefined** value after unset field.

### Actual Outcome

It give a **null** instead of **undefined**.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.1.3
  - Operating System:     Mac OS Mojave 10.14.6
  - Hardware:             Macbook Pro 2018
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS

- **JS SDK**
  - JS SDK version: 2.7.0 also try it on 2.2.1 and got the same issue 
  - Application? (Browser, Node, React-Native, etc): Browser

**Comment by dplewis** [comment]
@Basone01 What does the value look like in the database? If you `query.exists('some_field')` does it return?

**Comment by Basone01** [comment]
> @Basone01 What does the value look like in the database? If you `query.exists('some_field')` does it return?

Value of 'some_field' in database is null,
and it still return that object when use query.exists('some_field')

**Comment by dplewis** [comment]
I wrote a test case https://github.com/parse-community/Parse-SDK-JS/pull/909

Can you have a look or write a failing test?

**Comment by Basone01** [comment]
> I wrote a test case #909
> 
> Can you have a look or write a failing test?
> 
> If you want to run test cases check out the contributing guide
> 
> https://github.com/parse-community/Parse-SDK-JS/blob/master/CONTRIBUTING.md

I've just found my mistake.

I've overwrite 'set' method in my subclass like this below for some reason

`  set(key, value) {
    return super.set(key, value)
  }`

I didn't pass options parameter in the third arguments like this

` set(key, value, options) {
    return super.set(key, value, options)
  }`

And now it's work correctly thank you.

**Comment by dplewis** [comment]
No problem! I’m glad you got it working.
