### ISSUE TITLE
Included objects decay to pointers when updating

### ISSUE THREAD

**Issue by TylerBrock** [parse-community/Parse-SDK-JS#91]
We are seeing strange behavior that is different that that of the JS 1.5 and lower SDK in that when we update a field on an object that has included objects (fully hydrated), we see that the included objects decay to pointers after performing the update. We want to add this to the list of things we've discovered as blockers in #73.

This is a reproduction using the Parse JS SDK 1.6.9:

**Setup**

``` js
class Brand extends Parse.Object {
  constructor(attributes, options) {
    super('Brand', attributes, options);
  }
}
Parse.Object.registerSubclass('Brand', Brand);

class Item extends Parse.Object {
  constructor(attributes, options) {
    super('Item', attributes, options);
  }
}
Parse.Object.registerSubclass('Item', Item);
```

**Test**

``` js
var freshItem = new Item({cool: true});
var freshBrand = new Brand({item: item});

Parse.Object.saveAll([freshItem, freshBrand]).then((brand, item) => {
  var query = new Parse.Query(Brand);
  query.include('item');
  return query.get(brand.id);
}).then((savedBrand) => {
  var item = savedBrand.get('item');
  assert(item.has("cool"));  // has attributes of item (not decayed)
  assert(item.get("cool"));  // has attributes of item (not decayed)

  // This update will cause included objects on savedBrand to decay.
  brand.set('newField', true);

  return brand.save().then((updatedBrand) => {
    var item = savedBrand.get('item');
    assert(item.has("cool")); // fails, no attributes of item present (decayed)
    assert(item.get("cool")); // fails, no attributes of item present (decayed)
  });
})
```

When we attempt the same actions in the 1.5 SDK and lower the pointers do not decay (run line by line in our node REPL)

``` js
var Item = Parse.Object.extend("Item")
var Brand = Parse.Object.extend("Brand")

var brand = new Brand({name: "Acme"})
var item = new Item({brand: brand})

item.save()

var itemRef;
var itemQuery = new Parse.Query(Item);
itemQuery.include("brand").get("n0EnLswyJv").then(function(fetchedItem) {
  itemRef = fetchedItem;
})

itemRef.get("brand").get("name")
> 'Acme'

itemRef.set("price", 30)
itemRef.save()
itemRef.get("brand").get("name")
> 'Acme'
```

**Comment by diegohaz** [comment]
I'm having the same issue.

**Comment by polerin** [comment]
Same.  This is wrecking havoc with my cloud code.

**Comment by whynotmatt** [comment]
I'm seeing the same error.

**Comment by andrewimm** [comment]
I believe I have a fix. The "known server data" in the save response was overaggresively overwriting local data. Once I have some extra unit tests in place, I'll attempt to push this later today.

**Comment by andrewimm** [comment]
Actually, I'm stumped. I added some extra checks that I thought might help, but then I went back to make some unit tests that only pass with the new changes, and I was unable to make anything fail prior to these changes.

I went back and ran Tyler's tests line-by-line in node using v1.6.13, and I get the expected "correct" behavior, no matter which objects I manipulate. Since there are so many people here with the same issue, can someone please come up with a reproducible test case?

**Comment by polerin** [comment]
I'll try to rewrite one.  I'm sorta tight on time so it won't be right this second.

**Comment by TylerBrock** [comment]
Andrew, I also see the test work with 1.7.0, however we see this happen in production a lot in the following case:

1. Query for object and include related objects
2. Save object and wait on the result
3. Before the save returns, run a before save hook on the same api server
4. The save returns with an object no longer having the included related objects (decayed)

**Comment by andrewimm** [comment]
@TylerBrock is that using `parse-server`? if so, I think it's a problem for that codebase, not this one.

**Comment by TylerBrock** [comment]
No, using parse classic, we haven't moved off yet.

**Comment by andrewimm** [comment]
Okay, got confused by the "same api server" bit. I'll take a look and see if I can repro this.

**Comment by TylerBrock** [comment]
Thanks, let me know if i can help. We resolve the issue by storing the included object properties in a higher scope and then not depending on it further down the promise chain after the object decays.

**Comment by TylerBrock** [comment]
This is the annotated block of code where we have the hack for the decay (one example of it at least)

```js
  var phoneNumber;
  var messageQuery = new Parse.Query(Message);
  messageQuery.equalTo("sid", sid);
  messageQuery.include("fromAgent");
  messageQuery.first().then(function(message) {
    // We do this because message decays after being saved :-(
    phoneNumber = message.get('fromAgent').get('phoneNumber');
    message.set("status", newStatus);

    // ... do other stuff with message

    // message has a beforeSave() where we hydrate the object and serialize it back out
    // on this very same instance of Parse and that happens in between the next two lines
    return message.save();
  }).then(function(message) {
    // message.get('fromAgent').get('phoneNumber') is undefined here
  } 
```
