### ISSUE TITLE
`matchesKeyInQuery` not working in `liveQuery`

### ISSUE THREAD

**Issue by JeromeDeLeon** [parse-community/Parse-SDK-JS#911]
### Issue Description

I'm using `matchesKeyInQuery` and I got initial result when doing `query.find()` but when integrating `liveQuery`, I'm not able to get any data whenever I updated some fields on the object. It worked when I tried commenting out the `matchesKeyInQuery`.

### Steps to reproduce

1. Create 3 Classes (Sample, Test, Tester)
2. Fill them
```
Tester: {
    firstName: "Tester1",
}

Test: {
    name: "testName",
    tester: Pointer to Tester
}

Sample: {
    active: true,
    tester: Pointer to Tester
}
```

3.  Run this code (parse is already imported, and all classes were specified in Server config)
```js
const getSampleQuery = () => {
    const query = new Parse.Query("Sample");
    query.equalTo("active", true);

    return query;
}

const getQuery = () =>  {
    const query = new Parse.Query("Test");
    query.contains("name", "test");
    query.matchesKeyInQuery("tester", "tester", getSampleQuery());

    return query;
}

const test = async () => {
    const query = await getQuery();
    const subscription = await query.subscribe();

    console.log("initial", await query.find());

    subscription.on("open", () => {
      console.log("subscription opened");
    });

    subscription.on("close", () => {
      console.log("subscription closed");
    });

    subscription.on("enter", object => {
      console.log("object entered", object);
    });

    subscription.on("create", object => {
      console.log("object created", object);
    });

    subscription.on("update", object => {
      console.log("object updated", object);
    });

    subscription.on("leave", object => {
      console.log("object left", object);
    });
}

test();
```

4. Set the value of `name` in `Test` class to empty
### Expected Results

You would receive a `leave` event or `update` event when you update `name` in `Test`

### Actual Outcome

None

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.8.0
  - Operating System:     Windows 10
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **JS SDK**
  - JS SDK version: 2.7.0
  - Application? (Browser, Node, React-Native, etc): Browser

### Logs/Trace

After initial run, I got this on console:
```
initial [ParseObject]
subscription opened
```

Network WS log:
```
S: {"op":"connect","applicationId":"test_beta","javascriptKey":"","masterKey":"tester"}
R: {"op":"connected","clientId":"2c77585c-ae5b-4700-b723-4cdccc7cd3b1"}
S: {"op":"subscribe","requestId":1,"query":{"className":"Test","where":{"name":{"$regex":"\\Qtest\\E"},"tester":{"$select":{"key":"tester","query":{"where":{"active":true},"className":"Sample"}}}}}}
R: {"op":"subscribed","clientId":"2c77585c-ae5b-4700-b723-4cdccc7cd3b1","requestId":1}
```

**Comment by dplewis** [comment]
Did you add live query class names to your server config.

**Comment by JeromeDeLeon** [comment]
Yes. It's working properly without `matchesKeyInQuery`.

**Comment by dplewis** [comment]
Can you write a failing test case [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/integration/test/ParseLiveQueryTest.js#L20)?

**Comment by dplewis** [comment]
@JeromeDeLeon matchesKeyInQuery ($select) isn't supported by LiveQuery.
https://github.com/parse-community/parse-server/blob/master/src/LiveQuery/QueryTools.js#L335

You can check what is supported by looking at the [Live Query Protocol](https://github.com/parse-community/parse-server/wiki/Parse-LiveQuery-Protocol-Specification)

LiveQuery just does a synchronous matching, which results in fast responses. If we want matchesKeyInQuery to work we would have to query the database which goes against the O(1) matching of the protocol.
