### ISSUE TITLE
maxLimit isn't mentionned

### ISSUE THREAD

**Issue by oallouch** [parse-community/Parse-SDK-JS#917]
Hi,

On the server side, the maxLimit config value sets the maximum value the limit query parameter can have. But there's 2 issues :
. I can't find a default value on the server (in Options/Definitions.js). Is it normal ?
. On the client side (the js sdk), the comment still mentions the 1000 max.

Thx in advance,
Olivier

**Comment by dplewis** [comment]
`maxLimit` overrides if limit > maxLimit (unlimited by default). 

If maxLimit is 50 and `query.limit(200)` will only return 50 objects.

The default `limit` if limit is not set is 100;

https://github.com/parse-community/parse-server/blob/981628520584b71608b3fff2aeb57db8b5ed3e1f/src/Routers/ClassesRouter.js#L190

**Comment by oallouch** [comment]
Ok,no default value.
But maybe we should change the comment at
https://github.com/parse-community/Parse-SDK-JS/blob/719e98ff74ee99b820fcb8e6c37f32695d07e307/src/ParseQuery.js#L1489
(regarding the maximum limit of 1000)
