### ISSUE TITLE
When updating Parse.User.current(), after save() and call Parse.Object.fromJSON(anyParseObject), Parse.User.current() got roll back to previous data before save()

### ISSUE THREAD

**Issue by nelsonyang0710** [parse-community/Parse-SDK-JS#926]
### Issue Description

When updating Parse.User.current(), after save() and call Parse.Object.fromJSON(), Parse.User.current() got roll back to previous data before save()
I do use async-storage "@react-native-community/async-storage": "^1.6.1",
After I clear all async-storage, and re login again, then it shows updated current user data.
which caused the token invalid since after logout, the token is updated on the server but still cached the old data in app.
### Steps to reproduce

When updating Parse.User.current(), after save() and call Parse.Object.fromJSON(), Parse.User.current() got roll back to previous data before save()

### Expected Results

Parse.User.current() is consistent after saving

### Actual Outcome

Parse.User.current() change back to the data before saving

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : "parse-server": "~2.2.23"
  - Operating System:     [FILL THIS OUT]
  - Hardware:            Mac book
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS

- **JS SDK**
  - JS SDK version: 2.7.1
  - Application? (Browser, Node, React-Native, etc): React-Native

**Comment by davimacedo** [comment]
I am not sure I understood the issue. Would you mind to write a failing test case?

**Comment by dplewis** [comment]
The JSK has a SingleInstanceState for web clients, this mean any objects with the same ObjectId / localId will be synchronized and have the same data.

You could try Parse.Object.disableSingleInstance()
