### ISSUE TITLE
Missing lot's of documentation in order to create a custom authentication

### ISSUE THREAD

**Issue by rhuanbarreto** [parse-community/Parse-SDK-JS#934]
I'm trying to create a custom authentication using Keycloak OpenID Connect Provider as a source for authentication and I'm stumbling over many docs about how to create a custom authentication in order to support it as:

- https://docs.parseplatform.org/parse-server/guide/#custom-authentication
- https://docs.parseplatform.org/js/guide/#linking-users
- https://docs.parseplatform.org/rest/guide/#signing-up-and-logging-in

And in the end, some of the code mentioned on the docs are missing documentation in the SDK, as:

- [_registerAuthenticationProvider](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseUser.js#L799) - Missing all of it
- [_logInWith](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseUser.js#L809) - Missing all of it
- [_linkWith](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseUser.js#L80) - Incomplete, as it doesn't describe the function itself, only the no need to have a _logInWith even though the function exists.

And then I needed to read all the source in order to understand how the things work. I'm still developing the custom authentication, but I'm not fully aware of the inner workings on this, so for now I can't help opening a PR and doing this myself, but it's my duty to open an issue and point this out so all the community can improve it.

**Comment by dplewis** [comment]
https://docs.parseplatform.org/js/guide/#custom-authentication-module

Everything should be there to create a custom auth.

I can open a PR to document those functions.

**Comment by rhuanbarreto** [comment]
I thinks it's better. It's still not clear to me that for making a login, you need to create this provider. This could be better explained on why do you need each function in the provider and how it connects internally in the SDK.

In the end I didn't need to do more than the server. I'm using the rest API now, because it seems more convenient than creating this provider. But soon I will make an extension to the SDK to support Keycloak like the FacebookUtils.

**Comment by rhuanbarreto** [comment]
Also it's important to mention that an ID field is mandatory in order to make the 3rd party login work. I could understand it reading the other authentication methods.

**Comment by dplewis** [comment]
You are right. id field is required and I don’t think hyphen names modules work either.

**Comment by dplewis** [comment]
@rhuanbarreto Can you open a PR? We will gladly review it.
