### ISSUE TITLE
Unable to resolve module 'EventEmitter' - React Native 0.61.1

### ISSUE THREAD

**Issue by kekami** [parse-community/Parse-SDK-JS#936]
### Issue Description
After upgrading from react-native v0.60.4 to v0.61.1 I receive a red screen where parse is unable to location EventEmitter in the project. 

Using parse version 2.7.1.

Nothing else was changed between 0.60.4 => 0.61.1

### Steps to reproduce

1. Upgrade react native using https://react-native-community.github.io/upgrade-helper/
2. yarn
3. pod install
4. react-native run-ios
5. Start the packager

### Expected Results

Manage to start the app

### Actual Outcome

![Screenshot 2019-09-30 at 13 40 29](https://user-images.githubusercontent.com/24361798/65875748-31ad2900-e388-11e9-89da-a0028d92e07d.png)
### Environment Setup

- **JS SDK**
  - JS SDK version: 2.7.1
  - Application? (Browser, Node, React-Native, etc): RN0.61.1

**Comment by renanogueira** [comment]
same here

**Comment by VenomApps** [comment]
Whats the status on this is there a fix?

**Comment by OmidRReza** [comment]
this fixed my problem:

go to the file:  

> node_modules\parse\lib\react-native\EventEmitter.js


and change this line:

`const EventEmitter = require('EventEmitter');`

to this:

`const EventEmitter = require('../../../react-native/Libraries/vendor/emitter/EventEmitter');`

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/Parse-SDK-JS/pull/946

**Comment by BalalRaza** [comment]
When will we publish this update?

**Comment by jacinto123** [comment]
Yeah we really need this, I hope we can get this published soon.

**Comment by dplewis** [comment]
There are a few PR's opened, once they are reviewed we can do a release.

I'll draft one right now.

**Comment by DurandSacha** [comment]
I have a same problem here.

**Comment by dplewis** [comment]
@DurandSacha can you open a new issue and fill out the template as much as possible

**Comment by pastean** [comment]
`TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[0], "../../../react-native/Libraries/vendor/emitter/EventEmitter").prototype.addListener')`

I've been stuck on this for a couple hours. Can anyone point me in the right direction? Worked before adding @types/parse. Not working after removing the package though.

**Comment by maidrissi** [comment]
> 
> 
> `TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[0], "../../../react-native/Libraries/vendor/emitter/EventEmitter").prototype.addListener')`
> 
> I've been stuck on this for a couple hours. Can anyone point me in the right direction? Worked before adding @types/parse. Not working after removing the package though.
> 
> Only happens on react-native 0.64.0; 0.63.3 works fine.

go to the file:

`    node_modules\parse\lib\react-native\EventEmitter.js`

and change this line:

`var EventEmitter = require('../../../react-native/Libraries/vendor/emitter/EventEmitter');`

to this:

`import EventEmitter from 'react-native/Libraries/vendor/emitter/EventEmitter';`


Only solution that worked, for me, I have been pulling my hair out over this issue for 5 days. No solutions online.

**Comment by cjbland** [comment]
For what it's worth I'm using TypeScript, `parse@3.3.0` and @maidrissi solution worked for me.

**Comment by niraj-khatiwada** [comment]
I keep getting the same error. I even tried @maidrissi method but does not work.
![image](https://user-images.githubusercontent.com/51436631/152419873-08e826e1-b1d4-43fe-9bf8-ed67fd898d9f.png)

    "react-native": "0.66.1",
    "parse": "^3.3.0",
