### ISSUE TITLE
Cannot get schema in Parse SDK using Session Token

### ISSUE THREAD

**Issue by chromonav** [parse-community/Parse-SDK-JS#941]
### Steps to reproduce
- Initialize Parse SDK with client key, session token, 
run the following:
```
    Parse.Schema.all({
      useMasterKey: false,
      sessionToken: '' //a session token here 
    }).then(r => {
      console.log(r)
    })
```
### Expected Results
Should give schema

### Actual Outcome
Throws error: 
![image](https://user-images.githubusercontent.com/5052568/66272884-95ee5200-e88c-11e9-988b-846bef4d8701.png)

### Environment Setup

- **Server**
  - parse-server version: 3.9.0
  - Operating System:   OSX
  - Hardware:  16gb RAM, i5 processor
  - Localhost or remote server? Back4app

- **JS SDK**
  - JS SDK version: 2.7.1
  - Application: React

### Logs/Trace
![image](https://user-images.githubusercontent.com/5052568/66272944-2167e300-e88d-11e9-869d-51676645b383.png)

**Comment by santiagosemhan** [comment]
Hi @chromonav , **master key** is required to fetch the schema. I think you should not store the master key on your client-side. Can you give more details about what are you trying to do?

https://docs.parseplatform.org/js/guide/#schema

**Comment by chromonav** [comment]
@santiagosemhan according to documentation reference `Parse.Schema.get` should be allowed from client-side using session token without using MasterKey:

Please checkout: http://parseplatform.org/Parse-SDK-JS/api/2.7.1/Parse.Schema.html#get
Which is not working.

**Comment by santiagosemhan** [comment]
I recommend you to code a cloud function that return to frontend your schema data. So in your cloud function you could make additional controls or process the response and deliver only the required data and not all Parse schema data.

PS: Masterkey is required, use it in your cloud function.

**Comment by dplewis** [comment]
@chromonav This is my fault. When I added Parse.Schema, copied from Parse.Object documentation.

MasterKey is required. MasterKey would override any sessionToken you pass anyway.

I'll submit a PR to fix this.
