### ISSUE TITLE
[@types/parse] Schema is missing

### ISSUE THREAD

**Issue by JeffGuKang** [parse-community/Parse-SDK-JS#942]
### Issue Description

`Property 'Schema' does not exist on type 'typeof Parse'.ts(2339)`
`Schema` is missing in type.

```
import Parse from 'parse/node'

const schema = new Parse.Schema('_User') // ts lint error
```

"@types/parse": "^2.2.11",

Related url: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/parse

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [3.9.0]
  - Operating System:     [Mac OS]
  - Hardware:             []
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [localhost]

- **JS SDK**
  - JS SDK version: [2.7.1]
  - Application? (Browser, Node, React-Native, etc): [Node]

**Comment by dplewis** [comment]
@JeffGuKang Can you open a PR / Fix on the definitelyTyped repo?

**Comment by JeffGuKang** [comment]
@dplewis I will do it. But I am confusing about the `addIndex` method. 

The official doc describe `addIndex` as below. 

```
addIndex(name, type) → {Parse.Schema}

Adding an Index to Create / Update a Schema
- name: string Name of the field that will be created on Parse
- type: string Can be a (String|Number|Boolean|Date|Parse.File|Parse.GeoPoint|Array|Object|Pointer|Parse.Relation)
         */
```

But example is `schema.addIndex('index_name', {'field', 1});`

**Comment by dplewis** [comment]
`schema.addIndex('index_name', {'field': 1});`

`field` should exist in the schema before using `addIndex`

That function should be changed as the name could be generated by the index (currently not implemented).

**Comment by dplewis** [comment]
Closing via https://github.com/DefinitelyTyped/DefinitelyTyped/pull/39024
