### ISSUE TITLE
Parse.setAsyncStorage won't work with expo-secure-storage

### ISSUE THREAD

**Issue by ivnnv** [parse-community/Parse-SDK-JS#943]
### Issue Description

```
import * as SecureStore from 'expo-secure-store';
Parse.setAsyncStorage(SecureStore);
```
Throws an XMLHttpRequest  error.

### Steps to reproduce

Create a new project using expo init.
Import and set up Parse/react-native
Set expo's SecureStore as the AsyncStorage
Try to make any request: Parse.User.logIn()

### Expected Results

Expected to get the data from parse

### Actual Outcome

`XMLHttpRequest failed: {"line":128186,"column":40,"sourceURL":...
`
### Environment Setup

- **Server**
  - parse-server version: 2.8.4
  - Operating System: Linux? (Back2app)
  - Hardware:  ? (Back2app)
  - Localhost or remote server? Back2app

- **JS SDK**
  - JS SDK version: 2.7.1
  - Application? React-Native expo

**Comment by ivnnv** [comment]
I have investigated the issue and it turns out expo's SecureStorage isn't compatible with react-native's AsyncStorage implementation, mostly because Expo's don't include the callback which is called after getting / setting the value.

So I have created a wrapper around Expo using the same interface as AsyncStorage and it works! 
I attach here the sample code which I don't know if its worth to implement inside the setAsyncStorage controller, detecting if the storage object if expo's and then wrapping it (that would be a cool feature!)

```
import * as SecureStore from 'expo-secure-store';

const getExpoKey = (key) => {
  return key.split('/').join('_');
};

const ExpoAsyncStorage = {
  // Wrapper around Expo's SecureStore to match react-native's native AsyncStore interface
  // Expo doesn't support slash on the key path so we always need to replace them with underscores using getExpoKey(key)

  getItem: async (key, callback) => {
    try {
      const val = await SecureStore.getItemAsync(getExpoKey(key));
      callback(null, val);
    } catch (error) {
      console.log("AsyncSecureStore getItem error", error);
      return null;
    }
  },

  setItem: async (key, value, callback) => {
    try {
      await SecureStore.setItemAsync(getExpoKey(key), value);
      callback(null);
    } catch (error) {
      console.log("AsyncSecureStore setItem error", error);
      return false;
    }
  },

  removeItem: async (key, callback) => {
    try {
      await SecureStore.deleteItemAsync(getExpoKey(key));
      callback(null);
    }
    catch (error) {
      console.log("AsyncSecureStore removeItem error", error);
      return false;
    }
  },

  /*
    TODO: If we want a fully compatible wrapper we need to implement the rest of methods too
    mergeItem: function(key, value, callback) {}
    clear: function(callback) {}
    getAllKeys: function(callback): {}
    flushGetRequests: function() => {}
    multiGet: (keys, callback) {}
    multiSet: function(keyValuePairs, callback) {};
    multiRemove: function(keys, callback) {};
    multiMerge: function(keyValuePairs, callback)
  */
};

export default ExpoAsyncStorage;
```

**Comment by dplewis** [comment]
Sweet! I know there have been some issues with Expo.
