### ISSUE TITLE
[Discussion] _localId generated via counter

### ISSUE THREAD

**Issue by dplewis** [parse-community/Parse-SDK-JS#955]
I posted a comment [here](https://github.com/parse-community/Parse-SDK-JS/issues/899#issuecomment-540882389) about it.

There is currently an issue with a offline caching of objects. If an app (web app) reinitializes the SDK, the localId resets. The means any offline cached objects may have the same localId as another object.

iOS and android uses some form of generated long int (~8 bytes) which is then cached to the disk.

[iOS](https://github.com/parse-community/Parse-SDK-iOS-OSX/blob/5bf27a2d173d822c8e8d955ca9f25efccd7c0787/Parse/Parse/Internal/Object/LocalIdStore/PFObjectLocalIdStore.m#L192)

[Android](https://github.com/parse-community/Parse-SDK-Android/blob/cedc1dfb03348761688d5abd87c552a1b9cd4b19/parse/src/main/java/com/parse/LocalIdManager.java#L117)

I figures we could replace the counter with a UUID for localId or use something similar to it and avoid collision.

What do you think?

**Comment by wfilleman** [comment]
@dplewis Updated my post [here ](https://github.com/parse-community/Parse-SDK-JS/issues/899) with my successful experiment using a UUID for localIDs.
