### ISSUE TITLE
How to remove a relation from user object

### ISSUE THREAD

**Issue by pushpendra-codemymobile** [parse-community/Parse-SDK-JS#958]
I am trying to remove relation from a parse user object  but getting following error.

(node:7769) UnhandledPromiseRejectionWarning: TypeError: userObj.getRoles is not a function
    at users.map (/home/codemymobile/upkeep/core-service/server/api/v1/services/UserService.js:303:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Code spinet
=========
 
**await User.saveAll(users, {useMasterKey: true}).then(users => {
        users.map(async user => {
          const userObj = await self.findById(user.id, {useMasterKey: true});
          userObj.getRoles().removeAll(); 
})})**

As i don't have much knowedge about parse can anyone help me to resolve

**Comment by dplewis** [comment]
Please checkout the [Javascript Guide](https://docs.parseplatform.org/js/guide/#many-to-many-relationships).

When in doubt you can always look at the source code.
