### ISSUE TITLE
Encrypt Current User - LocalStorage

### ISSUE THREAD

**Issue by macarthuror** [parse-community/Parse-SDK-JS#967]
Hello guys :vulcan_salute:,

Right now I’m trying to encrypt the data which is storage in the browser and I’m using secure-ls , actually is working fine but only is encrypting the ping data not the Current User.

Do you have any idea of how to do it ?

Thanks and have a good day.

BTW. This is the code I’m using

```javascript
import SecureLS from 'secure-ls'
const ls = new SecureLS({ isCompression: false })

Parse.enableLocalDatastore()
Parse.setLocalDatastoreController({
  fromPinWithName: name => ls.get(name),
  pinWithName: (name, objects) => ls.set(name, objects),
  unPinWithName: name => ls.remove(name),
  getAllContents: () => ls.getAllKeys(),
  clear: () => ls.removeAll()
})
```

> I wrote it before in the [community forum](https://community.parseplatform.org/t/encrypt-current-user-localstorage/774) but no one shows up 😅

**Comment by dplewis** [comment]
Sorry for the late reply. That secure-ls trick looks cool.

The currentUser isn't stored in the localDatastore.

This is the [line](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseUser.js#L865) you are looking for.

**Comment by dplewis** [comment]
If you want you could do the same for setting the [StorageController](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/StorageController.browser.js)

**Comment by macarthuror** [comment]
Hello @dplewis 🖖
Sorry for not answering before and thanks for the line I was looking for.

Sure let me try it. 👌😁

**Comment by dplewis** [comment]
I would like to add SecureLS to the SDK but I’m skeptical. StorageController is swappable so we could have that option.

@acinader @davimacedo Thoughts?

**Comment by acinader** [comment]
Off the cuff, just documenting it on the readme and maybe the js sdk guide how to use it would be a decent first step? 

alternatively,  we could make an argument to initialize or a single call to use it wheen Parse SDK is initialized?

**Comment by dplewis** [comment]
I figure it could be the same as setAsyncStorage for React-Native. 

Secure LS has browser support issues i.e Microsoft Edge (insert rant here). I can open a PR for this and we can move the conversation there. @macarthuror what do you think?

**Comment by macarthuror** [comment]
@acinader  I'm gonna documented it in the Readme. Thanks.

@dplewis I like it, also I think we can use other solutions to improve the security without using other repo.

BTW @davimacedo [suggest](https://community.parseplatform.org/t/encrypt-current-user-localstorage/774) trying with `CoreManager.setStorageController()`

**Comment by dplewis** [comment]
I'm going to close this as users can add their own storage implementation if needed.
