### ISSUE TITLE
How Parse.Query() is work with sessionToken or ACL 

### ISSUE THREAD

**Issue by pushpendra-codemymobile** [parse-community/Parse-SDK-JS#974]
Hello all i want to know internal working of Parse.Query() with sessionToken or with ACL 

Suppose i have following mongoDB query 

db.getCollection('_User').updateOne({_id: 'TnLZJsghZE'}, 
{ $set: {
        "_wperm" : [
            "role:SPKTaprVMvxgedjpXlaZ",
            "rq7SSFAfjG",
            "role:ezltkinirrWCiKseYXiU"
        ],
        "_rperm" : [
            "role:SPKTaprVMvxgedjpXlaZ",
            "rq7SSFAfjG",
            "role:ezltkinirrWCiKseYXiU"
        ],
        "_acl" : {}
    }
});

then i want to fetch record by using Parse.Query() with the Id: TnLZJsghZE
am i able to get results as expected or not becuase here i have empty ACL

**Comment by dplewis** [comment]
When in doubt check the source code [RestQuery](https://github.com/parse-community/parse-server/blob/master/src/RestQuery.js#L189).

There have been talks about making an architecture blueprint.

https://github.com/parse-community/parse-server/issues/4615

Maybe document flow for CRUD operations @acinader @davimacedo Throughts?
