### ISSUE TITLE
Node API: Cannot use the Master Key, it has not been provided

### ISSUE THREAD

**Issue by jdillick** [parse-community/Parse-SDK-JS#976]
### Issue Description

Getting the following error after upgrading from 2.7.1 to 2.8.0. Reverting to 2.7.1 fixes issue.

```
Cannot use the Master Key, it has not been provided parse/lib/node/RESTController.js:321:15
```

### Steps to reproduce

On node/express server with initialized Parse Server, trying to use the node api similar to:

```
const ParseNode = require('parse/node');

const collection = 'MyCollection';
const schemaController = ParseNode.CoreManager.getSchemaController();

const schema = {
    classLevelPermissions: {
        createPermission: {
            'role:administrator': true,
        },
        retrievePermission: {
            'role:administrator': true,
        },
        updatePermission: {
            'role:administrator': true,
        },
        deletePermission: {
            'role:administrator': true,
        },
        addFieldPermission: {
            'role:administrator': true,
        },
    },
};

schemaController.create(
    collection,
    {
        className: collection,
        classLevelPermissions,
    },
    { useMasterKey: true },
);
```

In 2.8.0, in the node/RESTController.js, this is failing on `_CoreManager.default.get('MASTER_KEY')` check.

Apparently, the `_CoreManager.default.set('MASTER_KEY'...)` does not happen by simply initializing the Parse Server anymore...

I attempted to manually initialize the `parse/node` object, giving the appId and masterKey to that object after constructing the Parse Server, but that yields a different error when the controller makes the request:

```
{ MyCollection:
   { Error: XMLHttpRequest failed: {"UNSENT":0,"OPENED":1,"HEADERS_RECEIVED":2,"LOADING":3,"DONE":4,"readyState":4,"responseText":"","responseXML":"","status":410,"statusText":null,"withCredentials":false}
       at /dev/atomic-reactor/actinium/node_modules/parse/lib/node/RESTController.js:392:17
       at process._tickCallback (internal/process/next_tick.js:68:7)
     message:
      'XMLHttpRequest failed: {"UNSENT":0,"OPENED":1,"HEADERS_RECEIVED":2,"LOADING":3,"DONE":4,"readyState":4,"responseText":"","responseXML":"","status":410,"statusText":null,"withCredentials":false}',
     code: 100 }
```

### Expected Results

I expect the node API (on the same node/express as the Parse Server) to save the CLP on this class MyCollection, as it does in SDK 2.7.1.

### Actual Outcome

RESTController in the node SDK fails with error.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0
  - Operating System:     Mac OS Mojave 10.14.6 (18G103)
  - Hardware:           MBP 13-inch, 2017
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **JS SDK**
  - JS SDK version: 2.8.0
  - Application? (Browser, Node, React-Native, etc): Node

### Logs/Trace

```
   Error: Cannot use the Master Key, it has not been provided.
       at Object.request (/dev/atomic-reactor/actinium/node_modules/parse/lib/node/RESTController.js:321:15)
       at Object.send (/dev/atomic-reactor/actinium/node_modules/parse/lib/node/ParseSchema.js:538:27)
       at Object.create (/dev/atomic-reactor/actinium/node_modules/parse/lib/node/ParseSchema.js:560:17)
       at Object.actions.(anonymous function) [as Plugin] (/Users/johndillick/dev/atomic-reactor/actinium/.core/lib/collection.js:166:37)
       at Promise (/dev/atomic-reactor/actinium/node_modules/action-sequence/index.js:8:43)
       at process._tickCallback (internal/process/next_tick.js:68:7),
```

**Comment by jdillick** [comment]
So, seems that the main change is that the `parse/node` object no longer gets initialized when using the `parse-server` with `parse/node`.

If I add the following to my parse-server initialization:

From:
```
        const server = new ParseServer(config);
```

To (added parse/node initialization):
```
        const server = new ParseServer(config);
        const { appId, masterKey } = config;
        Parse.initialize(appId, null, masterKey);
        Parse.serverURL = config.serverURL;
```

Was this change intentional?

Cheers,

John

**Comment by dplewis** [comment]
@jdillick The parse/node is global when you initialize ParseServer.

https://github.com/parse-community/parse-server/blob/master/src/ParseServer.js#L362

Make sure you pass in the cloud folder path in your config.

[Example](https://github.com/parse-community/Parse-SDK-JS/blob/master/integration/server.js#L11)

**Comment by jdillick** [comment]
@dplewis Ah, I see what you are getting at. The cloud property wasn't the problem (we were setting that), but reading over that code in ParseServer init revealed the issue. The better fix ended up being a real facepalm. Instead of requiring Parse from `parse/node` in steps to reproduce as above, relying on the global `Parse` from ParseServer's `addParseCloud` works fine. 

My guess is that in 2.7.1 node SDK, requiring Parse like so gave you the same object that was decorated by the ParseServer:

```
// unnecessary require, but works fine in 2.7.1
const Parse = require('parse/node');
```
Thanks.
